### PR TITLE
Reintroduce reverted commits from rubygems

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
In recent rubygems syncronizations, some upstream commits were reverted due to failing tests.

This PR reintroduces these commits, and backports [the fix for the original issues](https://github.com/rubygems/rubygems/pull/3694) from rubygems upstream.

I believe this should pass CI.

Closes rubygems/rubygems#3618.

### CODE REVIEW

**Comment by hsbt** [comment]
@deivid-rodriguez Thanks, MigGW build was fragile status now. We will merge this tomorrow(JST).

**Comment by deivid-rodriguez** [comment]
I think the build failure is legit though and it's caused by https://github.com/ruby/ruby/pull/3211/commits/600cfa7a18ac19c287acae85897f848a970614e7. Let me try revert that commit and if CI passes, I'll address that separately.

**Comment by deivid-rodriguez** [comment]
@hsbt https://github.com/ruby/ruby/commit/600cfa7a18ac19c287acae85897f848a970614e7 was indeed the culprit so I kept that revert for now and will sync that separately.

**Comment by deivid-rodriguez** [comment]
Current failure on MinGW should be indeed due to the unstability you mentioned :+1:

**Comment by deivid-rodriguez** [comment]
@hsbt Just pinging you in case you forgot about this one since you said you would merge it a few days ago.

**Comment by hsbt** [comment]
👍

**Pull request merged**
