### PR TITLE
Try default `gcc` 9.4.0 to see if it exhibits the same compiler bugs.

### PR DESCRIPTION
**Pull request by ioquatix**
If https://github.com/ruby/ruby/pull/8393 works, let's try `gcc-9` to see if that mitigates the issue too. Perhaps this was a bug introduced in `gcc-10`.

### CODE REVIEW

**Comment by junaruga** [comment]
Thanks for the work!

**Comment by ioquatix** [comment]
@junaruga this is now passing:

image

I'm going to try merging this.

Hopefully https://github.com/ruby/ruby/pull/8393 continues to be okay.

**Comment by junaruga** [comment]
Using `gcc-9` makes sense for now, because we use `gcc` (version 9.4.0) on Ruby CI Ubuntu ppc64le and s390x. So, I agree using the `gcc-9`.

And the PR's Travis CI is passing.
https://app.travis-ci.com/github/ruby/ruby/builds/265789165

However, I see the used gcc version is actually not `gcc-9` but `gcc` (= version 9.4.0) in the Travis CI log. Because while the `&gcc-10` exists in `.travis.yml`, the ``
https://app.travis-ci.com/github/ruby/ruby/jobs/609434805#L139

```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

So, I think a proper fix is to add the `&gcc-9` referred by `*gcc-9` to explicitly showing the used gcc is `gcc-10`.

```
$ git diff .travis.yml
diff --git a/.travis.yml b/.travis.yml
index c6054ae672..3cbe921762 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -72,6 +72,24 @@ env:
         openssl
         zlib1g-dev
 
+  - &gcc-9
+    compiler: gcc-9
+    before_install:
+      - tool/travis_retry.sh sudo bash -c "rm -rf '${TRAVIS_ROOT}/var/lib/apt/lists/'* && exec apt-get update -yq"
+      - >-
+        tool/travis_retry.sh sudo -E apt-get $travis_apt_get_options install
+        ccache
+        gcc-9
+        g++-9
+        libffi-dev
+        libncurses-dev
+        libncursesw5-dev
+        libreadline-dev
+        libssl-dev
+        libyaml-dev
+        openssl
+        zlib1g-dev
+
   # --------
 
   - &arm64-linux
```

Or to use the default gcc (= version 9.4.0). I like this way, because it's simple and is aligning with the current RubyCI Ubuntu ppc64le and s390x.

```
$ git diff
diff --git a/.travis.yml b/.travis.yml
index c6054ae672..11ae8a9b45 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -82,12 +82,12 @@ env:
   - &ppc64le-linux
     name: ppc64le-linux
     arch: ppc64le
-    <<: *gcc-10
+    compiler: gcc
 
   - &s390x-linux
     name: s390x-linux
     arch: s390x
-    <<: *gcc-10
+    compiler: gcc
 
   - &arm32-linux
     name: arm32-linux
```

**Comment by junaruga** [comment]
When we fix on the 2nd way, I think the PR title can be like this.

"Try the system gcc 9.4.0 to see if it exhibits the same compiler bugs."

or

"Try the default gcc 9.4.0 to see if it exhibits the same compiler bugs."

**Comment by junaruga** [comment]
Can you change the commit message in the 2 commits to change the gcc-9 to gcc, including the keyword "Travis" and "ppc64le" and "s390x" and explaining the context and reasons? I think squashing the 2 commits to 1 commit is better, because it comes from the same reason, right?

The message can be like this. You can check how the commit messages are written in the past in these kind of cases by the `$ git log .travis.yml`.

```
.travis.yml: Try gcc 9.4.0 instead of gcc-10 in the ppc64le and s390x cases.

Use gcc 9.4.0 instead of gcc-10 to avoid failures in the ppc64le and s390x cases and align with RubyCI Ubuntu ppc64le and s390x.
```

**Review by junaruga — CHANGES_REQUESTED** [review]
I commented. Thanks!

**Comment by ioquatix** [comment]
I think you can commit to my branch if you want. Let me give you access.

**Comment by junaruga** [comment]
> I think you can commit to my branch if you want. Let me give you access.

I am a bit sick today. So, if you want to merge this PR today, I hope you change the PR by yourself.

**Comment by junaruga** [comment]
I changed my mind. I am working to update your branch now.

**Comment by junaruga** [comment]
I rebased the PR. Let's see the results of the Travis CI 

I confirmed the rebased commit uses the default gcc 9.4.0 as I expected in my forked repository's Travis in advance.
https://app.travis-ci.com/github/junaruga/ruby/builds/265795672

**Comment by junaruga** [comment]
All right. I executed Travis 2 times for this PR on ruby/ruby Travis. And I see ppc64le and 390x cases pass in the both 1st and 2nd time.

https://app.travis-ci.com/github/ruby/ruby/builds/265796147
https://app.travis-ci.com/github/ruby/ruby/builds/265795840

**Review by junaruga — APPROVED** [review]

**Pull request merged**
