### PR TITLE
Use mmap for allocating heap pages in the GC

### PR DESCRIPTION
**Pull request by peterzhu2118**
This PR serves two purposes:

1. `mmap` OS pages directly in the GC heap, this gives a performance gain
2. Fix a bug with auto compaction due to a failing `mprotect` call (ticket: https://bugs.ruby-lang.org/issues/17652).

# Performance

Calling `mmap` directly (over `posix_memalign`) gives a small performance gain, as shown in the benchmarks below.

```
+-------------------+--------------------------+--------------------------+---------------+
| Name              | Base score               | Feature score            | % improvement |
+-------------------+--------------------------+--------------------------+---------------+
| liquid parse      | 37.02 i/s (± 0.22%)      | 37.60 i/s (± 0.19%)      | 1.57%         |
| liquid render     | 120.08 i/s (± 0.35%)     | 120.58 i/s (± 0.23%)     | 0.42%         |
| optcarrot fps     | 41.45 fps (± 0.26%)      | 43.24 fps (± 0.14%)      | 4.33%         |
| optcarrot p95 fps | 41.05 fps (± 0.20%)      | 41.80 fps (± 0.03%)      | 1.83%         |
| railsbench        | 101.49 i/s (± 0.45%)     | 101.33 i/s (± 0.29%)     | -0.17%        |
+-------------------+--------------------------+--------------------------+---------------+
```

In the table above, base is Ruby master at 07ab172ebef28bb82c2650694548d123802d6c22 and feature is this branch.

# Auto compaction bug

Redmine ticket: https://bugs.ruby-lang.org/issues/17652

GC compaction will crash on some pages due to a failing `mprotect` call. According to the `mprotect` documentation:

> POSIX says that the behavior of mprotect() is unspecified if it is applied to a region of memory that was not obtained via mmap(2).

This causes `mprotect` to sometimes fail.

## Reproduction

```ruby
GC.auto_compact = true

times = 20_000_000
arr = Array.new(times)
times.times do |i|
  arr[i] = "#{i}"
end

arr = Array.new(1_000_000, 42)
GC.start

puts "ok"
```

## Expected output

Program runs and prints "ok".

## Actual output

Crashes on Ubuntu 18.04. See `crash.log` for the crash log (note that the log file has been truncated because it's too big).

### CODE REVIEW

**Comment by tenderlove** [comment]
I had to revert this because it doesn't work on Solaris.  We probably just need to add some extra guards for that platform and fall back to `posix_memalign`.  Here is the failure: http://rubyci.s3.amazonaws.com/solaris11-sunc/ruby-master/log/20210224T210007Z.fail.html.gz

**Comment by ko1** [comment]
Sorry I didn't check it.
Do you know why direct `mmap` is faster?
@peterzhu2118

**Comment by peterzhu2118** [comment]
Hey @ko1! `mmap` is not significantly faster. But I saw occasional crashes when using `mprotect` when using `posix_memalign` during compact. It no longer crashed when I switched to `mmap`. [The specification](https://man7.org/linux/man-pages/man2/mprotect.2.html) says:

> POSIX says that the behavior of mprotect() is unspecified if it is applied to a region of memory that was not obtained via mmap(2).

**Comment by mame** [comment]
Note: https://bugs.ruby-lang.org/issues/18447

**Pull request merged**
