### PR TITLE
delete rubysig.h

### PR DESCRIPTION
**Pull request by shyouhei**
This file as been obsoleted since commit 18684d9f7cb64b93ec610f1c1deeabcfea364c08.

Must be enough.

### CODE REVIEW

**Comment by nobu** [comment]
How about removing all under include/ruby/backward/2?

**Comment by shyouhei** [comment]
> How about removing all under include/ruby/backward/2?

That's my ultimate goal but case-by-case check is not a bad idea, especially when it comes to delete something.

**Comment by nobu** [comment]
I tried it and found some necessary definitions regardless of versions, such as `LONG_MAX` etc.
Probably misplaced headers?

**Comment by shyouhei** [comment]
Hmm, `LONG_MAX` shall be defined in `<limits.h>` (in C) or `<climits>` in C++.  I can hardly think of a OS/Compiler that need our own version of `LONG_MAX`.

But I admit there can be something misplaced.

**Pull request merged**
