### PR TITLE
Refactor rb_obj_call_init and rb_obj_call_init_kw

### PR DESCRIPTION
**Pull request by S-H-GAMELINKS**
`rb_obj_call_init` and `rb_obj_call_init_kw` func have similar code(in `eval.c`).
~~I think that better cut out and replace these code like `rb_obj_init` function.~~
I think that better refactor `rb_obj_init` and `rb_obj_call_init_kw`.

### CODE REVIEW

**Comment by nobu** [comment]
Isn’t it same as `rb_obj_call_init_kw`?

**Comment by S-H-GAMELINKS** [comment]
It's definitely the same.
I'll add `rb_obj_call_init_kw` declaration.

**Comment by nobu** [comment]
`rb_obj_call_init_kw` is a public API, you don’t need to declare it again.

**Comment by S-H-GAMELINKS** [comment]
OK, I'll remove it.

**Pull request merged**
