### PR TITLE
Experimental: Do not merge

### PR DESCRIPTION
**Pull request by BurdetteLamar**
This change works in the RDoc.  Running the CI to see whether it works in code.

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
Creating this PR launched only 4 checks.  How to make it do all?

**Comment by kaiquekandykoga** [comment]
I think the only way is removing the ignored paths from every workflow.

https://github.com/ruby/ruby/blob/7f5440756eb70117c3f884ea896c10bca8476b33/.github/workflows/ubuntu.yml#L4-L12

https://github.com/ruby/ruby/blob/7f5440756eb70117c3f884ea896c10bca8476b33/.github/workflows/wasm.yml#L4-L12

And so on. I just do not understand why to do that.

**Comment by BurdetteLamar** [comment]
> And so on. I just do not understand why to do that.

I want to know whether there can be any problems with this PR.  I don't know enough to know whether these 4 checks are enough, so wanted to run all checks.

**Comment by peterzhu2118** [comment]
I don't think this will cause any issues since it's just docs with pseudocode. It's just opening the source in the documentation will be empty (not that this pseudocode is really helpful in any way).

Looking at the git history, this was introduced in 3e5d7e31763362ecf98259755694585902d89f80.

**Comment by BurdetteLamar** [comment]
@nobu, I will be documenting how to do this (put non-ascii doc into doc/*.rdoc), and will refer to these files as examples.  I want it to be as simple as possible.  Ok with you to make this a real (non-experimental) PR?

**Comment by BurdetteLamar** [comment]
I don't really need to modify these existing files.  I can just make new example code.

**Pull request closed without merging**
