### PR TITLE
Remove DL as it's made redundant by Fiddle.

### PR DESCRIPTION
**Pull request by thejonanshow**
Pay special attention to changes to Win32API.rb, the arguments for DL::CFunc.new do not map 1:1 to Fiddle::Function.new.

### CODE REVIEW

**Comment by b-dean** [comment]
[Ruby is supposed to be following semantic versioning](https://www.ruby-lang.org/en/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/). How on earth does removing dl not constitute a breaking change?

On Windows Ruby 2.0 you can do:

```ruby
require 'dl/import'
```
but on 2.1 you cannot? That is a breaking change. I don't care that there was a deprecation warning in 2.1, that warning should stay in place until ruby 3 where you can make whatever breaking changes you want.

This causes all sorts of problems with gems, such as https://github.com/net-ssh/net-ssh/pull/221. They worked around it by having a bunch of `RUBY_VERSION` checks. But inside of the same MAJOR.MINOR version, they should **not** have to do that.

@tenderlove or others, any explanation on why this is okay? Or how it isn't a violation of [Semantic Versioning](http://semver.org/)?

**Comment by knu** [comment]
Ruby does not follow _the_ Semantic Versioning.  Please read the article you pointed to again.

**Comment by b-dean** [comment]
Oh ... so minor changes don't have to maintain APIs. That's frustrating from a semver standpoint because it's not semver. I made assumptions when it said "more Semantic Versioning" and didn't read all the details. Sorry.

**Comment by knu** [comment]
There are some historical reasons we cannot adopt semver.  One of them is, ironically, related to compatibility.  Ruby, inside its source tree and as a community, has had a history of making an assumption that each of the three numbers MAJOR, MINOR and TEENY should consist of a single digit, and so many libraries, applications and build tools rely on it.  Due to this, we cannot waste digits for MAJOR and MINOR by incrementing them so frequently, or we will be running out of digits really soon.

**Comment by b-dean** [comment]
Maybe when Ruby 3 comes around they could actually follow semver and make the code in ruby that assumes single digits stop doing that. The current major and minor could become just major and increase on API breaks, teeny could become minor and only add new api changes and not delete things like this `dl` change, patch would be more like the semver patch.

I don't know how many places in the Ruby source it's expecting single digit versions, but if gems are doing that and break, that seems okay to me if the major version goes up. I would expect that there will be lots of gems that stop working with a new major version anyway since that has happened in the past (such as with 1.9 vs 2.0 or even worse 1.8 vs 1.9). And if Ruby was actually following semver, this wouldn't be a weird surprising thing for stuff to break on a major version change.

**Pull request closed without merging**
