### PR TITLE
accurate (as possible) fdiv for Fixnum and Bignum

### PR DESCRIPTION
**Pull request by metanest**
This is an accurate (as possible) fdiv implementation for Fixnum and Bignum.

### CODE REVIEW

**Comment by metanest** [comment]
A Fixnum example is,
~~~
  $ ruby24 --disable=gems -e 'print "%a\n" % [2319276427521816828.fdiv(3325853508004318597)]'
  0x1.650ac352d9ccp-1
  $ ./miniruby -v --disable=gems -e 'print "%a\n" % [2319276427521816828.fdiv(3325853508004318597)]'
  ruby 2.5.0dev (2016-12-30) [x86_64-freebsd10.3]  <== (my patched version)
  0x1.650ac352d9cc1p-1
~~~
（due to 2319276427521816828/3325853508004318597r is irreducible, this pattern didn't affect by reducing ）

**Comment by nobu** [comment]
Current trunk is:

```
$ ruby -v -e 'x=2319276427521816828; y=3325853508004318597; z=x.fdiv(y)*y; p z, z-x'
ruby 2.5.0dev (2017-01-01 trunk 57245) [universal.x86_64-darwin15]
2.3192764275218166e+18
0.0
```

but yours is:

```
$ ./ruby -e 'x=2319276427521816828; y=3325853508004318597; z=x.fdiv(y)*y; p z, z-x'
2.319276427521817e+18
512.0
```

**Comment by metanest** [comment]
HMM, but it is correctly rounded value as below. I'm thinking mode better demonstration...
~~~
$ cat sample.rb
x=2319276427521816828
y=3325853508004318597
print "%a\n" % [2319276427521816828.fdiv(y)]
print "%x\n" % [(x<<57)/y]
$ ./miniruby sample.rb (this miniruby is my version)
0x1.650ac352d9cc1p-1
1650ac352d9cc0a
~~~

**Comment by metanest** [comment]
I've found more demonstrable edge case.
~~~
$ cat fdiv_edgecase.rb
#
require 'bigdecimal'

strx = '66767141308812624791109361755796'
stry = '17022200380664065'

bdx = BigDecimal(strx)
bdy = BigDecimal(stry)
print "#{(bdx/bdy).to_s('f')}\n"

x = strx.to_i
y = stry.to_i
print "%f\n" % [x.fdiv(y)]

$ ../ruby-trunk -v fdiv_edgecase.rb
ruby 2.5.0dev (2017-01-11 trunk 57302) [x86_64-freebsd10.3]
3922356676323412.249999999999999985313297082086923792468241814443649323
3922356676323412.500000

$ ../ruby fdiv_edgecase.rb # (mine)
3922356676323412.249999999999999985313297082086923792468241814443649323
3922356676323412.000000
~~~
How is this ?

**Comment by nobu** [comment]
Also in that case, `x.fdiv(y)*y` will not equal to `x` while currently does.
Maybe related to denormalization?

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this from master?

**Comment by k0kubun** [comment]
Let me close this as it has not been updated for a while. Please reopen this after resolving conflicts. Thanks.

**Pull request closed without merging**
