### PR TITLE
Use `size_t` for `RSTRING_LEN` in String#count

### PR DESCRIPTION
**Pull request by nobu**
https://hackerone.com/reports/1042722

### CODE REVIEW

**Comment by ioquatix** [comment]
Would it make sense to standardise on `size_t` for this kind of use case?

**Comment by ilyazub** [comment]
Reddit user found out that `String#count` became 3.4 times slower after this PR: https://www.reddit.com/r/ruby/comments/16d4ha6/comment/k04ohqu/?utm_source=share&utm_medium=web2x&context=3

```
Benchmark 1: ./ruby test.rb
  Time (mean ± σ):      95.5 ms ±   1.2 ms    [User: 93.9 ms, System: 1.9 ms]
  Range (min … max):    93.4 ms …  98.5 ms    30 runs

Benchmark 2: ./ruby.master test.rb
  Time (mean ± σ):     326.5 ms ±   2.0 ms    [User: 323.1 ms, System: 3.6 ms]
  Range (min … max):   324.2 ms … 329.1 ms    10 runs

Summary
  './ruby test.rb' ran
    3.42 ± 0.05 times faster than './ruby.master test.rb'
```

**Comment by Freaky** [comment]
Slightly-tweaked `test.rb` that demonstrates the difference just as well:

```ruby
html = IO.read('/dev/zero', 1024 * 1024)
Array.new(1000) { html.count($/) }
```

AMD 5700X, FreeBSD 13.2 (clang 14.0.5), tested against b1f0d009cbdf1990813c09165d372be29485f8ae and same with this patch reverted.

**Comment by ilyazub** [comment]
Here're the benchmark results using the [`benchmark-driver` gem](https://github.com/benchmark-driver/benchmark-driver).

```
$ benchmark-driver tmp/string_count_benchmark_driver.yml --rbenv '2.7.2;3.1.4;3.2.2'
Calculating -------------------------------------
                          2.7.2       3.1.4       3.2.2
               count     5.505k      2.820k      2.845k i/s -     10.000k times in 1.816505s 3.545864s 3.514397s

Comparison:
                            count
               2.7.2:      5505.1 i/s
               3.2.2:      2845.4 i/s - 1.93x  slower
               3.1.4:      2820.2 i/s - 1.95x  slower
```

Benchmark:

```yaml
# cat tmp/string_count_benchmark_driver.yml
loop_count: 10_000
prelude: |
  html = IO.read('/dev/zero', 1024 * 1024)
benchmark:
  count: html.count($/)
```

**Comment by ilyazub** [comment]
I created a Redmine ticket: https://bugs.ruby-lang.org/issues/19875

**Pull request merged**
