### PR TITLE
Provide a way to declare visibility of attributes defined by attr* methods in a single expression - v2

### PR DESCRIPTION
**Pull request by radarek**
Continuation of https://github.com/ruby/ruby/pull/3757. I will push each change as a separate commit to check which one fails on CI.

### CODE REVIEW

**Comment by mame** [comment]
Thanks, I believe this change is definitely innocent :-)

**Comment by radarek** [comment]
Yeah, I'm pretty sure too but still it's better to check :D.

**Comment by radarek** [comment]
@mame Could you please do not merge PR until I check all commits? Otherwise I will have to create PR for every one (build is not triggered after I push commit to alreade closed PR).

**Comment by mame** [comment]
Unfortunately, the Solaris CI in question builds and tests only the master branch. I logged in to the CI machine and tried to reproduce the issue on a local working copy (rather than the CI setup), but I couldn't reproduce the failure. So, merging each commit is the only way to test the issue.

**Comment by mame** [comment]
Ah. If you could create a branch that includes separate commits, I can cherry-pick and push each commit to the master. It is okay to me if you don't mind that the branch itself will not be eventually merged.

**Comment by radarek** [comment]
@mame Now I understand. So I will push all commits.

**Pull request merged**
