### PR TITLE
Support warning feature for bundled gems with bootsnap and zeitwerk

### PR DESCRIPTION
**Pull request by hsbt**
I added some fixes from https://github.com/ruby/ruby/pull/10244

### CODE REVIEW

**Comment by fxn** [comment]
Thanks @hsbt!

**Comment by mscrivo** [comment]
FYI, I'm not sure this is totally working as intended. We're using bootsnap and previously had no issues with 3.3.0, but upon updating to 3.3.1, now seeing this: 

```
/Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:130:in `<': comparison of String with nil failed (ArgumentError)

    msg = " #{RUBY_VERSION < SINCE[gem] ? "will no longer be" : "is not"} part of the default gems since Ruby #{SINCE[gem]}."
                             ^^^^^^^^^^
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:130:in `build_message'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:126:in `warning?'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:71:in `block (2 levels) in replace_require'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/logging-2.3.1/lib/logging.rb:10:in `<main>'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/mscrivo/.local/share/mise/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
```

**Comment by hsbt** [comment]
@mscrivo This change is not backport to 3.3.1 yet.

**Comment by hsbt** [comment]
@mscrivo Can you file your Gemfile and environment to https://bugs.ruby-lang.org/issues/20450?

**Pull request merged**
