### PR TITLE
The way iterator ‘each’ finally returns nil instead of array

### PR DESCRIPTION
**Pull request by nerzh**

### CODE REVIEW

**Comment by duerst** [comment]
Can you please explain the purpose of your commit? Just changing some return values of some functions does not make sense, because there are other functions that depend on the return values.

**Comment by nerzh** [comment]
@duerst 
```ruby
arr.each{ |value| ... }.other_method()
```
cause we can do it in two lines like this
```ruby
arr.each{ |value| ... }
arr.other_method()
```
so we’ll fix that problem. And people who use now one line version will be easily able to convert their code into two lines version.

Maybe there is no need to accept my PR cause it will broke a lot of already exists code, but I just want to spot that problem, cause it’s really incinvenient to see the whole array print in my console or log files.

**Comment by duerst** [comment]
I now understand that you want this to avoid long printouts in irb. As you say, this is backwards incompatible. If you want to pursue this, you should submit it as a feature request to https://bugs.ruby-lang.org/projects/ruby-trunk/issues/new. You should also fix the CI failures, but maybe you can wait with that.

**Comment by k0kubun** [comment]
The fork is deleted and we cannot update your branch to pass "check_master", so let me close this for now. :bow:

**Comment by nerzh** [comment]
Thanks, I’m just kidding. Just can’t understand why iteration returns array. It’s confusing. I understand that to change it needs to make some tests and it’s not so urgent thing. The accepting of pull-request was not my goal. I’ve opened it to bring some attention to this issue. Sorry for my disturbing you

**Pull request closed without merging**
