### PR TITLE
Add documentation for rb_tracepoint_new C level API

### PR DESCRIPTION
**Pull request by emilsoman**

### CODE REVIEW

**Comment by ko1** [comment]
How about to write we can not specify internal and not internal events simultaneously?

**Comment by emilsoman** [comment]
@ko1 Done (also squashed commits).

**Comment by ko1** [comment]
One more comment.

> + *   1. VALUE target_thval - Thread in which the tracepoint is to be created.

Please note something like "If false or nil (Qfalse or Qnil), it will not bind specific thread".

And do not pass 0 directly (Qnil will be nice) in example.

**Comment by emilsoman** [comment]
Sure. By the way, if target_thval is false or nil (Qfalse or Qnil), it will bind to the current thread, right ?

**Comment by ko1** [comment]
OMG! Thank you for asking this question.

Now, it is completely ignored and enable on *all* threads.

There are three options.
(a) Specify a thread
(b) Specify current thread
(c) Enable on all threads  <- current behavior with any option

Before documentation, we need to decide this spec.

(b) can be specify with (a) (rb_thread_current()). So nil (or false) specify (c) is reasonable for me.

**Comment by emilsoman** [comment]
@ko1 Thanks for explaining, it makes sense to use nil/false to bind tracepoints to all threads. So currently we're not making use of this param and binding to all threads. I'll document the same.

**Comment by emilsoman** [comment]
@ko1 Done.

**Comment by emilsoman** [comment]
By the way, I have a question for you. Why do we have to throw error when normal and internal events are mixed in `rb_tracepoint_new` ? Is there a limitation that holds us from using both kinds of events simultaneously ?

**Comment by ko1** [comment]
There are two reasons.

(1) we can't use any Ruby APIs in internal events. I added about it.
(2) We can employ 32 events because of 32 bit word. I will separate normal and internal event spaces.

**Comment by ko1** [comment]
Thank you, I committed it.

**Pull request closed without merging**
