### PR TITLE
Replace iff with if

### PR DESCRIPTION
**Pull request by gmcgibbon**
iff means if and only if, but readers without that knowledge might assume this to be a spelling mistake (see [examples](https://github.com/ruby/ruby/pulls?q=iff+)). To me, this seems like exclusionary language that is unnecessary. Simply using "if" instead should suffice.

I left some [vendored code](https://github.com/CocoaPods/Molinillo) comments and changelogs. Also happy to discuss alternatives like using "if and only if" expanded. Thanks!

cc @tenderlove

### CODE REVIEW

**Comment by chrisseaton** [comment]
As you say it means 'if and only if', so why not replace with that? I think you're losing something otherwise, aren't you?

**Comment by gmcgibbon** [comment]
To me I don't see any difference between "if" and "if and only if" in the context of code comments. Can you give an example of what I'm obfuscating with this change?

For example, I see no difference in `* Returns +true+ iff the last match was successful.` vs `* Returns +true+ if the last match was successful.`.

**Comment by tenderlove** [comment]
> To me I don't see any difference between "if" and "if and only if" in the context of code comments. Can you give an example of what I'm obfuscating with this change?

Same. To me "if" means the same thing as "if and only if". Neither `iff`, nor `if and only if` add any meaning IMO.  `iff` is confusing because most people don't use it, and I don't understand what `if and only if` buys you over the more concise and common `if`.

**Comment by chrisseaton** [comment]
It's not just fancy terminology for the sake of it - they're different logical operations.

'A iff B' means 'A if B and also B if A'.

'Returns true iff last match was successful' means 'Returns true if the last match was successful and if they last match was successful returns true'.

If I told you 'returns true if the last match was successful', and you get 'true' - does that mean the last match was successful? No it could also mean there wasn't any match.

Does it matter and mean something important in *these* cases? I don't know but someone took the time to make that extra point.

**Comment by chrisseaton** [comment]
Unrelated issue, so I'll put it in another comment - when you change spec titles you may break downstream projects depending on them.

We can update, but it's a bit of churn - @eregon can take a look.

**Comment by tenderlove** [comment]
> If I told you 'returns true if the last match was successful', and you get 'true' - does that mean the last match was successful? No it could also mean there wasn't any match. You were told true implied successful, but not successful implies true.

This makes sense.

> Does it matter and mean something important in _these_ cases? I don't know but someone took the time to make that extra point.

If it matters, then we should change `iff` to `if and only if`. I'd rather documentation uses more common language (even if it has to be long winded in order to be precise).

**Comment by eregon** [comment]
FWIW I think a nicer way to phrase
> Returns +true+ iff/if ...

is
> Returns whether ...

Which also make it clear what it returns if the condition doesn't hold (it returns `false`).

**Comment by chrisseaton** [comment]
I agree many of these look unnecessary. Here's one I don't think is:

https://github.com/ruby/ruby/pull/4035/files#diff-4512cf7bebece35cb856c3539cfb04ec0c52f3dc74c50f0d121ffe89f8077ed4R2484

I'll reword what it means verbosely for just 'if':

> autoload_reset will wake up any threads added to this if the GVL is released during autoload_require and may also wake them up up for some other reasons we haven't mentioned here, so it they get woken up it could be the GVL was released or it could be something else

And what it probably was really intended to mean using 'iff':

> autoload_reset will wake up any threads added to this if the GVL is released during autoload_require and will not wake them up otherwise, so if they're woken up that's definitely why it happened and that's what you need to handle

**Comment by gmcgibbon** [comment]
I changed all previous "iff" changes to "if and only if". I omitted the `Returns whether` changes because that's a larger changeset that should likely be done separately. Thanks for your feedback all!

**Comment by hsbt** [comment]
Do not change rubygems, molinillo, strscan and matrix etc. The canonical repository of them is different from `ruby/ruby`.

**Comment by gmcgibbon** [comment]
Ah, you're right. Many of these libraries have been gemified (https://github.com/ruby/matrix, https://github.com/ruby/logger, etc.). I will trim this PR down to only the core ruby changesets. 👍

**Comment by gmcgibbon** [comment]
Oops, I forgot to revert the net/* changes (because those are gems too). That's fixed now. Thanks for your patience. 😄

**Comment by tenderlove** [comment]
@eregon does it matter if the spec descriptions changed? @chrisseaton mentioned it [here](https://github.com/ruby/ruby/pull/4035#issuecomment-755557539).

**Comment by eregon** [comment]
It causes useless churn for tags, but since it's not so many specs it's fine to change those.

**Pull request merged**
