### PR TITLE
Replace "iff" with "if" for expressing conditions

### PR DESCRIPTION
**Pull request by kotp**
Spelling error.

### CODE REVIEW

**Comment by Arcovion** [comment]
https://en.wikipedia.org/w/index.php?title=Iff&redirect=no

**Comment by kotp** [comment]
https://www.merriam-webster.com/dictionary/iff in that case.

**Comment by kotp** [comment]
Thank you Arcovion.  My English is now better.

**Comment by zw963** [comment]
i almost belive this is typo. :smile:

**Comment by mikegee** [comment]
I've seen this "correction" before. Let's reconsider using "iff", since many people don't know the jargon.

**Comment by kotp** [comment]
Not just because of the jargon being known, but I don't believe that most of the comments and documentation generated from those comments are written to be "formal logic" language.  I feel it should be useful as a reference, not a specification, the former a little more relaxed (though still formal) in communication standards, the latter being filled with jargon because of the requirement to be precisely understood.

**Pull request closed without merging**
