### PR TITLE
[WIP] Stop worrying and love the LTO.

### PR DESCRIPTION
**Pull request by shyouhei**

### CODE REVIEW

**Comment by shyouhei** [comment]
Looking at CI failures...

**Comment by duerst** [comment]
@shyouhei : It is confusing to get messages about this change without any idea what "LTO" is supposed to mean. https://acronyms.thefreedictionary.com/LTO gives over 30 expansions, but none of them seems to make sense. Please expand acronyms, unless they are really, really obvious (such as HTML or YARV).

**Comment by edbond** [comment]
@duerst  I think LTO is for "Link Time Optimization" https://gcc.gnu.org/wiki/LinkTimeOptimization

**Comment by shyouhei** [comment]
@duerst I feel sympathy to you; three-letter acronyms don't actually describe themselves.  But the word LTO is the choice of compiler authors, not me.  See also https://gcc.gnu.org/ml/gcc/2009-10/msg00060.html

**Comment by shyouhei** [comment]
BTW still investigating but the CI failure seen in https://travis-ci.org/ruby/ruby/jobs/557713358 is because addr2line.c failing to decompose DWARF.  Which I suspect is a linker bug?  See also https://sourceware.org/bugzilla/show_bug.cgi?id=20882

**Comment by shyouhei** [comment]
No progress, let me close for now.  Will revisit later.

**Pull request closed without merging**
