### PR TITLE
Move `ruby_node_name` to node.c and rename prefix of the function

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by nobu** [comment]
`ruby_node_name` is prefixed with `ruby` instead of `rb`, because it can be called without a running interpreter, I think.
But it is ok.

**Comment by yui-knk** [comment]
Thanks for your information. OK, I will merge this.

**Comment by nobu** [comment]
Oops, the name was exported.
So, strictly speaking, this breaks binary compatibility.

**Comment by nobu** [comment]
Sorry, source level incompatibility.
But this would be only for ripper probably.

**Comment by yui-knk** [comment]
I renamed the function to the original by https://github.com/ruby/ruby/pull/7852.

**Pull request merged**
