### PR TITLE
Sync csv

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Comment by kou** [comment]
How did you move `doc/*` in ruby/csv to `doc/csv/*` in ruby/ruby?
Can we move `doc/*` to `doc/csv/*` in ruby/csv and sync `doc/csv/*` in ruby/csv to `doc/csv/*` in ruby/ruby?

**Comment by nobu** [comment]
Inserted a commit which does `git mv`, then squashed.

If ruby/csv does simply, probably it will become an empty commit and we'll be able to skip it, I think.
```
Try to pick these commits:
9b696906ec5cd2c42aef6d2656a635a9c8229c02: Moved docs under doc/csv
----
Pick 9b696906ec5cd2c42aef6d2656a635a9c8229c02 from ruby/csv.
Performing inexact rename detection: 100% (472800/472800), done.
The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
Skip empty commit 9b696906ec5cd2c42aef6d2656a635a9c8229c02
```

**Comment by kou** [comment]
OK. I'll move `doc/*` to `doc/csv/*` in ruby/csv.

**Comment by kou** [comment]
Done.

**Pull request merged**
