### PR TITLE
Fast and safe connect timeout for net

### PR DESCRIPTION
**Pull request by xiewenwei**
net/http, net/pop, net/smtp and net/ftp use `Timeout.timeout` to calculate connect_timeout.
Timeout.timeout is slow. It creates and destroys a thread every time.
Timeout.timeout is also dangerous. see [Timeout: Ruby's Most Dangerous API](http://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/)

It is more effective and safe to use socket timeout to accomplish that. 
Follow is the changes need to do.
1. Replace `TCPSocket.open` with `Socket.tcp`
2. Create `TCPSocket` with `TCPSocket.for_fd`

redmine issue is here:
[Use socket timeout for net/http and net/pop for open_timeout](https://bugs.ruby-lang.org/issues/12928)

### CODE REVIEW

**Comment by nobu** [comment]
Maybe what you need is `Socket.tcp` but returns `TCPSocket` instead of `Socket`.

**Comment by xiewenwei** [comment]
Good idea. I don't know `Socket.tcp` supports connect_timeout before. I will change it. Thank you.

**Comment by xiewenwei** [comment]
I use `Socket.tcp` now. `Socket.tcp` returns `Socket` instance. So I need to convert it to `TCPSocket` instance using `TCPSocket.for_fd`. Thank you for your advice. @nobu

**Comment by shugo** [comment]
Socket.tcp is designed to replace TCPSocket, so it's better to use Socket itself.

**Comment by nobu** [comment]
Replaced `addr` and `peeraddr` with modern `Addrinfo` interfaces, and all tests would pass without `for_fd` hack.

**Comment by xiewenwei** [comment]
I changed the codes. Removed TCPSocket.for_fd and used socket directly now.

**Comment by xiewenwei** [comment]
Eric Wong Post:

>  I agree with eliminating Timeout, but I don't think your
> solution is enough because it does not cover timeouts for
> DNS resolution (getaddrinfo(3) calls).
> 
> For timeouts, we would need to use resolv.rb instead of getaddrinfo(3)
> provided by libc to do timeouts without a separate thread. I started
> adding timeouts to resolv.rb last year but can't remember how far I got...
> I'm not sure if resolv.rb supports all the features of a modern
> getaddrinfo(3), either, AFAIK, not many people use resolv.rb.

I need to fix it.

**Comment by xiewenwei** [comment]
It is very stranger that Travis CI sometimes failed because timeout.

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this from master?

**Comment by k0kubun** [comment]
Let me close this as it has not been updated for a while. Please reopen this after resolving conflicts. Also please attach the redmine ticket to the pull request next time. Thanks.

**Pull request closed without merging**
