### PR TITLE
Raise ArgumentError in IO#sysread on Windows when given a negative length

### PR DESCRIPTION
**Pull request by javanthropus**
Fixes [Bug #18880]

### CODE REVIEW

**Review by nobu — CHANGES_REQUESTED** [review]
Could you add the test?

**Comment by javanthropus** [comment]
I have a pending PR in rubyspec that includes a relevant test that was disabled on Windows because of this bug.  I was planning to enable the test for all platforms once this was accepted.  Do you want a dedicated test added to this repository too?

**Comment by nobu** [comment]
To test/ruby/test_io.rb.

**Review by nobu — APPROVED** [review]

**Comment by nobu** [comment]
Thanks

**Pull request merged**
