### PR TITLE
YJIT: Use .as_side_exit() for jumps to counted exits

### PR DESCRIPTION
**Pull request by XrXr**
Fewer cycles running nops when these jumps are not taken. Fixing all
these so when they get copy pasted in the future we save on padding.

### CODE REVIEW

**Review by k0kubun — APPROVED** [review]
:+1:

**Comment by jimmyhmiller** [comment]
Why make it so we have to ensure we have as_side_exit rather than fixing the api to make this mistake difficult/impossible? Why the CodePtr/Target split for this stuff? Do we really want to default to unnamed side_exits? 

We have a lot of code we have to copy and paste to ensure we do things properly. Seems like with a little thought and some nice data types, we could avoid all of that.

**Comment by maximecb** [comment]
> Why make it so we have to ensure we have as_side_exit rather than fixing the api to make this mistake difficult/impossible? Why the CodePtr/Target split for this stuff? Do we really want to default to unnamed side_exits?
> 
> We have a lot of code we have to copy and paste to ensure we do things properly. Seems like with a little thought and some nice data types, we could avoid all of that.

We have a `CodePtr` type, but not all code pointers are necessarily side exits. That being said, you are right, it is kinda weird to see this:

```
asm.jo(side_exit.as_side_exit());
```

Presumably, when we generate a side-exit, it should always have the side exit type 😅

**Comment by XrXr** [comment]
So, I also considered another change where I do:
```
M yjit/src/codegen.rs
@@ -201,7 +201,7 @@ macro_rules! counted_exit {
     ($ocb:tt, $existing_side_exit:tt, $counter_name:ident) => {
         // The counter is only incremented when stats are enabled
         if (!get_option!(gen_stats)) {
-            $existing_side_exit
+            $existing_side_exit.as_side_exit()
         } else {
             let ocb = $ocb.unwrap();
             let code_ptr = ocb.get_write_ptr();
@@ -216,7 +216,7 @@ macro_rules! counted_exit {
             ocb_asm.compile(ocb);
 
             // Pointer to the side-exit code
-            code_ptr
+            code_ptr.as_side_exit()
         }
     };
 }
```
that one gave me 17 compile errors versus this diff which gave me under 10 lines to change.
I went with this diff cause I'm lazy. You can try making the alternative change above which would make these sites look nicer.
The need for .as_side_exit() versus .into() is because we need some way to action whether we pad the jumps to a constant size (needed for correctness in case it could be patched) or not (e.g. for side exits, internal labels).

**Pull request merged**
