### PR TITLE
Return earlier if pathname begins with a slash

### PR DESCRIPTION
**Pull request by ashmaroli**
Beneficial for long pathnames with a leading `'/'` by avoiding unnecessary traversal through the multiple chopped basenames.

With this, the time taken by this `:relative?` is going to be identical for the following samples:

```ruby
Pathname.new('/im/sure').relative?
Pathname.new('/im/absolutely/sure').relative?
Pathname.new('/im/absolutely/positively/sure').relative?
Pathname.new('/a/b/c/d/e/f/g/h/i/j/k/l/m/n/o/p/q/r/s/t/u').relative?
```

### CODE REVIEW

**Comment by ashmaroli** [comment]
@marcandre @akr Gentle remainder.. :bell:

**Comment by marcandre** [comment]
Right. I think we might as well fix this. It's not really acceptable for this to be `O(n)` when it should be `O(1)` in all cases.

I believe #2107 is compatible and efficient.

Any objection @akr?

**Comment by shyouhei** [comment]
I am not sure if a path starts with `File::SEPARATOR` is a relative path or not, on Windows.  @nobu do you have any idea?

**Comment by nobu** [comment]
From these test in test/pathname/test_pathname.rb, pathname considers such path an absolute path, at least.

```ruby
  defassert(:relative?, false, '/')
  defassert(:relative?, false, '/a')
  defassert(:relative?, false, '/..')
```

**Comment by ashmaroli** [comment]
I use Ruby on Windows and can confirm that **`Pathname`** considers paths with a leading forward slash to *not be* relative paths on Windows.

**Comment by shyouhei** [comment]
Thank you, then I have no worry about it.  The optomization seems neat. :+1:

**Comment by hsbt** [comment]
We already have this optimization from https://github.com/ruby/pathname/commit/b39c268cff0a28660f071f1a77d94bf962118476.

**Pull request closed without merging**
