### PR TITLE
[DOC] Add remark about call-seq

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
The more I think about this, the less I like it.  `array & other_array` has a naturalness, while `self & other_array` seems clunky.

But I think we should retain the guideline, one way or the other.

I'd be happy to see more opinions.

**Review by jeremyevans — APPROVED** [review]

**Comment by BurdetteLamar** [comment]
@jeremyevans, I'm not clear:  you approve `array & other_array`?  Or `self & other_array`?  (I know I've clouded the issue by changing my mind mid-stream.)

**Comment by jeremyevans** [comment]
I was looking at the patch when I approved it (which has `self &`).  I don't have strong feelings either way.  I think `self &` is more similar to the documentation of regular methods, which use implicit `self` (e.g. `method(arg)`, not `array.method(arg)`).

**Review by peterzhu2118 — APPROVED** [review]
I agree with @jeremyevans. I also don't have a strong opinion, but `self & obj` is more consistent with the rest of the documentation.

**Pull request merged**
