### PR TITLE
Reduce TIME_QUANTUM_MSEC to 10

### PR DESCRIPTION
**Pull request by nateberkopec**
Slightly inspired by https://bugs.ruby-lang.org/issues/15438

I looked at the comment above TIME_QUANTUM_MSEC, and thought: "Hm, that kernel version is almost more than 8 years old. I wonder if this has changed at all?"

Unfortunately I only have Mach kernel ready to test, but on current trunk, `ruby -e 'Thread.new{loop{}}; loop{p Time.now.usec; Thread.pass}'` returns:

```
226034
327316
429751
534853
744114
845836
49503
150224
358224
463104
667844
772864
877057
79469
179639
280823
381164
484960
```

With this patch: 

```
216443
228252
251055
275836
296450
308908
318965
339620
363152
374360
398569
422305
434776
447438
469987
481730
494399
514975
539736
562999
```

So, if that's the case, I think reducing the scheduling quantum may make sense?

I'm not that familiar with Linux's CFS, but we already use a 10ms quantum on Windows. It's my understanding that CFS' timeslices will always be between 0.75 and 6 milliseconds (https://elixir.bootlin.com/linux/latest/source/kernel/sched/fair.c#L49).

It might also be helpful to try benchmarking this change.

### CODE REVIEW

**Comment by nateberkopec** [comment]
I'll obviously have to update the comment. There's also a test somewhere that relates to this setting.

But looking for feedback from anyone who has more experience with OS schedulers than I do.

**Comment by nateberkopec** [comment]
Pinging @ko1 @k0kubun @ioquatix - if you have any intuitions or reactions, please let me know. 

Particularly @k0kubun  - do you think there are any benchmarks in ruby-bench that may stress context switching?

**Comment by k0kubun** [comment]
I'm not familiar enough with `TIME_QUANTUM_MSEC`, so I'll delegate that to @ko1 (you may want to review a request in tomorrow's developer meeting https://bugs.ruby-lang.org/issues/15459).

In terms of rubybench, it basically tries to copy benchmarks in [`benchmark/`](https://github.com/ruby/ruby/tree/trunk/benchmark) directory. And unfortunately I don't know such benchmark in the directory (is `benchmark/vm2_fiber_switch.yml` related?). 

So it would be appreciated to add a benchmark measuring the context switching. It would also encourage us to merge the patch more.

**Comment by ioquatix** [comment]
I can help with context switch benchmark.

**Comment by nateberkopec** [comment]
Came to fruition in #11981!

**Pull request closed without merging**
