### PR TITLE
Improve perfomance for Integer#size method [Feature #17135]

### PR DESCRIPTION
**Pull request by S-H-GAMELINKS**
ref: [Feature #17135 Improve perfomance for Integer#size method](https://bugs.ruby-lang.org/issues/17135)

### CODE REVIEW

**Review by k0kubun — APPROVED** [review]

**Comment by k0kubun** [comment]
Oops, sorry, could you rebase this as well? Also, I'd appreciate it if you can add your bench to benchmark/mjit_integer.yml instead because the current benchmark script cannot measure the actual benefit of this change.

**Comment by S-H-GAMELINKS** [comment]
Thanks! I'll rebase this PR later.

**Comment by marcandre** [comment]
Big picture:
1) If this patch is faster, it is a symptom of a bigger problem and not a solution
2) Is there any circumstance where `Integer#size` would be worth optimizing?

**Comment by k0kubun** [comment]
> 1. If this patch is faster, it is a symptom of a bigger problem and not a solution

As discussed in another PR https://github.com/ruby/ruby/pull/4234, we do NOT intend to make VM faster by this kind of patch. It's indeed a trivial difference. Thus a bigger problem you made up with doesn't really exist.

```
$ benchmark-driver -v --rbenv 'before;after' benchmark/mjit_integer.yml --filter size
before: ruby 3.1.0dev (2021-06-05T03:28:20Z master 033e76e760) [x86_64-linux]
after: ruby 3.1.0dev (2021-06-05T04:28:10Z improve_integer_size b1c542b5fa) [x86_64-linux]
Calculating -------------------------------------
                         before       after
        mjit_size(1)    27.370M     27.891M i/s -     40.000M times in 1.461440s 1.434165s

Comparison:
                     mjit_size(1)
               after:  27890796.2 i/s
              before:  27370267.3 i/s - 1.02x  slower
```

What we actually do here is telling MJIT (and YJIT https://github.com/Shopify/yjit/pull/61) to skip pushing/popping a stack frame for this method. 

```
$ benchmark-driver -v --rbenv 'before --jit;after --jit' benchmark/mjit_integer.yml --filter size
before --jit: ruby 3.1.0dev (2021-06-05T03:28:20Z master 033e76e760) +JIT [x86_64-linux]
after --jit: ruby 3.1.0dev (2021-06-05T04:28:10Z improve_integer_size b1c542b5fa) +JIT [x86_64-linux]
Calculating -------------------------------------
                     before --jit  after --jit
        mjit_size(1)      30.866M      43.288M i/s -     40.000M times in 1.295922s 0.924048s

Comparison:
                     mjit_size(1)
         after --jit:  43287787.4 i/s
        before --jit:  30866044.8 i/s - 1.40x  slower
```

It seems like you ignore whatever I say, but actually I clarified that to you before https://bugs.ruby-lang.org/issues/17502. Like explained there and https://github.com/ruby/ruby/pull/4018#issuecomment-753420158, please talk to @ko1 if you don't like using Ruby for annotations. I don't care whether we annotate methods in C or Ruby at all.

Just the frame omission alone makes it 1.4x faster, but thanks to shyouhei's work https://github.com/ruby/ruby/pull/3305#issuecomment-656554272, this _could_ even be faster if we inline the definition. The JIT-ed code could return `8` (`1.size`) without calculating it from `1`, for example. We aren't working on inlining definitions in this PR (which should be a separate PR) though. 

> Is there any circumstance where Integer#size would be worth optimizing?

Fair. But in what circumstance do you prefer not introducing speedup by just saying "you can optimize this"? I'm 100% sure this direction, in general, is easier to maintain than introducing an `opt_` insn for every single method you want to optimize (e.g. https://github.com/ruby/ruby/pull/2228).

**Comment by marcandre** [comment]
Thanks for the reply.

**Comment by S-H-GAMELINKS** [comment]
Thanks, to fixed PR and maerged.

**Pull request merged**
