### PR TITLE
Link ext bundles with bundle loader option for newer ld64 of Ventura

### PR DESCRIPTION
**Pull request by kateinoigakukun**
ld64 shipped with Xcode 14 emits a warning when using `-undefined
dynamic_lookup`.

```
ld: warning: -undefined dynamic_lookup may not work with chained fixups
```

Actually, `-undefined dynamic_lookup` doesn't work when:

1. Link a *shared library* with the option
2. Link it with a program that uses the chained-fixup introduced from
   macOS 12 and iOS 15

because `-undefined dynamic_lookup` uses lazy-bindings and they won't be
bound while dyld fixes-up by traversing chained-fixup info.

However, we build exts as *bundles* and they are loaded only through
`dlopen`, so it's safe to use `-undefined dynamic_lookup` in theory.
So the warning produced by ld64 is false-positive, and it results
failure of option checking in configuration. Therefore, it would be an
option to ignore the warning during our configuration.

On the other hand, `-undefined dynamic_lookup` is already deprecated on
all darwin platforms except for macOS, so it's good time to get rid of
the option. ld64 also provides `-bundle_loader <executable>` option,
which allows to resolve symbols defined in the executable symtab while
linking. It behaves almost the same with `-undefined dynamic_lookup`,
but it makes the following changes:

1. Require that unresolved symbols among input objects must be defined
   in the executable.
2. Lazy symbol binding will lookup only the symtab of the bundle loader
   executable. (`-undefined dynamic_lookup` lookups all symtab as flat
   namespace)

This patch adds `-bundle_loader $(RUBY)` when non-EXTSTATIC
configuration by assuming ruby executable can be linked before building
exts.

See "New Features" subsection under "Linking" section for chained fixup
https://developer.apple.com/documentation/xcode-release-notes/xcode-13-release-notes

Resolve https://bugs.ruby-lang.org/issues/18912

### CODE REVIEW

**Comment by XrXr** [comment]
Sorry to barge into your draft PR! I was trying out the Ventura beta and ran into the same linker errors. I made some fixes for `make test-spec` based on your changes and tested it on the beta and on Monterey:

- https://github.com/XrXr/ruby/commit/261fb57518c2c979e3e19f026a548bfac3c9e9da
- https://github.com/XrXr/ruby/commit/df87d93c7cb7fc0dd13789982dd3cf4f5da3c8f5 (macOS CI should be green)

It doesn't break the build, but I'm also getting some warnings from `make` that come from the changes to `PREP`:

```
make: Circular builtin_binary.inc <- ruby dependency dropped.
make: Circular ruby <- ruby dependency dropped.
```

I haven't tried removing those changes.

Good call for migrating to `-bundle_loader`!

**Review by XrXr — COMMENTED** [review]
I forgot to mention that on Monterey and older systems we pass both `-undefined dynamic_lookup` and `-bundle_loader`. It may be better to make sure we only pass one?

**Comment by kateinoigakukun** [comment]
@XrXr  Thank you for taking a look, Alan! Your fixes seem reasonable to me. 

> I forgot to mention that on Monterey and older systems we pass both -undefined dynamic_lookup and -bundle_loader. It may be better to make sure we only pass one?

Hmm, as far as I understand, it's safe to pass both `-undefined dynamic_lookup` and `-bundle_loader`.
And on second thoughts, removing `-undefined dynamic_lookup` from `DLDFLAGS` can break some ext builds if an ext has a reference to another ext's symbol. So it may be safer to keep `-undefined dynamic_lookup` as much as possible.

**Comment by hsbt** [comment]
👍

**Pull request merged**
