### PR TITLE
Enhanced RDoc for String#succ!

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Review by jeremyevans — COMMENTED** [review]
I think it's better to point users to the `succ` documentation, instead of just copying it and pasting it and replacing `succ` with `succ!`.

I am in favor of the call-seq change with the specific mention of the alias at the end.

**Comment by BurdetteLamar** [comment]
@jeremyevans, I don't agree about <tt>succ!</tt>'s referring to <tt>succ</tt>.  I don't think the reader should be sent elsewhere without a compelling reason.  What's your level of discomfort with leaving this as is?

(Aside:  when I was a young documentor, I *always* preferred using a macro processor (Unix m4), for this and many other reasons.)

**Comment by jeremyevans** [comment]
The documentation for the method is long and complex.  The implementation is exactly the same except one returns a new string.  In other cases in Ruby documentation, when methods share an implementation, we do not repeat the documentation in both cases.  For example, `Kernel#system` refers people to `Kernel#spawn`, it doesn't repeat the entire `spawn` documentation for the argument handling where it is the same.  For `String`, see `chop`/`chop!`, `chomp`/`chomp!`, `delete`/`delete!`, `downcase`/`downcase!` (and how `capitalize`/`capitalize!`/`upcase`/`upcase!` refer to `downcase`), etc.. I'm against unnecessary duplication in documentation. My level of discomfort with this change is: significant.

**Comment by BurdetteLamar** [comment]
> 
> 
> The documentation for the method is long and complex. The implementation is exactly the same except one returns a new string. In other cases in Ruby documentation, when methods share an implementation, we do not repeat the documentation in both cases. For example, `Kernel#system` refers people to `Kernel#spawn`, it doesn't repeat the entire `spawn` documentation for the argument handling where it is the same. For `String`, see `chop`/`chop!`, `chomp`/`chomp!`, `delete`/`delete!`, `downcase`/`downcase!` (and how `capitalize`/`capitalize!`/`upcase`/`upcase!` refer to `downcase`), etc.. I'm against unnecessary duplication in documentation. My level of discomfort with this change is: significant.

@jeremyevans, I would have happily settled for just your last word: significant.  :)

**Review by jeremyevans — APPROVED** [review]

**Comment by BurdetteLamar** [comment]
@jeremyevans , over the last year I've pushed 15-20 method docs for foo/foo! pairs that write up foo and foo! independently.  These have been reviewed, approved, and merged by several different Ruby committers.  Most of these are in Hash and Array, but also some earlier in ENV and CSV.

What about putting up a proposal in the guide, to see what others have to say, and to arrive at a consensus?

**Comment by jeremyevans** [comment]
For simple `foo/foo!` method pairs, I think it's fine to document them independently.  However, for more complex method pairs with extensive documentation, I think the cost of duplication outweighs the cost of indirection.

Certainly you can propose a change to the method documentation guide and see what other committers think regarding this.  It would be good to get feedback from other committers in this area.  Please be sure to reference this pull request as an example so that other committers have a good frame of reference when providing feedback.

**Comment by marcandre** [comment]
My preference is DRY.

Also, the way I understand `succ!` is that it's the in-place mutating version of `succ` and I like the doc to reflect that.

If the actual description of what the methods does fits in one or two sentences, I'd say it's ok to adapt it, otherwise I'd refer to the non-bang method for details.

**Pull request merged**
