### PR TITLE
String#squeeze and count: change other_str to limited_to

### PR DESCRIPTION
**Pull request by cielavenir**
@trans prefers limited_to and I agree with that.

cf: https://github.com/rubyworks/facets/pull/108

### CODE REVIEW

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this against master?

**Comment by k0kubun** [comment]
Let me close this as it has not been updated for a while. Please reopen this after resolving conflicts. Thanks.

**Comment by cielavenir** [comment]
@trans did not come to this thread and the discussion did not go well... But it is too emotional and I should not mention it too much...

**Comment by cielavenir** [comment]
Anyway, it is true that I don't see benefits to resolve conflicts right now.

**Comment by cielavenir** [comment]
This has been resolved positively in https://github.com/ruby/ruby/pull/5635

**Pull request closed without merging**
