### PR TITLE
Rename `D` to `debug` in `Net::HTTP`

### PR DESCRIPTION
**Pull request by baweaver**
Renames `D` to `debug` in `Net::HTTP` and introduces an alias for
backwards compatibility. This was done for readability reasons, in that
`D` did not clearly reflect what the method was doing and can cause some
confusion.

### CODE REVIEW

**Comment by ioquatix** [comment]
Yes please!

**Comment by hsbt** [comment]
@baweaver Can you submit this to https://github.com/ruby/net-http ? Thanks.

**Comment by baweaver** [comment]
@hsbt - Yep, one moment.

**Comment by baweaver** [comment]
Done. Let me know if you need anything else there.

**Pull request closed without merging**
