### PR TITLE
Fully separate positional arguments and keyword arguments

### PR DESCRIPTION
**Pull request by jeremyevans**

### CODE REVIEW

**Comment by jeremyevans** [comment]
The test-bundler failures appear to be due to:

```
/home/runner/work/ruby/ruby/src/tmp/1/gems/base/gems/mustermann-1.0.3/lib/mustermann/regular.rb:22:in `initialize': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

I think in order to fix this:

1. mustermann needs to be fixed (https://github.com/sinatra/mustermann/pull/97)
2. An updated mustermann gem needs  to be released
3. Bundler needs to be updated to use the updated mustermann version
4. Ruby needs to be updated to use the updated bundler

**Comment by namusyaka** [comment]
@jeremyevans Now the PR has been merged, and a new version including the changes has been released: https://rubygems.org/gems/mustermann/versions/1.1.0

**Comment by jeremyevans** [comment]
Now the failure is due to sinatra.  Sinatra needs a new release with the following commit: https://github.com/sinatra/sinatra/commit/d423f565ca9f461f3c2f1fe8bb08f708fef5d4e5.  Then bundler needs to be updated to use it, and the bundler changes merged into Ruby.

**Comment by namusyaka** [comment]
Released: https://rubygems.org/gems/sinatra/versions/2.0.8

**Pull request merged**
