### PR TITLE
Add `RB_` prefix for size_t to number conversion.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Review by nobu — APPROVED** [review]

**Comment by ioquatix** [comment]
@shyouhei I'd really value your input here as I trust you have a better eye for consistency given that you've been working on consistency across the whole code base.

**Review by phykos — APPROVED** [review]

**Comment by ioquatix** [comment]
Thanks @nobu :)

**Comment by shyouhei** [comment]
:+1: No idea why they have not been prefixed (maybe since the beginning?).  And sorry to be late!

**Comment by ioquatix** [comment]
Don't be sorry about it, I'd just like to coordinate any changes with your overall vision for consistency if possible :)

**Pull request merged**
