### PR TITLE
enc: Define missing `POSTLINK` variable in enc.mk

### PR DESCRIPTION
**Pull request by kateinoigakukun**
This is a follow up change to 71d511615b8dac459d6f88f5896b9859f99c999e 

Missing the variable definition caused `@` line in `enc.mk` and it's invalid with OpenBSD's make.
https://rubyci.s3.amazonaws.com/openbsd-current/ruby-master/log/20240302T093006Z.fail.html.gz
```console
rubyci-openbsd$ cat Makefile
foo:
	@
rubyci-openbsd$ make foo
: not found
*** Error 1 in /home/katei/tmp (Makefile:2 'foo': @)
```

### CODE REVIEW

**Comment by nobu** [comment]
How about importing used config variables automatically?

```diff
diff --git i/enc/Makefile.in w/enc/Makefile.in
index c57d6c17b5c..90e44e41a99 100644
--- i/enc/Makefile.in
+++ w/enc/Makefile.in
@@ -39,24 +39,12 @@ LIBRUBYARG_STATIC = $(LIBRUBYARG_SHARED)
 BUILTRUBY = $(topdir)/miniruby$(EXEEXT)
 
 empty =
-AR = @AR@
-LD = @LD@
-CC = @CC@
 ARFLAGS = @ARFLAGS@$(empty)
-RANLIB = @RANLIB@
 OUTFLAG = @OUTFLAG@$(empty)
 COUTFLAG = @COUTFLAG@$(empty)
 CFLAGS = $(CCDLFLAGS) @CFLAGS@ @ARCH_FLAG@
-cflags = @cflags@
-optflags = @optflags@
-debugflags = @debugflags@
-warnflags = @warnflags@
-CCDLFLAGS = @CCDLFLAGS@
 INCFLAGS = -I. -I$(arch_hdrdir) -I$(hdrdir) -I$(top_srcdir)
-DEFS = @DEFS@
 CPPFLAGS = @CPPFLAGS@ -DONIG_ENC_REGISTER=rb_enc_register
-LDFLAGS = @LDFLAGS@
-LDSHARED = @LDSHARED@
 ldflags  = $(LDFLAGS)
 dldflags = @DLDFLAGS@
 extdldflags = @EXTDLDFLAGS@
@@ -67,13 +55,7 @@ TARGET_NAME_ = $(@F) # BSD make seems unable to deal with @F with substitution
 TARGET_NAME = $(TARGET_NAME_:.@DLEXT@=)
 TARGET_ENTRY = @EXPORT_PREFIX@Init_$(TARGET_NAME)
 
-WORKDIRS = @WORKDIRS@
-
-NULLCMD = @NULLCMD@
-RM = @RM@
-RMDIR = @RMDIR@
-RMDIRS = @RMDIRS@
-MAKEDIRS = @MAKEDIRS@
+#### inherited variables ####
 
 .SUFFIXES: .trans
 
diff --git i/enc/make_encmake.rb w/enc/make_encmake.rb
index fcfc2c92678..bce75d62323 100755
--- i/enc/make_encmake.rb
+++ w/enc/make_encmake.rb
@@ -133,8 +133,26 @@
   dep = ""
 end
 mkin = File.read(File.join($srcdir, "Makefile.in"))
-mkin.gsub!(/@(#{CONFIG.keys.join('|')})@/) {CONFIG[$1]}
+vars = {}
+mkin.scan(/^\s*(\w+)\s*=/) {vars[$1] = true}
+keys = CONFIG.keys.join('|')
+refers = /\$\(\K(?:#{keys})(?=\))|\$\{\K(?:#{keys})(?=\})/
+inherited = {}
+scan_confvars = proc do |str|
+  str&.scan(refers) do |v|
+    unless vars[v] or inherited[v]
+      inherited[v] = scan_confvars.(CONFIG[v])
+    end
+  end
+  str
+end
+mkin.gsub!(/@(#{keys})@/) {scan_confvars.(CONFIG[$1])}
+scan_confvars.(dep)
+mkin = mkin.split(/\n#### inherited variables ####\n\K/, 2)
 File.open(ARGV[0], 'wb') {|f|
+  f.puts mkin.shift
+  inherited.each {|k, v| f.puts "#{k} = #{v}".strip}
+  f.puts
   f.puts mkin, dep
 }
 if MODULE_TYPE == :static
```

**Comment by kateinoigakukun** [comment]
Hmm, I'm hesitating to introduce a new Makefile template magic. I actually don't need make-time overriding for dependent variables `WASMOPT` and `wasmoptflags` for my workflow, so it might be simpler to expand those variables at configure-time

**Comment by kateinoigakukun** [comment]
Or how about just using `RbConfig::CONFIG` instead of `RbConfig::MAKEFILE_CONFIG` by default to substitute variables in Makefile? We can still use `::CONFIG` for inherited variables you often use to override if you want.

```diff
diff --git a/enc/make_encmake.rb b/enc/make_encmake.rb
index fcfc2c9267..39e144d842 100755
--- a/enc/make_encmake.rb
+++ b/enc/make_encmake.rb
@@ -133,7 +133,12 @@ def target_transcoders
   dep = ""
 end
 mkin = File.read(File.join($srcdir, "Makefile.in"))
-mkin.gsub!(/@(#{CONFIG.keys.join('|')})@/) {CONFIG[$1]}
+mkin.gsub!(/@(#{RbConfig::CONFIG.keys.join('|')})@/) do
+  # Variables that should not be expanded in Makefile.in to allow
+  # overriding inherited variables at make-time.
+  not_expand_vars = %w(CFLAGS)
+  not_expand_vars.include?($1) ? CONFIG[$1] : RbConfig::CONFIG[$1]
+end
 File.open(ARGV[0], 'wb') {|f|
   f.puts mkin, dep
 }
```

**Comment by nobu** [comment]
It may be good enough, but `not_expand_vars` should be defined outside the `gsub!` loop.

**Pull request merged**
