### PR TITLE
Add resolv_timeout to TCPSocket

### PR DESCRIPTION
**Pull request by mmasaki**
Add `resolv_timeout` to `TCPSocket.new`.
It makes DNS timeout customizable in the same way as `Socket.tcp`.

### CODE REVIEW

**Comment by mmasaki** [comment]
merged in 511fe23fa2bdf1f17faa91e0558be47b5bb62b2a

**Comment by ioquatix** [comment]
Great, this seems like useful feature. However, do you think we should call it `resolve_timeout`?

**Comment by mmasaki** [comment]
I intended to make it consistent with Socket.tcp (it accepts `resolv_timeout`).

**Comment by ioquatix** [comment]
When was `Socket.tcp` with `resolv_timeout` implemented? It seems like poor naming convention.

**Comment by mmasaki** [comment]
It was in 2019. 0e9d56f5e73ed2fd8e7c858fdea7b7d5b905bb64
Should we support `resolve_timeout` instead?

**Comment by ioquatix** [comment]
I think we should add `resolve_timeout` and add a 2nd option to `Socket.tcp` and add a deprecation warning for `resolv_timeout`. What do you think?

**Pull request closed without merging**
