### PR TITLE
YJIT: Upgrade bindgen to stabilize and reduce output

### PR DESCRIPTION
**Pull request by XrXr**
The new version has an option to merge everything into a big
`extern "C"` block and it's nicer.

More importantly, this upgrade fixes an issue where Ubuntu with Clang 12
and macOS with Clang 14 gave a one line diff for `rb_shape_t`. It was
slightly annoying because we use macOS locally.

### CODE REVIEW

**Comment by XrXr** [comment]
```
thread '<unnamed>' panicked at 'yjit invalidate rewrote branch past end of invalidated block: Branch { start: Some(CodePtr(0xaaaad18dcfdc)), end: Some(CodePtr(0xaaaad18df028)), targets: [Some(BranchTarget { address: Some(CodePtr(0xaaaad1ba9dd8)), id: BlockId { iseq: 0xffffb615f5e0, idx: 254 }, ctx: Context { stack_size: 5, sp_offset: 3, chain_depth: 1, local_types: [Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown, Unknown], temp_types: [Unknown, CString, CString, Fixnum, Fixnum, Unknown, Unknown, Unknown], self_type: UnknownHeap, temp_mapping: [MapToSelf, MapToStack, MapToStack, MapToStack, MapToStack, MapToStack, MapToStack, MapToStack] }, block: None }), None] } (code_size: 8260)', src/core.rs:2284:13
```
😲

**Comment by k0kubun** [comment]
🤔 Is it an unrelated problem?

**Comment by XrXr** [comment]
Hard to say, but it's probably not reproducible 😅

**Review by k0kubun — APPROVED** [review]
omg it disappeared by the retry 😬 it seems like we got one more crash to be fixed.

**Review by maximecb — APPROVED** [review]

**Pull request merged**
