### PR TITLE
[DOC] Remove Array#abbrev

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Doesn't seem to be in master any more. (Don't know what happened to it.)

### CODE REVIEW

**Comment by adam12** [comment]
It needs to be required first (unfortunately).

```ruby
require "abbrev"

["foo", "bar"].abbrev # => {"foo"=>"foo", "fo"=>"foo", "f"=>"foo", "bar"=>"bar", "ba"=>"bar", "b"=>"bar"}
```

**Comment by BurdetteLamar** [comment]
> It needs to be required first (unfortunately).
> 
> ```ruby
> require "abbrev"
> 
> ["foo", "bar"].abbrev # => {"foo"=>"foo", "fo"=>"foo", "f"=>"foo", "bar"=>"bar", "ba"=>"bar", "b"=>"bar"}
> ```

I see it documented at docs.ruby-lang.org in 3.1, 3.2, and 3.3, but not in master.  So will it be documented in 3.x, or not?

**Comment by adam12** [comment]
Oh, I see! I think it's [moved from default to bundled gem](https://github.com/ruby/ruby/commit/e28bdff94140bd9884e27ff1c42c31e121e65827) so presumably it's not included in the doc generation. Good catch.

**Comment by BurdetteLamar** [comment]
> Oh, I see! I think it's [moved from default to bundled gem](https://github.com/ruby/ruby/commit/e28bdff94140bd9884e27ff1c42c31e121e65827) so presumably it's not included in the doc generation. Good catch.

Thanks, @adam12.

**Review by peterzhu2118 — APPROVED** [review]

**Pull request merged**
