### PR TITLE
[DOC] Enhanced RDoc for Math module

### PR DESCRIPTION
**Pull request by BurdetteLamar**
- Revises intro.
- Adds "What's Here".
- Revises methods doc.

All this [reviewed and approved](https://github.com/BurdetteLamar/ruby/pulls?q=is%3Apr+is%3Aclosed) by @jeremyevans.

### CODE REVIEW

**Comment by jeremyevans** [comment]
I reviewed these in @BurdetteLamar's repository, and I'm OK with the changes. This should definitely be squashed before or when merging.

After going through this review process in a separate repository, I highly recommend against doing so for future documentation updates.  Future documentation updates should be submitted as normal pull requests to ruby/ruby, not batched up in a different repository and then merged into ruby/ruby.

**Review by jeremyevans — APPROVED** [review]
As I mentioned (https://github.com/ruby/ruby/pull/5837#issuecomment-1106747509), I'm OK with these changes.  Make sure to squash when merging.

**Comment by BurdetteLamar** [comment]
@jeremyevans, this has been up for three days (albeit largely weekend days).  Does we need to wait for anyone else to approve?

**Comment by jeremyevans** [comment]
> @jeremyevans, this has been up for three days (albeit largely weekend days). Does we need to wait for anyone else to approve?

I think it's fine to squash and merge now.

**Pull request merged**
