### PR TITLE
Ractor::LVar

### PR DESCRIPTION
**Pull request by ko1**
Ractor::LVar is Ractor-Local-Variable.
You can access LVar with value and value= methods, and they are
stored in per-Ractor storage.

https://bugs.ruby-lang.org/issues/17323

### CODE REVIEW

**Comment by marcandre** [comment]
I'm sorry, I don't understand the usefulness 😊
Could you provide an example of use-case?

**Comment by ko1** [comment]
> Could you provide an example of use-case?
> Is it to share a value between threads for a particular Ractor?

For example, if you want to make an cache per-ractor, you can use it.

```ruby
class Fib
  attr_reader :cache

  def initialize
    @cache = Ractor::LVar.new{ {} }
  end

  private def _fib n
    if n < 2
      1
    else
      fib(n-1) + fib(n-2)
    end
  end

  def fib n
    if v = @cache.value[n]
      v
    else
      ans = _fib(n)
      @cache.value[n] = ans
    end
  end
end

fiboner = Fib.new
p fiboner.fib(10) #=> 89
pp fiboner.cache.value
#=> {1=>1, 0=>1, 2=>2, 3=>3, 4=>5, 5=>8, 6=>13, 7=>21, 8=>34, 9=>55, 10=>89}
```

**Comment by marcandre** [comment]
So in your example, the feature is that the cache is not deeply copied when you pass that object to the Ractor?

Are there other use-cases?

**Comment by ko1** [comment]
> So in your example, the feature is that the cache is not deeply copied when you pass that object to the Ractor?

Yes. LVars are shareable.

> Are there other use-cases?

I'm not sure it is a feasible example, but we can set separate configuration between ractors.

Another idea is to provide unshareable, but similar to global variables, such as Random::DEFAULT which is discussed on https://bugs.ruby-lang.org/issues/17322.
We can use LVar to implement Ractor::default.

**Comment by ko1** [comment]
Rejected by Matz.

**Comment by marcandre** [comment]
Oh, I see. Has there been discussion about a mecanism for user classes to specify out to deep-clone them for Ractor passing, or at the very least to know they are being deeply-cloned for that?

**Comment by ko1** [comment]
I'll file the reason why it is closed on redmine.

> Oh, I see. Has there been discussion about a mecanism for user classes to specify out to deep-clone them for Ractor passing, or at the very least to know they are being deeply-cloned for that?

`Ractor.shareable?(obj)` and https://bugs.ruby-lang.org/issues/17273 are not enough?

**Comment by marcandre** [comment]
> `Ractor.shareable?(obj)` and https://bugs.ruby-lang.org/issues/17273 are not enough?

It is not clear to me, no.

For example, in your `Fib` example, if you wanted to:
- share `@cache` if possible (normal shallow dup)
- start new from `{}` otherwise (when Ractor copy)

It is feasible, but difficult:

```ruby
class RactorAutoUnshare < DelegateClass(Hash)
  def initialize_copy(_)
    # assume ractor-copy, as cache is internal and we never clone it ourselves
    __setobj__({}) # start from scratch
  end
end

class Fib
  def initialize
    @cache = RactorAutoUnshare.new({})
  end
  # ...
end
```
 
Did not test, but in theory that would work, but is technical, verbose, and needs indirection (via DelegateClass)...

I don't see a clear and clean solution, but it would be nicer to be able to specify how to deep copy an object. For example if we could write instead:

```ruby
class Fib
  def initialize
    @cache = {}
  end

  def initialize_clone(_fib, freeze: nil, deep: false)
    super
    @cache = {} if deep
  end
  # ...
end
```

**Comment by ko1** [comment]
`RactorAutoUnshare` is similar to `LVar` here?
With Endoh-san, we discussed same idea (delegator for per-ractor object), but it seems difficult to accept.

The reason why this proposal is rejected is, it is difficult to know it returns different value per ractor.
( Matz expected `foo.value` should be same) I don't agree his statement 100%, but it is reasonable objection.

I will provide LVar functionality with ractor-lvar gem, and try to understand it is confusing or not.
Also per-ractor proxy object like `RactorAutoUnshare` can be. However, we discussed that it can bring some troubles of the delegator class (which methods are really delegated or not). Creation interface is `Ractor::PerRactorProxy.new{ initial_value }` ?

At least, `Ractor#[]` like storage interface like `Thread#[]` will be provided in core

**Comment by marcandre** [comment]
> ractor-lvar gem

Ah, cool.

So we'll see what are the actual needs and we can advise for next year :-)

**Comment by ko1** [comment]
Also we can change the method name like `ractor_local_value` it can say clearly.

```
@cache = Ractor::LocalVariable.new{ Hash.new }
@cache.ractor_local_value[ key ] = val
```

It is clear that it can return ractor local values.

**Comment by marcandre** [comment]
Agreed, that makes it clearer

**Pull request closed without merging**
