### PR TITLE
Move structs to classes, ~1.10x faster Ripper.lex

### PR DESCRIPTION
**Pull request by schneems**
## Concept

I am proposing we replace the Struct implementation of data structures inside of ripper with real classes.

This will improve performance and the implementation is not meaningfully more complicated.

## Example

Struct versus class comparison:

```ruby
Elem = Struct.new(:pos, :event, :tok, :state, :message) do
  def initialize(pos, event, tok, state, message = nil)
    super(pos, event, tok, State.new(state), message)
  end

  # ...

  def to_a
    a = super
    a.pop unless a.empty?
    a
  end
end

class ElemClass
  attr_accessor :pos, :event, :tok, :state, :message

  def initialize(pos, event, tok, state, message = nil)
    @pos = pos
    @event = event
    @tok = tok
    @state = State.new(state)
    @message = message
  end

  def to_a
    if @message
      [@pos, @event, @tok, @state, @message]
    else
      [@pos, @event, @tok, @state]
    end
  end
end

# stub state class creation for now
class State; def initialize(val); end; end
```

## MicroBenchmark creation

```ruby
require 'benchmark/ips'
require 'ripper'

pos = [1, 2]
event = :on_nl
tok = "\n".freeze
state = Ripper::EXPR_BEG

Benchmark.ips do |x|
  x.report("struct") { Elem.new(pos, event, tok, state) }
  x.report("class ") { ElemClass.new(pos, event, tok, state) }
  x.compare!
end; nil
```

Gives ~1.2x faster creation:

```
Warming up --------------------------------------
              struct   263.983k i/100ms
              class    303.367k i/100ms
Calculating -------------------------------------
              struct      2.638M (± 5.9%) i/s -     13.199M in   5.023460s
              class       3.171M (± 4.6%) i/s -     16.078M in   5.082369s

Comparison:
              class :  3170690.2 i/s
              struct:  2638493.5 i/s - 1.20x  (± 0.00) slower
```

## MicroBenchmark `to_a` (Called by Ripper.lex for every element)

```ruby
require 'benchmark/ips'
require 'ripper'

pos = [1, 2]
event = :on_nl
tok = "\n".freeze
state = Ripper::EXPR_BEG

struct =  Elem.new(pos, event, tok, state)
from_class = ElemClass.new(pos, event, tok, state)

Benchmark.ips do |x|
  x.report("struct") { struct.to_a }
  x.report("class ") { from_class.to_a }
  x.compare!
end; nil
```

Gives 1.46x faster `to_a`:

```
Warming up --------------------------------------
              struct   612.094k i/100ms
              class    893.233k i/100ms
Calculating -------------------------------------
              struct      6.121M (± 5.4%) i/s -     30.605M in   5.015851s
              class       8.931M (± 7.9%) i/s -     44.662M in   5.039733s

Comparison:
              class :  8930619.0 i/s
              struct:  6121358.9 i/s - 1.46x  (± 0.00) slower
```

## MicroBenchmark data access

```ruby
require 'benchmark/ips'
require 'ripper'

pos = [1, 2]
event = :on_nl
tok = "\n".freeze
state = Ripper::EXPR_BEG

struct =  Elem.new(pos, event, tok, state)
from_class = ElemClass.new(pos, event, tok, state)

Benchmark.ips do |x|
  x.report("struct") { struct.pos[1] }
  x.report("class ") { from_class.pos[1] }
  x.compare!
end; nil
```

Gives ~1.17x faster data access:

```
Warming up --------------------------------------
              struct     1.694M i/100ms
              class      1.868M i/100ms
Calculating -------------------------------------
              struct     16.149M (± 6.8%) i/s -     81.318M in   5.060633s
              class      18.886M (± 2.9%) i/s -     95.262M in   5.048359s

Comparison:
              class : 18885669.6 i/s
              struct: 16149255.8 i/s - 1.17x  (± 0.00) slower
```

## Full benchmark integration of this inside of Ripper.lex

Inside of this repo with this commit

```
$ cd ext/ripper
$ make
$ cat test.rb
file = File.join(__dir__, "../../array.rb")
source = File.read(file)

bench = Benchmark.measure do
  10_000.times.each do
    Ripper.lex(source)
  end
end

puts bench
```

Then execute with and without this change 50 times:

```
rm new.txt
rm old.txt
for i in {0..50}
do
  `ruby -Ilib -rripper -rbenchmark ./test.rb >> new.txt`
  `ruby -rripper -rbenchmark ./test.rb >> old.txt`
done
```

I used derailed benchmarks internals to compare the results:

```
dir = Pathname(".")
branch_info = {}
branch_info["old"]  = { desc: "Struct lex", time: Time.now, file: dir.join("old.txt"), name: "old" }
branch_info["new"]  = { desc: "Class lex", time: Time.now, file: dir.join("new.txt"), name: "new" }
stats = DerailedBenchmarks::StatsFromDir.new(branch_info)
stats.call.banner
```

Which gave us:

```
❤️ ❤️ ❤️  (Statistically Significant) ❤️ ❤️ ❤️

[new] (3.3139 seconds) "Class lex" ref: "new"
  FASTER 🚀🚀🚀 by:
    1.1046x [older/newer]
    9.4700% [(older - newer) / older * 100]
[old] (3.6606 seconds) "Struct lex" ref: "old"

Iterations per sample:
Samples: 51

Test type: Kolmogorov Smirnov
Confidence level: 99.0 %
Is significant? (max > critical): true
D critical: 0.30049534876137013
D max: 0.9607843137254902

Histograms (time ranges are in seconds):

   [new] description:                                        [old] description:
     "Class lex"                                               "Struct lex"
              ┌                                        ┐                ┌                                        ┐
   [3.0, 3.3) ┤▇ 1                                           [3.0, 3.3) ┤ 0
   [3.3, 3.6) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 47       [3.3, 3.6) ┤ 0
   [3.5, 3.8) ┤▇▇ 2                                          [3.5, 3.8) ┤▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 46
   [3.8, 4.1) ┤▇ 1                                           [3.8, 4.1) ┤▇▇▇ 4
   [4.0, 4.3) ┤ 0                                            [4.0, 4.3) ┤ 0
   [4.3, 4.6) ┤ 0                                            [4.3, 4.6) ┤▇ 1
              └                                        ┘                └                                        ┘
                         # of runs in range                                        # of runs in range
```

To sum this up, the "new" version of this code (using real classes instead of structs) is 10% faster across 50 runs with a statistical significance confidence
level of 99%. Histograms are for visual checksum.

## Consequences

This is a breaking change as seen by the modifications needed to IRB (because the element no longer acts as an array as well). However, this constant is technically marked as "internal" via docs.

I want to gauge interest in such a change. What do you think of this opportunity to increase performance and tighten the API? If you like it, what are your thoughts on moving forwards? 

At a high level, the two options I see are: 

1) Break that API

If we go this route, we can support IRB's lex usage out of the box. I don't know how many other gems might be accessing the contents of `Lexer::Elem`. To gauge impact it might be possible to do some kind of a code scan on github, or maybe rubygems. By default it's not exposed via `Ripper.lex` so searching for `Lexer.new` should yield high-signal-low-noise results.

It looks like via https://github.com/search?q=Ripper%3A%3ALexer.new&type=code there are 1,225 results. However it looks like there's more than a few forks of the Ruby project that github does not identify as forks. I could filter by something else like more than 5 stars, but for some reason, the UI returns no results for these cases for me.

2) Perform a deprecation cycle where we deprecate the Struct methods (such as `[]` and `each_with_index`).

I've explored it a little, but the work is ultimately unknown. I think these are the methods we would need to implement in order to deprecate them:

```
[:pretty_print_cycle, :to_a, :==, :to_s, :[], :[]=, :deconstruct, :eql?, :each_pair, :select, :to_h, :filter, :values, :inspect, :deconstruct_keys, :dig, :members, :length, :size, :pretty_print, :each, :hash, :values_at]
```

### CODE REVIEW

**Comment by mame** [comment]
Thank you for your contribution! I like this change.

I confirmed the performance improvement with rdoc, a macro benchmark that uses Ripper.lex.

Without this patch:

```
$ rm -rf .ext/rdoc && time ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./libexec/rdoc" --root "." --encoding=UTF-8 --all --ri --op ".ext/rdoc" --page-dir "./doc" --no-force-update  "."
...
real    0m18.468s
user    0m18.060s
sys     0m0.400s
```

With this patch:

```
real    0m18.029s
user    0m17.691s
sys     0m0.336s
```

The speed up ratio is not so big (about 2%), but I ran them a few times to make sure it wasn't an error.

I understand this improvement as follows: (1) `tok.pos` is faster than `tok[0]`, and (2) attr_reader is faster than struct field access.

In regard to the incompatiblity,

> 2. Perform a deprecation cycle where we deprecate the Struct methods (such as `[]` and `each_with_index`).

I vote for this. IMO, it would be enough to mimic only `[]` for almost all cases. (I guess you mentioned `each_with_index` because of [this hunk](https://github.com/ruby/ruby/pull/5093/files#diff-00cab56d5cd91c959d4b06968b45aa010de48631b54a18593aabca9c261d075eR169), but I believe this code is a bug that just happens to be working well :-)

**Comment by schneems** [comment]
@mame thank you for the consideration. I updated to add `[]` method back in along with a deprecation https://github.com/ruby/ruby/pull/5093/commits/a66b299360168399f8684573d5646d1ed8740528. I've marked this as ready to review. Please take a look.

**Comment by k0kubun** [comment]
No objection to optimize `Ripper.lex`, which I'm a heavy user of, but you might also like https://github.com/ruby/ruby/pull/5131.

**Comment by mame** [comment]
@schneems Sorry for my late action. As k0kubun said, ko1 has improved the performance of field access of Struct. Could you measure the performance again?

**Comment by schneems** [comment]
## Master performance

I checked the performance of master after that commit versus 3.1.0-preview1 and it looks like master is slower by ~1.8% here are my raw numbers and benchmark scripts: https://gist.github.com/schneems/1edfff044a082ca61f962066541dfdb4.

I don't know if there is something else with `make runruby` that might be affecting the results, or perhaps some other change to master is slowing those results down.

## This patch

I am not sure how to reliably integration-test this patch against that C change. Running `make runruby` with different branches doesn't appear to re-compile the struct code. I could perhaps `make clean` between changing branches but that would add far too much time to produce 50-200 iterations.

I did however run the micro-benchmarks after pulling from master and re-compiling. Here are the results: https://gist.github.com/schneems/e1faf9bd43c626536f3631f8e6506583

The struct access is indeed faster now. It's being reported as "about same difference" as the class access. It actually looks slightly faster but it's within the margin of error.

Both class creation and `to_a` are still faster using a class instead of a struct:

```
Comparison:
     class creation :  3361272.1 i/s
     struct creation:  2770825.9 i/s - 1.21x  (± 0.00) slower
```

```
Comparison:
          class to_a:  9602229.1 i/s
         struct to_a:  6825047.7 i/s - 1.41x  (± 0.00) slower
```

I think there is a benefit to speeding up those two operations.

**Comment by schneems** [comment]
I was curious about how often each of these operations are called in `Ripper.lex`. I annotated the sourced code with a simple count of a global (https://gist.github.com/schneems/957703e08a183ddd25e632a0d0315753) this is what I got:

```
$ ruby -Iext/ripper/lib -rripper -e "Ripper.lex(File.read('array.rb')); h = { create: \$count_create, to_a: \$count_to_a, access: \$count_access}; puts h.inspect"
{:create=>424, :to_a=>212, :access=>212}
```

So it looks like create is called about 2x as much as `to_a` while `to_a` and access operations are  dead even.

Based on that call count info and the micro benchmark I posted previously I think this has roughly the same 1.10x faster impact on `Ripper.lex`, however it will not speed up access for places that use the internal Elem API (such as IRB and `dead_end`) because Koichi's patch made struct access comparable to regular object access.

It is my experience (with `dead_end`) that the bulk of time is spent generating the lex information rather than in consuming it (however you and @aycabta have more first-hand knowledge there with IRB).

**Comment by schneems** [comment]
I also annotated the tests in `test/irb/test_ruby_lex`

```
diff --git a/test/irb/test_ruby_lex.rb b/test/irb/test_ruby_lex.rb
index 32463f7fb6..dc500e4c9d 100644
--- a/test/irb/test_ruby_lex.rb
+++ b/test/irb/test_ruby_lex.rb
@@ -602,5 +602,10 @@ def foo
         pos_to_index[t.pos] = i
       }
     end
+
+    def teardown
+      h = { create: $count_create, to_a: $count_to_a, access: $count_access};
+      puts h.inspect
+    end
```

These were the results:

```
.{:create=>45,452, :to_a=>0, :access=>289,587}
```

The object is accessed 6.37x more often than it is created (289,587/ 45,452 # ~> 6.37x) . From my microbenchmark object access is 5.8x faster than creation (19.642M / 3.361M # ~> 5.8x). I don't know how close the irb tests are to real-world use.

**Comment by mame** [comment]
Thank you very much, what great this feedback is!

> it looks like master is slower by ~1.8%

I guess we'll have to look into this one. @ko1 has already added :eyes: emoji, so I believe he will take a look :trollface:

**Comment by schneems** [comment]
Sounds good. @ko1 let me know if I can help or give extra information. Also to be clear, I agree that the struct patch worked and makes master access faster, I don’t know why the delta exists between preview1.

Also if struct access can be sped up, maybe struct creation can be sped up as well and we wouldn’t need my patch. I don’t have the familiarity to understand optimizing that C code though. I don’t know if there’s a fundamental blocker or if it’s just never been attempted.

**Comment by mame** [comment]
Wait, [the test script](https://gist.github.com/schneems/1edfff044a082ca61f962066541dfdb4#file-gistfile1-txt) uses `array.rb`, but *the file was changed* after 3.1.0-preview1 https://github.com/ruby/ruby/commit/a24eeee5567a14841b37d9a3428e14e4f3c45c07 🤣 Did you make sure to use the same content file?

**Comment by mame** [comment]
> ## This patch
> Both class creation and `to_a` are still faster using a class instead of a struct:

According to @ko1's investigation, in terms of instance creation, the main difference between the current impl. has an overhead for calling `super` in `State#initialize`.

```
def initialize(i) super(i, Ripper.lex_state_name(i)).freeze end
```

After your patch, `initialize` simply assigns the arguments to instance variables, with no call to `super`. I didn't investigate `to_a`, but maybe there's something similar.

Anyway, I tried the current master (df8f8581153b4df7e7f042afd088b905f13b654c) with and without your patch, and the performance improvement is still observable: 17.7 sec. → 17.4 sec. It is never big, but maybe good. I'd like to merge it unless there is objection.

**Comment by schneems** [comment]
> Wait, the test script uses array.rb, but the file was changed after 3.1.0-preview1 a24eeee 🤣 Did you make sure to use the same content file? 

Oops, I did not 🙈 good catch.

>  I'd like to merge it unless there is objection.

It is okay with me. Please let me know if there are more questions or any requests for changes.

**Comment by yahonda** [comment]
@mame As discussed offline, this change cause a lot of warnings at Rails console. Please consider to address it. 

https://gist.github.com/yahonda/8cbb81e193b10f7f1be7f6ffb2c738e5

**Comment by schneems** [comment]
@yahonda I tried to reproduce this using chruby:

## Repro

```
 1042  ./configure --prefix="$HOME/.rubies/ruby-3.1.0-schneems" --with-opt-dir="$(brew --prefix openssl):$(brew --prefix readline):$(brew --prefix libyaml):$(brew --prefix gdbm):$(brew --prefix libffi)"
 1043  make
 1044  make install
```

Then:

```
$ chruby ruby-3.1.0-schneems-dev
$ cd /tmp
$ gem install rails -v 6.1.4.1
$ rails _6.1.4.1_ new myapp
$ cd myapp
$ bin/rails c
```

I could not reproduce the behavior.

I then added an older version of IRB via the `Gemfile`:


```
gem "irb", "1.3.7"
```

Then I could see the problem. 

## Issue

The problem is that I introduced a deprecation warning into `lexer.rb`. When I did this I fixed all the warnings on main/master, but didn't consider that older versions of IRB can still be used with this version of lexer.

Older versions of IRB are still using the old API so they emit many deprecation warnings.

## Mitigation

I believe that https://github.com/ruby/ruby/pull/5093 is sufficient for full mitigation. I guessed that was the case before, but I also wanted to exercise `rails c` with the existing lexer to ensure I hadn't missed any deprecation locations (perhaps if they're not covered by tests). That appears to not be the case.

**Comment by yahonda** [comment]
Thanks for the update and the test case which does not reproduce the warnings.

I've found it reproduces with Rails 7 which installs `debug` gem by default https://github.com/rails/rails/blob/7c10fe108adfb1cd1c35ce44d5fbc0dd820c76d4/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L48

`debug` gem supports Ruby 2.6 https://github.com/ruby/debug/blob/321b12d785fbe39fba7a01670e0826c4fae8c912/debug.gemspec#L13 and it explicitly installs irb gem https://github.com/ruby/debug/blob/321b12d785fbe39fba7a01670e0826c4fae8c912/debug.gemspec#L28

Then, technically removing `gem "debug", ">= 1.0.0", platforms: %i[ mri mingw x64_mingw ]` from Rails 7 application's Gemfile would remove the warnings , I do not mean to suggest uninstall debug gem. 

Here are steps to reproduce https://gist.github.com/yahonda/1a92a7cf34ba54ead33e3423274754d1

**Pull request merged**
