### PR TITLE
Fix cross build

### PR DESCRIPTION
**Pull request by larskanis**
[rake-compiler-dock](https://github.com/rake-compiler/rake-compiler-dock) makes use of the cross build capability of ruby to provide a build environment targeting to the Windows-RubyInstaller. Unfortunately ruby-2.3.0-preview1 doesn't cross build because of two issues. These are addressed in the attached commits.

### CODE REVIEW

**Comment by hsbt** [comment]
@nobu Please review this

**Comment by nobu** [comment]
Does "outside of builddir" mean an absolute path?
`nmake` does not have `-j` option, does it?

**Comment by larskanis** [comment]
> Does "outside of builddir" mean an absolute path?

Yes, rake-compiler extracts the tar file to `~/.rake-compiler/sources/` but the build runs in `~/.rake-compiler/builds/` . That works with ruby-1.8.7 to 2.2, but not with 2.3.0-preview1.

> nmake does not have -j option, does it?

There is no -j for nmake, but a cross build can be done with gnu make and `-j` . Using parallel workers for cross build runs fine for ruby-2.0 to 2.2, but not yet for 2.3.0-preview1.

**Comment by nobu** [comment]
`win32/Makefile.sub` is only for `nmake`.
GNU make never and cannot read it.

**Comment by larskanis** [comment]
> win32/Makefile.sub is only for nmake.

Since the dependency is there, it's best to declare it in `Makefile.sub` as well, even if it's implicit resolved by the build order of nmake. However I did not test with nmake, but with gnu make only.

**Comment by nobu** [comment]
Merged with keeping a relative path relative.

**Comment by larskanis** [comment]
OK, thank you @nobu !

**Pull request closed without merging**
