### PR TITLE
Make benchmark to bundled gems

### PR DESCRIPTION
**Pull request by hsbt**
https://bugs.ruby-lang.org/issues/20309

### CODE REVIEW

**Comment by eregon** [comment]
https://bugs.ruby-lang.org/issues/20309 doesn't mention moving `benchmark` to bundled gems.
Was it discussed anywhere?

**Comment by hsbt** [comment]
Do not rush to me. I will discuss this at next meeting.

**Comment by eregon** [comment]
I didn't mean to rush you, but yes I think it would be good to have some discussion about it on a Redmine ticket.
Updating the existing ticket without a comment doesn't notify watchers of the issue or the mailing list (unfortunately).

FWIW I found out about this PR from @Earlopain who started making PRs assuming `benchmark` will become a bundled gem. I think it's a bit too early for that, before the final decision has been taken to make it a bundled gem. (but doing that work is very much appreciated, thanks!)

**Comment by hsbt** [comment]
I merged this change to https://github.com/ruby/ruby/pull/11560

**Pull request closed without merging**
