### PR TITLE
RJIT

### PR DESCRIPTION
**Pull request by k0kubun**
[[Feature #19420]](https://bugs.ruby-lang.org/issues/19420)

### CODE REVIEW

**Comment by k0kubun** [comment]
> Notifying once per push would probably solve that.

Yeah, most likely. I may try that path next time.

> Regarding the Headline benchmarks, would you also have numbers with enough warmup for MJIT?

I used your [warmup harness](https://github.com/eregon/yjit-bench/blob/run_all/harness-warmup/harness.rb) and this was the medians that it printed ([full details](https://gist.github.com/k0kubun/7e6a1b3b4f9109742408058334ee281d)):

|bench         |interp (ms)|yjit (ms)|rjit (ms)|mjit (ms)|
|--------------|-----------|---------|---------|---------|
|activerecord  | 111       | 67      | 94      | 112     |
|hexapdf       | 1807      | 1173    | 1593    | 1777    |
|liquid-c      | 44        | 31      | 38      | 44      |
|liquid-render | 110       | 62      | 83      | 91      |
|mail          | 94        | 72      | 88      | 97      |
|psych-load    | 1432      | 986     | 1174    | 1202    |
|railsbench    | 1497      | 980     | 1340    | 1584    |
|ruby-lsp      | 45        | 33      | 40      | 95      |
|sequel        | 89        | 79      | 103     | 194     |

Also [this](https://gist.github.com/k0kubun/10ae929640aabf933fb93f2059b9fa35) was the last time I seriously benchmarked MJIT with enough warmup. At least on railsbench, I've only seen 1.02~1.05x speedup with MJIT at best, so RJIT will most likely be faster than MJIT regardless.

**Comment by tenderlove** [comment]
Now I need to make TenderJIT outperform RJIT 🤣

**Comment by k0kubun** [comment]
Good news is that you've got a lot of new `RubyVM::MJIT::C` APIs (which will be `RubyVM::RJIT::C` soon) for making that happen 😄

**Comment by jensengrey** [comment]
This is amazing. Wonderful work. 

The benchmark times include JIT overhead correct? Is there a graph of *just* the JIT overhead. What Ruby methods does RJIT rely heavily on and could they be sped up by RJIT? How does one use RJIT to make RJIT itself faster (lower latency).

**Comment by k0kubun** [comment]
Full details are in https://gist.github.com/k0kubun/4e31fd289f8e3543dc094421eca90861. I haven't implemented a feature to render a graph to visualize the warmup performance, but you can see how it behaves on the 1st iteration, etc.

**Pull request merged**
