### PR TITLE
Removed bundler-vendored files

### PR DESCRIPTION
**Pull request by nobu**
Remove duplicate and out-of-date files, which are not only confusing but also cause overridden constant warnings.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@nobu Unfortunately we need this so that people can choose the version of `fileutils` and `uri` that they want to use in their `Gemfile`'s. If this is passing CI, it means we're probably skipping the relevant tests under the ruby-core setup, but this will break things for our users, specially `fileutils`, which has a handful of released versions.

Please open a ticket upstream to discuss instead of making unilateral changes like this :pray: 

Also, please report the redefinition warnings so we can fix them.

**Comment by deivid-rodriguez** [comment]
Actually using `uri` inside `Gemfile`'s is not actually working due to being loaded by `rubygems`. It's not yet a problem because `uri` has a single released gem. So I guess we can unvendor that temporarily if you feel strongly about it, although we might have to reintroduce it if we want to support it in the future.

Regarding `fileutils`, maybe it's not needed either, but could you please open a ticket or PR upstream so we can be sure? We can live with patches being pushed directly here so that you can keep your CI green, but bigger changes should be discussed upstream, don't you think?

**Comment by deivid-rodriguez** [comment]
I'm double checking this with bundler's CI here: https://github.com/rubygems/rubygems/pull/3700. It would be nice to get rid of this indeed :crossed_fingers:.

**Comment by hsbt** [comment]
I'm happy to replace `FileUtils` to `File` and `Dir` implementations for activating problem. But `URI` is difficult for this.

**Comment by deivid-rodriguez** [comment]
I was having the exact same thought! If there's not many places where `bundler/setup` activates `fileutils`, we can replace those with `Dir` and `File` :+1:.

**Comment by simi** [comment]
I had the same idea as well for fileutils. I can open PR in rubygems if needed.

**Comment by deivid-rodriguez** [comment]
Regarding `URI`, we're going to at least have to maintain our minimal implementation, so to me it seems simpler to vendor the `URI` implementation. There's many stuff we could avoid though such as `URI::LDAP`, `URI::LDAPS`, URI::MailTo`, `URI::Ftp` and so on.

**Comment by deivid-rodriguez** [comment]
Well, it sounds like `Bundler::FileUtils` is not being used at all by `bundler/setup`, so @nobu is right and this is not needed! Also made a manual realworld test of trying to pin a `Gemfile` to `fileutils 1.1.0` on ruby 2.7 where the default version is `1.4.1` and it worked fine even after removing the vendored copy. My apologies since I believe I spoke too early :sweat_smile:.

**Comment by deivid-rodriguez** [comment]
But now I'm making other tests and I'm not getting the results I expect... I'd like to look at this more careful and move this discussion to https://github.com/rubygems/rubygems/pull/3700 if that's ok with you all.

**Comment by nobu** [comment]
These two libraries seem to have no significant differences.
I'm curious why only they are special, but not others, as Bundler seems using gemified libraries more.

**Comment by deivid-rodriguez** [comment]
The problem is that `bundler/setup` uses these internally (turns out it might not, but let's say it does). That means when `bundler/setup` is required, the default gem version of these gems gets activated, and that can conflict with the version the user has chosen to specify in the `Gemfile`.

**Comment by nobu** [comment]
I see, got it.
So let's close this for now.

**Pull request closed without merging**
