### PR TITLE
Add missing OP_CCLASS_MB case in init_cache_table_index

### PR DESCRIPTION
**Pull request by makenowjust**
Fix https://bugs.ruby-lang.org/issues/19104#note-4 report.

The reason for this bug is that the line `case OP_CCLASS_MB:` is missing in the function `init_cache_table_index`.
Thank you @byroot for report!

### CODE REVIEW

**Comment by byroot** [comment]
Thank you. I just triggered another CI build with this patch. I'll report back in ~30m.

**Review by byroot — APPROVED** [review]
Our CI is now all green with this patch. Thank you!

**Comment by eregon** [comment]
Wouldn't it be safer to add `default:` case in the switch and `rb_bug()` or some fallback in there?

**Comment by makenowjust** [comment]
@eregon I'm not sure calling `rb_bug()` from Onigmo code is possible or good practice. I added to return `ONIGERR_UNDEFINED_BYTECODE` or `ONIGERR_UNEXPECTED_BYTECODE` instead.

**Review by mame — APPROVED** [review]

**Pull request merged**
