### PR TITLE
Correct doc return values for some ENV methods

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Comment by krzysiek1507** [comment]
Psst! You don't have to create a new branch and PR when you want to update your changes. You can use `git commit --amend` to commit your changes to the last commit and then `git push origin branch_name -f` (or `--force`) to push it to the remote branch. The changes will just appear.

**Comment by BurdetteLamar** [comment]
Psst!  There are no changes, so even --force does not work.

I don't know why or how the build fails, when the changes are all in the comments.  I have no changes to make, so I need somehow to get  a new build started.  Any suggestion how to get a failed build to restart will be welcome.

**Comment by krzysiek1507** [comment]
You can try `git commit --amend` without changes and `git push` with `--force`. It should change the commit hash and it should trigger builds.

BTW. Does it matter if tests are green when the only thing you change is comments?

**Comment by BurdetteLamar** [comment]
Thanks, I will try those.  I doubt that anyone will merge a PR that's not green, but do you think I should leave a red PR and hope for the best?

**Comment by krzysiek1507** [comment]
I think so.

**Comment by BurdetteLamar** [comment]
A while back, one of The Powers That Be marked one of my PRs as "no ci," b/c it was comments (doc) only.  Is that possible here?

**Pull request closed without merging**
