### PR TITLE
WIP: memory_view: finalizer GC safety issue

### PR DESCRIPTION
**Pull request by XrXr**
The finalizer of Fiddle::memory_view uses rb_memory_view_release(),
which traverses the super chain to find the memory view entry. Trouble
is, while finalizing object x, it's unsafe to access any object other
than x. Depending on finalization order, other objects might have been
finalized and released already.

This memory safety issue manifests as a crash on my machine reliably
when I run the following:

    make test-all TESTS='test/fiddle/test_memory_view.rb -n/test_memory_view_from_pointer/'

On CI, there are many instances of this crash. For example:
 - http://rubyci.s3.amazonaws.com/osx1015/ruby-master/log/20211022T114502Z.fail.html.gz
 - http://rubyci.s3.amazonaws.com/solaris10-sunc/ruby-master/log/20211022T090002Z.fail.html.gz

This change checks for object liveness before access, however, I don't
think this fix is completely correct while it does avoid the crash.

In the event that the klass which stores the memory view entry is
finalized before rb_memory_view_release is called, the memory view entry
will be leaked. Also, it's possible that during finalization, the
address of the super class has been repurposed for a different object.

It seems that memory view needs to handle double-free coming from the
above situation. One free comes the class storing the entry going away,
and another when the Fiddle object finalizes.

cc: @ko1 @mrkn

### CODE REVIEW

**Comment by sergiodj** [comment]
Hi,

FWIW, I've been helping with the Ruby 3.0 transition on Debian and found that [ruby-netcdf](https://tracker.debian.org/pkg/ruby-netcdf) causes the ruby interpreter to segfault with a very similar output than the ones that can be found in the links from the description of this PR.

If you're interested, here's the corresponding Debian bug with an excerpt of the crash message:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=996324

I spent some time debugging it, and even built a version of Ruby with the patches available here, but unfortunately the problem still persists.  I left a message briefly explaining what I did in the Debian bug above, but I'd be happy to provide more details if needed.

Thanks.

**Comment by XrXr** [comment]
@sergiodj Looks like it's not related to this issue. `memory_view` is new in Ruby 3.0 so the old gem can't be using it.

**Comment by mrkn** [comment]
I consulted with @ko1 about how to fix this issue yesterday.
As the consequence, we found that we can stop looking up memory view entry in class at `rb_memory_view_release`.
I'm trying this approach in #5088.

**Comment by XrXr** [comment]
Avoiding the lookup altogether sounds good to me since I also had the same idea: https://github.com/ruby/ruby/pull/5012#discussion_r736934129 :). Closing this in favor of #5088.

**Pull request closed without merging**
