### PR TITLE
[Bug #19108] Check for the encoding of pack/unpack format

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Comment by eregon** [comment]
This fixes the issue in there but not https://bugs.ruby-lang.org/issues/19108#note-3. I believe we should fix both.

**Comment by nobu** [comment]
> This fixes the issue in there but not https://bugs.ruby-lang.org/issues/19108#note-3. I believe we should fix both.

It seems a different issue.

**Comment by eregon** [comment]
Should I file a different Redmine ticket then?
In my view it's the same issue: pack/unpack unexpectedly uses $VERBOSE=true warnings instead of exceptions for erroneous cases.

**Comment by eregon** [comment]
I filed https://bugs.ruby-lang.org/issues/19150

**Pull request merged**
