### PR TITLE
Use write barriers for Backtrace objects

### PR DESCRIPTION
**Pull request by jhawthorn**
Follow up to #7240, which enabled WB for Backtrace::Location. cc @casperisfine @peterzhu2118 

Backtrace objects hold references to:
* iseqs - via the captured `rb_backtrace_location_t`
* strary - a lazily allocated array of strings
* locary - a lazily allocated array of backtrace locations

Co-authored-by: Adam Hess <HParker@github.com>

### CODE REVIEW

**Review by peterzhu2118 — COMMENTED** [review]
It looks like `bt_update_cfunc_loc` updates the iseq on the backtrace buffer, we might need a write barrier there.

**Comment by casperisfine** [comment]
I assume the `backtrace_update` (compact function), doesn't need to fire write barriers?

**Comment by peterzhu2118** [comment]
> I assume the backtrace_update (compact function), doesn't need to fire write barriers?

The compact function doesn't need to fire write barriers.

**Comment by jhawthorn** [comment]
> It looks like `bt_update_cfunc_loc` updates the iseq on the backtrace buffer, we might need a write barrier there.

I think (?) those are covered. It's called from two locations in `rb_ec_partial_backtrace_object`, for the first it's assigning an iseq right after we `RB_OBJ_WRITE` just into other locations, and in the second we call `RB_OBJ_WRITTEN(btobj, Qundef, cfp->iseq);` afterwards.

**Pull request merged**
