### PR TITLE
[ruby/etc] Tag `etc` as Ractor-safe

### PR DESCRIPTION
**Pull request by marcandre**
The only state is via `getgrent` which is thread-safe

### CODE REVIEW

**Comment by ko1** [comment]
```ruby
static void
each_group(void)
{
    if (group_blocking) {
	rb_raise(rb_eRuntimeError, "parallel group iteration");
    }
    group_blocking = (int)Qtrue;
    rb_ensure(group_iterate, 0, group_ensure, 0);
}
```

It can be race with other ractors without synchronization.

**Comment by ko1** [comment]
ditto:

```C
static void
each_passwd(void)
{
    if (passwd_blocking) {
	rb_raise(rb_eRuntimeError, "parallel passwd iteration");
    }
    passwd_blocking = (int)Qtrue;
    rb_ensure(passwd_iterate, 0, passwd_ensure, 0);
}
```

**Comment by marcandre** [comment]
> ditto:
> 
> ```c
> static void
> each_passwd(void)
> {
>     if (passwd_blocking) {
> 	rb_raise(rb_eRuntimeError, "parallel passwd iteration");
>     }
>     passwd_blocking = (int)Qtrue;
>     rb_ensure(passwd_iterate, 0, passwd_ensure, 0);
> }
> ```

Ohhh, thanks, I add looked at `static` variables but missed this one. I wish is was easier to grep for those, they get confused with static functions.
I'll fix that tomorrow.

**Comment by ko1** [comment]
How to solve it?

* use ruby_atomic.h in srcdir (but it should be located in ext/, not supported in gem)
* use `rb_native_mutex_lock() in include/ruby/thread_native.h
* introduce another API for that?

**Comment by marcandre** [comment]
> How to solve it?

Since `getgrent` is thread-local, can I not use Ractor-local to store `passwd_blocking` above? This way one should be able to call `group{}` from two Ractors at the same time, no?

**Comment by ko1** [comment]
sorry I didn't read details and why the global recursive check is needed.

**Comment by marcandre** [comment]
You were right (of course 😅), only some platform have it thread-local. Using global mutex.

Is there a `#IFDEF` to check availability of `rb_native_mutex_trylock`?

**Comment by marcandre** [comment]
> Is there a `#IFDEF` to check availability of `rb_native_mutex_trylock`?

I used `HAVE_RB_EXT_RACTOR_SAFE`

**Comment by mrkn** [comment]
+1

**Comment by marcandre** [comment]
Thank you @ko1 for guidance and @mrkn for reviewing

**Pull request merged**
