### PR TITLE
Handle hash and splat nodes in defined?

### PR DESCRIPTION
**Pull request by jeremyevans**
This skips a prism test, because the prism compiler needs an update to fix this bug as well.

Fixes [Bug #20043]

### CODE REVIEW

**Review by ko1 — APPROVED** [review]

**Comment by kddnewton** [comment]
Hey @jeremyevans — I see that you're commenting out the prism test. Would you like to pair on implementing this in prism? Or is there any other way I can support you in this? Obviously we don't want to just merge this as-is, because if our tests keep getting commented out they're not functioning as tests anymore, just blockers.

**Comment by jeremyevans** [comment]
@kddnewton Thanks for checking.  I don't think I have time to pair, but if you can post a diff to update the prism compiler to fix this issue, I'd definitely like to incorporate it into this PR.

**Comment by kddnewton** [comment]
@jeremyevans yeah, happy to. Would you mind holding off merging this until it's ready?

**Comment by jeremyevans** [comment]
Sure, no rush.

**Comment by jeremyevans** [comment]
@kddnewton I think Matz approved this change at the last developer meeting. Any chance you could work on the prism changes so that this can be merged?

**Comment by kddnewton** [comment]
Hey @jeremyevans yeah absolutely I'll move it up on my list

**Comment by kddnewton** [comment]
Hey @jeremyevans — I hope it's okay, I rebased and pushed a new commit straight to your branch. I've fixed up all of the cases for prism, so it should be good to go.

One additional thing, I noticed that on this branch the `**` operator started crashing if it was in the middle of a hash. I've added support for it to the prism compiler, but I'm happy to remove it if you'd rather say those are just "expression". Let me know either way.

**Comment by jeremyevans** [comment]
@kddnewton Thanks for working on this.  I'll see if I can fix the parse.y compiler to handle `**` inside of hashes.

**Pull request merged**
