### PR TITLE
Use realpath(3) instead of custom realpath implementation if available

### PR DESCRIPTION
**Pull request by jeremyevans**
One reason to do this is simplicity, as this approach is ~30 lines of
code instead of ~200.  Performance wise, this performs 20%-115% better
on OpenBSD 6.5.  Benchmark included.

By using realpath(3), we can better integrate with system security
features such as OpenBSD's unveil(2) system call.

Do not use realpath(3) on Windows even if it is defined, as the
approach for checkign for absolute paths does not work for drive
letters.

When using RB_REALPATH_DIR, only use realpath(3) on OpenBSD and FreeBSD,
as those operating systems have a realpath(3) that does not require the
last component of the path to exist. On other operating systems,
fallback to the previous approach when RB_REALPATH_DIR is used.

Benchmark results (e1 with this commit, e2 without):

```
Warming up --------------------------------------
        relative_nil    59.391k i/s -     61.555k times in 1.036441s (16.84_s/i)
        absolute_nil    45.757k i/s -     45.804k times in 1.001025s (21.85_s/i)
   relative_relative    52.546k i/s -     53.820k times in 1.024253s (19.03_s/i)
   absolute_relative    46.094k i/s -     46.236k times in 1.003080s (21.69_s/i)
   relative_absolute    39.835k i/s -     40.032k times in 1.004937s (25.10_s/i)
Calculating -------------------------------------
                             e1          e2 
        relative_nil    62.692k     29.247k i/s -    178.172k times in 2.842009s 6.091879s
        absolute_nil    45.976k     33.015k i/s -    137.271k times in 2.985678s 4.157852s
   relative_relative    53.874k     28.899k i/s -    157.636k times in 2.925997s 5.454685s
   absolute_relative    47.370k     32.768k i/s -    138.282k times in 2.919160s 4.219978s
   relative_absolute    40.277k     33.146k i/s -    119.505k times in 2.967095s 3.605446s

Comparison:
                     relative_nil
                  e1:     62692.3 i/s 
                  e2:     29247.5 i/s - 2.14x  slower

                     absolute_nil
                  e1:     45976.5 i/s 
                  e2:     33014.9 i/s - 1.39x  slower

                relative_relative
                  e1:     53874.3 i/s 
                  e2:     28899.2 i/s - 1.86x  slower

                absolute_relative
                  e1:     47370.5 i/s 
                  e2:     32768.4 i/s - 1.45x  slower

                relative_absolute
                  e1:     40276.8 i/s 
                  e2:     33145.7 i/s - 1.22x  slower
```

### CODE REVIEW

**Comment by nobu** [comment]
> Do not use realpath(3) on Windows even if it is defined, as the
> approach for checkign for absolute paths does not work for drive
> letters.

s/checkign/checking/ ?

**Comment by jeremyevans** [comment]
> s/checkign/checking/ ?

Yep, that's a typo in the commit message.  Assuming this last commit passes on Travis and other committers are OK with this change, I'll squash these changes into a single commit and fix the commit message.

**Comment by nobu** [comment]
Isn't it better to separate `realpath(3)` version and the current impl, and make `rb_check_realpath_internal` to call them?

**Comment by jeremyevans** [comment]
@nobu I think you are absolutely right, and that change will make things significantly simpler.  I'll work on that.

**Comment by ioquatix** [comment]
Nice work. I like that you could remove code and it got faster :)

**Pull request merged**
