### PR TITLE
Set and Prime should set Enumerator#size

### PR DESCRIPTION
**Pull request by kachick**
ruby 2.3.0dev (2015-06-12 trunk 50846) [x86_64-linux]

```ruby
require 'set'

set = Set.new [2, 4, 6]
p set.map.size  #=> 3
p set.each.size #=> nil, expected: 3
```

```ruby
require 'prime'

p Prime.each_with_index.size #=> nil, expected: Infinity
```

### CODE REVIEW

**Comment by marcandre** [comment]
Indeed. I'll commit the `Prime` part, @knu is maintainer for `Set` IIRC.

**Comment by marcandre** [comment]
Committed for `prime`. Thanks for the patch!

**Comment by kachick** [comment]
@marcandre Thanks to merge the patch! :)

**Comment by knu** [comment]
Thanks for your contribution!

**Comment by kachick** [comment]
@knu Thanks to merge! :)

**Pull request closed without merging**
