### PR TITLE
Let Fiber#raise work with transferring fibers (explicit kwarg)

### PR DESCRIPTION
**Pull request by nevans**
This seems like a feature that would be just as useful for transferring fibers as it is for yielding fibers.

I'm using a kwarg, so this is not automatic; the caller must know how to handle the fiber. If you call a yielding fiber with transfer: true or a transferring fiber without transfer: true, a FiberError will be raised.

```ruby
yielding_fiber.raise "message"
transferring_fiber.raise "message", transfer: true
```
Alternative (implicit) approach: #3795
Ruby issue: https://bugs.ruby-lang.org/issues/17331

### CODE REVIEW

**Comment by nevans** [comment]
I thought I had this working and passing tests, but apparently I'm doing the kwarg scan args wrong. Oops. I'll push a fix later.

**Comment by ioquatix** [comment]
Can you infer `transfer` from the state of the fiber?

**Comment by nevans** [comment]
> Can you infer `transfer` from the state of the fiber?

I definitely _can_. It would've been a lot simpler because I was doing the kwarg wrong at first. I just don't like that API. :wink: 

Maybe I'm wrong but: raising through resume, generator style, is like raising from a block you've passed down into to a function. Raising from a transfer, full coroutine style, is like a scheduler sending you e.g. a timeout or IO error. Although the lines blur, the two styles are different API's to me: talking to a child vs talking to a peer. You should know which one you're dealing with. It also makes a difference in where control goes (where that exception might be raised) when the fiber exits. It feels like it makes as much sense to be explicit here as it does to use different methods for resume and transfer.

But I guess I don't feel super strongly about it. And I feel differently about `cancel`! :laughing:  Because cancel isn't sending any thing to the fiber that the fiber can react to, there's no issue of API divergence. But it does have the same control flow issue. I can definitely be convinced they should both be explicit, or that they should both be implicit, or that raise should be explicit and cancel should be implicit. (cancel explict and raise implicit makes no sense to me)

I'll make another PR that infers it, and let others decide. :slightly_smiling_face:

**Comment by ioquatix** [comment]
There is no point adding an option for which only introduces failure cases, so I'd definitely prefer it without the `kwarg`.

**Comment by nevans** [comment]
i suppose you're probably right?

I just like to keep `transfer` and `resume` as two separate commands in my mental model. And the way I mentally think of raise is more like "resume with passed args or resume with an exception to be raised" vs "transfer with passed args or transfer with an exception to be raised". It feels to me like subtle bugs could creep in if you lose track of which type of fiber you're dealing with.

But there's definitely a case to be made that `raise` is special.  And just because caller should know whether to call resume or transfer, there's not necessarily a lot of benefit to forcing them to prove that knowledge when raising.

Anyway, the other PR is here: https://bugs.ruby-lang.org/issues/17331 :slightly_smiling_face:

**Comment by nevans** [comment]
Closed in favor of the implicit version at #3795. (Thanks @ioquatix and @eregon.)

**Pull request closed without merging**
