### PR TITLE
Fold symbol tables for tracking basic operation method redefinition changes into a single ID table

### PR DESCRIPTION
**Pull request by methodmissing**
I stumbled onto these 2 tables while working on https://github.com/ruby/ruby/pull/2809 and experimented at first with converting `vm_opt_mid_table` to an ID table for alignment with other method table concerns.

The fact that it stored a stable `Qtrue` value also hinted at a possibility of collapsing it into one table mapping `ID` -> `basic operation`.

The `rb_method_definition_t::original_id` seems stable to me as even when aliased, it would not change the method definition.

I see this contract used in [dtrace](https://github.com/ruby/ruby/blob/e014e6bf6685f681998238ff005f6d161d43ce51/vm.c#L602) hooks, [trace instruction](https://github.com/ruby/ruby/blob/e014e6bf6685f681998238ff005f6d161d43ce51/vm.c#L601) hooks and [code coverage](https://github.com/ruby/ruby/blob/0c2d731ef210c9121e2a97cc5b0d7594a80389f3/ext/coverage/coverage.c#L150) as well.

```
static ID
frame_func_id(const rb_control_frame_t *cfp)
{
    const rb_callable_method_entry_t *me = rb_vm_frame_method_entry(cfp);

    if (me) {
	return me->def->original_id;
    }
    else {
	return 0;
    }
}

/*!
 * The original name of the current method.
 *
 * The function returns the original name of the method even if
 * an alias of the method is called.
 * The function can also return 0 if it is not in a method. This
 * case can happen in a toplevel of a source file, for example.
 *
 * \returns the ID of the name or 0
 * \sa rb_frame_callee
 * \ingroup defmethod
 */
ID
rb_frame_this_func(void)
{
    return frame_func_id(GET_EC()->cfp);
}
```

Thoughts?

### CODE REVIEW

**Comment by methodmissing** [comment]
Failed on Travis CI `arm64` with unrelated:

```
  1) Failure:
DRbTests::TestDRbSSLCore#test_02_basic_object [/home/travis/build/ruby/ruby/test/drb/drbtest.rb:165]:
[NoMethodError] exception expected, not #<RangeError: "580" is recycled object>.
```

**Comment by jhawthorn** [comment]
I introduced `vm_opt_mid_table` in #2752. I think making `vm_opt_mid_table` an id_table makes sense, but I'm not 100% sure the tables can be combined like this (but I'm hopeful they can).

`vm_opt_method_table` was storing the specific methods which are expected to be optimized (ie. tied to the specific classes). `vm_opt_mid_table` just stores the id which are optimized on _some_ classes.

For example, previously redefining `Array#&` wouldn't change anything in `redefined_flag`. Now, because `&` is a BOP (only optimized for `Integer#&`) it will set a flag on it.

That said, maybe that's fine, because the flag is set per-class and `BASIC_OP_UNREDEFINED_P` checks both BOP and class, but it is a change to consider.

If this is a valid change, we can probably also remove the class argument of `add_opt_method`/`vm_init_redefined_flag`.

**Comment by methodmissing** [comment]
Good points and thanks for the input. I'll add tests during the day to confirm behavior. Also the primary reason why I ran it past the mailing list as well - takes some time to let all the method definition and dispatch paths sink in :smile:

**Comment by methodmissing** [comment]
First off your due diligence in https://github.com/ruby/ruby/pull/2752 is excellent and sets a very high standard. Thank you.

Thus far boots Redmine on Rails 5 and 6 just fine. I tested with this smaller script too:

```ruby
class Integer
  def +(i)
    0
  end
end

i = 10
i = i + 10
p i # 0

class String
  alias_method :ltlt, :<<
end

str = "test"
str.ltlt "i"
str.ltlt "ng"
p str # testing

class Array
  def [](i)
    :aref
  end
end

a = %w(a b c)
p a["b"] # :aref

class Proc
  def call(*args)
    :called
  end
end

proc = Proc.new {}
p proc.call # :called
```

Output:

```
lourens@CarbonX1:~/src/ruby/ruby$ ./ruby bop.rb
0
"testing"
:aref
:called
```

And took at stab @ a test case to bundle with this PR, but off course it failed pretty badly because it also fubars test unit :disappointed: 

```ruby
# frozen_string_literal: false
require 'test/unit'

# Test case to ensure BOP (basic operation) redefinitions are respected
# by vm_opt_* instructions

class Integer
  def +(i)
    0
  end
end

class String
  alias_method :ltlt, :<<
end

class Array
  def [](i)
    :aref
  end
end

class Proc
  def call(*args)
    :called
  end
end

class TestBopRedefined < Test::Unit::TestCase
  def test_integer
    i = 10
    i = i + 10
    assert_equal 0, i
  end

  def string_string
    str = "test"
    str.ltlt "i"
    str.ltlt "ng"
    assert_equal "testing", str
  end

  def test_array
    a = %w(a b c)
    assert_equal :aref, a["b"]
  end
  
  def test_proc
    proc = Proc.new {}
    assert_equal :called, proc.call
  end
end
```

Which fails CI with:

```
generate_index tests are being skipped.  Install builder gem.
/home/runner/work/ruby/ruby/src/tool/lib/test/unit/parallel.rb:74:in `_run_suite': undefined method `<<' for :called:Symbol (NoMethodError)
	/home/runner/work/ruby/ruby/src/tool/lib/test/unit/parallel.rb:31:in `block in _run_suites'
	/home/runner/work/ruby/ruby/src/tool/lib/test/unit/parallel.rb:30:in `map'
	/home/runner/work/ruby/ruby/src/tool/lib/test/unit/parallel.rb:30:in `_run_suites'
	/home/runner/work/ruby/ruby/src/tool/lib/test/unit/parallel.rb:128:in `run'
	/home/runner/work/ruby/ruby/src/tool/lib/test/unit/parallel.rb:213:in `<main>'
```

**Comment by methodmissing** [comment]
Conclusions regarding relying on `rb_method_definition_t::original_id` (facilitating an ID table) VS a pointer to a `rb_method_definition_t` struct as index seems positive. Further references to assignment of method definitions to method entries (I was looking for possible divergence between method entry and definition with regards to `original_id`):

* This seems like a very prominent assignment callsite, `rb_method_definition_set` - https://github.com/ruby/ruby/blob/71ae2acee1459d467e5d5a56745cc9da7c32a264/vm_method.c#L232
* It's frequently preceded by `rb_method_defition_create` https://github.com/ruby/ruby/blob/71ae2acee1459d467e5d5a56745cc9da7c32a264/vm_method.c#L348
* Examples of this pairing: https://github.com/ruby/ruby/blob/master/vm_method.c#L440-L443 , https://github.com/ruby/ruby/blob/master/vm_method.c#L484-L485 , https://github.com/ruby/ruby/blob/master/vm_method.c#L614-L616
* Also https://github.com/ruby/ruby/blob/e014e6bf6685f681998238ff005f6d161d43ce51/proc.c#L1499
* And https://github.com/ruby/ruby/blob/e014e6bf6685f681998238ff005f6d161d43ce51/proc.c#L1536-L1546

@shyouhei @ko1 any additional thoughts on this change?

**Pull request closed without merging**
