### PR TITLE
URI::Generic: Respect no_proxy for both parent domain and subdomains

### PR DESCRIPTION
**Pull request by harsimranmaan**
It is now possible to add just the subdomains for proxy bypass.
In a setting where the main domain needs to go through proxy while
the subdomains don't, it is now possible to just add the subdomains
to the no_proxy list.

The assumption that both subdomains and the parent domain should
behave the same wrt no_proxy has been removed.

eg: Adding .example.com in no_proxy would allow example.com
to go through the proxy.

 Addresses: https://bugs.ruby-lang.org/issues/14345

### CODE REVIEW

**Comment by harsimranmaan** [comment]
Do I need a reviewer here?

**Comment by hsbt** [comment]
Please submit a new issue to our "official" tracker: https://bugs.ruby-lang.org/

We didn't handle new feature on GitHub.

**Comment by harsimranmaan** [comment]
Hi, Any update on this?

**Comment by harsimranmaan** [comment]
@hsbt

**Comment by hsbt** [comment]
No update. I'm not maintainer of `Net::HTTP` library.

**Comment by harsimranmaan** [comment]
@matz Could you suggest how we take this forward?

**Comment by hsbt** [comment]
@harsimranmaan Current `URI` maintainer is not active. So, I'm going to ask this feature request at next developer meeting. Please no rush and wait a few months.

**Pull request closed without merging**
