### PR TITLE
More rdoc for ENV#[] and ENV#fetch

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Comment by tenderlove** [comment]
Looks great!  I've got a couple questions though:

1. Does this look correctly formatted when run through the RDoc parser (I'm not great at RDoc format)
2. Do we have tests that cover the documentation you've added?  If not we should add them.

Thanks for this patch!

**Comment by BurdetteLamar** [comment]
Here are images from the rdoc:


image

These are covered very well in test/ and pretty well in spec/.  I will be improving the latter.

**Comment by BurdetteLamar** [comment]
(Sorry about the selected part in the second image.  The blueness is not part of the page itself.)

**Comment by BurdetteLamar** [comment]
Will re-open for re-try.

**Pull request closed without merging**
