### PR TITLE
Clarify spawn pgroup documentation.

### PR DESCRIPTION
**Pull request by jrafanie**
Be more specific regarding "other values" by having "non-zero positive integers"
Add nil, the default value, as a possible value and what it means.

Try to use more consistent language.

I saw the "Other values" in the documentation and had to read it a few times to understand what it meant.
I hope the change below help clarify this for others.

### CODE REVIEW

**Comment by jrafanie** [comment]
@zzak I see you added some documentation around spawn, could you please review when you get a chance and let me know what you think of this doc change?  Thanks in advance!  :heart:

**Comment by jrafanie** [comment]
Thank you @nobu :smile:

**Comment by zzak** [comment]
@jrafanie LGTM, thank you! ^^

**Comment by jrafanie** [comment]
Thanks @zzak !!!  :bow:  I appreciate it!

**Pull request closed without merging**
