### PR TITLE
Refer autoconfigured endian macro

### PR DESCRIPTION
**Pull request by nobu**
Remove the case `RB_IO_BUFFER_HOST_ENDIAN` is not defined.

`REG_DWORD` on Windows is unconditionally equal to `REG_DWORD_LITTLE_ENDIAN`, which probably would have been added for symmetry with `REG_DWORD_BIG_ENDIAN` not for portability.

### CODE REVIEW

**Review by ioquatix — APPROVED** [review]
LGTM, thanks.

Just to confirm, the compiler provides `WORDS_BIGENDIAN`?

**Comment by nobu** [comment]
`WORDS_BIGENDIAN` is defined by `AC_C_BIGENDIAN`, a macro of autoconf.

**Comment by ioquatix** [comment]
Does every windows build use autoconf?

**Comment by nobu** [comment]
Windows builds do not use autoconf, then `WORDS_BIGENDIAN` is kept undefined.
I don't think big-endian Windows has ever existed.

**Comment by nobu** [comment]
> I don't think big-endian Windows has ever existed.

So `REG_DWORD` is equal to `REG_DWORD_LITTLE_ENDIAN`.

**Pull request merged**
