### PR TITLE
Get `ruby_nonempty_memcpy` to have C linkage

### PR DESCRIPTION
**Pull request by xtkoba**
Fixes [Bug #17788]

### CODE REVIEW

**Review by shyouhei — APPROVED** [review]
CI failure seems unrelated.

**Comment by aliismayilov** [comment]
any chance this can be merged? The mentioned bug is blocking us from migrating from ruby 2 to 3.

**Comment by shyouhei** [comment]
Merged! Thank you.

**Comment by jwoodrow** [comment]
Hi 👋 

Any news on when this will be released in a ruby version ? I see it was merged on the 13th of July and 3.0.2 was released the 7th of July.

We're having issues that apparently this seems to address but have no way of using it with ruby's docker images

**Comment by svoop** [comment]
Thanks for this fix, @xtkoba !!

@jwoodrow Same here, we're stuck on Ruby 2 as `mini_racer` which won't compile on the Ruby 3.0.2 Alpine Docker image. If no 3.0.3 is cut beforehand, the Xmas release of Ruby 3.1 should help.

**Comment by lloeki** [comment]
I remember being able to work around this for some gems by using clang instead of gcc, something along the lines of:

```
apk update
apk add clang
env CC=clang CXX=clang++ gem install mini_racer
```

**Comment by jwoodrow** [comment]
> I remember being able to work around this for some gems by using clang instead of gcc, something along the lines of:
> 
> 
> 
> ```
> 
> apk update
> 
> apk add clang
> 
> env CC=clang CXX=clang++ gem install mini_racer
> 
> ```

Hey @lloeki  ! It just so happens that I'm having issues with one of the gems you publish (sq_mini_racer as a dependence of sqreen) in an ruby:3.0.1alpine docker container the gem refuses to build because of this error. That's why I'm hoping a new ruby release would come soon since I can't seem to fork the sq_mini_racer gem to monkeypatch it.

Any idea how I could fix this since the clang solution doesn't seem to work for sq_mini_racer ?

**Comment by shyouhei** [comment]
Hello.  This pull request is merged.  3.1 (expected to happen next month) must include it.  If you want this also be seen in 3.0.3 (maybe, no concrete plan yet), you might want to file a backport request at https://bugs.ruby-lang.org/issues/new .  A backport request looks like for example https://bugs.ruby-lang.org/issues/18252 .

**Comment by svoop** [comment]
@shyouhei Thanks for the insights! Our project is under no pressure, so I can wait for Ruby 3.1, but maybe @jwoodrow would like to have a go filing a backport request.

**Comment by jwoodrow** [comment]
@shyouhei Thanks for the info, just like @svoop I have no immediate need for this fix I was asking if it was already planned because I'm trying to do some optimizations for a project's docker image and this would have helped but I can circumvent this somewhat. So I won't be filing for a backport neither

**Comment by shyouhei** [comment]
JFTY ruby 3.1 preview 1 includes this fix.

**Comment by tisba** [comment]
For reference, in case somebody stumbles across this PR: There is a backport request for Ruby 3.0.x: https://bugs.ruby-lang.org/issues/18574

**Comment by lloeki** [comment]
That backport request was changed to closed 25 days ago, not sure if it's been backported.

**Comment by tisba** [comment]
FYI: It has been backported to `ruby_3_0` in https://github.com/ruby/ruby/commit/2bb5fa495bf9d366d3c1fefc6b093dc4830f27bf.

**Comment by Startouf** [comment]
I confirm that the bug existed in ruby 3.0.3 and is fixed on ruby 3.0.5. See https://github.com/brianmario/charlock_holmes/issues/166

**Pull request merged**
