### PR TITLE
Added auto detected of authentication type based on smtp server capabilities.

### PR DESCRIPTION
**Pull request by martini**
If you want to configure SMTP for sending emails with SMTP Auth in Rails or directly via Net::SMTP you need to define the accepted auth type of the smtp server (which is complicated and need some experience to find out what you need to enter). Most SMTP servers work with "plain" (currently the default auth type of Net::SMTP) but for exchange (also Office365) you need to use "login". 

To make the config easier this pull request adds auto detection of supported auth types for SMTP server and use first working auth type.

 -=> So no auth type option need to be set in Rails / Net::SMTP unless you really want to use a certain auth type.

### CODE REVIEW

**Comment by thorsteneckel** [comment]
Nice! Actually it would be interesting in which order the checks should get performed. Imho the most secure one should be the one first tried and so on...

**Comment by ninthwalker** [comment]
Doesn’t look like this was ever merged?

**Comment by manuel0013** [comment]
Ruby gems I work on the gem locks as well.

**Comment by hsbt** [comment]
@martini Can you move this to https://github.com/ruby/net-smtp? `net-smtp` has been extracted from ruby repo.

**Pull request closed without merging**
