### PR TITLE
skip inlining cexpr! that are no attr! inline

### PR DESCRIPTION
**Pull request by shyouhei**
Requested by @ko1.

### CODE REVIEW

**Comment by ko1** [comment]
Any problem to merge it?

**Comment by shyouhei** [comment]
@ko1 not yet sure if the CI failure is because of this.

**Comment by shyouhei** [comment]
OK, `git rebase` solved the CI failure.  Was not because of this pull request.  Merging.

**Comment by ko1** [comment]
Thank you for merging it!

**Pull request merged**
