### PR TITLE
Generate ruby_method_ids constants separately

### PR DESCRIPTION
**Pull request by nobu**
The pre-defined ID sequences in id.h are generated automatically at the compile time so that the repository is magic-number free, but currently cruby_ids.inc.rs generated from the header file is committed into the repository.  This is that the dependencies are inverted (or broken).

This PR separates pre-defined ID list from the rust source, and makes an intermidiate tool named as cruby_ids_gen, which generate the rust source.  This depends on that YJIT does not support cross-compilation.

### CODE REVIEW

**Comment by k0kubun** [comment]
> This depends on that YJIT does not support cross-compilation.

Are you working on fixing cross-compilation of YJIT?

**Comment by XrXr** [comment]
I'm also interested to hear more about the motivation to do this, because it does add another moving part to the build process. Because `git checkout` would not give the complete rust source, we'll need some follow-up changes to maintain the currently level of editor support (e.g. with [rust-analyzer](https://rust-analyzer.github.io/)).

With regards to not having generated files in the repo, maybe it's time to move the entirety of `cruby_bindings.inc.rs` to be generated at dev build time and/or release tar ball build time similar to `id.{c,h}`. That'd add even more build process complexity than this PR, though. It'd also be another difference between git checkout builds and release tar ball builds. It's a big change with risks, and I think git repo hygiene along is not compelling enough of a reason to go forward. But if it also helps with cross compilation support, somehow, then maybe?

**Comment by nobu** [comment]
> I'm also interested to hear more about the motivation to do this, because it does add another moving part to the build process. 

This is
> This is that the dependencies are inverted (or broken).

**Comment by XrXr** [comment]
Sorry, I don't understand how the dependencies are inverted, or what is depending on what. The id.h generation tool doesn't look at the Rust source, so id.h doesn't depend on YJIT's file. The checked in IDs don't update when `defs/id.def` updates, because there is no build time dependency between the two. Is that what you mean that the dependency is broken? But then, it's no different from what happens if the signatures of C functions YJIT uses change.

---

An option for removing the ids without adding a build step is to look them up on boot similar to what C extensions do: https://github.com/xrxr/ruby/commit/5ae36f850b533a10d457a0851f7140e2de2c755a
What do you think?

**Comment by nobu** [comment]
Any progress on this?

**Comment by nobu** [comment]
I'm wondering of removing `defs/id.def`.

**Comment by maximecb** [comment]
@XrXr

**Comment by XrXr** [comment]
@nobu https://github.com/ruby/ruby/pull/8676 looks alright to you for removing the ids?

**Comment by nobu** [comment]
Thank you, it looks great.
If C had richer macro capabilities, I'd want to extract `rb_intern` literals like it.

**Pull request closed without merging**
