### PR TITLE
ruby_3_2: Pass Travis CI with the latest config file.

### PR DESCRIPTION
**Pull request by junaruga**
This PR passes with the latest Travis CI that exists on master and ruby_3_3 branches.
I confirmed it passed on my forked repository.
https://app.travis-ci.com/github/junaruga/ruby/builds/268122652

The PR is related to the following issue ticket.
https://bugs.ruby-lang.org/issues/19999

### CODE REVIEW

**Comment by junaruga** [comment]
I can confirm Travis CI passed. I think some failing GitHub Actions checks are not related to this PR.
https://app.travis-ci.com/github/ruby/ruby/builds/268123109

**Comment by junaruga** [comment]
I rebased this PR on the latest ruby_3_2 branch.
I confirmed that the Travis CI passed on my forked repository.
https://app.travis-ci.com/github/junaruga/ruby/builds/268613656

**Comment by junaruga** [comment]
@nagachika Could you review this PR? The `.travis.yml` on the ruby_3_2 branch is same with the one on the master and ruby_3_3 branches.

**Review by nagachika — APPROVED** [review]

**Comment by nagachika** [comment]
I've just trigger re-run on failed jobs, since https://github.com/ruby/ruby/pull/9773 was merged on master branch. But it doesn't work as I expected. Travis-CI jobs cannot be re-run from the operations on GitHub Actions?

**Comment by junaruga** [comment]
Thank you for your review!

> It seems that the s390x pipeline has a problem right now.

This was a Travis infra issue. And I was told by Travis support that it was fixed. I confirmed it was fixed on the master branch. And now I am manually running this PR's Travis s390x again.
https://bugs.ruby-lang.org/issues/20013#note-15

**Comment by junaruga** [comment]
> I've just trigger re-run on failed jobs, since #9773 was merged on master branch. But it doesn't work as I expected. Travis-CI jobs cannot be re-run from the operations on GitHub Actions?

I commented above at the same time as your comment above. OK. Yes we cannot re-run Travis CI by triggering the re-run on the GitHub Actions.

A way to re-run Travis CI is
1. Click the "Details" link for "Travis CI - Pull Requst".
2. Click one of the job links on [the page](https://github.com/ruby/ruby/pull/9410/checks?check_run_id=21013361801).
3. Click "Restart Job" button at the top right on [the job page](https://app.travis-ci.com/github/ruby/ruby/jobs/617040177).

**Pull request merged**
