### PR TITLE
[DOC] Note about call-seq return type

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Review by jeremyevans — COMMENTED** [review]
The way the first chunk this is written encourages call-seq for Ruby methods, which I don't think we should recommend.  It's true that the call-seq RDoc generates doesn't indicate the return type, but this is Ruby, types generally shouldn't matter, what matters is what methods the returned object responds to.

No issues with the changes in the second chunk.

**Comment by BurdetteLamar** [comment]
> The way the first chunk this is written encourages call-seq for Ruby methods, which I don't think we should recommend. It's true that the call-seq RDoc generates doesn't indicate the return type, but this is Ruby, types generally shouldn't matter, what matters is what methods the returned object responds to.
> 
> No issues with the changes in the second chunk.


@jeremyevans, there are literally thousands of return types in the call-seqs in ruby/*.c, all put there manually.  How can return types in .c flourish, but be not ok in .rb?  Are there other committers who should weigh in on thiis?

**Comment by jeremyevans** [comment]
> @jeremyevans, there are literally thousands of return types in the call-seqs in ruby/*.c, all put there manually. How can return types in .c flourish, but be not ok in .rb?

If you are going to write a manual call-seq (as you have to for C function methods), it makes sense to use a return type.  However, you should not write a manual call-seq just to include a return type.

**Comment by BurdetteLamar** [comment]
> However, you should not write a manual call-seq just to include a return type.

I disagree.  I think an author should write a manual call-seq when it seems useful:  add a return type, improve parameter names, etc.

Let's hear from some other committers;  anyone in particular you'd like?

**Comment by jeremyevans** [comment]
Unsurprisingly, my opinion about this has not changed in the last 7 hours.  From looking in the standard library, only a small percentage of Ruby methods use call-seq (<2%).  I don't have anyone in particular to recommend for review, but I encourage any committer to contribute their thoughts.

Adding a call-seq just for a return type is redundant in most cases, as the method documentation will usually include information regarding what the method returns.

The places where it makes sense to add a call-seq are when you have multiple distinct ways of calling a method, and the arguments to the method mean different things depending on how many arguments are provided (or whether a block is provided).

You are welcome to push back on this and wait and see if another committer agrees with you.  However, IMO, you should reword the pull request so that it only recommends call-seq for Ruby methods in cases where there are benefits beyond the return type.

**Comment by BurdetteLamar** [comment]
I'm calling this a swing and a miss.

**Pull request closed without merging**
