### PR TITLE
HTTPS server name indication (SNI): explicit server_name in Net::HTTP

### PR DESCRIPTION
**Pull request by aspettl**
**Current behavior and problem:**
At the moment, the host name or IP address given in the URL is used to provide the server name for SNI in HTTPS connections. While this behavior is sufficient in most cases, establishing a connection to a fixed IP using a certain server name is not possible.

**Proposed solution:**
This patch decouples the server name used for SNI from the address used for connecting. Default value for the new `ssl_server_name` attribute is the address, so the default behavior stays exactly the same.

**Notes**
* There are scenarios where a client would like to select a specific host when e.g. DNS round robin is configured. Examples: fallback strategies, monitoring of individual hosts.
* This has nothing to do with the HTTP "Host" header, which one needs to set additionally.

Issue in Redmine: https://bugs.ruby-lang.org/issues/15215

### CODE REVIEW

**Comment by DamirSvrtan** [comment]
Are there any blockers for this to get merged in?

**Comment by aspettl** [comment]
I guess the maintainers see this as "not important enough to pay attention" because I got no feedback at all :-/ So please feel free to up-vote this in Redmine: https://bugs.ruby-lang.org/issues/15215 - I don't think it will be noticed here.

**Comment by DamirSvrtan** [comment]
Hi Aaron! Thanks for effort.

I’ve registered on redmine, however don’t see an upvote functionality in
Redmine (at least not on my phone). Could you help a bit more on this?

**Comment by aspettl** [comment]
Thanks for the effort, unfortunately I think there really is no simple upvote functionality because the issues are basically mailing list based (at least I have that impression).

**Pull request closed without merging**
