### PR TITLE
Explicit refs to Enumerable in RDoc for Array and Hash

### PR DESCRIPTION
**Pull request by BurdetteLamar**
In What's Here for Array and Hash, add an explicit reference to Enumerable.

### CODE REVIEW

**Review by jeremyevans — APPROVED** [review]

**Comment by BurdetteLamar** [comment]
@jeremyevans, how to nudge this along?

**Comment by jeremyevans** [comment]
This is a documentation only change, so CI shouldn't matter.  Not sure why check_branch is hanging.  Would you like me to commit this manually?

**Comment by BurdetteLamar** [comment]
> This is a documentation only change, so CI shouldn't matter. Not sure why check_branch is hanging. Would you like me to commit this manually?

That's affirmative, and thanks.

**Comment by jeremyevans** [comment]
Merged at 383685b52b086643f7d6e65a4d74fda90d3a64af

**Pull request closed without merging**
