### PR TITLE
Auto-enable YJIT build when rustc >= 1.58.0 present

### PR DESCRIPTION
**Pull request by maximecb**

### CODE REVIEW

**Comment by XrXr** [comment]
Looking at the logs for non-YJIT CI jobs:
```
checking for rustc... rustc
error: couldn't create a temp dir: Permission denied (os error 13) at path "/dev/rmetaQAoc4d"

error: aborting due to previous error

```

I also get this error locally. Looks like this `--emit=mir` trick is outdated :/

**Comment by maximecb** [comment]
Awright so I think I found the right incantation to get `rustc` to output to stdout only.

However, we forgot to check that we're on a supported platform. We'd need to add some extra logic to check that we're on x86|arm64 and Linux|unix|macOS

I think that should be fairly doable within the configure script? 🤔

**Review by jeremyevans — APPROVED** [review]
Builds fine on OpenBSD amd64.  Approach seems good to me, building YJIT support by default if possible, but not enabling it by default at runtime.

**Comment by maximecb** [comment]
Thank you for reviewing Jeremy :)

**Pull request merged**
