### PR TITLE
Add Hash#except ENV#except

### PR DESCRIPTION
**Pull request by timoschilling**
https://bugs.ruby-lang.org/issues/15822
According to `Hash#slice`, I would like to add `Hash#except`. Same for `ENV.except`.

### CODE REVIEW

**Comment by bogdanvlviv** [comment]
What do you think about adding `except!` to Ruby?
(Active Support has it for years, https://github.com/rails/rails/blob/ac1ba44f8d46ebbbe6889629d263e5690631f6a1/activesupport/lib/active_support/core_ext/hash/except.rb#L20)

**Comment by timoschilling** [comment]
just for the record:
`except!` is added by https://github.com/ruby/ruby/pull/2171

**Comment by bogdanvlviv** [comment]
> just for the record:
> except! is added by #2171

@timoschilling #2171 only adds `Hash#extract!` that is different from `except!`

```ruby
 hash = { a: true, b: false, c: nil }
hash.except!(:c) # => { a: true, b: false }
hash             # => { a: true, b: false }
```

```ruby
 hash = { a: true, b: false, c: nil }
hash.extract!(:c) # => { c: nil }
hash             # => { a: true, b: false }
```

I haven't open any PR with `Hash#execpt!` cause I thought it could be something you are interested in to do in the scope of this PR.

**Comment by ioquatix** [comment]
I'm not sure `except(*keys)` is the best design, because in some situations, you can leverage data structures more effectively if you write `except(keys)`.

For example:

```ruby
keys = Set.new([:x, :y, :z])

[:a, :x, :b, :y].except(keys)
```

It can be implemented more efficiently by `keys.include?(item)`. Maybe the data structure should do this internally. But I just thought I'd mention it..

**Comment by timoschilling** [comment]
merged by 82ca8c73034b0a522fd2970ea39edfcd801955fe

**Pull request closed without merging**
