### PR TITLE
Rename mjit_exec to jit_exec

### PR DESCRIPTION
**Pull request by k0kubun**
It's no longer specific to MJIT.

### CODE REVIEW

**Comment by nobu** [comment]
Also `mjit_exec_slowpath` -> `mjit_exec`?

**Comment by nobu** [comment]
There are still some `mjit_exec` in comments.

**Comment by k0kubun** [comment]
> Also mjit_exec_slowpath -> mjit_exec?

It could have a better name, but it's in fact specific to MJIT, so the `mjit_` prefix is intentional.

**Comment by k0kubun** [comment]
addressed those two points https://github.com/ruby/ruby/pull/6262/commits/1924421b50963bcba90b914ed250f448ec59ec50 https://github.com/ruby/ruby/pull/6262/commits/6efd4c6459307f9c3397023dfa1ca866e75ab1c9

**Comment by maximecb** [comment]
<3

**Pull request merged**
