### PR TITLE
Better cooperation between attr methods with public protected private v3

### PR DESCRIPTION
**Pull request by radarek**
Continuation of #3757. Each hange pushed as a separate commit to check which one fails on CI.

### CODE REVIEW

**Comment by radarek** [comment]
@mame I pushed the rest of #3757 as separate commits.

**Comment by mame** [comment]
Thank you very much! I'll cherry-pick and push each to the master branch and wait for a few builds.

**Comment by mame** [comment]
Well... I've pushed all commits a few hours ago. The Solaris CI has built and tested the master branch about ten times, and no failure happened so far.

It is mysterious. Only when the changeset had been committed previously, something was wrong with the machine? I don't know at all, and I will wait to see what happens for a bit longer, but anyway, now it works great. Thank you very much for your cooperation.

**Comment by marcandre** [comment]
Great news, thanks @mame

**Comment by radarek** [comment]
Happy to hear that. @marcandre, @mame thanks for code review and assistance.

**Pull request closed without merging**
