### PR TITLE
YJIT should die if we compile on Aarch64 with no instruction cache clear available

### PR DESCRIPTION
**Pull request by noahgibbs**
From pairing session with @maximecb and @kddnewton.

### CODE REVIEW

**Comment by kddnewton** [comment]
What platforms does this actually die on? I wasn't clear if we ever got it to trigger.

**Comment by noahgibbs** [comment]
Should die if somebody tries to compile on aarch64, which needs icache clear, on a non-GCC-descended compiler. So that should only happen if you used something like ICC (https://community.intel.com/t5/Intel-C-Compiler/Intel-C-Compiler-for-Linux-and-ARM/m-p/926585).

**Comment by noahgibbs** [comment]
But no, we never triggered it. I checked later and clang defines __GNUC__ and the icache-clear compiler intrinsic instruction we're using. The docs seemed inconclusive, but it looks like it works exactly as well as with GCC (so right now it's not working on that Graviton instance.)

**Comment by kddnewton** [comment]
I guess I'm wondering if we should error in this case or if we should assume that when we're compiling ARM and there's no icache-clear function if that means it's not necessary? I don't know enough about those other systems.

**Comment by noahgibbs** [comment]
ARM is going to need an icache clear for our use case, including on non-GNU compilers. Right now we would literally just not do anything (compiles to nothing), which would result in something like the illegal instruction problem we're currently debugging on Graviton - cases where the instruction cache hadn't caught up with the executable memory we're writing. I'd prefer a #error during compile, given the choice.

**Pull request merged**
