### PR TITLE
Add example code for aliased Array methods

### PR DESCRIPTION
**Pull request by BurdetteLamar**

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
@drbrain and @ioquatix:  I'd hate to merge with no review at all.  Can you take a look?

**Comment by BurdetteLamar** [comment]
Duelling reviews.  @esparta asked for these dupes.  I asked for another opinion, and @drbrain said he's comfortable either way, my choice.  I don't know how this gets resolved.

**Comment by BurdetteLamar** [comment]
For my part, I'm happy to omit the dupes by closing this PR.  Then I can get back to work.

**Comment by BurdetteLamar** [comment]
@esparta, I'm closing this PR.  @drbrain was agnostic on this, and both @jeremyevans and I think it does not add value.

**Comment by esparta** [comment]
No problem, its a matter of opinions and the maintainers have the call. We can continue the other areas on documentation.

**Pull request closed without merging**
