### PR TITLE
Fix the implementation of guard known class for symbol

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by k0kubun** [comment]
Could you add a test if this is fixing something? This diff is basically a reverse of https://github.com/ruby/ruby/pull/6359 except for the `i` vs `u` of `RUBY_SYMBOL_FLAG`.

**Comment by jimmyhmiller** [comment]
@k0kubun I can definitely figure out how to add a good test for this tomorrow. It came up as I was implementing opt_send methods. The previous version actually crashes for arm as there is no 8 bit `cmp` there. Maybe there is a better implementation?

@maximecb thoughts?

**Comment by k0kubun** [comment]
Perhaps we could resort to the `and` implementation only when it is not on a register (where `with_num_bits` is applicable) if the crash is about `unwrap` after `with_num_bits`.

**Comment by maximecb** [comment]
@jimmyhmiller we do have some platform-agnostic tests for the backend in this file here `yjit/src/backend/tests.rs`. Basically little snippets of IR we want to make sure the backend can digest properly.

I think I understand the problem a bit better now 🤔 

We *can* load a single byte on arm64, but we don't have a single-byte comparison instruction.

I guess my first question is: is it choking on a memory operand or a register?

If it's choking on a memory operand, then we should make sure to load the 8-bit operand in the arm instruction splitting.

**Comment by jimmyhmiller** [comment]
@maximecb It is choking on a register being 8 bits. Playing around with things, I could keep the existing code and add a split like this to cmp [here](https://github.com/ruby/ruby/blob/31461c7e0eab4963ccc8649ea8ebf27979132c0c/yjit/src/backend/arm64/mod.rs#L318)

```rust

  fn split_less_than_32(asm: &mut Assembler, opnd0: Opnd) -> Opnd {
      match opnd0 {
          Opnd::Mem(_) | Opnd::Reg(_) | Opnd::InsnOut { .. } => {
              match opnd0.rm_num_bits() {
                  8 => asm.and(opnd0.with_num_bits(64).unwrap(), Opnd::UImm(0xff)),
                  16 => asm.and(opnd0.with_num_bits(64).unwrap(), Opnd::UImm(0xffff)),
                  32 | 64 => opnd0,
                  bits => unreachable!("Invalid number of bits. {}", bits)
              }
          }
          _ => opnd0
      }
  }
```

Maybe there is a better way? At this point in the process, it is actually an InsnOut, but the error is trying to make an 8 bit register.

**Comment by maximecb** [comment]
I think for this specific situation we basically have no choice but to do an `and` with 0xFF since there is no 8-bit compare.

Your solution should work, though you may also need to split/load opnd0 if it's a memory operand 🤔 

Should definitely add some small tests to `yjit/src/backend/tests.rs`

**Comment by jimmyhmiller** [comment]
Closing. Will open with a solution that is arm specific.

**Pull request closed without merging**
