### PR TITLE
Update RubyGems 3.5.16 and Bundler 2.5.16 for Ruby 3.3

### PR DESCRIPTION
**Pull request by hsbt**

### CODE REVIEW

**Comment by k0kubun** [comment]
>  1\) Error:
>  TestGemSource#test_dependency_resolver_set_file_uri:
>  Zlib::DataError: invalid distance too far back

Is this failure relevant?

**Comment by hsbt** [comment]
@k0kubun It seems flaky test. I re-run failed CI and confirm to pass test with MinGW.

**Comment by deivid-rodriguez** [comment]
Yeah, we've been seeing that failure intermittently for a long time, it should not be specific to this changeset.

**Review by k0kubun — APPROVED** [review]
:+1:

**Comment by k0kubun** [comment]
@hsbt @deivid-rodriguez: @jeremyevans has reported that Ruby 3.3.5, which shipped this PR, creates a `.lock` file for every single gem executable under `$prefix/bin`. Is that intentional?

**Comment by hsbt** [comment]
https://github.com/rubygems/rubygems/pull/7939 fixed that. I will submit fixed version of rubygems for Ruby 3.3.6.

**Comment by deivid-rodriguez** [comment]
Yes, that's my fault and not intentional. Will release a fixed version soon!

**Pull request merged**
