### PR TITLE
Merge NODE_DEF_TEMP and NODE_DEF_TEMP2

### PR DESCRIPTION
**Pull request by yui-knk**

### CODE REVIEW

**Comment by nobu** [comment]
I thought using `ctxt` instead of `VALUE nd_cval`, but that struct isn’t visible in the header?

**Comment by yui-knk** [comment]
There are 2 options for using `ctxt` instead of `VALUE nd_cval`.

## Option 1

Move these definitions to `rubyparser.h` from `parse.y`

* `enum shareability`
* `enum rescue_context`
* `struct lex_context`

## Option 2

Move these definitions to `parse.y` from `rubyparser.h`

* `struct RNode_DEF_TEMP`
* `RNODE_DEF_TEMP`

I prefer #2 because `NODE_DEF_TEMP` is only used parse.y internal.

What you think about it?

**Comment by nobu** [comment]
I second option 2.

**Comment by yui-knk** [comment]
Added a commit for option 2.

**Review by nobu — APPROVED** [review]

**Pull request merged**
