### PR TITLE
add to_i method to TrueClass and FalseClass object

### PR DESCRIPTION
**Pull request by tracyloisel**
add to_i method to TrueClass and FalseClass object

### CODE REVIEW

**Comment by pluce** [comment]
Maybe we could set the constants in a separate header file ?

**Comment by mikegee** [comment]
Could you please justify this?

**Comment by mikegee** [comment]
I only recently began following this repository. I am accustomed to changes being discussed at https://bugs.ruby-lang.org, so please excuse my ignorance of the process here.

https://bugs.ruby-lang.org/projects/ruby/wiki/HowToContribute says:
> Pull request to https://github.com/ruby/ruby is acceptable for tiny fixes. But pull requests which need discussions will be simply ignored.

I suspect the Ruby maintainers would want to discuss whether `true` and `false` have a `to_i` method. I also think adding that method requires some justification. (Ruby has been ok for a long time without it.)

**Comment by Roman2K** [comment]
This seems like bloat to me, solving a very specific problem in a very general. You're assuming `true` means `1` for any Ruby code. If `true` means `1` for your project, define such a mapping in that particular project. And definitely not at the boolean-class level (`{True,False}Class#to_i`) but rather a simple Hash constant (`{true => 1, false => 0}`) more or less global depending on the scope.

**Comment by mikegee** [comment]
Here's another technique:

```ruby
pry> BOOL = [false, true].freeze
[
    [0] false,
    [1] true
]
pry> BOOL.index(false)
0
pry> BOOL.index(true)
1
```

**Comment by drbrain** [comment]
You'll need to address the conflict this pull request has with the existing behavior:

```
$ ruby -e 'if 0 then puts true else puts false end'
true
$ ruby -e 'if 1 then puts true else puts false end'
true
```

In your https://bugs.ruby-lang.org feature request.

**Comment by Roman2K** [comment]
@drbrain Don't see behaviour conflict there:
> `$ ruby -e 'if 0 then puts true else puts false end'`

You seem to imply that any value returned by a method of `false` should also evaluate to false to avoid confusion 🤔

Even if this PR was merged, the fact that zero still evaluates to true (being non-nil, non-false) seems natural to me.

Just like `false.to_s` evaluates to true:
```ruby
if false.to_s then p :ok end   # prints :ok
```

**Comment by tracyloisel** [comment]
Haha. I’m honored by the attention of this commit! 

Many times in my work I was calling for such conversion because I need to insert a boolean equation in an integer calculation for sorting collection or naming element.

Furthermore, this conversion strictly follows the theory of Boolean algebra. 

I want to thank you all for your kindness and your participation

**Comment by tracyloisel** [comment]
@mikegee : Ruby is full of stuff that merely improves on readability. I love that about the language. I'd rather read .to_i after a boolean variable than anything else. It's opiniated. I confess

**Comment by Roman2K** [comment]
@tracyloisel 

> Ruby is full of stuff that merely improves on readability

Syntactic sugar in Ruby such as `unless` and `size` + `length`, are fully application-agnostic, they don't assume anything about your usage: `unless` in one script can only have the same meaning in any other script. `size` on an Array can only have the same meaning as `size` and `length` on another Array. If you find this is not true, then you're not dealing with an Array and you should subclass/wrap it.

The same thing about application-agnosticism cannot be said about some global mapping of core constants to static values. This mapping only has its place as a library at best. Like a boolean algebra library.

**Comment by tracyloisel** [comment]
Gosh, the PR was missing rb_define_method instructions... Does anyone here really read the files changed ???? tsss

**Comment by drbrain** [comment]
@tracyloisel please note @mikegee said:

> https://bugs.ruby-lang.org/projects/ruby/wiki/HowToContribute says:
>
>> Pull request to https://github.com/ruby/ruby is acceptable for tiny fixes. But pull requests which need discussions will be simply ignored.

So no, we don't check.

**Comment by shevegen** [comment]
>  It's opiniated. I confess

I do not think that the opinion or being opinioated is the problem.

Ultimately any proposals have to convince matz primarily and the
discussions happen on https://bugs.ruby-lang.org/projects/ruby-trunk 
although I also understand github discussion, they are very convenient.

To the topic at hand, I think that .to_i on true or false is a bit strange
largely because Ruby follows its own internal philosophy rather than
C customs, e. g. "0 being false and all else being true". And, by the
way, I can understand it to some extent. :)

In LPC, a language that is largely C but used for some oldschool
MUDs, they follow method invocation styles where, if a method
does not exist, it does not crash the program or end it, it just
assumes that the result will be wrong. Like:

  object tp; tp = this_player();
  sword->move(tp);

Or something like that; and if the method move() does not exist,
things just continue but of course without the sword being relocated
to the player object. There are pros and cons with that approach.
(I mention it specifically because I once wanted to write a MUD in
ruby. I am still not even sure about which semantics to use... so 
I guess I may write two different engines where the behaviour
can be LPC-specific, or also ruby-specific).

In general ruby being so dynamic, one can just modify all the
behaviour as you want to. But I understand why you want to
have certain behaviour in the main language. :)

While I personally am mildly against the proposal, it's nothing
that has me fret about it. But I think there are many somewhat
similar suggestions here and there; it would be nice if there
could be an additional "evil" branch of ruby that may be as
opinionated, where people can just pull in crazy stuff that 
modifies how ruby behaves. Like in the above example,
something like:

  require 'bool_on_steroids'

And similar requires that are available by default. :D

Then people could specifically enable things like the
above, just with one extra require note.

(Or if you want to denote that it is evil, you could have
the require be:

require 'evil/bool_on_steroids'

and group similar behaviour all into the evil namespace.
There used to be evil.rb, it was cool! Run-time change
of classes to shapechange into other classes, I liked
the idea. Or to have a generic Button class, that, depending
on the GUI toolkit at hand, would be a Tk Button or a GTK
Button or a QT button - you get the idea. Sorry for the 
digression, I was just having too many ideas!)

**Comment by danielpclark** [comment]
> Many times in my work I was calling for such conversion because I need to insert a boolean equation in an integer calculation for sorting collection or naming element.

@tracyloisel If you need something that evaluates zero as false you could do something like this for your projects.

```ruby
class Integer
  def to_bool
    !self.zero?
  end
end
```

**Comment by k0kubun** [comment]
As drbrain explained several times, please create an account on https://bugs.ruby-lang.org and file a ticket there. Thank you.

**Comment by k0kubun** [comment]
This hasn't been discussed since the ticket was not filed. Let's close this until a ticket is filed.

**Pull request closed without merging**
