### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by shyouhei**
Making pull requests just to confirm actual CI run.

### CODE REVIEW

**Comment by shyouhei** [comment]
Will merge this.

**Comment by nobu** [comment]
Isn't it better to keep `name:` tags?

**Comment by shyouhei** [comment]
@nobu Here is the master(left) / pull requested(right) screenshot.  I don't think the changed output is that obscure.  Do you prefer master's display?

Screenshot from 2020-02-26 15-26-24

**Comment by nobu** [comment]
I just worried that `configure` lines could be very long and ellipsized.
No worry?

**Comment by shyouhei** [comment]
Then let's add `name:` to that entry.

**Pull request merged**
