### PR TITLE
Fix formatting for padding argument in Base64#urlsafe_encode64

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by mame** [comment]
Looks good to me.  I'd like to import the pull request to Ruby SVN trunk, but I don't know the workflow to do so.  Any one could tell me?

**Comment by davydovanton** [comment]
@mame I don't know too :sweat:
But I think that you need pull my commit and after that push this to ruby svn `trunk` branch like [this](https://github.com/ruby/ruby/commit/0c14c3ab0b1bbf3f2a5b2c0accb2a53528635e44)

**Comment by davydovanton** [comment]
So I am sure that @zzak or @hsbt will help :smiley:

**Comment by mame** [comment]
Thanks, actually @hsbt is now helping me on IRC :-)

**Comment by davydovanton** [comment]
super! :clap:

**Comment by mame** [comment]
Great.  Thank you @davydovanton !

**Comment by davydovanton** [comment]
thanks! :star2:

**Pull request closed without merging**
