### PR TITLE
Update link to Email address specification (URI::MailTo)

### PR DESCRIPTION
**Pull request by travelerspb**
The current link leads to 404, I updated to the actual one.

### CODE REVIEW

**Comment by znz** [comment]
I access current URL and get 301 instead of 404.

```
% curl --head 'http://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html#valid-e-mail-address'
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3
Date: Mon, 20 Aug 2018 06:45:00 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html
```

**Comment by travelerspb** [comment]
curl is awesome but try to access it from a browser:

**Comment by znz** [comment]
I misunderstood because browser does not show 404 page finally.
I understand final 404 page on browser redirects to new page with javascript.

```
% curl -L --head 'http://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html#valid-e-mail-address'
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3
Date: Mon, 20 Aug 2018 07:30:00 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://www.whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html

HTTP/2 301
server: nginx/1.10.3
date: Mon, 20 Aug 2018 07:30:01 GMT
content-type: text/html
content-length: 185
location: https://whatwg.org/specs/web-apps/current-work/multipage/states-of-the-type-attribute.html
access-control-allow-origin: *
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

HTTP/2 301
server: nginx/1.10.3
date: Mon, 20 Aug 2018 07:30:03 GMT
content-type: text/html
content-length: 185
location: https://html.spec.whatwg.org/multipage/states-of-the-type-attribute.html
access-control-allow-origin: *
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

HTTP/2 404
server: nginx/1.10.3
date: Mon, 20 Aug 2018 07:30:04 GMT
content-type: text/html; charset=utf-8
content-length: 1021
vary: Accept-Encoding
etag: "5b76f1e2-3fd"
access-control-allow-origin: *
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-xss-protection: 1; mode=block

```

**Comment by travelerspb** [comment]
my bad, next time will describe the problem more precise!

**Pull request closed without merging**
