### PR TITLE
Fast path argument parsing for the "01" format with rb_scan_args_fastpath_0_1

### PR DESCRIPTION
**Pull request by methodmissing**
I noticed a bunch of core APIs invoking `rb_scan_args` with the `"01"` format string. This argument parser helper method is quite heavy weight for the special case of parsing a single optional argument.

This is an internal only API and another low hanging fruit is the `"02"` format string.

### CODE REVIEW

**Comment by nobu** [comment]
Do you mean "heavy weight" for compilers?
Or do you mind non-gcc compiler cases?

**Comment by methodmissing** [comment]
@nobu I was just experimenting after noticing a lot of internal calls to `rb_scan_args` are for very simple cases such as these formats, which are mostly straight forward lookups into `*argv` after simplified bounds checking as well:

* `"01"` - no required args, 1 optional arg
* `"02"` - no required args, 2 optional args
etc.

Generated with GCC (`-O3`):

```
Dump of assembler code for function rb_scan_args_fastpath_0_1:
   0x00000000002216d0 <+0>:	test   %edi,%edi
   0x00000000002216d2 <+2>:	jne    0x2216e8 <rb_scan_args_fastpath_0_1+24>
   0x00000000002216d4 <+4>:	test   %rdx,%rdx
   0x00000000002216d7 <+7>:	je     0x2216e0 <rb_scan_args_fastpath_0_1+16>
   0x00000000002216d9 <+9>:	movq   $0x8,(%rdx)
   0x00000000002216e0 <+16>:	mov    %edi,%eax
   0x00000000002216e2 <+18>:	retq   
   0x00000000002216e3 <+19>:	nopl   0x0(%rax,%rax,1)
   0x00000000002216e8 <+24>:	cmp    $0x1,%edi
   0x00000000002216eb <+27>:	jne    0x2216fb <rb_scan_args_fastpath_0_1+43>
   0x00000000002216ed <+29>:	test   %rdx,%rdx
   0x00000000002216f0 <+32>:	je     0x2216e0 <rb_scan_args_fastpath_0_1+16>
   0x00000000002216f2 <+34>:	mov    (%rsi),%rax
   0x00000000002216f5 <+37>:	mov    %rax,(%rdx)
   0x00000000002216f8 <+40>:	mov    %edi,%eax
   0x00000000002216fa <+42>:	retq   
   0x00000000002216fb <+43>:	sub    $0x8,%rsp
   0x00000000002216ff <+47>:	mov    $0x1,%edx
   0x0000000000221704 <+52>:	xor    %esi,%esi
   0x0000000000221706 <+54>:	callq  0x1c7690 <rb_error_arity>
End of assembler dump.
```

`rb_scan_args` currently has 400 lines disassembled. Differences in code size:

```
lourens@CarbonX1:~/src/ruby/trunk$ nm -S --size-sort -t d ./ruby | grep rb_scan_args$
0000000002234128 0000000000001770 T rb_scan_args
lourens@CarbonX1:~/src/ruby/trunk$ nm -S --size-sort -t d ./ruby | grep rb_scan_args_fastpath_0_1$
0000000002234064 0000000000000059 t rb_scan_args_fastpath_0_1
```

I used this script for benchmarks (0 arg, 1 arg cases):

```yaml
prelude: |
  str = "12345"
  ary = [5, 1, 3, 4, 2]
  /c(.)t/ =~ 'cat'
benchmark:
  str_to_i_0: str.to_i
  str_to_i_1: str.to_i(16)
  ary_min_0: ary.min
  ary_min_1: ary.min(3)
  exc_new_0: Exception.new
  exc_new_1: Exception.new(str)
  re_last_match_0: Regexp.last_match
  re_last_match_1: Regexp.last_match(0)
loop_count: 10000000
```

```
lourens@CarbonX1:~/src/benches$ benchmark-driver -e "rb-scan-args-fast-path::~/src/ruby/ruby/ruby -I~/src/ruby/ruby/lib -I~/src/ruby/ruby/. -I~/src/ruby/ruby/.ext/x86_64-linux --disable-gems" -e "trunk::~/src/ruby/trunk/ruby -I~/src/ruby/trunk/lib -I~/src/ruby/trunk/. -I~/src/ruby/trunk/.ext/x86_64-linux --disable-gems" -v --repeat-count=24 --run-duration=1 rb_scan_args.yml
rb-scan-args-fast-path: ruby 2.6.0dev (2018-11-26 rb-scan-args-f.. 65975) [x86_64-linux]
last_commit=Fast path argument parsing for the "01" format with rb_scan_args_fastpath_0_1
trunk: ruby 2.6.0dev (2018-11-26 trunk 65975) [x86_64-linux]
Calculating -------------------------------------
                     rb-scan-args-fast-path       trunk 
          str_to_i_0                31.003M     29.758M i/s -     10.000M times in 0.322549s 0.336044s
          str_to_i_1                28.728M     28.269M i/s -     10.000M times in 0.348095s 0.353749s
           ary_min_0                43.269M     41.910M i/s -     10.000M times in 0.231114s 0.238604s
           ary_min_1                 4.019M      3.924M i/s -     10.000M times in 2.487877s 2.548165s
           exc_new_0                12.468M     12.284M i/s -     10.000M times in 0.802078s 0.814068s
           exc_new_1                12.153M     11.711M i/s -     10.000M times in 0.822815s 0.853932s
     re_last_match_0                65.070M     65.025M i/s -     10.000M times in 0.153681s 0.153787s
     re_last_match_1                17.139M     16.990M i/s -     10.000M times in 0.583463s 0.588584s

Comparison:
                       str_to_i_0
rb-scan-args-fast-path:  31003022.1 i/s 
               trunk:  29758004.7 i/s - 1.04x  slower

                       str_to_i_1
rb-scan-args-fast-path:  28727784.4 i/s 
               trunk:  28268668.7 i/s - 1.02x  slower

                        ary_min_0
rb-scan-args-fast-path:  43268635.1 i/s 
               trunk:  41910459.3 i/s - 1.03x  slower

                        ary_min_1
rb-scan-args-fast-path:   4019491.8 i/s 
               trunk:   3924392.5 i/s - 1.02x  slower

                        exc_new_0
rb-scan-args-fast-path:  12467612.8 i/s 
               trunk:  12283989.4 i/s - 1.01x  slower

                        exc_new_1
rb-scan-args-fast-path:  12153405.3 i/s 
               trunk:  11710532.8 i/s - 1.04x  slower

                  re_last_match_0
rb-scan-args-fast-path:  65069822.9 i/s 
               trunk:  65025130.7 i/s - 1.00x  slower

                  re_last_match_1
rb-scan-args-fast-path:  17139052.3 i/s 
               trunk:  16989928.5 i/s - 1.01x  slower
```

**Comment by methodmissing** [comment]
And also relevant is these patterns I saw:

* The `argc > 0` condition to skip a method call in https://github.com/ruby/ruby/blob/aaf9fc1f688f5e1965f11ab0bcabb3116fd40256/re.c#L3965 (can forward fix if this changeset makes sense)
* And the case statement in the `Array#rotate` methods which is pretty much doing the same thing as this optimization - https://github.com/ruby/ruby/blob/aaf9fc1f688f5e1965f11ab0bcabb3116fd40256/array.c#L2595-L2599 (same for forward fixing if the change makes sense)

**Comment by methodmissing** [comment]
Also possible to remove the NULL check branches by inverting the NULL args passed in https://github.com/ruby/ruby/pull/2025/files#diff-347f10a1abb5b6f87bc8fe155cf63a3eR1494 and the `Array#rotate` methods

**Comment by methodmissing** [comment]
Removed NULL checks in https://github.com/ruby/ruby/pull/2025/commits/8a05674cdd7fa96429f98d2dcf82f67ce09467c9 and converted the calls not coercing any argument values from calling `rb_scan_args*` to `rb_error_arity` as that's the only possible outcome the original function would have.

**Comment by nobu** [comment]
I meant that `rb_scan_args` with a literal format string will be optimized by gcc.
For instance, `rb_scan_args(argc, argv, "01", &dummy);` in `ext/bigdecimal/bigdecimal.c:BigDecimal_dump` is compiled as just 2 lines:

        # clang (Apple LLVM version 10.0.0)
        cmpl    $2, %edi
        jae     LBB60_11

and

        # gcc 7.3.0:
        cmpl    $1, %edi
        ja      .L978

**Comment by nobu** [comment]
Assembled size comparison of `rb_scan_args_fastpath` and `rb_scan_args_fastpath_0_1` doesn't make sense.
The former is necessary for other patterns anyway, and the latter is just an addition.

**Comment by methodmissing** [comment]
Thanks for the feedback

**Pull request closed without merging**
