### PR TITLE
IPAddr add helper commands get_ip and get_subnet

### PR DESCRIPTION
**Pull request by x89**
I had to implement the following for some nicer methods in another instance where I'm using the code. It's my first Ruby PR so please let me know if I've messed anything up!

```ruby
  def get_ip
    self.inspect.split(/[\/:]/).slice(2)
  end

  def get_subnet
    self.inspect.split(/[\/:>]/).slice(3)
  end
```

### CODE REVIEW

**Comment by x89** [comment]
I'm a bit confused as to why the first CI build is failing, on my own machine it returns success:

```travis
$ make -s $JOBS test-rubyspec MSPECOPT=-j
generating x86_64-linux-fake.rb
In file included from /usr/include/bits/libc-header-start.h:33:0,
                 from /usr/include/stdio.h:28,
                 from ../include/ruby/defines.h:101,
                 from ../include/ruby/ruby.h:36,
                 from ../version.c:12:
/usr/include/features.h:373:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^~~~~~~
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
x86_64-linux-fake.rb updated
ruby 2.5.0dev (2017-05-29 ipaddr-get-sub.. 58948) [x86_64-linux]
[- | ==================100%================== | 00:00:00]      0F      0E 

Finished in 20.919751 seconds

3569 files, 26409 examples, 200760 expectations, 0 failures, 0 errors, 0 tagged
```

**Comment by hsbt** [comment]
@x89 Can you rebase from our latest master?

**Comment by x89** [comment]
@hsbt this was from the `trunk` branch, should I be using the `2.4` branch instead?

**Comment by x89** [comment]
Okay it seems to have worked now, I created a bug report (feature request) as well https://bugs.ruby-lang.org/issues/13610

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this from master?

**Comment by k0kubun** [comment]
Let me close this as it has not been updated for a while. Please reopen this after resolving conflicts. Thanks.

**Pull request closed without merging**
