### PR TITLE
Disable iseq-dumped builtin module for universal (macOS x86_64 + arm64) binaries

### PR DESCRIPTION
**Pull request by bhamiltoncx**
During the build, Ruby has special logic to serialize its own builtin module to disk using the binary iseq format during the build (I assume for speed so it doesn't have to parse builtin every time it starts up).

However, since iseq format is architecture-specific, when building on x86_64 for universal x86_64 + arm64, the serialized builtin module is written with the x86_64 architecture of the build machine, which fails this check whenever ruby imports the builtin module on arm64:

https://github.com/ruby/ruby/blob/1fdaa0666086529b3aae2d509a2e71c4247c3a12/compile.c#L13243

Thankfully, there's logic to disable this feature for cross-compiled builds:

https://github.com/ruby/ruby/blob/1fdaa0666086529b3aae2d509a2e71c4247c3a12/builtin.c#L6

This disables the iseq logic for universal builds as well.

Fixes [Bug #18286]

### CODE REVIEW

**Review by tenderlove — APPROVED** [review]
Good catch!

**Comment by ccaviness** [comment]
@nobu Could you have a look at this? It is also necessary for universal support, and goes along with #7373 which you already committed back in February. Thank you.

**Comment by JasonLunn** [comment]
@nobu @tenderlove - is there an issue preventing this from getting merged?

**Comment by bhamiltoncx** [comment]
Thanks, all!

**Comment by ccaviness** [comment]
For the record, this ended up being superseded by #8708

**Pull request merged**
