### PR TITLE
YJIT: Implement send when called without keywords or blocks

### PR DESCRIPTION
**Pull request by noahgibbs**
Currently send will side-exit when called with keyword arguments. So this will only optimise cases where send is called without them.

If I run "WARMUP_ITRS=1 MIN_BENCH_ITRS=1 MIN_BENCH_TIME=0 ruby -I./harness --yjit-stats benchmarks/railsbench/benchmark.rb" with latest CRuby master, I get about 64,700 side exits for send without this PR. With this PR, the number of send-with-keywords side exits is below 100.

The total number of side exits is reduced by about the same amount -- around 60,000 -- but there are about 1.8 million side exits remaining, so it's only around a 3.2% reduction in side exits. There was no measurable difference in speed with or without the patch.

"No keywords" is a limitation of using rb_f_send for this purpose. By exposing a different endpoint, we could allow keywords. But rb_f_send checks the pushed frame for keywords in the call, and we don't push a frame. For now, no keywords in the call. Blocks have a similar problem - I'm not sure how to pass them without a pushed frame, though CRuby presumably does it successfully. I'm not having any luck with it.

### CODE REVIEW

**Comment by noahgibbs** [comment]
Ah, looks like my block handling is incorrect in some cases. I'll fix that.

**Comment by maximecb** [comment]
Looks pretty good. Nice work :)

I like that you've added tests.

**Comment by maximecb** [comment]
I just realized, you opened this PR on ruby/ruby, but it should be a PR on `yjit_backend_ir` under `shopify/ruby`.

Happens to me all the time 😅

**Comment by noahgibbs** [comment]
Okay, new test failure in test_refinement.rb, where send_z_on is failing because it doesn't think the method Z, added by a refinement, exists. This may be enough to keep me from succeeding here -- it looks like rb_f_send in vm_eval.c may have some differences in refinement handling from how send works in vm_insnhelper.c.

I think this is going to require rethinking send. At a minimum it seems like it's going to require switching endpoints. I'll close this for now and see if I can make it work a different way.

**Pull request closed without merging**
