### PR TITLE
Merge RubyGems/Bundler master

### PR DESCRIPTION
**Pull request by hsbt**
Merged from https://github.com/rubygems/rubygems/commit/fe96fb6e2ac5a8b6df5e852470d11fa854301eca

We need to support rust extension to ruby/ruby.

### CODE REVIEW

**Comment by simi** [comment]
It seems CI needs to be updated as well somehow

```
unknown command: " \"  wrapper.h:1:10: fatal error: 'ruby.h' file not found\\n\" +"
  unknown command: " \"  thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic(\\\"wrapper.h:1:10: fatal error: 'ruby.h' file not found\\\\n\\\")', /home/runner/.cargo/git/checkouts/rb-sys-b0d7af9720667455/1aa5b58/build.rs:135:10\\n\" +"
  unknown command: " \"  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\\n\"]"

```

**Comment by hsbt** [comment]
Yes, rb-sys package couldn't find the development header from ruby repo before installation. I try to fix it or ignore the tests.

**Comment by simi** [comment]
@ianks maybe any idea how to manually pass path to Ruby headers (since pkg-config fails if I understand it well at https://github.com/ianks/rb-sys/blob/main/build.rs)?

**Comment by ianks** [comment]
> @ianks maybe any idea how to manually pass path to Ruby headers (since pkg-config fails if I understand it well at https://github.com/ianks/rb-sys/blob/main/build.rs)?

For bindgen, you can pass it with an env var:

`BINDGEN_EXTRA_CLANG_ARGS=-I/path/to/include`

**Comment by ianks** [comment]
@simi @hsbt happy to help as well!

**Comment by hsbt** [comment]
still happened `chdir` teardown errors: https://github.com/ruby/ruby/pull/5669/checks?check_run_id=5787109619

**Comment by deivid-rodriguez** [comment]
I see it's still failing with latest upstream changes. Maybe https://github.com/rubygems/rubygems/pull/5459 fixes things?

**Comment by hsbt** [comment]
@deivid-rodriguez I tried with #5459. But It's still failing. This issue caused by `ruby.h` location of ruby-core test suite. I'll investigate to point the location of `ruby.h` header in non-installation environment.

Maybe, I will skip tests of cargo builder when I give up this.

**Comment by ianks** [comment]
@hsbt Did you try `BINDGEN_EXTRA_CLANG_ARGS="-I/absolute/path/to/ruby/include"` I noticed you tried the extra clang args previously, but I'm not sure if using a relative path would have worked

**Comment by hsbt** [comment]
@ianks Yes, But It's not working at first.

**Pull request merged**
