### PR TITLE
Fix various autoload race conditions.

### PR DESCRIPTION
**Pull request by ioquatix**
This PR attempts to address two race conditions outlined in <https://bugs.ruby-lang.org/issues/18782>.

1. It's possible to race on adding and then deleting items in `autoload_featuremap`. When this happens, two threads will try to load the same file with different autoload data and deadlock.
2. When finishing autoload, it's necessary to clear `ele->state` before setting constants. If this is not synchronised, a thread can see the cleared `ele->state` before seeing the constants and assume the constant is not being autoloaded and then fail with `NameError`.

This PR also introduces a new critical section macro for helping debug these issues. You can quickly reproduce these issues by inserting `rb_thread_schedule()` at relevant locations (i.e. (1) after setting hash in or (2) after calling `ele->state = 0`).

This test case can reproduce both cases:

```
# test.rb
autoload_path = File.join(__dir__, "foobar.rb")
File.write(autoload_path, 'module Foo; end; module Bar; end')

100_000.times do
	$stderr.puts "--------------------"
	autoload :Foo, autoload_path
	autoload :Bar, autoload_path

	t1 = Thread.new {Foo}
	t2 = Thread.new {Bar}

	t1.join
	t2.join

	Object.send(:remove_const, :Foo)
	Object.send(:remove_const, :Bar)

	$LOADED_FEATURES.delete(autoload_path)
end
```

Example failure of case (1):

```
-------------------- (success)
autoload_by_someone_else ele=0x55f33b806a30 ele->state=(nil)
autoload_by_someone_else ele=0x55f33b806a30 ele->state=(nil)
check_autoload_required 2
autoload_by_someone_else ele=0x55f33b806a30 ele->state=0x7fdd678be780
check_autoload_required 4
autoload_by_someone_else ele=0x55f33b806a30 ele->state=0x7fdd678be780
check_autoload_required 4
ele=0x55f33b806a30 ele->state=0x7fdd678be780 = NULL
check_autoload_required 4
-------------------- (failure)
autoload_by_someone_else ele=0x55f33b806a30 ele->state=(nil)
autoload_by_someone_else ele=0x55f33b6e8f40 ele->state=(nil)
check_autoload_required 2
check_autoload_required 3
autoload_by_someone_else ele=0x55f33b806a30 ele->state=0x7fdd6779d780
check_autoload_required 1
autoload_by_someone_else ele=0x55f33b806a30 ele->state=0x7fdd6779d780
check_autoload_required 1
ele=0x55f33b806a30 ele->state=0x7fdd6779d780 = NULL
ele=0x55f33b6e8f40 ele->state=0x7fdd678be780 = NULL
../test.rb:12:in `join': No live threads left. Deadlock? (fatal)
3 threads, 3 sleeps current:0x000055f33b771250 main thread:0x000055f33b66e090
* #<Thread:0x00007fdd6a2cb0b0 sleep_forever>
   rb_thread_t:0x000055f33b66e090 native:0x00007fdd6a71c3c0 int:0
   
* #<Thread:0x00007fdd676e0090 ../test.rb:9 sleep_forever>
   rb_thread_t:0x000055f33b770ff0 native:0x00007fdd6789e640 int:1 mutex:0x000055f33b7c5100 cond:1
    depended by: tb_thread_id:0x000055f33b66e090
   
* #<Thread:0x00007fdd676e1238 ../test.rb:10 sleep_forever>
   rb_thread_t:0x000055f33b771250 native:0x00007fdd679bf640 int:0
   

	from ../test.rb:12:in `block in <main>'
	from ../test.rb:4:in `times'
	from ../test.rb:4:in `<main>'
make: *** [uncommon.mk:1250: runruby] Error 1
```

Example failure of case (2):

```
[0x7f175fe5b0c8] rb_autoload_str mod=Object id=Foo file="/home/samuel/Projects/ioquatix/ruby/foobar.rb"
[0x7f175fe5b0c8] rb_autoload_str const_set mod=Object id=Foo file="/home/samuel/Projects/ioquatix/ruby/foobar.rb"
[0x7f175fe5b0c8] rb_autoload_str mod=Object id=Bar file="/home/samuel/Projects/ioquatix/ruby/foobar.rb"
[0x7f175fe5b0c8] rb_autoload_str const_set mod=Object id=Bar file="/home/samuel/Projects/ioquatix/ruby/foobar.rb"
[0x7f175fe61d88] rb_const_search_from value == Qundef -> autoloading
[0x7f175fe61e78] rb_const_search_from value == Qundef -> autoloading
[0x7f175fe61e78] Assigning constants...
[0x7f175fe61d88] rb_const_search_from value == Qundef -> autoloading
[0x7f175fe61e78] autoload_const_set name=:Foo value=Foo
[0x7f175fe61e78] autoload_const_set name=:Bar value=Bar
#<Thread:0x00007f175fe61d88 ../test.rb:11 run> terminated with exception (report_on_exception is true):
../test.rb:11:in `block (2 levels) in <main>': uninitialized constant Bar (NameError)
../test.rb:11:in `block (2 levels) in <main>': uninitialized constant Bar (NameError)
make: *** [uncommon.mk:1250: runruby] Error 1
```

These failures are very uncommon but it does impact Ruby as far back as 2.7, and probably earlier.

### CODE REVIEW

**Comment by ioquatix** [comment]
Another failure:

```
--------------------
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=(nil)
check_autoload_required 2
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=0x7f203bffe780
check_autoload_required 4
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=0x7f203bffe780
check_autoload_required 4
ele=0x562449f8e9b0 ele->state=0x7f203bffe780 = NULL
--------------------
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=(nil)
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=(nil)
check_autoload_required 2
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=0x7f2033efe780
check_autoload_required 4
check_autoload_required file=0x7f203c968530 /home/samuel/Projects/ioquatix/ruby/foobar.rb
autoload_by_someone_else ele=0x562449f8e9b0 ele->state=0x7f2033efe780
check_autoload_required 4
check_autoload_required 4
#<Thread:0x00007f203bf604c0 ../test.rb:10 run> terminated with exception (report_on_exception is true):
../test.rb:10:in `block (2 levels) in <main>': uninitialized constant Bar (NameError)
ele=0x562449f8e9b0 ele->state=0x7f2033efe780 = NULL
../test.rb:10:in `block (2 levels) in <main>': uninitialized constant Bar (NameError)
make: *** [uncommon.mk:1250: runruby] Error 1
```

**Comment by ioquatix** [comment]
@fxn this might be interesting to you.

**Comment by fxn** [comment]
You found it! Congratulations! :)

**Comment by ioquatix** [comment]
@fxn has this been going on for a while?

**Comment by fxn** [comment]
@ioquatix Zeitwerk has been out for about 3 years, and have never been reported thread-safety issues like (2) for now. 
 Case (1) does not affect Zeitwerk, because constants map to different files by design.

I have a [Ruby compatibility test suite](https://github.com/fxn/zeitwerk/blob/main/test/lib/zeitwerk/test_ruby_compatibility.rb) with some basic safety net about some language features the gem relies on. [This test](https://github.com/fxn/zeitwerk/blob/441c07e2aecc824e423d9708634fe986c5e7c7d9/test/lib/zeitwerk/test_ruby_compatibility.rb#L296-L317) covers the basic case in which context switching does not happen in the middle of an autoload for a given constant reference. As you see, this is extremely basic, mostly oriented to see how other Rubies behave wrt to these edge details, not meant to be a proper suite for Ruby (TruffleRuby did not pass this one last time I checked).

**Comment by ioquatix** [comment]
@fxn do you have any performance benchmarks for autoload?

**Comment by fxn** [comment]
Nope!

**Pull request merged**
