### PR TITLE
Import ruby/ruby-signature

### PR DESCRIPTION
**Pull request by soutaro**
This PR is to move source code from ruby/ruby-signature to ruby/ruby. Waiting for any suggestion to finish the transition. 🙏 

The expected workflow is the following:

1. `ruby-signature` gem is under development for Ruby 2.7.
2. The gem will release for Ruby 2.7 as an opt-in gem.
3. The gem will ship with Ruby 2.8/3.0. (No need to `gem install` with those versions.)
3. ruby/ruby will be the _upstream_ for the library once this PR get merged.

Questions I have:

* [ ] How can I run tests?
* [ ] How can I run `racc` for parser.
* [ ] How can I write .gemspec for ruby/ruby repository.

### CODE REVIEW

**Comment by hsbt** [comment]
I have the some concerns.

1. How use `test/signature` instead of `test/ruby-signature`? Because the test files for `lib/foo` are `test/foo` or `test/test_foo.rb` in the current structure.
2. How move `sig/test` to `test/sig`?

**Comment by k0kubun** [comment]
Just curious: Is there any motivation to make this default gems instead of bundled gems? 

Default gems are double-master development and hard to sync. Because of the maintenance cost, in general I insist that we should not use default gems unless we need to *workaround* load issues (rubygems, bundler, and its dependencies).

**Comment by soutaro** [comment]
I'm sorry for the late reply. (It was 1.5 months ago. 😱)

@hsbt Sounds reasonable. I'll try to move the files.

@k0kubun I don't have strong opinion, and it seems like making RBS a bundled gem makes sense to me. What I don't want is having double-master. I strongly want to have one upstream in _ruby_ repository.

**Comment by soutaro** [comment]
We had talked about this and concluded that ruby-signature repo won't be merged for now. The gem will be ship with Ruby3 as a _bundled gem_, but the development will continue on ruby/ruby-signature repository.

* Meeting note: https://hackmd.io/IAsLEuiKR8uyYBFC7Qdczg?edit

**Pull request closed without merging**
