### PR TITLE
YJIT: Deduplicated Context

### PR DESCRIPTION
**Pull request by k0kubun**
Discussion: https://github.com/Shopify/ruby/issues/484

I implemented Context deduplication using `HashSet<Rc<Context>>`. A challenge with this design compared to https://github.com/ruby/ruby/pull/7279 is that `Context`s are not automatically cleaned up. To address that issue, this PR proposes to sweep `Context`s on `code_gc`.

## Impact
25 itrs on railsbench with darwin-aarch64 stats build: 9.19MB -> 8.80MB (4.2% reduction)

Note that Packed Context https://github.com/ruby/ruby/pull/7279 was a 3.4% reduction, so this PR is more memory-efficient.

### Before
https://github.com/ruby/ruby/commit/e9e4e1cb46

```
yjit_alloc_size:           9,188,351
live_context_size:         1,029,496
live_context_count:           27,092
```

### After
https://github.com/Shopify/ruby/commit/5c70fff208

```
yjit_alloc_size:           8,803,417
context_set_size:            329,728
context_set_count:             6,059
live_context_count:           27,097
```

### CODE REVIEW

**Comment by maximecb** [comment]
This looks pretty good 👍 

Only thing I would add is maybe a metric for context deduplication/sharing ratio, e.g.
context_set_count /  live_context_count

Then there is the question of whether we want to merge this now, or wait and see the impact of adding more information to the context, or investigate other potential solutions 🤔 The one other thing that may work is hash consing over all contexts. May result in better sharing, but it does have more implementation complexity.

Currently @jimmyhmiller is working on an experiment in tracking the class of self.

**Comment by k0kubun** [comment]
> Then there is the question of whether we want to merge this now, or wait and see the impact of adding more information to the context

My initial intention was to allow adding more fields to `Context` by optimizing its memory layout first, but now it does feel like we should add more fields to `Context` first to evaluate the method correctly 😅

We still have 10 months before the release and the impact of this PR is not that significant as of now, so I'm okay with leaving it until we finalize the Context for Ruby 3.3 YJIT. Versioning `Block`s based on a specific receiver class or a given block ISEQ does seem necessary for making calls monomorphic, and we can't have a conclusion without the actual implementation of it.

> or investigate other potential solutions 🤔 The one other thing that may work is hash consing over all contexts. May result in better sharing, but it does have more implementation complexity.

Meanwhile, I think it's worth experimenting with too. If we manage to achieve it with a simple implementation and it has the best impact, then we should probably go with it anyway.

**Comment by k0kubun** [comment]
> Meanwhile, I think it's worth experimenting with too. If we manage to achieve it with a simple implementation and it has the best impact, then we should probably go with it anyway.

Hmm, but hash consing would also mean that accessing Context involves some extra overhead, so it actually comes with the same concern as packed Context. I guess we should benchmark the cost with 30k methods/ifelse.

**Comment by maximecb** [comment]
> We still have 10 months before the release and the impact of this PR is not that significant as of now, so I'm okay with leaving it until we finalize the Context for Ruby 3.3 YJIT.

This is definitely the best we have so far. I suppose we can wait at least a few weeks until we have some data regarding shape/class tracking for self and maybe we evaluate hash consing in a bit more depth.

> Hmm, but hash consing would also mean that querying Context involves some extra overhead, so it actually comes with the same concern as packed Context. I guess we should benchmark the cost with 30k methods/ifelse.

We have 3 separate ideas that are along the same vein. Going to outline them to avoid confusion 😅 :
1. Your packed context implementation
2. My suggestion for a delta compression that shares entries in a table
3. "True" hash consing, which shares similarities with 2

At first I thought that 2 was quite promising, but after thinking about it some more, I think that it's relatively complex, we have no guarantee that it scales well for long ISEQs, and I realized the other day that comparing two contexts would require decompressing them, which would be potentially expensive.

Packed contexts also share the difficulty that comparing contexts requires decompressing the contexts. All 3 approaches involve some amount of traversal or decompression overhead for querying to know if some property is true.

Hash consing is similar to 2 (delta compression), except that the shared bits are shared among all ISEQs. It also has the property that two identical contexts must be represented by the same node. It's a bit like shape trees that way.

One cool thing about hash consing is that we can compare two context IDs for equality for free with a pointer/uint comparison. If we use greedy versioning, this could perform well. With regards to querying, it's no slower than 1 and 2. It doesn't have potentially pathological growth in length like 2.

Downside of hash consing is that it's hard to know how much sharing we'll actually get without implementing it. It's also not completely trivial how to GC it. May be possible with simply Rc since it's acyclic, but using Rc would increase memory overhead some.

**Comment by k0kubun** [comment]
> it's no slower than 1 and 2.

Hmm, yeah, finding an exact match with hash consing would be more efficient than 1 and 2.

By the way, do you intend to use a pointer to a cons tree as `ctx` during codegen, or use it only when it's stored in `Block` or `BranchStub`? I'm guessing the latter would be a simpler implementation. This part wouldn't change the efficiency of finding an exact-matching `Context` much, but it's nice to be on the same page for reducing mental overhead during discussions.

> It's also not completely trivial how to GC it. May be possible with simply Rc since it's acyclic, but using Rc would increase memory overhead some.

It seems like we're okay with doing Context GC only on `code_gc` (as this PR does). Then I guess we could temporarily create a `HashSet` of pointers, traversing all `Block`s and `BranchStub`, which would hopefully be a smaller list right after the Code GC process, and then traverse the tree, checking each node against the `HashSet`.

If using `Rc` makes it much simpler, I might just do it though.

**Comment by k0kubun** [comment]
> If using Rc makes it much simpler, I might just do it though.

Sharing a `Box` in multiple places seems not straightforward (taking a Box out of CodegenGlobals would at least be `&'static Box`), so I might go with it regardless of the GC concern. Also maybe I should pair on this with @XrXr.

**Comment by maximecb** [comment]
> By the way, do you intend to use a pointer to a cons tree as ctx during codegen, or use it only when it's stored in Block or BranchStub? I'm guessing the latter would be a simpler implementation. This part wouldn't change the efficiency of finding an exact-matching Context much, but it's nice to be on the same page for reducing mental overhead during discussions.

You're probably right that keeping the context object decompressed while doing codegen is conceptually simpler. Also helps us visualize all the things we're storing in the context struct.

> It seems like we're okay with doing Context GC only on code_gc (as this PR does). Then I guess we could temporarily create a HashSet of pointers, traversing all Blocks and BranchStub, which would hopefully be a smaller list right after the Code GC process, and then traverse the tree, checking each node against the HashSet.
> If using Rc makes it much simpler, I might just do it though.

I think for maximum compactness we would probably want a vector of objects, and use some `u32` indices into that vector.  Then we could mark which objects are live during code GC.

> Also maybe I should pair on this with @XrXr and/or @jimmyhmiller.

If you want, we could actually pair with all 4 of us. Tuple now supports that apparently.

**Pull request closed without merging**
