### PR TITLE
Use `userinfo` for authenticated proxy 

### PR DESCRIPTION
**Pull request by jdamick**
From pull #1148 

In spite of proxy_uri.userinfo has username and password for authenticated proxy, open_http method of open-uri.rb ignores it. Actually, lots of softwares expect this value as a credential for authenticated proxy.

I have retained his original change & added a unit test for it.  cc/ @hsbt

### CODE REVIEW

**Comment by nobu** [comment]
What about simply:

```diff
@@ -270,6 +270,9 @@
     if URI::HTTP === target
       # HTTP or HTTPS
       if proxy
+        unless proxy_user && proxy_pass
+          proxy_user, proxy_pass = proxy_uri.userinfo&.split(':', 2)
+        end
         if proxy_user && proxy_pass
           klass = Net::HTTP::Proxy(proxy_uri.hostname, proxy_uri.port, proxy_user, proxy_pass)
         else
```

**Comment by jdamick** [comment]
agreed, i'll simplify the original change

**Comment by hsbt** [comment]
@jdamick Thank you for your test. I'll merge after test passes.

**Comment by jdamick** [comment]
all set, thanks!

**Pull request closed without merging**
