### PR TITLE
Update link to doc/contributing.rdoc

### PR DESCRIPTION
**Pull request by 180909**

### CODE REVIEW

**Comment by nobu** [comment]
The RDoc is generated with `--page-dir=$(srcdir)/doc` option, this PR makes the link broken.

**Comment by yevgenko** [comment]
> The RDoc is generated with `--page-dir=$(srcdir)/doc` option, this PR makes the link broken

@nobu could you please clarify how can I observe the effect of broken link?

**Comment by yevgenko** [comment]
The link is currently broken in master documentation https://docs.ruby-lang.org/en/master/CONTRIBUTING_md.html

**Comment by nobu** [comment]
1. apply this PR.
2. configure and build rdoc, `make html`.
3. open the generated HTML file `.ext/html//CONTRIBUTING_md.html`.
The broken link probably would be by the procedure to generate that site.
I’ll ask the maintainer.

**Pull request closed without merging**
