### PR TITLE
Flag 2 parse.y branches as unlikely in functions pushback and newtok respectively

### PR DESCRIPTION
**Pull request by methodmissing**
### pushback

2nd column from right is branch misprediction expressed as percentage missed.

before

Screenshot from 2019-07-03 22-50-26

after

Screenshot from 2019-07-03 23-38-01

### newtok

2nd column from right is branch misprediction expressed as percentage missed.

before

Screenshot from 2019-07-03 22-55-25

after

Screenshot from 2019-07-03 23-36-14

### CODE REVIEW

**Comment by nobu** [comment]
Which lines in these pictures should I read?
Highlighted lines are not related?

**Comment by methodmissing** [comment]
@nobu sorry my mistake, the highlighted lines is irrelevant - I was awake too late

Relevant for

* `pushback` line 1 (ignore the highlight, relevant is column 2 from the right, branch miss %)
* `newtok` line 3 (ignore the highlight, relevant is column 2 from the right, branch miss %)

**Comment by methodmissing** [comment]
I can generate output from `perf` later today - it's easier to read / parse.

**Comment by methodmissing** [comment]
`perf` diff of branch misses (used max sample frequency for this laptop):

```
lourens@CarbonX1:~/src/redmine$ sudo perf record -e branch-misses -F 12750 bin/rails c -e production
/home/lourens/src/redmine/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.1.1/lib/active_record/associations/builder/collection_association.rb:26: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
Loading production environment (Rails 5.2.1.1)
irb(main):001:0> RUBY_REVISION
=> "23c92b6f820f670994026423d4c7b5abcf51eafa"
irb(main):002:0> exit
[ perf record: Woken up 4 times to write data ]
[ perf record: Captured and wrote 1.002 MB perf.data (25231 samples) ]
lourens@CarbonX1:~/src/redmine$ sudo perf record -e branch-misses -F 12750 bin/rails c -e production
/home/lourens/src/redmine/vendor/bundle/ruby/2.7.0/gems/activerecord-5.2.1.1/lib/active_record/associations/builder/collection_association.rb:26: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
Loading production environment (Rails 5.2.1.1)
irb(main):001:0> RUBY_REVISION
=> "0ac82c0f4ee0a0785238c61b85f5b3e6606a979b"
irb(main):002:0> exit
[ perf record: Woken up 4 times to write data ]
[ perf record: Captured and wrote 1.020 MB perf.data (25714 samples) ]
```

With `sudo perf diff`, `baseline` is master, `delta abs` is the relative % difference in branch miss events

```
# Event 'branch-misses'
#
# Baseline  Delta Abs  Shared Object       Symbol                                              
# ........  .........  ..................  ....................................................
#
     0.06%     -0.01%  ruby                          [.] newtok <<<<<<<<<<<<<<<<<<<
     0.07%     +0.01%  ruby                          [.] rb_str_set_len
     0.47%     -0.01%  ruby                          [.] rgengc_check_relation.part.86
     0.09%     +0.01%  ruby                          [.] rb_wb_protected_newobj_of
     0.01%     +0.01%  ruby                          [.] rb_ivar_defined
```

For `pushback` no delta or other meaningful info using `perf`

```
0.08%             ruby                          [.] pushback.isra.10.part.11
```

**Comment by nobu** [comment]
Maybe `pushback` is small enough to be cached, or to be inlined?

**Comment by methodmissing** [comment]
Correct.

* `isra` in the function name references the GCC `-fipa-sra` enabled by opt level `03`

```
Perform interprocedural scalar replacement of aggregates, removal of unused parameters and replacement of parameters passed by reference by parameters passed by value.
```

* The `part` in the name refers to the GCC [function splitting](https://github.com/gcc-mirror/gcc/blob/master/gcc/ipa-split.c#L21-L75) optimization pass

**Pull request closed without merging**
