### PR TITLE
Expose alternative interface to Readline

### PR DESCRIPTION
**Pull request by graywolf**

### CODE REVIEW

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this from master?

**Comment by graywolf** [comment]
I've rebased on the master, hope now everything is in order.

**Comment by graywolf** [comment]
Everything seems to pass now, expect for the last one with "AppVeyor build cancelled". What can I do about that?

**Comment by k0kubun** [comment]
Sorry, I requeued your AppVeyor build now.

**Comment by graywolf** [comment]
All builds seems to pass, anything I can do to help push this forward?

**Comment by k0kubun** [comment]
same as https://github.com/ruby/ruby/pull/1995#issuecomment-570004446

**Comment by graywolf** [comment]
Open PR in readline-ext repo.

**Pull request closed without merging**
