### PR TITLE
fix https://github.com/ruby/ruby/pull/1722

### PR DESCRIPTION
**Pull request by shyouhei**
... by actually documenting everything.

I'm pretty sure I made literally thousands of mistakes here (this is a 25k+ LOC pull request), but I believe this is at least better than nothing.

### CODE REVIEW

**Comment by ioquatix** [comment]
This looks great.

Did you automate the process or do it by hand?

I have some bindings for `ffi-clang` which allow you to extract comments from the C/C++ AST. Maybe helpful for mechanical transforms.

**Comment by shyouhei** [comment]
I did this by hand simply because I wasn't aware of your `ffi-clang`.

**Comment by ioquatix** [comment]
I'm not suggesting that `ffi-clang` would easily solve your problem (I'm not sure about how easy AST rewriting is with comments), but parsing symbols with attached comments is relatively straight forward. If you think it can help, I'm happy to revive the gem and update it to the latest clang.

https://github.com/ioquatix/ffi-clang

Example: https://github.com/ioquatix/ffi-clang/blob/master/examples/docs.rb

**Comment by shyouhei** [comment]
CI is green... Let's merge this.

**Comment by larskanis** [comment]
@shyouhei  Wow, this is a great improvement! I've spend so many hours to inspect ruby sources in order to understand the C-API for writing extensions. This work makes it a lot easier now.

[doc/extension.rdoc](https://github.com/ruby/ruby/blob/master/doc/extension.rdoc) describes many functions in one sentence. This is now somewhat duplicated in the header files. It would be interesting to link them together.

Is there an official URL for the generated Doxygen pages?

**Comment by shyouhei** [comment]
@larskanis extension.rdoc has its own purpose (provides basics rather than comprehensive lists of things).  I don't think we can replace that document using doxygen.

But yes, we lack official doxygen pages, which are definitely nice if any.

**Pull request merged**
