### PR TITLE
Repair internal links

### PR DESCRIPTION
**Pull request by BurdetteLamar**
In previous PR, made last-minute file move, but did not adjust links to that file.  This repairs.

### CODE REVIEW

**Review by jeremyevans — APPROVED** [review]

**Comment by BurdetteLamar** [comment]
@jeremyevans, I have messed up this PR (thought I had already merged it).  It now has my next commit, which changes most "Convert" to "Format".  Should this be merged?  Or should I close and start over?

**Comment by jeremyevans** [comment]
I think this is fine to merge.

**Comment by BurdetteLamar** [comment]
@jeremyevans, we're expecting @peterzhu2118 to return about now.  Do you want to continue with this file, or should I asl Peter to step in?

**Comment by jeremyevans** [comment]
It @peterzhu2118 has time, he can take over.  If not, I'm happy to continue reviewing.

**Comment by peterzhu2118** [comment]
I'm back. Feel free to tag me for reviews.

**Pull request merged**
