### PR TITLE
Prefer cc/gcc over clang on Solaris

### PR DESCRIPTION
**Pull request by shyouhei**
Requested by @tankf33der at https://bugs.ruby-lang.org/issues/17949#change-92430

### CODE REVIEW

**Comment by shyouhei** [comment]
Our CI is basically a no-op here, because we don't have a Solaris+clang combination.  I need someone else's review before pressing the green merge button.

**Comment by tankf33der** [comment]
Testing, will be back asap.

**Comment by tankf33der** [comment]
Solaris11 now compiles by gcc out of box.

**Comment by junaruga** [comment]
@tankf33der I have a question. How do you install clang on your Solaris 10 or 11? I could not find clang package on https://www.opencsw.org/get-it/packages/ . We have SPARC Solaris 10 and 11 servers where clang is not installed. I want to consider to install clang on the environments in the future if it is easy to install.

**Comment by tankf33der** [comment]
> @tankf33der I have a question. How do you install clang on your Solaris 10 or 11? I could not find clang package on https://www.opencsw.org/get-it/packages/ . We have SPARC Solaris 10 and 11 servers where clang is not installed. I want to consider to install clang on the environments in the future if it is easy to install.

@junaruga 
Solaris11 had LLVM6 **package** for many years via builtin standard `pkg` (IPS subsystem) and from version `Oracle Solaris 11.4.30.88.3  Support Repository Update (Oracle Solaris 11.4 SRU 30.88.3)  (Doc ID 2751881.1)` Solaris11 has updated to LLVM11.
You must consider check `pkgsrc` to use in Solaris10 and 11 if you do not have active support plan from Oracle.

I am interested in learn something new and  help you get LLVM, find me privately.

BTW, I gonna try compile ruby3 on IRIX too :)

**Pull request merged**
