### PR TITLE
Finish adding support for AES-CCM mode

### PR DESCRIPTION
**Pull request by louismullie**
Currently, only the GCM mode of authenticated encryption is supported in Ruby. This patch adds support for the CCM mode of authenticated encryption. It also adds support for explicitly setting IV length, which is required by OpenSSL when dealing with non-standard IV lengths in CCM mode. See https://bugs.ruby-lang.org/issues/9642 for more information.

More details:

- Add #ossl_is_ccm macro for AES-128-CCM, AES-192-CCM and AES-256-CCM
- Modify OpenSSL::Cipher#authenticated? to return true for CCM modes
- Add ossl_ccm_set_auth_tag and ossl_ccm_get_auth_tag methods
- Modify OpenSSL::Cipher#auth_tag and OpenSSL::Cipher#auth_tag= to
support CCM
- Add OpenSSL::Cipher#iv_len= method to support non-standard CCM IV
lengths
- Add some documentation on how to use non-standard CCM IV lengths

### CODE REVIEW

**Comment by hsbt** [comment]
@nahi Can you review this?

**Comment by zzak** [comment]
I'm not sold on this patch, and releasing "as-is" is taking priority at the moment.

I also think making `iv_len` public is a bad decision.

**Comment by rhenium** [comment]
OpenSSL needs to know the plaintext length before setting the AAD or starting encrypting. So if we want support AES-CCM in OpenSSL::Cipher, we need another method #plaintext_len=, and of course this is a very bad idea.

**Comment by rhenium** [comment]
As commented before, CCM does not fit with the interface of OpenSSL::Cipher. Please open a new issue at https://github.com/ruby/openssl if you have ideas about this.

**Pull request closed without merging**
