### PR TITLE
process.c: add :exception option to Kernel.#system

### PR DESCRIPTION
**Pull request by k0kubun**
```rb
system('bundle check || bundle install')
# The following gems are missing
# (snip)
# Install missing gems with `bundle install`
# Could not reach host index.rubygems.org. Check your network connection and try again.
# => false

system('bundle check || bundle install', exception: true)
# The following gems are missing
# (snip)
# Install missing gems with `bundle install`
# Could not reach host index.rubygems.org. Check your network connection and try again.
# => RuntimeError: Command failed with status (17): bundle check || bundle install

system('bundler2', exception: true)
# => Errno::ENOENT: No such file or directory - bundler2
```

https://bugs.ruby-lang.org/issues/14386

### CODE REVIEW

**Comment by k0kubun** [comment]
exit status in error message seems wrong. fixing...

**Comment by eregon** [comment]
Looks nice :+1: 

*If you would like*, you can write specs directly under `spec/ruby` for the new feature.
This can be done instead of test under test/ruby ([Feature #13666](https://bugs.ruby-lang.org/issues/13666)).
I think specs would clarify what is being tested and what is the expected behavior.

**Comment by k0kubun** [comment]
> If you would like, you can write specs directly under spec/ruby for the new feature.

Oh, I didn't know that. I appreciate your work on merging two upstreams.

> I think specs would clarify what is being tested and what is the expected behavior.

:+1: I've just committed immediately before your comment, but I'll try that next time!

**Comment by k0kubun** [comment]
Merged in https://github.com/ruby/ruby/commit/fb29cffab05cb5446c1e6cd68035c39143b02763

**Comment by k0kubun** [comment]
I added specs describing this feature at https://github.com/ruby/ruby/commit/c50220619be5c1d83768611a41d27442dd2056de.

**Comment by eregon** [comment]
Thanks!

**Pull request closed without merging**
