### PR TITLE
Improve performance some Float and IO class constants [Feature #19097]

### PR DESCRIPTION
**Pull request by S-H-GAMELINKS**
Improve performance some Float and IO class constants written by Ruby.

benchmark:

```yaml
benchmark:
  Float_RADIX: |
    Float::RADIX
  Float_MANT_DIG: |
    Float::MANT_DIG
  Float_DIG: |
    Float::DIG
  Float_MIN_EXP: |
    Float::MIN_EXP
  Float_MAX_EXP: |
    Float::MAX_EXP
  Float_MIN_10_EXP: |
    Float::MIN_10_EXP
  Float_MAX_10_EXP: |
    Float::MAX_10_EXP
  Float_MIN: |
    Float::MIN
  Float_MAX: |
    Float::MAX
  Float_EPSILON: |
    Float::EPSILON
  Float_INFINITY: |
    Float::INFINITY
  Float_NAN: |
    Float::NAN
  IO_READABLE:
    IO::READABLE
  IO_WRITABLE: |
    IO::WRITABLE
  IO_PRIORITY: |
    IO::PRIORITY
  IO_SEEK_SET: |
    IO::SEEK_SET
  IO_SEEK_CUR: |
    IO::SEEK_CUR
  IO_SEEK_END: |
    IO::SEEK_END
loop_count: 20000000

```

result:

```bash
sh@DESKTOP-L0NI312:~/rubydev/build$ make benchmark/benchmark.yml -e BENCH_RUBY=../install/bin/ruby -e COMPARE_RUBY=~/.rbenv/shims/ruby
../ruby/revision.h unchanged
compare-ruby: ruby 3.2.0dev (2022-11-01T05:34:05Z master 6bf458eefd) [x86_64-linux]
built-ruby: ruby 3.2.0dev (2022-11-02) [x86_64-linux]
# Iteration per second (i/s)

|                  |compare-ruby|built-ruby|
|:-----------------|-----------:|---------:|
|Float_RADIX       |    228.823M|  761.580M|
|                  |           -|     3.33x|
|Float_MANT_DIG    |    222.657M|  306.364M|
|                  |           -|     1.38x|
|Float_DIG         |    217.899M|  301.107M|
|                  |           -|     1.38x|
|Float_MIN_EXP     |    223.007M|  258.014M|
|                  |           -|     1.16x|
|Float_MAX_EXP     |    222.264M|  311.401M|
|                  |           -|     1.40x|
|Float_MIN_10_EXP  |    206.392M|  298.762M|
|                  |           -|     1.45x|
|Float_MAX_10_EXP  |    205.242M|  310.312M|
|                  |           -|     1.51x|
|Float_MIN         |    219.295M|  339.811M|
|                  |           -|     1.55x|
|Float_MAX         |    217.156M|  295.903M|
|                  |           -|     1.36x|
|Float_EPSILON     |    199.553M|  299.349M|
|                  |           -|     1.50x|
|Float_INFINITY    |    217.590M|  317.187M|
|                  |           -|     1.46x|
|Float_NAN         |    218.890M|  275.118M|
|                  |           -|     1.26x|
|IO_READABLE       |    287.937M|  289.072M|
|                  |           -|     1.00x|
|IO_WRITABLE       |    215.121M|  294.124M|
|                  |           -|     1.37x|
|IO_PRIORITY       |    210.967M|  337.100M|
|                  |           -|     1.60x|
|IO_SEEK_SET       |    228.084M|  294.323M|
|                  |           -|     1.29x|
|IO_SEEK_CUR       |    229.345M|  305.353M|
|                  |           -|     1.33x|
|IO_SEEK_END       |    219.930M|  275.197M|
|                  |           -|     1.25x|

```

`COMPARE_RUBY` is `ruby 3.2.0dev (2022-11-01T05:34:05Z master 6bf458eefd) [x86_64-linux]`. `BENCH_RUBY` is ahead of `ruby 3.2.0dev (2022-11-01T05:34:05Z master 6bf458eefd) [x86_64-linux]`.

### CODE REVIEW

**Comment by eregon** [comment]
How come `rb_define_const` produces constants which are slower to read??? cc @k0kubun

**Comment by k0kubun** [comment]
> How come rb_define_const produces constants which are slower to read??? cc @k0kubun

🤔 It seems weird to me too. I'd need some time to investigate it to give an answer. FYI the author of `Primitive` is @ko1, so he might know more than me.

**Comment by S-H-GAMELINKS** [comment]
Probably because `Primitive.cconst!` is called only once at compile time and not at evaluation time.
FYI: https://github.com/ruby/ruby/commit/a3e6f52c17061f012c4e638b3343b57752ed7603

So `Primitive.cconst!` probably works like `C++`'s `constexpr` to improve performance.

**Comment by k0kubun** [comment]
A constant isn't a method, so there's nothing to be evaluated with a constant defined by `rb_define_const` either.

**Comment by nobu** [comment]
I can't see the improvement.

---
compare-ruby: ruby 3.2.0dev (2022-10-30T14:21:31Z master 7ed10abdd9) [x86_64-darwin21]
built-ruby: ruby 3.2.0dev (2022-11-02) [x86_64-darwin21]
\# Iteration per second (i/s)

|                  |compare-ruby|built-ruby|
|:-----------------|-----------:|---------:|
|Float_RADIX       |    222.220M|  201.595M|
|                  |       1.10x|         -|
|Float_MANT_DIG    |    220.510M|  196.858M|
|                  |       1.12x|         -|
|Float_DIG         |    217.791M|  202.519M|
|                  |       1.08x|         -|
|Float_MIN_EXP     |    216.516M|  205.789M|
|                  |       1.05x|         -|
|Float_MAX_EXP     |    219.858M|  200.829M|
|                  |       1.09x|         -|
|Float_MIN_10_EXP  |    210.777M|  204.390M|
|                  |       1.03x|         -|
|Float_MAX_10_EXP  |    219.392M|  203.248M|
|                  |       1.08x|         -|
|Float_MIN         |    222.715M|  200.842M|
|                  |       1.11x|         -|
|Float_MAX         |    229.948M|  202.231M|
|                  |       1.14x|         -|
|Float_EPSILON     |    213.220M|  196.661M|
|                  |       1.08x|         -|
|Float_INFINITY    |    218.446M|  205.884M|
|                  |       1.06x|         -|
|Float_NAN         |    214.397M|  201.068M|
|                  |       1.07x|         -|
|IO_READABLE       |    216.612M|  207.842M|
|                  |       1.04x|         -|
|IO_WRITABLE       |    224.467M|  199.617M|
|                  |       1.12x|         -|
|IO_PRIORITY       |    224.565M|  211.831M|
|                  |       1.06x|         -|
|IO_SEEK_SET       |    225.650M|  212.215M|
|                  |       1.06x|         -|
|IO_SEEK_CUR       |    207.978M|  197.039M|
|                  |       1.06x|         -|
|IO_SEEK_END       |    224.027M|  197.701M|
|                  |       1.13x|         -|

**Comment by S-H-GAMELINKS** [comment]
Thanks for confirming the benchmark.
It doesn't seem to improve in other environments, so I'll close this pull request.

**Pull request closed without merging**
