### PR TITLE
Proposal: Add Time#ceil

### PR DESCRIPTION
**Pull request by osyo-manga**
https://bugs.ruby-lang.org/issues/15772

### CODE REVIEW

**Comment by nobu** [comment]
Please rebase and squash.

**Comment by osyo-manga** [comment]
@nobu Sorry, I fixed it.

**Comment by nobu** [comment]
Similar changes to cc0e460bccbf005d23616be1ea2624a161a4ecdd and 60de17258ba0be6c113e60ce237c3b8608457da7 may be better.

**Comment by osyo-manga** [comment]
Thank! I fixed docs.

**Pull request closed without merging**
