### PR TITLE
Implement OP_ASGN2 NODE locations

### PR DESCRIPTION
**Pull request by ydah**

### CODE REVIEW

**Comment by yui-knk** [comment]
Seem good, @ydah could you rebase the PR to resolve conflict?

**Comment by ydah** [comment]
@yui-knk Maybe, nothing to confict. Please re-check this PR?

**Comment by ydah** [comment]
@yui-knk I did it. Could you please re-review this PR?

**Comment by yui-knk** [comment]
Thank you!

**Pull request merged**
