### PR TITLE
Added a rotate function for the matrix class

### PR DESCRIPTION
**Pull request by rumblinthebronx**
Added a method that rotates the matrix clockwise or counter clockwise.

### CODE REVIEW

**Comment by greggzst** [comment]
@marcandre Ping!

This can be useful e.g to create a spiral matrix by adding the elements to the beginning of matrix and rotating it.

**Comment by marcandre** [comment]
I'm not familiar with "spiral matrix",  nor can I find any reference to it. What are they, what can they be used for?

**Comment by greggzst** [comment]
@marcandre 

Spiral matrix is presented here - [spiral matrix stackoverflow].(https://stackoverflow.com/questions/33684970/print-2-d-array-in-clockwise-expanding-spiral-from-center)
But I mean it's just an example e.g. python has matrix rotate method so does matlab so I reckon they are there to make some operations easier and I think Ruby's Matrix class has a shortage of methods and functionalities so it would be great to enhance it.

**Comment by marcandre** [comment]
Thanks for this pointing out. I remain unconvinced of the actual use of this method. I feel the goal with `matrix` is to provide all functionalities that are actually useful. For other things that are easy to do and seem only useful in homeworks, I'm much less enthusiastic. That's why I'm asking for an actual usecase.

**Comment by greggzst** [comment]
I see your point there. Thanks a lot anyway.

**Comment by marcandre** [comment]
I'll close this, and will gladly reopen and consider if given an actual use case. If that was the case, some kind of `reverse`/`flip` method might be in order too, but again I don't know of a real use for either. Thanks

**Comment by stomar** [comment]
In case this is reopened some time (which I do not advocate hereby): the API with `rotate(true)` vs. `rotate(false)` for indicating direction should be changed at all costs to something that is more self-explanatory.

**Pull request closed without merging**
