### PR TITLE
YJIT: Test more kw and rest cases and change exit name

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Review by XrXr — APPROVED** [review]
By the way, is it intentional that you used `===` over `==`? Might be better to prefer `==` in the future just because it's more popular, so that readers don't stop and think that maybe there is some special intention behind the test choosing `===`.

**Comment by k0kubun** [comment]
Yeah, if you're checking equality and not pattern-matching something, `==` seems more appropriate.

```rb
irb(main)[01:0]> /a/ === "a"
=> true
irb(main)[02:0]> /a/ == "a"
=> false
```

**Comment by jimmyhmiller** [comment]
@k0kubun 
```ruby
irb(main):006:0> my_func("test") == [["test"], nil, false]
=> false

```

**Comment by k0kubun** [comment]
What do you mean? `my_func("test") === [["test"], nil, false]` is also false, right?

`my_func("test") == [["test"], nil, true]` returns true.

**Comment by jimmyhmiller** [comment]
My bad. Copied the wrong thing. I assumed it was object identity for ==. Will change.

**Pull request merged**
