### PR TITLE
RubyGems certs - remove AddTrust, add GlobalSign Root R3

### PR DESCRIPTION
**Pull request by MSP-Greg**
Fixes broken CI.

### CODE REVIEW

**Comment by ioquatix** [comment]
Thanks for figuring this out and making a PR.

**Comment by MSP-Greg** [comment]
@ioquatix

I believe all the normal CI is passing, except Windows (both mingw & mswin) has three test-all failures.

Before the PR, they were failing during install of the bundled gems, so the test-all failures are new.

The ['Compilations' workflow](https://github.com/ruby/ruby/runs/1504590874) appears stuck on the , you might cancel it.

I'll see about the Windows issues, maybe a separate PR...

**Comment by hsbt** [comment]
@ioquatix Did you confirm this root certificate is valid and generate by globalsign?

**Comment by hsbt** [comment]
I did confirm this file same as https://valid.r3.roots.globalsign.com/ .

**Pull request merged**
