### PR TITLE
added support for path stat in ftp

### PR DESCRIPTION
**Pull request by soleboxy**
net/ftp: raw ftp command stat can also be used to get path status (file and dir)
added that functinality to ftp.rb

### CODE REVIEW

**Comment by soleboxy** [comment]
i thought it was worth adding since the standard does support it and it would be a more complete implementation , it is an optional parameter and the default behavior stays the same , so there will be no breakage.

p.s
maybe i should add another method since the stat on a path is more of an alternative to list that uses the control plane of the protocol. 
what do you think?

**Comment by soleboxy** [comment]
@hsbot @nobu  it looks like shugo just copy pasted my stuff and added a line in the news text.
could you please attribute those commits to me?

or at least mention me here:
https://bugs.ruby-lang.org/projects/ruby/wiki/Contributors

**Comment by hsbt** [comment]
see https://github.com/nobu/ruby/commit/c6e97a5b90f2bf74dd37df59e974a243117f3b61

**Comment by hsbt** [comment]
I added you to https://bugs.ruby-lang.org/projects/ruby/wiki/Contributors

**Comment by shugo** [comment]
We can't change the author of the SVN commit log, so I've added credit to NEWS in 94ca443 instead.
Thanks for your contribution.

**Pull request closed without merging**
