### PR TITLE
Introduce Comparable#clamp [Bug #10594]

### PR DESCRIPTION
**Pull request by nerdinand**

### CODE REVIEW

**Comment by myrridin** [comment]
I'm considering a PR to Rails for this functionality. Is there any update regarding this PR and the likelihood it will be merged?

**Comment by drbrain** [comment]
I believe this is too late for Ruby 2.3.

Also, #<=> typically returns -1, 0, or 1, so what value does this add?

```
$ ruby -e 'p -5 <=> 5'
-1
```

**Comment by nerdinand** [comment]
I still hope this will be merged some day. It's been around for months but sadly I'm getting no answer to my question here: https://bugs.ruby-lang.org/issues/10594

@drbrain I don't quite understand your question. The PR does not change `#<=>` at all, but only adds a new method `#clamp` on anything that implements `#<=>`.

**Comment by drbrain** [comment]
Ah, I misread the documentation. I understand now.

I think you still need to provide an answer for the behavior for `"good".clamp "morning", "evening"`

**Comment by nerdinand** [comment]
For the record: This has been merged in https://github.com/ruby/ruby/commit/d5a0b8e3cc48632d0cb99553a7aaf233b22a1eac

**Comment by nerdinand** [comment]
It's part of Ruby 2.4.0

**Pull request closed without merging**
