### PR TITLE
Bump bindgen from 0.63.0 to 0.69.4 in /yjit/bindgen 

### PR DESCRIPTION
**Pull request by ChuckWoodraska**
This [PR bumped shlex](https://github.com/ruby/ruby/pull/9652) in the `Cargo.lock` file but I think what really needs to happen is to bump `bindgen` in the `Cargo.toml` file so that it pulls in shlex 1.3.0 correctly otherwise when it builds it looks like the lock file ends up with shlex 1.1.0

### CODE REVIEW

**Comment by ChuckWoodraska** [comment]
Not sure if this is failing on the `diff` or what: https://github.com/ruby/ruby/actions/runs/9485958865/job/26139167171?pr=10980

**Comment by k0kubun** [comment]
This is what we meant:

Screenshot 2024-06-12 at 10 55 54

I think the CI should show a button that we can push to apply the bindgen changes to the PR. In the meantime, please just include the diff in your branch.

**Comment by XrXr** [comment]
I just tested it without this patch locally and it looks like it's building shlex v1.3.0 correctly, respecting the lock file. I guess your build process involves regenerating the lock file?

**Comment by ChuckWoodraska** [comment]
I'm using ruby-install to install Ruby and when I look at the `usr/local/src/ruby-3.3.3/yjit/bindgen/Cargo.lock` I'm seeing shlex 1.1.0

Commands I'm running to get there:
```
wget https://github.com/postmodern/ruby-install/releases/download/v0.9.3/ruby-install-0.9.3.tar.gz
tar -xzvf ruby-install-0.9.3.tar.gz
cd ruby-install-0.9.3/
make install
ruby-install --system ruby 3.3.3
```

When I pull down and look at the 3.3.3 Release from [here](https://github.com/ruby/ruby/releases/tag/v3_3_3), the lock file shows shlex at 1.1.0

**Comment by XrXr** [comment]
The 3.3.3 release is based off of the release branch https://github.com/ruby/ruby/tree/ruby_3_3, not `master`. To get the shlex update into a release we need a backport and I've filed https://github.com/ruby/ruby/pull/10985 to do that.

Note that if you're just building ruby, `yjit-bindgen` isn't part of the build process at all. It mostly just runs on our CI for making changes.

Thanks!

**Pull request closed without merging**
