### PR TITLE
Add Method Documentation Guide

### PR DESCRIPTION
**Pull request by jeremyevans**
This documents how methods for core classes and classes in the
standard library should be documented.

### CODE REVIEW

**Comment by marcandre** [comment]
I really like it, clear and detailed 👍 🙇‍♂️

There is one thing that I would like to see in the documentation that we don't have. I hope this is a good place to discuss it. Here's my thinking:

I think we could improve existing documentation with **mentions of related methods**. For example, `Enumerable#all?`, `Enumerable#none?`, `Enumerable#one?` do not mention each other, although I think a reader that isn't familiar with the all the numerous methods of `Enumerable` could definitely benefit from that; `Enumerable#count` could also gain from referring to these.

Another example is `Enumerable#chunk` that mentions `chunk_while` and `slice_when`, which is *great*. But `Enumerable#partition` does not mention `group_by` which I find related; and they both are kind of related to `chunk` & al. too, as they all offer a way to divide an enumerable into different groups.

Even methods that are substrings of another (`repeated_permutation` vs `permutation`), or even start with the same name, (e.g. `min` and `min_by`) should imo have a mention of each other. I would go as far as mentioning `Array#map!` as related to `Enumerable#map`.

It could be as simple as finishing the documentation with "Related: #repeated_permutation, #combination".

WDYT?

**Comment by jeremyevans** [comment]
@marcandre Thanks for the review. I agree with you that it makes sense to mention related methods in some cases.  This is similar to how man pages work (the SEE ALSO section).  I can add that as an optional section to the guide, to the very end.

**Comment by drbrain** [comment]
I think we should have a section describing the intended audience.

Documentation for Ruby covered by this guide is written in English, but not all consumers are native speakers of English.  When I review documentation the most frequent thing I've given feedback on is the complexity of the written English.

The current guide overall implies that authors and reviewers should prefer simple, concise language.  It's also written in a style that matches my expectations, but I would like something more explicit.  I think this is a start, but I may have made this writing too simple for our target level of English:

```markdown
== Use of English

Readers of this documentation may not be native speakers of English.  Documentation should be written with this in mind.

Use short sentences and group them into paragraphs that cover a single topic.  Avoid complex verb tenses, excessive comma-separated phrases, and idioms.

When writing documentation define unusual or critical concepts in simple language.  Provide links to authoritative sources, or add a general description to the top-level documentation for the class or module.
```

I think [VoA Learning English](https://en.wikipedia.org/wiki/Learning_English_(version_of_English)) is a reasonable guide to emulate, but I don't feel linking it is entirely appropriate (as Voice of America can be considered American propaganda).

**Comment by jeremyevans** [comment]
@drbrain That is an excellent point.  I plan to include your text verbatim.  We can always refine it later if needed.

**Comment by ioquatix** [comment]
I am happy with this document but there are two things that might be useful to discuss further:

- How to add cross references vs plain inline teletype text.
- A short RDoc guide, given that most people would already understand markdown. So maybe just a few pointers on how to do inline code, block code, very basic formatting, and when such things are appropriate.

**Comment by marcandre** [comment]
>     * A short RDoc guide, given that most people would already understand markdown. So maybe just a few pointers on how to do inline code, block code, very basic formatting, and when such things are appropriate.

Good point. Ideally, such a guide should probably be in RDoc's doc, and a link here to that guide would be quite helpful. If I'm not mistaken, [current RDoc's doc](https://ruby-doc.org/stdlib-2.7.1/libdoc/rdoc/rdoc/index.html) refers to the README that can't be found on `ruby-doc.org`...

**Comment by esparta** [comment]
> Good point. Ideally, such a guide should probably be in RDoc's doc, and a link here to that guide would be quite helpful. If I'm not mistaken, current RDoc's doc refers to the README that can't be found on ruby-doc.org...

Almost every time I need to check up about RDoc I go to the Markup reference, which is not easy to find if you don't know what are you looking for:

https://docs.ruby-lang.org/en/2.5.0/RDoc/Markup.html#class-RDoc::Markup-label-RDoc+Markup+Reference

So a pointer to that would be helpful.

**Comment by jeremyevans** [comment]
@ioquatix @esparta Thanks, I pushed a change to link to the RDoc markup reference.  I used the master branch link so we shouldn't need to update it as the Ruby version changes.

@BurdetteLamar I would appreciate it if you could review the current guide and add your thoughts.

**Comment by BurdetteLamar** [comment]
I have no comments.  Actually, I'm moving on to other work.

**Pull request merged**
