### PR TITLE
Make Base64.urlsafe methods actually urlsafe.

### PR DESCRIPTION
**Pull request by dragonsinth**
https://bugs.ruby-lang.org/issues/10740

### CODE REVIEW

**Comment by jkingdon** [comment]
Looks good to me based on https://tools.ietf.org/html/rfc4648#section-5 and the "padding" section of http://en.wikipedia.org/wiki/Base64

A strict reading of RFC4648 (section 3.2 in particular) might imply that one should allow the caller of these methods to decide whether they want to generate/require padding, but in the urlsafe case it seems better to omit padding, since including it defeats the point of making the encoding urlsafe.

**Comment by danielribeiro** [comment]
+1

**Comment by chriseckhardt** [comment]
:+1:

**Comment by dragonsinth** [comment]
Pushed a change, waiting for CI.  I don't actually know how to run the tests locally. :/

**Comment by drbrain** [comment]
Travis doesn't run the unit tests. `make test` for all tests, `make test TESTS=subdir` to run just the tests in that subdirectory IIRC, `make help` should say

**Comment by dragonsinth** [comment]
Thanks so much, `make test-all TESTS=test/base64` did it for me.  Should be good to go now.

**Comment by dragonsinth** [comment]
@mame

**Comment by hsbt** [comment]
merged at https://github.com/ruby/ruby/commit/6b6680945ed3274cddbc34fdfd410d74081a3e94

**Pull request closed without merging**
