### PR TITLE
updated hash syntax to 1.9

### PR DESCRIPTION
**Pull request by askl56**
Updated outdated hash syntax to 1.9 standards for code and style consistency.

### CODE REVIEW

**Comment by marshall-lee** [comment]
> +5,391 −5,391
> 574 files changed

Was it a sed or awk?

**Comment by hsbt** [comment]
At least you should fix broken tests.

**Comment by knu** [comment]
I tend to disagree with this kind of global migration of a large codebase with a rich history.  It would break the `svn/git blame` history for no real benefits.  I'd prefer updating portions of the code as they are touched.

**Comment by askl56** [comment]
Fair enough, sorry guys I was just trying to help :+1:

**Comment by marshall-lee** [comment]
> I'd prefer updating portions of the code as they are touched.

:+1: for this!

**Pull request closed without merging**
