### PR TITLE
Pattern matching pin operator against expression [Feature #17411]

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Review by marcandre — APPROVED** [review]
Really nice!

**Comment by marcandre** [comment]
I created doc for this in #3986

Can both be merged now?

**Comment by k-tsj** [comment]
Thanks, @nobu.

This patch seems to be slightly buggy, so I've revised the patch (https://github.com/k-tsj/ruby/tree/p_expr_ref).

```
$ miniruby -e '
  case 0
  in ^(0+0)
  end
'
-e:3: NODE_IN: unknown node (NODE_OPCALL)
-e: compile error (SyntaxError)
```

**Comment by marcandre** [comment]
Did you mean to create a new PR for this @k-tsj ?

**Comment by k-tsj** [comment]
@marcandre:
You don't need to create a new one.
I will merge it after I get Matz's final agreement.

**Pull request closed without merging**
