### PR TITLE
Change quote symbol in expection 'NoMethodError'

### PR DESCRIPTION
**Pull request by ShockwaveNN**
Change it to match symbol after `#{mid}`

### CODE REVIEW

**Comment by marcandre** [comment]
Thanks for the PR, but I'm afraid that this is the standard error message, is it not?

    > ruby -e "42.foo"
    -e:1:in `<main>': undefined method `foo' for 42:Fixnum (NoMethodError)

**Comment by ShockwaveNN** [comment]
Oh, sorry. I see now, that same syntax used in many places. But I cannot understand why quotes not paired

**Comment by marcandre** [comment]
I think it's a poor man's replacement for ‘ and ’
The fact that ASCII only had one single and one double quote, instead of an opening and closing pair for each is a tragedy that will plague us till the end of time.

**Comment by ShockwaveNN** [comment]
Isn't ruby use UTF-8 for default since Ruby-2.0 (or so). Are we really should consider ASCII symbols to end of time?

**Comment by nobu** [comment]
External encoding is not always UTF-8.

**Pull request closed without merging**
