### PR TITLE
NEWS: add backquotes

### PR DESCRIPTION
**Pull request by marcandre**
lots of them. Looks much better this way.

Also updated intro that was no longer accurate

### CODE REVIEW

**Comment by zverok** [comment]
I am not sure it is a good decision, actually. I assumed there is no backticks to let RDoc find class definitions: https://docs.ruby-lang.org/en/master/NEWS_md.html#label-Core+classes+updates
image

Not sure if people actually read NEWS at `docs.ruby-lang.org`, but still...

**Comment by marcandre** [comment]
Oh, I see. Since I was running rdoc only on that file, I wasn't seeing that. I'll revise. Thanks!

**Comment by marcandre** [comment]
Updated, and created https://github.com/ruby/rdoc/issues/783

**Comment by marcandre** [comment]
Merged in a495cb2fd5

**Pull request closed without merging**
