### PR TITLE
Doc guide for class/module

### PR DESCRIPTION
**Pull request by BurdetteLamar**
* Adds some documentation guide for class/module.
* Segregates the parts common to method and class/module.
* Adds links to specific sections in RDoc documentation.

### CODE REVIEW

**Comment by BurdetteLamar** [comment]
> 
> 
> I think this is a good change. However, I'd like to get feedback from another committer before merging.

@jeremyevans, anyone in particular you have in mind?

**Review by marivaldo — APPROVED** [review]

**Comment by BurdetteLamar** [comment]
> 
> 
> I think this is a good change. However, I'd like to get feedback from another committer before merging.

@jeremyevans, good to go?

**Comment by jeremyevans** [comment]
> > I think this is a good change. However, I'd like to get feedback from another committer before merging.
> 
> @jeremyevans, good to go?

Not yet.  I appreciate @marivaldo's review, but we need feedback from another committer.

**Comment by BurdetteLamar** [comment]
> 
> 
> > > I think this is a good change. However, I'd like to get feedback from another committer before merging.
> > 
> > 
> > @jeremyevans, good to go?
> 
> Not yet. I appreciate @marivaldo's review, but we need feedback from another committer.

@jeremyevans, can you request a review from someone you think should see this?

**Comment by BurdetteLamar** [comment]
@marcandre, can you help out with this PR?  It needs either to move forward or to be closed.

**Review by ioquatix — APPROVED** [review]

**Review by marcandre — APPROVED** [review]
LGTM 👍

**Pull request merged**
