### PR TITLE
String as Regexp.new options

### PR DESCRIPTION
**Pull request by nobu**
https://bugs.ruby-lang.org/issues/18788

### CODE REVIEW

**Comment by jaynetics** [comment]
@nobu two small thoughts:

- maybe encoding flags should be supported like in [my newbie attempt](https://github.com/ruby/ruby/pull/6040) so that the literal notation and `Regexp.new` behave the same way?
- maybe the warning isn't ideal because it will make people use `true` or `false` which are currently very exotic, and if people use `"i"`, `Regexp::IGNORECASE` etc., that would be more readable?

**Comment by nobu** [comment]
The failures I saw in the CIs were `"n"`.
If we allow encoding options in the second argument, these bugs will be "fixed" silently in Ruby 3.2 but will never be noticed in earlier versions.
It seems too confusing to me.

**Comment by nobu** [comment]
Regarding the warning, do you want to deprecate `true`/`false` as well as non-integer, non-string, non-boolean objects, and to make the argument integer or string only?
It would be worth to be considered in the future, but feels early a little.

**Comment by jaynetics** [comment]
> If we allow encoding options in the second argument, these bugs will be "fixed" silently in Ruby 3.2 but will never be noticed in earlier versions. It seems too confusing to me.

i see!

> Regarding the warning, do you want to deprecate true/false as well

maybe not deprecate it yet, but also not recommend it anymore.

i would warn like so (i haven't tested this code):

```
else if ((f = str_to_option(opts)) >= 0) flags = f;
else if (opts == Qtrue) flags = ONIG_OPTION_IGNORECASE;
else if (opts != Qfalse && !NIL_P(opts)) {
  rb_category_warn(RB_WARN_CATEGORY_DEPRECATED,
                   "using %"PRIsVALUE" to make a Regexp case-insensitive is deprecated",
                   rb_class_name(CLASS_OF(opts)));
  flags = ONIG_OPTION_IGNORECASE;
}
```

this would match a [recent update to the Regexp documentation](https://github.com/ruby/ruby/commit/51ea67698e36f9a0a3a3aa9a4566b6bec4b41bd3#diff-c3675fa319803b2f5a775defa40694edb9a761baa3a54fa78e1fdef8f918cc7cL3558) that removed the suggestion to pass `true`.

i would also suggest updating the documentation like so:

```diff
--- a/re.c
+++ b/re.c
@@ -3663,6 +3663,11 @@ rb_reg_match_p(VALUE re, VALUE str, long pos)
  *
  *  Optional argument +options+ is one of the following:
  *
+ *  - A String of options:
+ *
+ *      Regexp.new('foo', 'i')  # => /foo/i
+ *      Regexp.new('foo', 'im') # => /foo/im
+ *
  *  - The logical OR of one or more of the constants
  *    Regexp::EXTENDED, Regexp::IGNORECASE, and Regexp::MULTILINE:
  *
```

and maybe here as well:

```diff
```diff
--- a/doc/regexp.rdoc
+++ b/doc/regexp.rdoc
@@ -615,10 +615,10 @@ pattern:

 Options may also be used with <tt>Regexp.new</tt>:

-    Regexp.new("abc", Regexp::IGNORECASE)                     #=> /abc/i
-    Regexp.new("abc", Regexp::MULTILINE)                      #=> /abc/m
-    Regexp.new("abc # Comment", Regexp::EXTENDED)             #=> /abc # Comment/x
-    Regexp.new("abc", Regexp::IGNORECASE | Regexp::MULTILINE) #=> /abc/mi
+    Regexp.new("abc", "i")           #=> /abc/i
+    Regexp.new("abc", "m")           #=> /abc/m
+    Regexp.new("abc # Comment", "x") #=> /abc # Comment/x
+    Regexp.new("abc", "mi")          #=> /abc/mi

 == Free-Spacing Mode and Comments
```

**Pull request merged**
