### PR TITLE
Permit "+" operator as an alias to merge hashes

### PR DESCRIPTION
**Pull request by dctremblay**
The main reason why I absolutely appreciate Ruby programming language is because operators are ubiquitous among the syntax. That's why I think that be able to merge hashes with the + operator would be extremely cool.

I thought to contribute that patch while doing something I thought was not homogenous throught the syntax. It this case it was a Redmine plugin. For instance :

```ruby
def self.fetch_and_summation(scope, extra_conditional)

    in_trackers = {:tracker => {:is_closed => false}}
    in_scope = {(scope.class.name.downcase.to_sym) => scope}
    # [...] Many more others conditionals similar to those

    stuff[:estimated_hours] = Issue.where(in_trackers.merge(in_scope).[...]).group(:category).sum([...])[...]
    # [...] Many more others queries similar to this

    return stuff;

end
```
Using `k1.merge(k2).merge(k3)` seems very scary compared to the rest of source code.

With that patch it would look like more like this :
```ruby
stuff[:estimated_hours] = Issue.where(in_tracker + in_scope + extra_conditional + [...])
```

It is ultra sexy isn't it ? It works directly from an alias of the blessed core Hash.merge method.

### CODE REVIEW

**Comment by znz** [comment]
Rails 3.0 only had `#&` alias for `#merge`, but removed. http://apidock.com/rails/v3.0.9/ActiveRecord/SpawnMethods/%26

**Comment by dcotet** [comment]
Interesting, why they removed a such functionality ? That patch is meant for the Ruby Lang; Rails was used for example purposes.

**Comment by znz** [comment]
I don't know why removed, because [removed commit](https://github.com/rails/rails/commit/fbd917f50a6046d02dd6a64ccfb1aed0cbce68d8) and [deprecated commit](https://github.com/rails/rails/commit/66003f596452aba927312c4218dfc8d408166d54) have no references.

**Comment by qnet-herwin** [comment]
It looks pretty much like a duplicate of  #1359 to me

**Comment by k0kubun** [comment]
This feature https://bugs.ruby-lang.org/issues/6225 looks like rejected by Matz. Please discuss it to persuade him there, and reopen this once it's accepted. Thanks.

**Pull request closed without merging**
