### PR TITLE
.travis.yml: Ubuntu 20.04 Focal Fossa

### PR DESCRIPTION
**Pull request by shyouhei**
This is a LTS.  Must be better than Xenial.

### CODE REVIEW

**Comment by shyouhei** [comment]
Oops, i686 failure reminds me that Ubuntu no longer provides 32bit binaries.  What to do?

- Stick to Xenial, or Bionic (which seems supported until 2023).
- Drop i686

**Comment by shyouhei** [comment]
@k0kubun @mame @junaruga I want to hear your opinions.

**Comment by mame** [comment]
> Oops, i686 failure reminds me that Ubuntu no longer provides 32bit binaries.

Really?  Focal seems to provide i386 binaries.  (I don't know the difference between i386 and i686.)

```
E: Unable to locate package libffi6:i386
E: Unable to locate package libgdbm3:i386
E: Unable to locate package libreadline6:i386
```

These failures seems due to the change of package versions: [libffi7](https://packages.ubuntu.com/focal/libffi7), [libgdbm6](https://packages.ubuntu.com/focal/libgdbm6), and [libreadline8](https://packages.ubuntu.com/focal/libreadline8) in Focal.  i386 packages seems available.

**Comment by shyouhei** [comment]
It seems Ubuntu [now officially has "selected" packages for i386](https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts).  The selection itself is unclear.  A developer says [1,700 out of 3,000](https://lists.ubuntu.com/archives/ubuntu-devel/2019-November/040852.html).

So yes.  They are sunsetting 32bit environments.  Maybe we can build ruby today, but maybe not tomorrow.

**Comment by nurse** [comment]
> Stick to Xenial, or Bionic (which seems supported until 2023).

I for this. I think we still check ILP32 for a while.

**Comment by k0kubun** [comment]
As long as a similar environment is covered by any other CI (preferably GitHub Actions for better availability of concurrency), I'm not against dropping anything from Travis CI. 
If the purpose to drop i686 is just for .travis.yml maintenance reasons and we do not intend to drop the support, we could override `dist: xenial` only for i686 for now or move the environment to GitHub Actions instead.

**Comment by shyouhei** [comment]
> we could override dist: xenial only for i686 for now 

Let me try this.

**Comment by junaruga** [comment]
> Stick to Xenial, or Bionic (which seems supported until 2023).

:+1:

**Comment by mame** [comment]
I completely agree with @k0kubun.

BTW, I gave [a try to Focal's i386 packages](https://github.com/ruby/ruby/pull/3173).  They seem to [work perfect](https://travis-ci.org/github/ruby/ruby/jobs/693499192) to build ruby.  `make test-spec` fails, but this issue is the same as other architectures including amd64.

**Comment by junaruga** [comment]
> If the purpose to drop i686 is just for .travis.yml maintenance reasons and we do not intend to drop the support, we could override dist: xenial only for i686 for now or move the environment to GitHub Actions instead.

My above +1 meant to override `dist: ` for i686 case. And the current code overriding `dist: bionic` looks good to me.

**Comment by shyouhei** [comment]
The situation so far:

- Dependency issues are almost resolved; all runs except Baseruby:2.2 at least install what are necessary.
- [`BASERUBY: 2 2` fails](https://travis-ci.org/github/ruby/ruby/jobs/693735432), because Travis no longer ships ruby 2.2 in their container.
    - This is understandable. Ruby 2.2 does not compile with OpenSSL 1.1.
    - This means **we have to give up either ruby 2.2 or openssl 1.1**.
- The `make test-spec` issue @mame pointed is ubiquitous.  While seemingly environmental, it has to be worked around before merging the pull request,.
- Additionally, [bionic's i686 tests fail with "invalid stdio handle"](https://travis-ci.org/github/ruby/ruby/jobs/693735429#L3013).  This is not seen in @mame's focal try.  Might worth use his changeset.
- I don't understand why `tools/update-deps` [fails this way](https://travis-ci.org/github/ruby/ruby/jobs/693499198).  Maybe directory sort order etc?

**Comment by GrahamCampbell** [comment]
> This is a LTS. Must be better than Xenial.

Xenial was also LTS, and is still supported.

**Comment by hsbt** [comment]
@shyouhei I'm closing this because we leave from Travis now for Ruby CI env.

**Pull request closed without merging**
