### PR TITLE
Delete or warn deprecated features (rev. 2)

### PR DESCRIPTION
**Pull request by shyouhei**
Revised #3394

|Feature|Warned (without `-w`) since|This pull request|
|:-|-:|:-|
|`Hash#index`|1.9.0|Deletes it|
|`IO#bytes`|2.0.0|Deletes it|
|`Enumerator.new` without a block|2.0.0|Deletes it|
|`Thread.exclusive`|2.3.0|Deletes it|
|`Data`|2.5.0|Deletes it|
|`Struct::Tms`|2.6.0|Deletes it|
|`Object#=~`|2.7.0|Knells for 3.1|
|`Dir.exists?`|2.8.0|Knells for 3.2|
|`FileTest.exists?`|2.8.0|Knells for 3.2|
|`$,`,`$/`,`$\`,`$;`|2.8.0|Knells for 3.2|
|`lambda(&variable)`|2.8.0|Knells for 3.2|

### CODE REVIEW

**Comment by shyouhei** [comment]
I wasn't aware of #3408.  It seems https://github.com/ruby/ruby/pull/3412/commits/b35167256b34752246a0ad02bb06e84a67190f7d is better.  Much concise, also it does not delete specs.

**Comment by nobu** [comment]
Why 3.1 and 3.2?
Can't we delete the deprecated feature warned since 2.7 in 3.0?

**Comment by shyouhei** [comment]
@nobu Because @marcandre wants "two full releases with non-verbose warning" in #3394, those what we started warning since 2.7 cannot be deleted in 3.0.

**Comment by jeremyevans** [comment]
> @nobu Because @marcandre wants "two full releases with non-verbose warning" in #3394, those what we started warning since 2.7 cannot be deleted in 3.0.

I disagree with @marcandre, and there are plenty of prior cases where we removed features after a single full release with a non-verbose warning.  $SAFE and numbered parameter assignment outside of a block are two examples in 2.7 and 3.0.

One full release with a non-verbose warning is sufficient.  If the warning is non-verbose in 2.7, we can remove in 3.0.  If the warning is only verbose in 2.7, we need to make it non-verbose in 3.0, and then we can remove it in 3.1.

**Comment by marcandre** [comment]
> > @nobu Because @marcandre wants "two full releases with non-verbose warning" in #3394, those what we started warning since 2.7 cannot be deleted in 3.0.
> 
> One full release with a non-verbose warning is sufficient. 

Agreed. I only suggested two full releases "for methods where removal affords quite small saving", i.e. when there's not a compelling reason to remove things (e.g. `Dir.exists?`). One full release is fine. The original PR had zero full releases between non-verbose warning and removal of minor things like `Dir.exists?`...

**Comment by marcandre** [comment]
Thanks @shyouhei for the research on versions with explicit warnings 👍

I'm not sure adding a future release number in the warning is actually helpful; “It's tough to make predictions, especially about the future” 

Maybe a comment in the code as to which version the non-verbose warning was added would be best.

**Comment by shyouhei** [comment]
> I'm not sure adding a future release number in the warning is actually helpful; “It's tough to make predictions, especially about the future”

Those release number might not help users, but does help us a lot at.  I skipped various deprecated features in this pull request thanks to proper annotations on them ("it is not yet the time").

> Maybe a comment in the code as to which version the non-verbose warning was added would be best.

Might be an option to keep the APIs as-is (they take the prediction), and just stop showing that info at runtime?

**Comment by shyouhei** [comment]
Do we have consensus that we delete `Object#=~` today?  Can cherry-pick https://github.com/ruby/ruby/pull/3394/commits/82ab4df61014eda75b97c3177ce65a69bf17390b then.

**Comment by marcandre** [comment]
> just stop showing those info at runtime?

Sure, that's fine

> Do we have consensus that we delete Object#=~ today?

I have no objection; was probably never a good idea to use that

**Comment by shyouhei** [comment]
#3424

**Pull request closed without merging**
