### PR TITLE
monitor.rb: Fix the bug that an exception still causes a state inconsistency

### PR DESCRIPTION
**Pull request by yoheimuta**
If an exception is raised from another thread and this thread is just after mon_enter, the exception breaks the state of MonitorMixin. 

I'm sure this behavior contradicts users' pure expectations because the comment says [Prevent interrupt on handling interrupts; for example timeout errors. it may break locking state](https://github.com/ruby/ruby/commit/f91879a7b548284c93743168acfd11e3d2aeefac). Besides, once it happens, restoring this inconsistency is hardly possible for an application depending on the library using a monitor internally.

To prevent that situation, it needs to block interruption in mon_synchronize entirely.

PS. I fully understand that I had better(+ want to) create a Redmine issue beforehand in order to discuss it carefully. I tried to register hard, but [unfortunately, it failed at the moment](https://github.com/ruby/b.r-l.o/issues/119). I'm afraid it could bother you, but I'm taking a chance that [this PR doesn't need a long discussion](https://bugs.ruby-lang.org/projects/ruby/wiki/HowToContribute). That said, I prepared an alternative [bug-report at my gist space](https://gist.github.com/yoheimuta/f899df23ff5e7e2ad274ea183c38690f) by reference to the official examples. It includes a description, an output of `ruby -v`, a reproducible script, and script logs. If you feel this PR should need a discussion, I'm willing to close it. Thank you.

### CODE REVIEW

**Comment by yoheimuta** [comment]
> Some checks were not successful

[memo] Given that recent checks regarding the ruby_2_6 branch continue failing, I guess it's not caused by my commit.

- ref. https://github.com/ruby/ruby/commits/ruby_2_6

**Comment by yoheimuta** [comment]
@unak @nurse ping [[1]](https://bugs.ruby-lang.org/projects/ruby/wiki/ReleaseEngineering) [[2]](https://bugs.ruby-lang.org/issues/15992)

- ref. [If the ticket doesn't have any replies after 10 days, you can send a reminder.](https://github.com/ruby/ruby/blob/1729fd8c0acd66aec20bb6986bd82913c9dc190d/doc/contributing.rdoc#label-How+To+Report)

**Comment by hsbt** [comment]
@yoheimuta Ruby 2.6 didn't use GitHub. Can you file this to https://bugs.ruby-lang.org/?

**Comment by yoheimuta** [comment]
@hsbt Thank you for telling me.
I filed https://bugs.ruby-lang.org/issues/17669 and closed https://github.com/ruby/b.r-l.o/issues/119.

**Pull request closed without merging**
