### PR TITLE
Merge URI-0.12.0 for Ruby 3.0

### PR DESCRIPTION
**Pull request by hsbt**
https://bugs.ruby-lang.org/issues/19414

### CODE REVIEW

**Comment by hsbt** [comment]
We decide to backport URI-0.10.2 into `ruby_3_0`.

**Comment by noraj** [comment]
How could we do? https://github.com/ruby/ruby/blob/ruby_3_0/lib/uri.rb is still missing `require_relative 'uri/ws'` and `require_relative 'uri/wss'`.

**Comment by noraj** [comment]
Also was https://github.com/ruby/uri/commit/81263c9e94bd67ca01deee238842a88c2c8885f3 the commit fixing this bug?

```irb
irb(main):004:0> URI('ldap://ds.example.com:389/dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)')
=> #<URI::LDAP ldap://ds.example.com/dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)>
irb(main):005:0> URI('ldap:///dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)')
=> #<URI::LDAP ldap:/dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)>
```

**Comment by hsbt** [comment]
@noraj Please file your concerns to https://github.com/ruby/uri, not this.

**Comment by noraj** [comment]
Sorry the second message may seem out of scope. But the first one is totally in the context.

An issue was submitted on Ruby issue tracker ([uninitialized constant URI::WSS in 3.0.X and 3.1.X](https://bugs.ruby-lang.org/issues/19414)) which lead to https://github.com/ruby/ruby/pull/7260 and https://github.com/ruby/ruby/pull/7261 backport PRs. But since #7260 was not merged the issue remains where `require_relative 'uri/ws'` and `require_relative 'uri/wss'` are missing from https://github.com/ruby/ruby/blob/ruby_3_0/lib/uri.rb. No need to open an issue on https://github.com/ruby/uri since https://github.com/ruby/uri/blob/v0-12/lib/uri.rb already include the change, it's just not backported on 3.0.

The second message is also about backporting, the bug is already fixed in uri 0.12.1 which is already backported on 3.1 and 3.2 branches but not on 3.0.

With uri `0.12.1`
```irb
irb(main):002:0> URI('ldap:///dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)')
=> #<URI::LDAP ldap:///dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)>
```
With uri `0.11.1`
```
irb(main):003:0> URI('ldap:///dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)')
=> #<URI::LDAP ldap:/dc=example,dc=com?givenName,sn,cn?sub?(uid=john.doe)>
```

**Comment by hsbt** [comment]
Unfortunately, there is no chance to fix it because Ruby 3.0 is already only security fix status. Please use URI-0.11.x or 0.12.x.

**Pull request closed without merging**
