### PR TITLE
Remove dead code in rb_obj_copy_ivar

### PR DESCRIPTION
**Pull request by peterzhu2118**
The removed code is a duplicate of the code above.

### CODE REVIEW

**Comment by peterzhu2118** [comment]
cc. @jemmaissroff

**Comment by tenderlove** [comment]
Are you sure this is true?  I think `rb_ensure_iv_list_size` mutates the shape on `dest`

**Comment by peterzhu2118** [comment]
The `initial_shape` on line 293 (which is above this patch) gets the shape of `dest`, then rebuilds the shape on line 298, then expands the iv_list on line 303.

It then gets the shape of `dest` in `initial_shape` on line 306 (which is removed in this patch), this `initial_shape` is the exact same shape as the one above (since the shape of `dest` was not changed). And then performs the exact same steps as above. The rebuilding of the shape should result in the same shape, so the second call to `rb_ensure_iv_list_size` shouldn't ever do anything.

**Comment by tenderlove** [comment]
@peterzhu2118 nice.  Thank you for explaining!

**Pull request merged**
