### PR TITLE
Support American Fuzzy Lop

### PR DESCRIPTION
**Pull request by shyouhei**
Insert __AFL_INIT() so that AFL can defer snapshotting process image.
This speeds up AFL from 75.57 exec/sec to 1225 exec/sec on my machine.

As of writing you need to compile using afl-clang-fast compiler
frontend, and run ruby with afl-fuzz.  Consult [AFL's document](https://github.com/mirrorer/afl/blob/master/llvm_mode/README.llvm) for more
info.

### CODE REVIEW

**Comment by clod81** [comment]
@shyouhei I tried to use your solution, but I don't seem to gain any speed. 
I get good speed improvements by using this modified version of `main.c`: 
https://gist.github.com/clod81/6f1b9f3e23ac2d8200fd2139503ce5d9

To be specific, I tried to compile Ruby version 2.4.2 with the change you suggested, as per: https://gist.github.com/clod81/531eda153b06eb3f75510e42a86f3166 , but again, no speed improvement there.

**Comment by shyouhei** [comment]
@clod81 Thank you.

However your proposed `main.c` seems inappropriate because `ruby_options()` can run arbitrary ruby script including threads and/or child process creations, IO operations, and timer manipulations.  They are prohibited by the AFL document I mentioned above.  `__AFL_INIT();` must be inserted much earlier.

And I guess that relates to the reason your test does not gain speed up; perhaps you specified some heavay-lifting command line options like `-r rails` ?

**Comment by clod81** [comment]
@shyouhei no, I was just trying `ruby` alone. For example, when calling Marshal.load, with my setup it on my machine it was running with around 500 execs per sec, with this setup, around 10 or 20 (I will need to double check that). I will try to setup a docker image later today with your proposed setup, and we can try it out.

**Comment by clod81** [comment]
@shirosaki 

Here a docker image with the setup you suggested:
- https://hub.docker.com/r/clod81/afl-ruby-2.4.2-persist-in-ruby.c

This one with my attempt:
- https://hub.docker.com/r/clod81/afl-ruby2.4.2

I've been using my setup to fuzz a few gems with C extensions, and I didn't have any issue with it

**Comment by zelivans** [comment]
@shyouhei I am also unable to reproduce the improvement in fuzzing with this patch. I tested by fuzzing a simple logic (only IO.binread).

Perhaps you could share the arguments you ran afl with?

Thanks

**Pull request closed without merging**
