### PR TITLE
Adds a return value for attr* methods

### PR DESCRIPTION
**Pull request by jballanc**
This pull request changes `attr`, `attr_reader`, `attr_writer`, and
`attr_accessor` so that the now return an array of symbols representing
the methods that have effectively been added. This matches with the
behavior of `def` since the 2.1.0 release.

### CODE REVIEW

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this against master?

**Comment by k0kubun** [comment]
Let me close this as it has not been updated for a while. Please reopen this after resolving conflicts.

Also please file a ticket to discuss the feature at http://bugs.ruby-lang.org/ or attach the link to the pull request if it's already filed. Thanks.

(I sometimes want this feature too, for doing `private attr_reader :foo`. But this change might be considered as backward incompatibility and so you should file a ticket to discuss the change.)

**Comment by k0kubun** [comment]
znz told me that you actually filed https://bugs.ruby-lang.org/issues/9453, and sadly it seems to have been rejected.

**Comment by jballanc** [comment]
Hah...funny to see this old issue pop up in my inbox. Too bad that this was rejected, however it does seem like Ruby hasn't exactly progressed in the way I thought it might regarding method decoration (i.e. I'm not sure I've seen anyone really do anything terribly interesting with the fact that `def` now returns a symbol...).

**Pull request closed without merging**
