### PR TITLE
gc.h: Add SET_MACHINE_STACK_END specific for Powerpc64

### PR DESCRIPTION
**Pull request by leitao**
Currently we are not able to grab the correct end/top of the stack on
powerpc64 due to the fact that it uses the fallback function.

The fallback function does not return the correct top of the stack
because it adds a new frame and the returned top of the stack contains
this frame overhead that could be something around 112 bytes on
Powerpc64.

This patch simply gets the correct top of the stack pointer, which is
always on r1 register according to both ABI v1 and ABI v2 (Little
endian).

Signed-off-by: Breno Leitao <leitao@debian.org>

### CODE REVIEW

**Comment by shyouhei** [comment]
It seems nobody on the project can review this pull request.  Can we just merge this to see if anyone can test this in the preview?

**Comment by shyouhei** [comment]
I very much appreciate if I could have any advice on it from @odaira.

**Comment by odaira** [comment]
@shyouhei I review it in a few days.

**Comment by ioquatix** [comment]
It looks okay to me. If there are issues you would potentially see segfaults. So it should be obvious.

**Comment by ioquatix** [comment]
Just to add to this, we also use this code path in fiber code for efficient stack GC. When I had the code wrong, GC may fail in various ways. So fiber tests are a good check for this. Not exhaustive, but a good indicator of issues.

**Comment by odaira** [comment]
The patch looks good to me.  I tested it on Linux ppc64 and ppc64le.  It should work on all the ABIs.

**Comment by shyouhei** [comment]
Great!  Thank you.  Let's merge this then.

**Comment by AndreaRibuoli** [comment]
Anyone ever tried this on AIX or IBM i PASE? 

I patched locally with: 

``` c
 #elif defined(__powerpc64__) && !defined(_AIX) && defined(__GNUC__)
```

to avoid native assembler failure in PASE.

**Pull request merged**
