### PR TITLE
Update peephole optimizer to avoid unnecessary array allocations

### PR DESCRIPTION
**Pull request by jeremyevans**
These unnecessary array allocations are at least generated by multiple
assignment.

Briefly, the optimizations are:

```
newarray(2)/expandarray(2, 0) -> swap
newarray(X)/expandarray(X, 0) -> opt_reverse(X)
newarray(X)/expandarray(Y, 0) -> putnil*(Y-X)/opt_reverse(Y) # X < Y
newarray(X)/expandarray(Y, 0) -> pop*(X-Y)/opt_reverse(Y) # X > Y
duparray/expandarray -> putobject/expandarray
```

opt_reverse is the same as the reverse instruction previously
present, which was removed last year.  I renamed it to opt_reverse
because it is only used by the optimizer.

benchmark/masgn.yml shows a 35-85% performance improvement in the
cases where the unnecessary allocation is avoided.

While I've only tested multiple assignment cases, this optimization
should apply to all use of the combination of these instructions,
which is why I think it makes sense to be in the peephole optimizer.

Currently, the YJIT tests are broken with this, but I'm not yet sure
why that is.

### CODE REVIEW

**Comment by maximecb** [comment]
> Currently, the YJIT tests are broken with this, but I'm not yet sure
why that is.

The YJIT tests seem to be passing?

**Comment by jeremyevans** [comment]
> > Currently, the YJIT tests are broken with this, but I'm not yet sure
> > why that is.
> 
> The YJIT tests seem to be passing?

They are now.  The were broken before the last commit.  @XrXr told me I needed to take a patch produced by one of the failing YJIT CI jobs, and apply it.  I did that and it fixed the issue.  I think all Ruby committers would appreciate it if YJIT could handle changes to instructions automatically, since it obviously knows how to fix the issue.

**Comment by maximecb** [comment]
> > > Currently, the YJIT tests are broken with this, but I'm not yet sure
> > > why that is.
> > 
> > 
> > The YJIT tests seem to be passing?
> 
> They are now. The were broken before the last commit. @XrXr told me I needed to take a patch produced by one of the failing YJIT CI jobs, and apply it. I did that and it fixed the issue. I think all Ruby committers would appreciate it if YJIT could handle changes to instructions automatically, since it obviously knows how to fix the issue.

IIUC the issue is that when adding/removing instructions, some of the constants for instruction ids change. That means the YJIT Rust bindings need to be regenerated. We could regenerate them every time YJIT is built @XrXr ?

**Comment by XrXr** [comment]
The binding generation tool depends on Clang, so if we always run it during build we’d make YJIT require Clang to build which is undesirable. The output works with GCC, so checking it in to Git severs that dependency at the cost of the annoyance mentioned above. We could maybe move the binding generation to when building a release tarball and maybe require Clang for YJIT development or something. That would be a more complicated setup, though.

**Pull request merged**
