### PR TITLE
fix for #9367

### PR DESCRIPTION
**Pull request by bearmini**
xmldecl is now also using :attribute_quote context setting.

### CODE REVIEW

**Comment by kou** [comment]
I've reviewed and commented at https://redmine.ruby-lang.org/issues/9367#note-10
There is no response. I want to close it.

**Comment by hsbt** [comment]
Thanks your comment for issue status.

**Comment by knu** [comment]
Looks like Ruby Redmine is not a good place for a code review.  I think @bearmini could update (force-push) this PR for every revised patch and @kou could then add line comments.

**Comment by konung** [comment]
Hi. 
I ran into the same issue.  Since there seems to be a question of "why would you do that", based on the discussion on Rubymine, I'd like to add a comment.
I came across this when dealing with XML generated for consumption by a Java (Jetty) based service (used in ebXML exchange popular in Automotive industry).  


1. It complains the file is malformed and won't parse it if the XML declaration is not double quoted, like the rest of the document. 
2. It also doesn't want to parse single quoted attributes in XML file. ( Specifying ` doc = REXML::Document.new(source);     doc.context[:attribute_quote] = :quote` -> works!) 
3. Finally it doesn't like '\n' UNIX-style line endings, and wants Windows-style endings ( I sidestepped the issue by using `File.write(src, str, crlf_newline: true)` when generating final file. )

So the only remaining problem is 1 - right now I'm working around the issue by parsing the file before saving and replacing single quotes with double quotes in xml  declaration. But I wanted to explain why this is a useful option, despite not being 100% true to the standard. 

Thank you

**Comment by kou** [comment]
@konung Can you open a new issue at https://github.com/ruby/rexml/issues ?
We should move to ruby/rexml.

**Comment by kou** [comment]
Thanks.

**Pull request closed without merging**
