### PR TITLE
Improve Time#== performance

### PR DESCRIPTION
**Pull request by Watson1978**
Time#== will be faster around 40%.

* Before
```
              user     system      total        real
Time#==   1.940000   0.000000   1.940000 (  1.950250)
```

* After
```
              user     system      total        real
Time#==   1.340000   0.010000   1.350000 (  1.348283)
```

* Test code
```
require 'benchmark'

Benchmark.bmbm do |x|
  x.report "Time#==" do
    t = Time.now
    2000000.times do
      t == Time.now
    end
  end
end
```

### CODE REVIEW

**Comment by hsbt** [comment]
build fail of appveyor is not related this pull request. After it fixed, I will re-run appveyor build.

**Comment by nobu** [comment]
Why not overriding `Time#==`?
Why should `Comparable` take care of `Time` only?

**Comment by Watson1978** [comment]
Users can override Time#<=> and then the behavior of Time#== shoul follow its method, I guess.
So, I didn't override Time#==.

If there is way to detect recursive check, It should be used in here. Sorry, I didn't know that.

**Comment by hsbt** [comment]
@Watson1978 Can you rebase to https://github.com/ruby/ruby/commit/5e62a1bd2988529490baaff3149f12d812a6a5ea ?

**Comment by nurse** [comment]
How about overriding `Time#==` which checks `Time#<=>` is override or not.

**Comment by shyouhei** [comment]
The problem preventing us from merging this pull request is how the performance is improved (that is, special case `Time` class in universal `Comparable#==`).  Why is `Time` the only thing we have to care about there? We need a justification to the design.

**Comment by Watson1978** [comment]
It is better to override `Time#==`.

**Pull request closed without merging**
