### PR TITLE
Merge rubygems 3.2.13 and bundler 2.2.13

### PR DESCRIPTION
**Pull request by hsbt**

### CODE REVIEW

**Comment by hsbt** [comment]
@deivid-rodriguez RubyGems 3.2.12 has an issue of TCPSocket extension.  See https://github.com/ruby/ruby/pull/4233/checks?check_run_id=2012773746#step:13:130

Can you look at this?

**Comment by deivid-rodriguez** [comment]
@sonalkr132 fixed this and I released it as 3.2.13.

**Comment by hsbt** [comment]
Unfortunately, RG-3.2.13 is still failing on macOS. and the rubygems master branch with ruby/ruby master ( https://github.com/ruby/ruby/runs/2027448311 ) is same state with timeout error.

**Comment by hsbt** [comment]
@nurse  I removed RubyGems 3.2.13 and 3.2.12 from this pull-request. I will submit the new pull-request after fixing them on https://github.com/ruby/ruby/pull/4143

**Comment by hsbt** [comment]
Ah, 3.2.11 is still failing with `tcpsocket_init.rb`. I couldn't merge the latest stable version of rubygems yet.

We should fix it for Ruby 3.0.

**Comment by deivid-rodriguez** [comment]
My recommendation is to skip those tests when running tests under ruby-core. This code not hit by all users, only by those having timeout issues and opt-in into the workaround, so I don't think it's critical to run those tests from ruby-core.

**Comment by sonalkr132** [comment]
actually, it is being hit. The test I wrote doesn't reset the env https://github.com/rubygems/rubygems/pull/2662/files#diff-14ff8042cb97edbed47f52a9d93bcb33af668778bdb378f0585df265c2aabe44R79 ie testing following this will have override enabled.

Unfortunately, this doesn't seem to be the only issue. I looking into this further.

**Comment by deivid-rodriguez** [comment]
> actually, it is being hit. The test I wrote doesn't reset the env https://github.com/rubygems/rubygems/pull/2662/files#diff-14ff8042cb97edbed47f52a9d93bcb33af668778bdb378f0585df265c2aabe44R79 ie testing following this will have override enabled.

Technically all tests should get the ENV reset after they are done, so I don't think it should be an issue? Anyways, I mean it's not hit by end users of rubygems, so those tests are not critical to run here.

**Comment by hsbt** [comment]
@sonalkr132 @deivid-rodriguez The all of tests was passed with https://github.com/ruby/ruby/pull/4233/commits/2d8521580a4012d07ce15f22e00f591415d1bd90

**Comment by hsbt** [comment]
Should I bump rubygems-3.2.13.1 or wait a rubygems 3.2.14?

**Comment by deivid-rodriguez** [comment]
I'll release 3.2.14 today!

**Comment by deivid-rodriguez** [comment]
3.2.14 is out :+1:.

**Comment by hsbt** [comment]
@deivid-rodriguez Unfortunately, RG 3.2.14 was missing with https://github.com/rubygems/rubygems/pull/4431.

**Comment by deivid-rodriguez** [comment]
Oh, I forgot to include it, sorry! :man_facepalming:

I see that you already tagged it for backporting so we'll get it out with 3.2.15 :+1:.

**Review by nurse — APPROVED** [review]

**Pull request merged**
