### PR TITLE
Add Queue#peek to fetch the head object in queue, without removing it.

### PR DESCRIPTION
**Pull request by tagomoris**
This feature is required for cases like below:

```ruby
    queue = Queue.new

    10.times do
      Thread.new do
        queue << Task.new(at: Time.now + 30)
      end
    end

    Thread.new do # executor
      while true
        if queue.peek.to_be_fired?(Time.now)
          task = queue.pop
          # processing...
        end
        sleep INTERVAL
      end
    end
```

I have many use cases to enqueue tasks, which have conditions to be fetched or not. `Queue#peek` provides possibility to handle such requirement.

### CODE REVIEW

**Comment by tagomoris** [comment]
@drbrain Correct - it's just for a single consumer.

But right now, I have another idea to get a solution for my problem by adding block argument to `Queue#pop`, instead of adding `Queue#peek`:

```ruby
Thread.new do # executor
  while true
    if task = queue.pop{|task| task.to_be_fired?(Time.now) } # block is evaluated in mutex lock
      # processing...
    end
    sleep INTERVAL
  end
end
```

This idea can be applied for the case of multiple consumers.
But this fix requires to add mutex synchronization everywhere in code of `Queue`... Hmm.

**Comment by tagomoris** [comment]
The approach to accept block (to pop items) requires too large patch (to rewrite almost entire `Queue`), so it looks unacceptable.
I pushed another commit on this pull-request to add thread unsafe.

What do you think about it?

**Comment by matthewd** [comment]
IMO that makes it sound *too* unsafe... by itself, it's no more "unsafe" than something like `q.pop unless q.empty?`

The above example is indeed unsafe for multiple consumers, but that's not being included in the documentation. (And could be fixed by the caller adding a separate consumer-only mutex around the peek-check-pop.)

**Comment by eregon** [comment]
Isn't the non-block version `Queue.pop(true)` enough for this?
Then you immediately get an exception if the queue was empty, or its pops an element if there was one available.

**Comment by eregon** [comment]
We could also have a blocking version of `Queue#pop` with a timeout, that's easy to implement and safer.

**Comment by matthewd** [comment]
@eregon that doesn't put the item back onto the head of the queue if the condition is false

(a timeout on `Queue#pop` would certainly be nice -- but it seems unrelated to this use case)

**Comment by eregon** [comment]
Right, I missed that part.

In such a case which only works with one consumer, maybe the simplest is just to use a custom class using an Array and a Mutex, which synchronizes push and pop:
```ruby
def push(e)
  @mutex.synchronize do
    @array.push(e)
  end
end

def pop
  @mutex.synchronize do
    unless @array.empty?
      if yield @array.first
        @array.shift
      end
    end
  end
end
```
That seems better than adding a method to Queue that would only make sense when there is only one consumer.

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this from master?

**Comment by tagomoris** [comment]
The @eregon 's comment is reasonable. Let me close this.

**Pull request closed without merging**
