### PR TITLE
Reviving .travis.yml (don't merge)

### PR DESCRIPTION
**Pull request by salamani**
Fixes https://github.com/ruby/ruby/commit/6b978d542704a5614af5e9375c4b31b8d2618652

### CODE REVIEW

**Comment by salamani** [comment]
@hsbt I see this pr was closed! Are there any issues to be fixed or we moving away from travis ?

**Comment by junaruga** [comment]
@salamani Thank you for the PR. Why do you want to add `.travis.yml`? Did you test the `.travis.yml` on your forked repository?

Here is why we deleted `.travis.yml`. 
https://github.com/ruby/ruby/commit/6b978d542704a5614af5e9375c4b31b8d2618652

> Remove .travis.yml
> 
> Reason:
> * Recent build is failed.
>   https://travis-ci.org/github/ruby/ruby/jobs/762561190
> * Current configuration uses Ubuntu 16.04 (xenial), whose EOL is Apr 2021.
>
> If someone want to recover Travis CI builds, please fix above two issues.

Could you check this ticket too? We are trying to revive again. But personally for the x86_64 (amd64) cases including i686 case, I want to migrate it to GitHub Actions, because it consumes the credit points given by Travis. I only want to run non-x86 cases in Travis for now.
https://bugs.ruby-lang.org/issues/17818

Maybe some of the cases in Travis are already migrated to GitHub Actions.
https://bugs.ruby-lang.org/issues/17720#note-10

**Comment by junaruga** [comment]
> Fixes 6b978d5

Ah you recognize the commit where we deleted `.travis.yml`.

**Comment by junaruga** [comment]
@salamani I think you might need to explain more about your PR, or need to communicate with stakeholders and get a consensus from them by a Ruby bugs ticket before sending the PR. So, if you have comments to revive Travis, your comments are welcome on the ticket: https://bugs.ruby-lang.org/issues/17818 .

**Comment by salamani** [comment]
Hi
when we look at why the travis was removed(https://github.com/ruby/ruby/commit/6b978d542704a5614af5e9375c4b31b8d2618652). It was because of two reasons
```
1. Current configuration uses Ubuntu 16.04 (xenial), whose EOL is Apr 2021.
2. Recent build is failed.
  https://travis-ci.org/github/ruby/ruby/jobs/762561190
  If someone want to recover Travis CI builds, please fix above two issues.
```
How I fixed the issue
```
1. I moved to Ubuntu 18.04 (bionic)
2. On Ubuntu 16.04(xenial) Build was failing due to dependency issue only for amd64 system, where as arm and s390x were not facing the issue. 
   On Ubuntu 18.04(bionic) I fixed the dependencies which are facing the issue and then obsersed that all build and tests passing for amd64/arm/s390x
```

**Comment by cwsolee** [comment]
I saw updates on https://bugs.ruby-lang.org/issues/17818 regarding the Travis credit concern which is resolved now. I don't think we can re-open this PR but this PR should have all the fix needed to revive Travis. Let us know what we could do to help.

**Comment by junaruga** [comment]
> How I fixed the issue
@salamani Oh thanks! Did you test the PR on https://travis-ci.org/github/salamani/ruby right?
I could not see any CI result on https://travis-ci.org/github/linux-on-ibm-z/ruby that is a source repository for this PR.

I saw s390x case is failed. Did you see the case is passed?
https://travis-ci.org/github/salamani/ruby/jobs/766444927

Is it possible to run Travis CI 10 times removing the following lines of allow_failures?

```
$ git diff
diff --git a/.travis.yml b/.travis.yml
index 5d8b30e818..0b03cf93f6 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -212,9 +212,9 @@ matrix:
     - <<: *arm64-linux
     - <<: *s390x-linux
   allow_failures:
-    - name: arm32-linux
-    - name: arm64-linux
-    - name: s390x-linux
+    # - name: arm32-linux
+    # - name: arm64-linux
+    # - name: s390x-linux
   fast_finish: true
 
 before_script:
```

**Comment by junaruga** [comment]
@cwsolee Yeah, the situation is improved now. But it's still not ideal. The ideal situation is unlimited builds for non x86_64 (amd64). Fortunately Travis is considering it now for Ruby project. Right now we got 25,000 credits yesterday. If we consume 40 credits (10 credits for Linux x 4 jobs) per 1 build, we can run Travis 625 times (= 25000 / 40).

> I don't think we can re-open this PR but this PR should have all the fix needed to revive Travis. Let us know what we could do to help.

I can reopen this PR for your convenience, but maybe eventually it's better for me to create an new PR based on this PR after @salamani tested more considering my requests rather than to merge this PR directly. Of course I would include your names in the commit message. Because I want to add 2 commits for the PR, and I also update commit messages by explaining the context, why we revive Travis.

My plan for the new PR is
* The 1st commit is just revert commit of `6b978d542704a5614af5e9375c4b31b8d2618652` that is `git revert 6b978d542704a5614af5e9375c4b31b8d2618652`.
* The 2nc commit is update from the 1st commit to fix the issues. I also will remove a logic that was used for x86_64 case such as `&gcc-8` or `&clang-8 in `.travis.yml`. Because it seems some compiler's cases are already migrated to GitHub Actions.
https://github.com/ruby/ruby/blob/master/.github/workflows/compilers.yml

I appreciate your PR! Thank you.

By the way, you guys are working on IBM Z (s390x) at IBM, right seeing [the forked repository](https://github.com/linux-on-ibm-z)? And your motivations for this PR is to add s390x case in Travis to guarantee the case right? I assume you are motivated to add s390x case in Travis into popular open source projects. For a smooth contribution tips, I think you can explain who you are and what's the motivation for the PR. In my first impression for this PR, seeing your GitHub activities, I wondered why you suddenly sent PR to add `.travis.yml` to Ruby, even when your activities does not show Ruby related things. I even thought there was a potential rick to inject a not good code in this PR. [There is a case that GitHub Actions are used for an attack.](https://www.bleepingcomputer.com/news/security/github-actions-being-actively-abused-to-mine-cryptocurrency-on-github-servers/).

**Comment by junaruga** [comment]
@hsbt I reopened this PR, because the PR includes a code to fix 2 things (1. upgrade to bionic, 2. fix i686 case) and it's for @salamani 's convenience. As I wrote above, I would not merge this PR directly, instead I will send another new PR based on this PR. If you have a concern, let me know. Thanks.

**Review by junaruga — CHANGES_REQUESTED** [review]
I see this PR's Travis is failed. Could you check it?

As a note, on the latest master branch there are failures related to our infra. We are trying to fix the failures.

In the mean time,  could you test more running the Travis on your forked branch removing allow-faiulres lines to check if it works?

Could you split this 1 commit into 2 commits as I wrote above? Because I want to see what you changed.

Thanks!

**Comment by cwsolee** [comment]
@junaruga Yes, my team ported lots of open source package to Z(s390x), you can check out what my team does here https://www.ibm.com/community/z/open-source-software. We've long history with Ruby, we provided an z VM to the jenkins CI years ago, still running there. We enabled z on Travis a while back, after Travis support z. We noticed the removal of Travis and doesn't look too bad to fix, even though they're not z specific problem, we figure we can PR the changes and revive Travis. @salamani will respond to your question tomorrow,

**Comment by hsbt** [comment]
Basically, The decision of CI strategy is maintainers convenience. I have no concerns if @junaruga handle non-x86 platform with the several CI service.

**Comment by salamani** [comment]
@junaruga 
* Travis failure is due to testcase(https://github.com/ruby/ruby/blob/master/test/irb/test_init.rb#L67) failure, I tried to comment this test, builds are successful.
* About removing the arm/s390x lines of allow_failures
   s390x build terminated for `travis_wait 50 $SETARCH make -s test-all -o exts TESTOPTS="${TESTOPTS} ${TEST_ALL_OPTS}" RUBYOPT="-w" with error 
   ```
   The job exceeded the maximum time limit for jobs
   ```
   With change from `travis_wait 50` to `travis_wait 60` : s390x also looked good for me.

**Comment by junaruga** [comment]
@salamani Thank for checking. You do not have to change this PR. I will try to revive `.travis.yml` by myself referring this PR and [our past PRs related to Travis](https://github.com/ruby/ruby/pulls?q=is%3Apr+Travis+is%3Aclosed) such as #3170, #3535. Stay tuned!

**Comment by junaruga** [comment]
Note as it seems Ubuntu focal is the latest version in Travis as well as GitHub Actions, I will try focal.
https://docs.travis-ci.com/user/reference/linux/

**Comment by junaruga** [comment]
I sent my own PR #4518 to revive the Travis here.

By the way, I did split this PR's commit into 2 commits, the original one to revert + what you changed on my forked repo's branch.
https://github.com/junaruga/ruby/commits/wip/ibm-z-travis

And the following commit is what you changed. I did not see the test failure commented "spec/ruby/library/socket/socket/getnameinfo_spec.rb fails" there when I was working. Do you know why? I did not use this PR's logic actually. But thank you! 
https://github.com/junaruga/ruby/commit/ea01ca71b92cce1ca1f595d55a02076708d22c1a

Now I would close this PR. Thanks.

**Comment by salamani** [comment]
If "spec/ruby/library/socket/socket/getnameinfo_spec.rb fails" not seen, It is good see that logic is removed.
The log for failure which was observed
```
Socket.getnameinfo using IPv4 using a 3 element Array as the first argument using NI_NUMERICHOST as the flag returns an Array containing the numeric hostname and service name ERROR
SocketError: sockaddr resolved to multiple nodename
/home/travis/build/<ruby_replica>/ruby/spec/ruby/library/socket/socket/getnameinfo_spec.rb:111:in `getnameinfo'
/home/travis/build/<ruby_replica>/ruby/spec/ruby/library/socket/socket/getnameinfo_spec.rb:111:in `block (6 levels) in <top (required)>'
/home/travis/build/<ruby_replica>/ruby/spec/ruby/library/socket/socket/getnameinfo_spec.rb:65:in `<top (required)>'
```
and checking the https://travis-ci.community/t/localhost-resolves-to-127-0-1-1-instead-of-127-0-0-1-on-bionic/4764, those changes were made.

Thanks.

**Pull request closed without merging**
