### PR TITLE
sync NDEBUG, RUBY_DEBUG, and RUBY_NDEBUG

### PR DESCRIPTION
**Pull request by shyouhei**
- When NDEBUG is defined that shall be honoured.
- When RUBY_DEBUG is defined that shall be honoured.
- When both are defined and conflicts, warnings shall be rendered.
- When nothing is specified, nothing shall happen.

### CODE REVIEW

**Comment by shyouhei** [comment]
Confirmed that when configured with no options at all, miniruby does not include any references to glibc's `__assert_fail` on my machine.

**Comment by ko1** [comment]
who use `RUBY_NDEBUG`?

**Comment by shyouhei** [comment]
> who use `RUBY_NDEBUG`?

3rd party gems.  `RUBY_NDEBUG` is a public API so we cannot delete.

**Comment by ko1** [comment]
Thank you. I tried gem-codesearch and I can't find any usage of it (at least public gems).
To make it simple, obsolete it is good idea for me.

And if it is not important, I think independent file is overkill (and the patch will be more smaller).

**Comment by shyouhei** [comment]
Deprecating `RUBY_NDEBUG` sounds a good idea.  However it shall at least work until we delete.  It won't make things any simpler I guess.  Hundreds of lines of preprocessor directives are definitely worth a file to me.

Besides, do you know how to deprecate a macro?  I know how to deprecate a function but I have no idea how to do the same thing for macros.

**Comment by shyouhei** [comment]
@ko1 do you mind if I press the merge button?

**Comment by ko1** [comment]
If `RUBY_NDEBUG` will be obsolete, I against to introduce new file and so many `depend` changes because it will be removed. This is my personal preference, so only little conviction. I want to ask other comments.

I talked Nobu about it and he suggested to introduce functions to return 0 or 1 and show compile time warning instead of using 1 or 0 literals.

I doubt someone uses this macro, so just remove it is another idea, and people can report issues if it is used, after releasing preview versions. Also, if it is used, but it is easy to define this macro in their source code.

**Comment by shyouhei** [comment]
I prefer API stability than "kill them all and let God sort them out"-kind of maneuvers.

**Comment by shyouhei** [comment]
Let me at least deprecate the macro (for a year, as usual) before actually deleting it.  In order to do so, I don't think the separate file is a bad idea.

I guess what @ko1 actually doesn't like is those dependency hell, not the header file itself.  That is also a headache to me, but kind of off-topic.

**Comment by ko1** [comment]
I also don't like fine-grain file separation because it is difficult to understand the overall code (of course, the maintaining dependency is also tough). For example, I think small deprecation macro should not have newly created 1 file. It increases the understanding cost. Without a file, it can be commented just as `/* obsolete */` in assert.h and can skip to read. With a file, people need to open it and read carefully (and find obsolete comment).

But also it is *my preference* and *my guess*, only a weak excuse and I may wrong. I have no evidence (I didn't survey software engineering papers). If there are clear advantages overcome the disadvantages, I don't care. For me, it seems disadvantages are bigger than.

**Comment by shyouhei** [comment]
I have just opened  #3338.  It is now rather obvious that the macro in question is deprecated.  At one sight you can clearly see the deprecation comment.

The same contents has been overlooked by everyone for 13 years in a very big header.  It is a bad idea no wonder to let deprecated constants be submerged into other parts.

**Comment by nobu** [comment]
Originally the name `NDEBUG` has been introduced with the `assert` macro.
So it doesn’t feel worth to separate only the `RUBY_NDEBUG` from `ruby_assert` family.

**Comment by nobu** [comment]
And `RUBY_NDEBUG` has been defined in ruby_assert.h and not a public API.

**Comment by shyouhei** [comment]
@nobu _You_ made `RUBY_NDEBUG` public.  Namely in commit 32f013514460574eed03aa678f87ed7ca9600872.

**Comment by shyouhei** [comment]
Please just confirm the fact: that `RUBY_NDEBUG` do exist, under `include/`, for a while.  Whether you wanted it be private or not doesn't matter.  It is there.  Already.  We have to take care of it.

**Comment by shyouhei** [comment]
Merged ndebug.h into assert.h.  Any other comments before merging this?

**Comment by ko1** [comment]
I'm still not sure why "RUBY_NDEBUG" is described in the begging of file.
If we deprecate it, it should not be there.

**Comment by ko1** [comment]
> 3rd party gems. `RUBY_NDEBUG` is a public API so we cannot delete.

Private gems can use `RUBY_NDEBUG`, but no public gems use it (https://gist.github.com/ko1/ce8a8e9851282ba2a7524b3f6c44b562).
It is difficult to use `RUBY_NDEBUG` instead of `NDEBUG`.
This is why I think the risk of deletion is low.

**Comment by mame** [comment]
This caused some warnings like:

```
compiling array.c
array.c:56:1: warning: 'should_not_be_shared_and_embedded' defined but not used [-Wunused-function]
   56 | should_not_be_shared_and_embedded(VALUE ary)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
array.c:50:1: warning: 'should_be_T_ARRAY' defined but not used [-Wunused-function]
   50 | should_be_T_ARRAY(VALUE ary)
      | ^~~~~~~~~~~~~~~~~
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
```

These functions seem to be used only in the expression of `assert`. I'm unsure about the good way to disable them. @shyouhei could you prevent the warnings?

**Comment by shyouhei** [comment]
`MAYBE_UNUSED` should just suffice.  Will add them.

**Pull request merged**
