### PR TITLE
Get rid of the redundant stat() in rb_check_realpath_internal

### PR DESCRIPTION
**Pull request by casperisfine**
Ref: https://github.com/ruby/ruby/pull/2205

From my understanding this `stat()` call is not useful as it happens after `realpath()` succeeded. So unless I'm missing a corner case of `realpath()` I don't see how `realpath()` could succeed and `stat()` fail.

I ran the associated tests and specs, and they all pass (at least on my machine, CI might tell otherwise).

### CODE REVIEW

**Comment by casperisfine** [comment]
@jeremyevans could I get your review on this?

**Comment by jeremyevans** [comment]
Some operating systems allow realpath to return a path that does not exist on the filesystem.  I think FreeBSD and older versions of OpenBSD at least.  To be conservative, I would only skip the stat check on operating systems that have been confirmed to have realpath return success only if the path exists.

**Comment by casperisfine** [comment]
@jeremyevans that's super surprising, at least the manpages really don't make it seem that way: https://man.openbsd.org/OpenBSD-2.2/realpath.3

> ERRORS
     The function realpath() may fail and set the external variable errno for
     any of the errors specified for the library functions chdir(2),
     close(2),  fchdir(2),  lstat(2),  open(2),  readlink(2) and getcwd(3).

But to be safe I added a check for `__LINUX__` and `__APPLE__`. I feel like there should be comment explaining why, but I can't figure out how to formulate it.

**Comment by casperisfine** [comment]
@jeremyevans is there anything else needed for this patch to be acceptable?

**Comment by jeremyevans** [comment]
I don't think there is anything else needed.  I should be safe to merge now.

**Comment by nobu** [comment]
Why indented by `#if`?

**Comment by casperisfine** [comment]
@nobu I just corrected it.

**Comment by nobu** [comment]
I meant the indentation _inside_ `#if`.

**Comment by casperisfine** [comment]
My bad, I corrected that as well.

**Comment by casperisfine** [comment]
Thanks!

**Pull request merged**
