### PR TITLE
test/fiber/test_queue.rb: Make the stuck test fail.

### PR DESCRIPTION
**Pull request by junaruga**
This PR is to make the stuck tests fail immediately in a better way.

I observed the 2 tests in the `test/fiber/test_queue.rb` getting stuck in some GCC compilers in ppc64le Ubuntu, even when the timeout `queue.pop(timeout: 0.0001)` is set in the code. This commit is to make the test fail rather than getting stuck.

The issue can happen in the current RubyCI ppc64le server with GCC 11.4.0. We also observed the issue an older GCC compiler in the past in Ubuntu focal ppc64le.
https://github.com/ruby/ruby/pull/8739#issuecomment-1783355021

Here is the reproducer for the issue.
https://github.com/junaruga/report-ruby-fiber-hung_up-tests

```
+ make -s test-all TESTS=../test/fiber/test_queue.rb RUBYOPT=-w
generating enc.mk
making enc
making srcs under enc
generating transdb.h
transdb.h unchanged
making trans
making encs
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk updated
generating makefile exts.mk
exts.mk unchanged
linking shared-object -test-/array/resize.so
Run options:
  --seed=47121
  "--ruby=./miniruby -I../lib -I. -I.ext/common  ../tool/runruby.rb --extout=.ext  -- --disable-gems"
  --excludes-dir=../test/.excludes
  --name=!/memory_leak/
  -j9
  -q
  --tty=no

# Running tests:

[1/1] 3507820=test_queue
^C
^C
...
```

After applying this PR, when the test hit the issue, the result is below. I checked it on RubyCI ppc64le server.

```
jaruga@ruby1:~/git/ruby/ruby/build$ make -s test-all TESTS="../test/fiber/test_queue.rb" RUBYOPT="-w"
generating enc.mk
making enc
making srcs under enc
generating transdb.h
transdb.h unchanged
making trans
making encs
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk unchanged
generating makefile exts.mk
exts.mk unchanged
Run options:
  --seed=26297
  "--ruby=./miniruby -I../lib -I. -I.ext/common  ../tool/runruby.rb --extout=.ext  -- --disable-gems"
  --excludes-dir=../test/.excludes
  --name=!/memory_leak/

# Running tests:

[1/2] TestFiberQueue#test_pop_with_timeout = 1.00 s
  1) Failure:
TestFiberQueue#test_pop_with_timeout [/home/jaruga/git/ruby/ruby/test/fiber/test_queue.rb:11]:
The test gets stuck due to a possible compiler bug.
Exception raised:
<#<Timeout::Error: execution expired>>
Backtrace:
  /home/jaruga/git/ruby/ruby/lib/timeout.rb:43:in `rescue in handle_timeout'
  /home/jaruga/git/ruby/ruby/lib/timeout.rb:40:in `handle_timeout'
  /home/jaruga/git/ruby/ruby/lib/timeout.rb:195:in `timeout'
  /home/jaruga/git/ruby/ruby/test/fiber/test_queue.rb:51:in `block in assert_nothing_stuck'.

Leaked file descriptor: TestFiberQueue#test_pop_with_timeout: 5 : #<IO:fd 5>
Leaked file descriptor: TestFiberQueue#test_pop_with_timeout: 6 : #<IO:fd 6>
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
ruby    3669508 jaruga    5r  FIFO   0,13      0t0 61598837 pipe
ruby    3669508 jaruga    6w  FIFO   0,13      0t0 61598837 pipe
Leaked thread: TestFiberQueue#test_pop_with_timeout: #<Thread:0x00007eb168d5b630 /home/jaruga/git/ruby/ruby/test/fiber/test_queue.rb:12 sleep>
Finished tests in 1.066764s, 1.8748 tests/s, 6.5619 assertions/s.
2 tests, 7 assertions, 1 failures, 0 errors, 0 skips

ruby -v: ruby 3.3.0dev (2023-10-27T19:09:03Z master 4aee6931c3) [powerpc64le-linux]
make: *** [uncommon.mk:942: yes-test-all] Error 1
```

### CODE REVIEW

**Comment by ioquatix** [comment]
Thanks for working on this.

I don't think using `Timeout.timeout` here is a good idea.

If you want to limit the thread join, provide an argument to join, e.g.

```ruby
thread = Thread.new{...}

until thread.join(2) # 2 seconds maximum timeout until we kill it.
  thread.kill
end
```

**Comment by junaruga** [comment]
OK. Thanks for review. I will modify on your suggested way.

**Comment by junaruga** [comment]
I thought a boolean variable is better than number variable `kill_count` in this case.

**Comment by junaruga** [comment]
I rebased the PR on your way. I used the boolean value `timeout` instead of `kill_count`. So, the result in the failing case is below. What do you think?

```
jaruga@ruby1:~/git/ruby/ruby/build$ make -s test-all TESTS="../test/fiber/test_queue.rb" RUBYOPT="-w"
generating enc.mk
making enc
making srcs under enc
generating transdb.h
transdb.h unchanged
making trans
making encs
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk unchanged
generating makefile exts.mk
exts.mk unchanged
Run options:
  --seed=4799
  "--ruby=./miniruby -I../lib -I. -I.ext/common  ../tool/runruby.rb --extout=.ext  -- --disable-gems"
  --excludes-dir=../test/.excludes
  --name=!/memory_leak/

# Running tests:

[1/2] TestFiberQueue#test_pop_with_timeout = 2.00 s
  1) Failure:
TestFiberQueue#test_pop_with_timeout [/home/jaruga/git/ruby/ruby/test/fiber/test_queue.rb:26]:
Getting stuck due to a possible compiler bug.
Expected true to be false.

Leaked file descriptor: TestFiberQueue#test_pop_with_timeout: 5 : #<IO:fd 5>
Leaked file descriptor: TestFiberQueue#test_pop_with_timeout: 6 : #<IO:fd 6>
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
ruby    3693354 jaruga    5r  FIFO   0,13      0t0 61644190 pipe
ruby    3693354 jaruga    6w  FIFO   0,13      0t0 61644190 pipe
Finished tests in 2.067022s, 0.9676 tests/s, 3.3865 assertions/s.
2 tests, 7 assertions, 1 failures, 0 errors, 0 skips

ruby -v: ruby 3.3.0dev (2023-10-27T19:09:03Z master 4aee6931c3) [powerpc64le-linux]
make: *** [uncommon.mk:942: yes-test-all] Error 1
```

**Comment by junaruga** [comment]
Travis CI ppc64le is failing with another issue. This is not related to this PR.
https://app.travis-ci.com/github/ruby/ruby/jobs/612375819#L2906

```
  1) Failure:

TestRDocGeneratorJsonIndex#test_generate [/home/travis/build/ruby/ruby/test/rdoc/test_rdoc_generator_json_index.rb:108]:

.js files should be the same timestamp of original
```

**Comment by junaruga** [comment]
> I rebased the PR on your way. I used the boolean value `timeout` instead of `kill_count`. So, the result in the failing case is below. What do you think?

Maybe I think the `kill` (true/false) is better than `timeout` (true/false). Let me modify again.

**Comment by junaruga** [comment]
OK. Now rebased with `kill` (true/false). the result on the RubyCI Ubuntu ppc64le jammy server is below.

```
jaruga@ruby1:~/git/ruby/ruby/build$ make -s test-all TESTS="../test/fiber/test_queue.rb" RUBYOPT="-w"
generating enc.mk
making enc
making srcs under enc
generating transdb.h
transdb.h unchanged
making trans
making encs
generating makefiles ext/configure-ext.mk
ext/configure-ext.mk unchanged
generating makefile exts.mk
exts.mk unchanged
Run options:
  --seed=12531
  "--ruby=./miniruby -I../lib -I. -I.ext/common  ../tool/runruby.rb --extout=.ext  -- --disable-gems"
  --excludes-dir=../test/.excludes
  --name=!/memory_leak/

# Running tests:

[2/2] TestFiberQueue#test_pop_with_timeout = 2.00 s
  1) Failure:
TestFiberQueue#test_pop_with_timeout [/home/jaruga/git/ruby/ruby/test/fiber/test_queue.rb:26]:
Getting stuck due to a possible compiler bug.
Expected true to be false.

Leaked file descriptor: TestFiberQueue#test_pop_with_timeout: 5 : #<IO:fd 5>
Leaked file descriptor: TestFiberQueue#test_pop_with_timeout: 6 : #<IO:fd 6>
COMMAND     PID   USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
ruby    3855819 jaruga    5r  FIFO   0,13      0t0 61744853 pipe
ruby    3855819 jaruga    6w  FIFO   0,13      0t0 61744853 pipe
Finished tests in 2.066826s, 0.9677 tests/s, 3.3868 assertions/s.
2 tests, 7 assertions, 1 failures, 0 errors, 0 skips

ruby -v: ruby 3.3.0dev (2023-10-27T19:09:03Z master 4aee6931c3) [powerpc64le-linux]
make: *** [uncommon.mk:942: yes-test-all] Error 1
```

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
This PR may fix the stuck/hang: https://github.com/ruby/ruby/pull/8393 - do you want to try applying it and see if it helps?

**Comment by junaruga** [comment]
> This PR may fix the stuck/hang: #8393 - do you want to try applying it and see if it helps?

I don't understand what your idea is, and what I try.

**Comment by ioquatix** [comment]
It causes the compiler to generate different code which doesn't hang.

**Comment by junaruga** [comment]
> It causes the compiler to generate different code which doesn't hang. I don't know if the mutex code path is used for queue but it may be.

OK. Maybe I understood your idea. The PR #8393 is an implementation to fix stuck/hang. However, we don't know if implementation is used for `Thread::Queue` that causes the stuck/hang in your opinion. So, you are asking me if adding the implementation for the `Thread::Queue` is a good idea.

Yes, I think so. That's a good idea. Because while we avoid the stuck/hang to the tests in `test_queue.rb` in this PR, users may face stuck/hang in their real use cases.

I don't want to do it by myself. It's great if you do it. You have a reproducer to test stuck/hang in RubyCI ppc64le server.
https://github.com/junaruga/report-ruby-fiber-hung_up-tests

I am going to merge this PR now. I think this PR's assertion may be still useful even after you implement for the `Thread::Queue`.

Thanks for your review!

**Comment by ioquatix** [comment]
That all seems reasonable to me.

**Pull request merged**
