### PR TITLE
YJIT: Show --yjit-stats of railsbench on CI

### PR DESCRIPTION
**Pull request by k0kubun**
Currently, while we can see the after-merge stats of some revisions on https://speed.yjit.org, it's harder to see the before-merge stats of pull requests. As a result, we sometimes realize stats changes after merging PRs, e.g. https://github.com/Shopify/ruby/issues/445.

If we can confirm the metrics of railsbench on pull requests by just looking at CI, we could probably reduce the possibility of such commits. Assuming railsbench is the benchmark we're currently the most interested in, this PR automatically checks --yjit-stats of railsbench.

You'll be able to compare the yjit-bench CI results of the master branch and your pull request.

### CODE REVIEW

**Comment by noahgibbs** [comment]
I assume this is so we can inspect the current and previous runs in GitHub Actions?

**Comment by k0kubun** [comment]
Oh, yes. I meant to write some description but forgot to do so as my work hours were ending.

Maybe we may want to compare master vs PR on PRs?

**Comment by jimmyhmiller** [comment]
I would much rather merge this and see if it ends up being brittle. The only network access it is relying on is the same network access needed for all the tests to run, access to a github repo. I was planning on working on a bot for this. But @k0kubun beat me to the punch with a CI build.

I think it would be actually love something a bit more comprehensive. On PRs that have yjit changes, it would be great to have a bot comment the stats between it and master highlighting the performance/exit improvements and regressions. Doesn't have to fail anything, just inform.

**Comment by k0kubun** [comment]
> I think it would be actually love something a bit more comprehensive. On PRs that have yjit changes, it would be great to have a bot comment the stats between it and master highlighting the performance/exit improvements and regressions.

Me too. I actually imagined a bot like that first and then decided to have this quick alternative first. To have the situation where we can at least look at it as early as possible, I'd like to leave it for another PR and let it replace this PR later.

> I see what you're trying to do but my concern would be that this makes the CI more brittle? We're going to need to install many libraries for yjit-bench / railsbench, and if that install fails, the CI is going to be red? In general, I don't like having things that require network access on the CI.
>
> Is there a way to make it so that we have this railsbench install and stats print in the CI, but if there's an error and it can't run, the CI won't be red. Make this task run, but make it not mandatory for the CI to pass.

Sounds good. I think this is what you wanted https://github.com/ruby/ruby/pull/6403/commits/a3dd27a515610c07f9b4cbf8ff405c2be48bc728.

**Review by maximecb — APPROVED** [review]

**Pull request merged**
