### PR TITLE
BUG 20655: cont.call triggers the ensure function specified by rb_ensure

### PR DESCRIPTION
**Pull request by tagomoris**
The `cont.call` in the required ruby script triggers the ensure function specified on `rb_ensure` when the ruby script is required as the result of `func1` of `rb_ensure`.

https://bugs.ruby-lang.org/issues/20655

### CODE REVIEW

**Comment by ko1** [comment]
confirmed with pure ruby script:

```ruby
require 'continuation'

Dir.chdir('/tmp') do
  p [__LINE__, tmp = Dir.pwd]
  cont = nil
  callcc{|c| cont = c}
  p [__LINE__, Dir.pwd]
  exit! if Dir.pwd != tmp
  cont.call
end
```

```
[4, "/tmp"]
[7, "/tmp"]
[7, "/tmp"]
[7, "/home/ko1/ruby/build/trunk"]
```

`Dir.chdir` uses `rb_ensure` and ensure func will restore the pwd (`/home/ko1/ruby/build/trunk` in this case).

**Comment by tagomoris** [comment]
I created the bug ticket: https://bugs.ruby-lang.org/issues/20655

**Comment by tagomoris** [comment]
The patch (by @mame ) was cherry-picked from https://github.com/ruby/ruby/pull/11264

**Comment by tagomoris** [comment]
And I also included the test case inspired by the @ko1 's comment.

**Pull request merged**
