### PR TITLE
Gemify rake

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by drbrain** [comment]
I approve of this change.

**Comment by voxik** [comment]
Now I noticed that some RubyGems were failing due to missing Rake, so the 7d2b6a8cab9cf1238df9c1546c09ea4d6b313ab4 commit add bundled gems on $LOAD_PATH (although the approach is rather naive ATM, but it can be improved later if needed).

**Comment by voxik** [comment]
Weird, why it fails on travis? The gems are not expanded there for some reason?

**Comment by hsbt** [comment]
@voxik Travis instance is fragile environment :(

**Pull request closed without merging**
