### PR TITLE
reuse cc->call

### PR DESCRIPTION
**Pull request by shyouhei**
I noticed that in case of cache misshit, re-calculated `cc->me` can be the same method entry than the pevious one.  That is an okay situation but can't we partially reuse the cache, because `cc->call`
should still be valid then?

One thing that has to be special-cased is when the method entry gets amended by some refinements.  That happens behind-the-scene of call cache mechanism.  We have to check if `cc->me->def` points to the previously saved one.

```
Calculating -------------------------------------
                          trunk        ours
vm2_poly_same_method     1.534M      2.025M i/s -      6.000M times in 3.910203s 2.962752s

Comparison:
             vm2_poly_same_method
                ours:   2025143.9 i/s
               trunk:   1534447.2 i/s - 1.32x  slower
```

### CODE REVIEW

**Comment by shyouhei** [comment]
@k0kubun is it okay for us to add benchmark?

**Comment by k0kubun** [comment]
> is it okay for us to add benchmark?

It's always welcomed, at least by me. 

Renaming existing benchmarks may bother RubyBench maintainers, but adding new one is completely harmless for it too.

**Comment by k0kubun** [comment]
Perhaps this should also be special-cased:

```
1)
The private keyword changes visibility of previously called methods with same send/call site FAILED
Expected NoMethodError but no exception was raised (2 was returned)
/home/travis/build/ruby/ruby/spec/ruby/language/private_spec.rb:50:in `block (2 levels) in <top (required)>'
/home/travis/build/ruby/ruby/spec/ruby/language/private_spec.rb:4:in `<top (required)>'
```
https://travis-ci.org/ruby/ruby/jobs/586452224

**Comment by shyouhei** [comment]
OK, pushed 2089a3c4542cb2d86496730dd75b78d82dab2d16

**Pull request merged**
