### PR TITLE
Language tweaks to Fiber [doc]

### PR DESCRIPTION
**Pull request by marcandre**
Documentation for `Fiber.blocking?` removed as I can't make sense of it either.
It appears untested.

### CODE REVIEW

**Comment by zverok** [comment]
Thanks :+1:
My Ukrainian English leaves much to be desired :shrug:

**Comment by marcandre** [comment]
I wish my "French-Canadian english" was even better 😅

**Comment by ioquatix** [comment]
I'm not sure I understand the intention of this PR. Can you explain it?

**Comment by ioquatix** [comment]
```
irb(main):005:0> Fiber.new(blocking: false) {Fiber.blocking?}.resume
=> false
irb(main):006:0> Fiber.new(blocking: true) {Fiber.blocking?}.resume
=> 1
```

**Comment by marcandre** [comment]
Odd, I thought I had merged it already.

The PR only rephrases the doc and removed the documentation for `Fiber.blocking?` until it was clarified... When does it ever return an integer different than 1?

**Comment by ioquatix** [comment]
```
irb(main):005:0> Fiber.new(blocking: false) {Fiber.blocking?}.resume
=> false
```

**Comment by ioquatix** [comment]
It returns false, or something that is truthy. During the development it was possible to return more than 1 due to blocking mutex, but it was changed. Such a construct may be introduced in the future.

**Comment by marcandre** [comment]
I tweaked the doc for `Fiber.blocking?`

**Comment by ioquatix** [comment]
Thanks!

**Pull request merged**
