### PR TITLE
Merge CGI-0.3.5

### PR DESCRIPTION
**Pull request by hsbt**

### CODE REVIEW

**Review by nagachika — APPROVED** [review]

**Comment by grosscr** [comment]
Are there plans to pull CGI forward to 0.3.6? There was a fix recently pulled in around [domain validation](https://github.com/ruby/cgi/pull/29) that some of our applications are dependent on.

**Comment by hsbt** [comment]
@grosscr Do you have CGI application affect with this?

**Comment by grosscr** [comment]
Our automated test suites started failing with an "invalid domain" error when our docker images pulled in the latest ruby patch. We have not deployed this changes to any environments yet, anticipating that our SSO cookie logic will start failing because the same cookie is shared across our site domain through multiple applications.

**Comment by hsbt** [comment]
You can update cgi-0.3.6 with the latest stable Ruby versions. and We have a plan to pick cgi-0.3.6 for the next release.

**Comment by djberg96** [comment]
> You can update cgi-0.3.6 with the latest stable Ruby versions. and We have a plan to pick cgi-0.3.6 for the next release.

Are you planning on backporting the latest cgi into Ruby 3.0? I see it in 3.1 and 3.2 but not 3.0.

**Pull request merged**
