### PR TITLE
gcc 14 on macOS

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Comment by XrXr** [comment]
Seems like a GCC bug, no? Might be worth reporting.

**Comment by nobu** [comment]
As for `-pipe`, https://github.com/Homebrew/homebrew-core/issues/195299

**Comment by nobu** [comment]
I can't make a short code to reproduce `-Warray-bounds` warning.

**Comment by nobu** [comment]
At least, the warning seems to need:
1. gcc-14 on aarch64 macOS
2. `-O3`
3. successive `RB_TYPE_P()`

**Pull request merged**
