### PR TITLE
YJIT: Fix code GC freeing stubs with a trampoline

### PR DESCRIPTION
**Pull request by XrXr**
Stubs we generate for invalidation don't necessarily co-locate with the
code that jump to the stub. Since we rely on co-location to keep stubs
alive as they are in the outlined code block, it used to be possible for
code GC inside branch_stub_hit() to free the stub that's its direct
caller, leading us to return to freed code after.

Stubs used to look like:

```
mov arg0, branch_ptr
mov arg1, target_idx
mov arg2, ec
call branch_stub_hit
jmp return_reg
```

Since the call and the jump after the call is the same for all stubs, we
can extract them and use a static trampoline for them. That makes
branch_stub_hit() always return to static code. Stubs now look like:

```
mov arg0, branch_ptr
mov arg1, target_idx
jmp trampoline
```

Where the trampoline is:

```
mov arg2, ec
call branch_stub_hit
jmp return_reg
```

Code GC can now free stubs without problems since we'll always return
to the trampoline, which we generate once on boot and lives forever.

This might save a small bit of memory due to factoring out the static
part of stubs, but it's probably minor.

[Bug #19234]

---
see also: #6933

### CODE REVIEW

**Comment by maximecb** [comment]
This seems like a good change since it makes the stubs smaller.

But, can you explain why the stubs were not colocated with their code? Is it because the assembler can switch page in the middle of a block?

**Review by maximecb — APPROVED** [review]

**Comment by maximecb** [comment]
> I like the code gen change. But the bug this is fixing and how this fixes it are just too subtle for me to review. Don't hold up the PR, but would love a walk through to understand this better.

IIUC it's because stubs don't always end up on the same page as the code jumping to them. So the stubs aren't always marked as live, meaning they can get collected.

If a stub gets collected while it's being called, then there's no more valid code to return to. This change makes it so that the trampoline part always remains live, so the address you return to is always valid.

**Comment by k0kubun** [comment]
> But, can you explain why the stubs were not colocated with their code? Is it because the assembler can switch page in the middle of a block?

It's kind of explained in https://github.com/ruby/ruby/pull/6933. On `invalidate_block_version`, we could generate stubs much later than the original inline code, not generating any inline code in new pages at that moment.

**Comment by XrXr** [comment]
> But, can you explain why the stubs were not colocated with their code? Is it because the assembler can switch page in the middle of a block?

The main way get this right now seems to be from invalidation regenerating branches with jumps to stubs. So for example a way this can happen is when we generate blocks A and B first, then we generate enough code to switch to a different page, and then we invalidate B. We generate a stub in the latest page and then patch A to jump to the stub.

**Comment by k0kubun** [comment]
Just in case, I confirmed that this doesn't have a negative impact on benchmarks too:

```
before: ruby 3.2.0dev (2022-12-14T18:21:46Z master 7a63114f8e) +YJIT [x86_64-linux]
last_commit=Remove dead code in get_next_shape_internal
after: ruby 3.2.0dev (2022-12-15T16:10:10Z yjit-stub-trampoline 30b3efca3d) +YJIT [x86_64-linux]

-------------  -----------  ----------  ----------  ----------  ------------  -------------
bench          before (ms)  stddev (%)  after (ms)  stddev (%)  before/after  after 1st itr
activerecord   64.7         0.5         64.5        0.6         1.00          1.00
hexapdf        1218.8       1.4         1203.2      1.0         1.01          1.00
liquid-render  65.8         1.3         66.2        1.2         0.99          1.01
mail           76.8         0.4         77.3        0.5         0.99          0.99
psych-load     979.0        0.1         981.6       0.1         1.00          1.00
railsbench     1074.9       1.7         1071.4      1.7         1.00          1.00
ruby-lsp       39.4         25.9        39.2        25.4        1.00          0.99
-------------  -----------  ----------  ----------  ----------  ------------  -------------
```

**Review by k0kubun — APPROVED** [review]
Looks good to me :+1:

**Pull request merged**
