### PR TITLE
YJIT: Invalidate JIT code only for ISEQ_TRACE_EVENTS

### PR DESCRIPTION
**Pull request by k0kubun**
Events that are not part of `ISEQ_TRACE_EVENTS` don't modify ISEQs to use `trace_*` insns, so we shouldn't need to invalidate everything.

### CODE REVIEW

**Review by maximecb — COMMENTED** [review]
Nice 👌 

Could you add a small yjit test as well using tracing events that don't touch ISEQs?

**Comment by XrXr** [comment]
I'm a bit surprised that no tests fail, because we rely on patching to fire `c_return` when we return to a generated C call while the event is on. Not sure how we're firing the event otherwise. If you look at the codegen, we don't put code for firing the event usually.

**Comment by XrXr** [comment]
I think we might want to change only the if condition and keep the invalidation at the end of the function. Theoretically, when we release the VM lock inside `rb_yjit_tracing_invalidate_all()`, we could yield to another sleeping ractor. With this patch the lock release comes before the global events update, so there is a window where we could compile new code with outdated event info.

**Comment by k0kubun** [comment]
Addressed feedback from both of you.

> It looks like now the logic for the else that comes after the diff is outdated now because it assumes RUBY_EVENT_C_RETURN is not part of ISEQ_TRACE_EVENTS?

Agreed. I wondered why it existed, and looking at it again, I'm sure we can clean it up. But that involves function removals, so I'll make it a separate PR.

**Review by XrXr — APPROVED** [review]

**Pull request merged**
