### PR TITLE
Directly allocate FrozenCore as an ICLASS

### PR DESCRIPTION
**Pull request by peterzhu2118**
It's a bad idea to overwrite the flags as the garbage collector may have set other flags.

### CODE REVIEW

**Comment by nobu** [comment]
clang and gcc don't seem to optimize global variable accesses.

**Comment by peterzhu2118** [comment]
@nobu I'm not sure what you mean. I switched back to using a local variable and checked the compiled instructions using `objdump`, it doesn't look any different. I'm on clang on ARM on macOS. What kind of optimizations are you referring to?

**Comment by nobu** [comment]
Sorry to be unclear.
x86_64 macOS clang 14.0.3 generates code to access the global variable for each time.

**Comment by ko1** [comment]
BTW maybe frozen  core objects are not needed any more because we has builtin function feature.

**Pull request merged**
