### PR TITLE
REXML Transitive formatter fixes + compact output

### PR DESCRIPTION
**Pull request by orgads**
Support compact output for the Transitive formatter.

### CODE REVIEW

**Comment by kou** [comment]
Is there any difference between `Default` formatter and `compact` version `Transitive` formatter?

**Comment by orgads** [comment]
Yes. One change I've noticed is that the default formatter reorders attributes.

**Comment by kou** [comment]
Is it important? Could you show us what output do you want?

**Comment by orgads** [comment]
```
#!/usr/bin/env ruby

require 'rexml/document'
require 'rexml/formatters/default'
require 'rexml/formatters/transitive'

def test_formatter(type, doc, compact = false)
  puts "Output for #{type} with compact=#{compact}"
  formatter = type.new
  formatter.compact = compact if formatter.respond_to? :compact=
  formatter.write(doc, $stdout)
  puts
end

doc = REXML::Document.new(%q{
<?xml version="1.0" encoding="UTF-8"?>
<root>
  <node>
    <property   foo="42"      bar="44"  >  text  </property>
    <property      goo='44'   gar='42'    >other text</property>
  </node>
</root>
})
test_formatter(REXML::Formatters::Default, doc)
test_formatter(REXML::Formatters::Transitive, doc, false)
test_formatter(REXML::Formatters::Transitive, doc, true)
```

The output is:
```
Output for REXML::Formatters::Default with compact=false
<?xml version='1.0' encoding='UTF-8'?>

<root>
  <node>
    <property bar='44' foo='42'>  text  </property>
    <property gar='42' goo='44'>other text</property>
  </node>
</root>

Output for REXML::Formatters::Transitive with compact=false
<?xml version='1.0' encoding='UTF-8'?>

<root
>
  <node
  >
    <property foo='42' bar='44'
    >  text  </property
    >
    <property goo='44' gar='42'
    >other text</property
    >
  </node
  >
</root
>

Output for REXML::Formatters::Transitive with compact=true
<?xml version='1.0' encoding='UTF-8'?>

<root>
  <node>
    <property foo='42' bar='44'>  text  </property>
    <property goo='44' gar='42'>other text</property>
  </node>
</root>
```

Notice that both of them transform double quotes into single ones, and condense whitespace between attributes.

Default sorts the attributes, while Transitive doesn't.

Transitive (by default) adds a newline on each tag ending, which looks really bad, and makes the output hard to read. The introduced compact attribute addresses that.

**Comment by kou** [comment]
> Default sorts the attributes, while Transitive doesn't.

Again. Is it important?

**Comment by orgads** [comment]
Sorry, I thought you referred to the change itself.

Well, it shouldn't be important on most platforms, but I'd expect that Transitive keeps the original form, rather than adding whitespace trash.

The fact that Default can be used instead of Transitive doesn't make Transitive correct as it is.

**Comment by kou** [comment]
> The fact that Default can be used instead of Transitive doesn't make Transitive correct as it is.

It's not a Transitive problem. Because Transitive is created to implement the indent style.

**Comment by kou** [comment]
Think about this case for Transitive use case:

```ruby
#!/usr/bin/env ruby

require 'rexml/document'
require 'rexml/formatters/default'
require 'rexml/formatters/transitive'

def test_formatter(type, doc)
  puts "Output for #{type}"
  formatter = type.new
  formatter.write(doc, $stdout)
  puts
end

doc = REXML::Document.new(%q{<?xml version="1.0" encoding="UTF-8"?><root><node><property foo="42" bar="44">text</property><property goo='44' gar='42'>other text</property></node></root>})
test_formatter(REXML::Formatters::Default, doc)
test_formatter(REXML::Formatters::Transitive, doc)
```

Output:

```text
Output for REXML::Formatters::Default
<?xml version='1.0' encoding='UTF-8'?><root><node><property bar='44' foo='42'>text</property><property gar='42' goo='44'>other text</property></node></root>
Output for REXML::Formatters::Transitive
<?xml version='1.0' encoding='UTF-8'?><root
><node
  ><property foo='42' bar='44'
    >text</property
    ><property goo='44' gar='42'
    >other text</property
    ></node
  ></root
>
```

**Pull request closed without merging**
