### PR TITLE
Added fix for s390x on Travis build

### PR DESCRIPTION
**Pull request by dandotimujahid**
- Granted write permission to **_../gems_** to a non root user to fix the Travis build on s390x.

### CODE REVIEW

**Comment by nobu** [comment]
Could you explain the reason why it is needed?

**Comment by dandotimujahid** [comment]
Hi @nobu 
Updating the change. Instead of using sudo,  giving write permission to the required folder.  **_../gems/_**  directory doesn't have write permission for a non root user, hence the failure.
After giving write permission to **_../gems/_** directory for a non root user, **make -s install** command executes successfully.
These changes are required due to this commit: https://github.com/ruby/ruby/commit/2f0d9e74c82c12d253ac808b636385ba27a4b115
I have updated the PR with the necessary changes. Could you please take a look?
Thanks.

**Comment by dandotimujahid** [comment]
@nobu Could you please take a look? Thanks.

**Comment by dandotimujahid** [comment]
Closing this as the changes are no longer valid.

**Pull request closed without merging**
