### PR TITLE
Add GC.with_stress

### PR DESCRIPTION
**Pull request by kou**
We can replace EnvUtil.#under_gc_stress with this.

### CODE REVIEW

**Comment by kou** [comment]
@nobu What do you think about this? I want to reduce `EnvUtil` dependency to remove `EnvUtil` from https://github.com/ruby/* libraries.

**Comment by nobu** [comment]
Is `flag` parameter mandatory?
As for `under_gc_stress`, it was probably always `true`.

**Comment by kou** [comment]
Yes.
If we should provide `flag=true` API, we can also provide `GC.under_stress(flag=true) {...}` API.

Do you want to omit `true` argument when you use `GC.with_stress`? It seems that we don't often use `GC.with_stress`. So I think that `GC.with_stress(true) {...}` is acceptable.

BTW, `GC.with_stress(true) {...}` is shorter than `EnvUtil.under_gc_stress {...}`.

**Comment by ko1** [comment]
How about to extend the `GC.stress` like that:

```ruby
def GC.stress param = true, &b
  if b
    begin
      GC.stress = param
    ensure
      GC.stress = ...
    end
  else
    GC.traditonal_stress
  end
end
```

and we don't need to discuss about the method name.

**Comment by kou** [comment]
Thanks for the suggestion.
I opened https://bugs.ruby-lang.org/issues/18143 with the suggestion.

**Comment by kou** [comment]
Rejected.

**Pull request closed without merging**
