### PR TITLE
Merge YJIT: an in-process JIT compiler

### PR DESCRIPTION
**Pull request by maximecb**
This PR introduces YJIT, a just-in-time compiler built using a Lazy Basic Block Versioning (LBBV) compiler architecture. For more details about the technique, please refer to Maxime’s published paper and recorded talks:
 
- ECOOP 2015 paper: https://arxiv.org/pdf/1411.0352.pdf
- ECOOP 2015 talk: https://www.youtube.com/watch?v=S-aHBuoiYE0
- RubyKaigi 2021 talk: https://www.youtube.com/watch?v=PBVLf3yfMs8
 
YJIT currently provides [average speedups of 23%](https://speed.yjit.org/benchmarks/bench-2021-10-18-121121) over the CRuby interpreter on realistic benchmarks, and near-instant warm-up time. Plans are to include YJIT in the Ruby 3.1 preview release so that more users can test it out and benefit from potential performance gains.
 
Current limitations:
- Disabled by default, must specify `--yjit` to enable or set `RUBY_YJIT_ENABLE=1`
- Currently supports only macOS and Linux.
- Currently supports only x86-64 CPUs.
- On unsupported platforms, Ruby runs with the interpreter just like before
- No garbage collection for generated code. Will produce an error if `--yjit-exec-mem-size` is exceeded. This should be fixed in the coming months.
- YJIT uses more memory when active because it needs to allocate machine code. This can be adjusted by setting `--yjit-exec-mem-size`.
 
YJIT integrates closely with the interpreter and some core runtime routines such as `rb_obj_is_kind_of()` and `rb_str_eql_internal()`. YJIT also introduces a number of callbacks (see `yjit.h`) so that it can be notified of certain events, such as constants or methods being redefined. These changes are necessary so that YJIT can deoptimize code. These callbacks could potentially be useful for MJIT as well.
 
YJIT does not spawn an external compiler as a sub-process for compilation. YJIT compiles concurrently with Ruby code execution on the same thread. Despite this, it provides near-instant warm-up. That is, YJIT typically delivers a speedup on the first iteration of our benchmarks.
 
Shopify is committed to making sure that YJIT remains in good working order. This PR adds new test workflows to help detect issues early on. Should bugs and issues arise, we will assist in investigating and fixing these in a timely manner. If necessary, code generation for specific YARV instructions can be disabled by commenting a single line near the end of `yjit_codegen.c`.
 
We have tried to keep the YJIT code clean and approachable. The codebase is well-commented. We have a number of non-Shopify contributors who have found YJIT and submitted code.
 
YJIT makes additional runtime checks if compiled with `RUBY_DEBUG > 0`. It can also collect runtime statistics if compiled with `RUBY_DEBUG` or `YJIT_STATS > 0` and also run with the `--yjit-stats` option or the `RUBY_YJIT_STATS` environment variable set to 1.
 
YJIT cannot be enabled at the same time as MJIT. Both can be compiled into Ruby, but only one can be active at runtime.
 
Contributors to the YJIT project so far:
Alan Wu
Aaron Patterson
Benson Muite
Dylan Smith
Eileen Uchitelle
Max Bernstein
Marc Feeley
Jose Narvaez
Jean Boussier
John Hawthorn
Kevin Newton
Maxime Chevalier-Boisvert
Mike Dalessio
Noah Gibbs
Takashi Kokubun
Ufuk Kayserilioglu

### CODE REVIEW

**Comment by maximecb** [comment]
@XrXr @noahgibbs

**Comment by noahgibbs** [comment]
> Is there any motivation to support YJIT_RUBY_ENABLE/RUBY_YJIT_STATS environment variables
> while you can also use RUBYOPT="--yjit --yjit-status"?

Primarily so we can activate YJIT or stats without having to worry about preserving/changing RUBYOPT, which may contain other options.

**Comment by maximecb** [comment]
It's more convenient for some of the build systems we use in production, where it can be tricky to change command-line options for some ruby builds and not others.

**Comment by k0kubun** [comment]
got it.

Another point: I see the following when I try to switch it to "Rebase and merge":

Screen Shot 2021-10-19 at 5 29 07 PM

Given that ruby/ruby disables merge commits, the only remaining option is "Squash and merge". Would that be okay for you, or would you like to take a look at making it possible to use "Rebase and merge" to keep commit history?

**Comment by k0kubun** [comment]
I tried the rebase locally, and it succeeded. It's probably just a limitation of GitHub. I can probably manually rebase and push it.

**Comment by k0kubun** [comment]
I think it's good enough for the first merge. We can address minor issues after that, including my above comment.

Now that Matz gave the approval to make you a committer, how would you like to finish merging it? We can either wait for you to go through https://bugs.ruby-lang.org/projects/ruby/wiki/CommitterHowto#What-to-do-for-registering-you-as-a-committer and let you merge it yourself, or let me push them to unblock the preview release early while doing the process in case it takes a long time.

**Comment by XrXr** [comment]
I merged it: 6a9e2b3cc381fd1b6c5ec5eddb077ea5468ef75e

**Comment by hsbt** [comment]
@maximecb @XrXr Thanks for your works. But this large pull-request broke our dev environment like slack-bot, email notification and more. Please consider to squash or minimum step of merge process in the next work.

**Comment by kapso** [comment]
BTW I tried `YJIT_RUBY_ENABLE` and it does not work, but `RUBY_YJIT_ENABLE` does work. I tested this using `RubyVM::YJIT.runtime_stats`

Picked this from here - https://shopify.engineering/yjit-faster-rubying

**Comment by maximecb** [comment]
Hi @noahgibbs ! Would it be possible to update the blog post?

**Comment by noahgibbs** [comment]
Yup! I'll get on that.

**Comment by noahgibbs** [comment]
Hm. RUBY_YJIT_ENABLE is what I'm seeing in both the blog post and in the Ruby source code. I think we may have had it the other way some time back but changed it already? But what I'm seeing there now looks right, and I'm not finding YJIT_RUBY_ENABLE currently. @kapso, can you shift-reload the blog post in your browser and make sure you're seeing the latest version?

**Pull request closed without merging**
