### PR TITLE
[WIP] Adjust sp with dead code

### PR DESCRIPTION
**Pull request by wanabe**
I found some potential sp inconsistencies with https://github.com/ruby/ruby/pull/3401 patch.
I tried to fix them with dead code.
And the PR contains https://bugs.ruby-lang.org/issues/16695#note-5 patch.

### CODE REVIEW

**Comment by ko1** [comment]
Could you add tests for them?

**Comment by wanabe** [comment]
Thank you for reviewing!

> Could you add tests for them?

Sure. I'll try later, maybe next weekend.
Most cases are "potential" issues, so I think the tests will check ISeq directly.

**Comment by wanabe** [comment]
When I tried to add tests, I found some additional areas that may need to be fixed.
It will take me a while to do that. Also, in the meantime, I'm going to add "[WIP]" to the PR title.

**Comment by wanabe** [comment]
Ah sorry, I missed the estimate. These changes in the PR are too much.
I changed my mind that the priority should be to fix the original problem https://bugs.ruby-lang.org/issues/16695 quickly.
So I close the PR and re-open another one for 16695. Please wait.

**Pull request closed without merging**
