### PR TITLE
appveyor.yml - test install std-lib (dflt gems) CLI

### PR DESCRIPTION
**Pull request by MSP-Greg**
Add tests for std-lib items with CLI.  PR only adds checks for Appveyor, not Travis,

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@hsbt

Added three lines to rbinstall.rb, seems to fix the issue.  Also, added bundle_ruby to bundler executables.

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this from master?

**Comment by MSP-Greg** [comment]
Like the OpenSSL PR, I've run the reabse in my fork.

I placed the output at the top of tests, example here:
https://ci.appveyor.com/project/MSP-Greg/ruby/builds/26772607/job/1cg66h05rdpn9kyd?fullLog=true#L3311

Is that location ok?

**Comment by k0kubun** [comment]
I don't like the way just showing versions in appveyor.yml independently. It makes appveyor.yml redundant and long, and I feel it makes harder to maintain AppVeyor CI. Why don't we have something not in 

Besides, as the concurrency of AppVeyor is limited, we're softly deprecating AppVeyor in favor of GitHub Actions. While we know we cannot fully deprecate AppVeyor yet because GitHub Actions does not support targets tested in AppVeyor, I believe this one is completely fine to be done in GitHub Actions instead.

Could you consider implementing the check details outside CI configuration, and call it from GitHub Actions workflow? Then please ask a review from hsbt.

**Comment by k0kubun** [comment]
Also, if your requirement is preventing bugs in rbinstall.rb, please consider writing tests of rbinstall.rb on tmpdir or something which can be executed in `make test-all`, instead of just relying on actual `make install` on CI environment.

**Comment by MSP-Greg** [comment]
> Could you consider implementing the check details outside CI configuration, and call it from GitHub Actions workflow? Then please ask a review from hsbt.

Yes.  Closing for now...

**Pull request closed without merging**
