### PR TITLE
Hash delete multiple keys

### PR DESCRIPTION
**Pull request by kddeisz**
Allow Hash#delete to delete multiple keys at once, as in:

    { a: 'a', b: 'b', c: 'c' }.delete(:a, :b)

In reference to https://bugs.ruby-lang.org/issues/13211#change-64570

### CODE REVIEW

**Comment by nobu** [comment]
Please issue a feature request at https://bugs.ruby-lang.org/projects/ruby-trunk/issues/new

**Comment by kddeisz** [comment]
@nobu Sorry not sure if I did this right or not. I opened an issue here: https://bugs.ruby-lang.org/issues/13211 but it didn't get much attention so I opened the PR here as well. Let me know how to proceed. Thanks!

**Comment by nobu** [comment]
Have you read the comment by Urabe-san?

**Comment by kddeisz** [comment]
I did - I added the patch file to clarify things. It's much more important to get the multiple delete than the return value, which I'm happy to make into anything that makes sense.

**Comment by shyouhei** [comment]
> It's much more important to get the multiple delete than the return value

May I ask you the reason why?

**Comment by kddeisz** [comment]
Sorry I should've been more clear, I meant that the actual feature request is to delete multiple keys from the hash. I'd be happy to change the name of the method to `delete_many` or something to that effect if that would be more clear?

**Comment by kddeisz** [comment]
Oh sorry I see. The biggest use case for me is when you have some kind of global configuration hash that may come from some external source (an API or a configuration file, etc.) and you want to configure nested objects. For example, if we have an `Account` that has a child `User` object, then this:

```
class Account
  def initialize(config)
    config.delete(:a, :b, :c)
    @user = User.new(config)
  end
end

class User
  def initialize(config)
    ...
  end
end
```

is an example. You would be deleting the hash keys that are specific to account so that unnecessary configuration isn't going into the user class (especially if they have overlapping keys).

**Comment by nobu** [comment]
Just an idea, I think you can write it by keyword arguments.

```ruby
class Account
  def initialize(a: nil, b: nil, c: nil, **user_config)
    @user = User.new(**user_config)
  end
end
```

**Comment by kddeisz** [comment]
Yes that would work as well, but it doesn't handle the problem of deleting the account-specific configuration

**Comment by kddeisz** [comment]
That is a good solution, I hadn't thought of that.

**Pull request closed without merging**
