### PR TITLE
Enhanced RDoc for Range

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Introductory material revised.

### CODE REVIEW

**Review by jeremyevans — APPROVED** [review]
Reads fine to me.

**Comment by BurdetteLamar** [comment]
@jeremyevans, a question.  The three methods defined in ruby\ext\json\lib\json\add\range.rb are not available in my irb, even after requiring 'json'.  Do I need to do something more to make them available?
>irb --version
irb 1.3.5 (2021-04-03)
>ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]

**Comment by jeremyevans** [comment]
I would guess you need to `require 'json/add/range'` to make them available.

**Comment by BurdetteLamar** [comment]
> 
> 
> I would guess you need to `require 'json/add/range'` to make them available.

Perfect.  Thanks.

**Pull request merged**
