### PR TITLE
Ruby hacking guide.

### PR DESCRIPTION
**Pull request by ioquatix**
Based on https://bugs.ruby-lang.org/projects/ruby/wiki/DeveloperHowto which is a bit out of date and hard to find.

### CODE REVIEW

**Comment by nobu** [comment]
Should note that `-j16` is GNU make specific.

**Comment by ioquatix** [comment]
@nobu I looked up how we can make this easier for users. `make` does not seem to have any auto-detection features for number of cores, which seems odd to me, since it should be an incredibly useful feature to default to parallel build. Some people suggested `make -j$(nproc)` or something equivalent but it seems platform specific too. I can explain this in the guide but I guess I'm just a little surprised there isn't an easy, fast default.

**Comment by nobu** [comment]
Apart from the number of cores, `-j` option itself is GNU make specific, I mean.
Regarding the number, I set `NUMBER_OF_PROCESSORS` env var in scripts dispatched by `$OSTYPE` from bashrc, and then `GNUMAKEFLAGS` with it.

**Comment by ioquatix** [comment]
@nobu Okay, I'm going to add this to the guide, because I think this is excellent advice.

**Comment by jeremyevans** [comment]
OpenBSD make supports `-j`, and checking online, FreeBSD, NetBSD, and DragonflyBSD do as well, so it does not appear to be GNU make specific.

**Comment by ioquatix** [comment]
Okay, I've made a subsequent PR to address this, but I'll note that other `make` implement it too.

https://github.com/ruby/ruby/pull/5295

**Pull request merged**
