### PR TITLE
Check SPECIAL_CONST_P before RBASIC_CLASS to avoid SEGV

### PR DESCRIPTION
**Pull request by eagletmt**

### CODE REVIEW

**Comment by eagletmt** [comment]
Only rubyspec tests are failing.
It seems to be caused by rubyspec's change.

**Comment by sorah** [comment]
:eyes: https://bugs.ruby-lang.org/issues/11291

**Comment by sorah** [comment]
Committed at r50982 cc77375d2dabff398500bf4ee6c7d37087159155

**Comment by eagletmt** [comment]
:star:

**Pull request closed without merging**
