### PR TITLE
remove remains of ivar2 experimental feature

### PR DESCRIPTION
**Pull request by cremno**
ivar2 were an experimental feature during 1.9 development. These
so-called private or class local instance variables (@_foo) were
introduced by 72f2d2a00d8ae3861a15ca92bf9322951a22b6cf and shortly
thereafter removed by b83ed6d1bd710c0f3397dafbba3b96e1311bcc6a.

The removal was incomplete though. Let's remove its last remains.

### CODE REVIEW

**Review by shyouhei — APPROVED** [review]

**Comment by cremno** [comment]
I don't know why the MJIT check has failed. Is it unrelated or could I have missed something, @k0kubun?

**Comment by k0kubun** [comment]
The CI already fails randomly in master, which is under investigation. Don't worry about that for now.

**Comment by ko1** [comment]
Sorry for long absent. The patch seems nice but it seems there is a conflict.
Could you resolve it? and I'll merge it.

**Comment by cremno** [comment]
Looks like somebody else already removed it: 9d0ae387c86f3fc85cf00a9a4cf8c6e18b4181bf. Can't remove something that doesn't anymore so I'm closing this.

**Comment by ko1** [comment]
Thank you for checking it.

**Pull request closed without merging**
