### PR TITLE
warning for nil HTTP header instead of error

### PR DESCRIPTION
**Pull request by teosz**

### CODE REVIEW

**Comment by hsbt** [comment]
What's test/csv/test_headers.rb changes?

**Comment by teosz** [comment]
I have added null header test case

**Comment by hsbt** [comment]
Please fix to failing tests

**Comment by teosz** [comment]
I forced rebase my branch, now all tests are passed

**Comment by hsbt** [comment]
I wonder advantage of this pull request. What's usecase or scenario with this changes?

**Comment by teosz** [comment]
Is useful for debugging,  with, to say the header:
```ruby
{
Authorization: nil
}
```
now  you'll get the error  `undefined method 'strip' for nil:NilClass`, I think `net/http: warning: nil HTTP header: Authorization` it's more relevant

**Pull request closed without merging**
