### PR TITLE
add error_highlight gem

### PR DESCRIPTION
**Pull request by mame**
```
$ ./local/bin/ruby -e '1.time {}'
-e:1:in `<main>': undefined method `time' for 1:Integer (NoMethodError)

1.time {}
 ^^^^^
Did you mean?  times
```

https://bugs.ruby-lang.org/issues/17930

This includes some changes in did_you_mean gem. I'll create a PR for them to its upstream after the CI passed successfully.

### CODE REVIEW

**Comment by osyo-manga** [comment]
Marking will be broken if the error message contains multibyte characters.

```shell
$ ./ruby -e 'ああああ.time {}'
-e:1:in `<main>': undefined local variable or method `ああああ' for main:Object (NameError)

ああああ.time {}
^^^^^^^^^^^^
```

```shell
$ ./ruby -e '1.あああ {}'
-e:1:in `<main>': undefined method `あああ' for 1:Integer (NoMethodError)

1.あああ {}
 ^^^^
```

This can be calculated by using `Reline::Unicode.get_mbchar_width`, but I'm not sure if that's correct.

```diff
diff --git a/lib/error_squiggle/core_ext.rb b/lib/error_squiggle/core_ext.rb
index 6274eecb77..67d9eff5ea 100644
--- a/lib/error_squiggle/core_ext.rb
+++ b/lib/error_squiggle/core_ext.rb
@@ -1,3 +1,5 @@
+require "reline"
+
 module ErrorSquiggle
   module CoreExt
     SKIP_TO_S_FOR_SUPER_LOOKUP = true
@@ -31,7 +33,9 @@ def to_s
       end

       if spot
-        marker = " " * spot[:first_column] + "^" * (spot[:last_column] - spot[:first_column])
+        prefix_size = spot[:line][...spot[:first_column]].chars.map { |c| Reline::Unicode.get_mbchar_width(c) }.sum
+        mark_size = spot[:line][spot[:first_column]...spot[:last_column]].chars.map { |c| Reline::Unicode.get_mbchar_width(c) }.sum
+        marker = " " * prefix_size + "^" * mark_size
         points = "\n\n#{ spot[:line] }#{ marker }"
         msg << points if !msg.include?(points)
       end
```

**Comment by mame** [comment]
@osyo-manga Thank you. It is a known issue. At the dev-meeting we agreed that we would not address the issue soon.

**Comment by yahonda** [comment]
Let me update that some Rails unit tests have been affected by this change. Some of changes should be easy but https://github.com/rails/rails/issues/42678 looks difficult for me.

**Comment by mame** [comment]
Hi @yahonda! Thank you very much for letting me know the issue. I've just pushed https://github.com/ruby/ruby/commit/3a95834739aababba9eac418d7f122a1e499684b. I guess it will fix the issue.

**Comment by mame** [comment]
> Let me update that some Rails unit tests have been affected by this change.

Ah, could you give me references to other issues too? I know that it breaks a test that exactly checks an error message, which is unavoidable, but I'd like to know if there is another kind of issues.

**Comment by yahonda** [comment]
Thanks for the fix.
Other failures are due to check the error message like https://buildkite.com/rails/rails/builds/78919#cb534e49-fdc6-4f5a-b047-e134afd4d0a4/1092-1101

All of them will be fixed by https://github.com/rails/rails/pull/42680/files once it is merged.

**Pull request merged**
