### PR TITLE
Add Readline.variable_value method

### PR DESCRIPTION
**Pull request by graywolf**

### CODE REVIEW

**Comment by k0kubun** [comment]
Now master branch has a required check "check_branch", but I couldn't update your branch to include it. Could you rebase this from master to run it?

**Comment by graywolf** [comment]
I've rebased on the master, hope everything is fine now.

**Comment by nobu** [comment]
I think that “compilation on windows” is inexact.
It should depend on the version of libreadline, and libedit doesn't have that function.

**Comment by graywolf** [comment]
Yes, technically it should've been "Fix linking on non-gnu readline variants".

Anyway everything seems to pass now, expect for the last one with "AppVeyor build cancelled". What can I do about that?

**Comment by k0kubun** [comment]
Sorry for the inconvenience, we got a too long build queue... I requeued your AppVeyor build.

**Comment by graywolf** [comment]
All builds seems to pass, anything I can do to help push this forward?

**Comment by k0kubun** [comment]
This PR is listed too lower in the ruby/ruby PR list now. It might be better to file this PR in https://github.com/ruby/readline-ext (and/or https://github.com/ruby/readline) instead. At least actual readline.gem maintainers do not seem to be aware of this PR.

Cloud you open a PR there and close this here?

**Comment by graywolf** [comment]
Opened PR in readline-ext repo.

**Pull request closed without merging**
