### PR TITLE
Use __builtin_ppc_get_timebase on POWER with clang

### PR DESCRIPTION
**Pull request by pkubaj**

### CODE REVIEW

**Comment by shyouhei** [comment]
Our CI is a no-op here because we don't have POWER + clang combination.

@odaira Can you take a look?

**Comment by odaira** [comment]
Sure, I'll take a look.

**Comment by odaira** [comment]
I confirmed that the patch works for GCC; i.e. adding `defined(__clang__)` does not have a bad impact on building by GCC.  I'm installing clang in my POWER env, but it might take some time.

**Comment by pkubaj** [comment]
Have you finished your testing?

**Comment by shyouhei** [comment]
Let me merge this!  If it breaks anything let me know; I'll revert then.

**Pull request merged**
