### PR TITLE
[DOC] Improve links to labels in string.c and struct.c

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Use RDoc @ notation instead of html reference.

### CODE REVIEW

**Review by nobu — APPROVED** [review]
There are many other `#class-` and `#module-` links in these two files.

**Comment by peterzhu2118** [comment]
I did a global find and replace in #5530 (see commits 9bbb6d7a89bbc8ac425c7fdc86656eaa6740cd09 and 615eeeec01306e1724782f66e32adcc767f85a1c).

**Comment by BurdetteLamar** [comment]
> There are many other `#class-` and `#module-` links in these two files.

I was wanting to get rid of some of the worst offenders -- those citing .html.

**Comment by zverok** [comment]
@BurdetteLamar @nobu Sorry for jumping in late (I was traveling for last few days, and expected to have more time to participate, but I haven't, so sorry for postponing some reviews!).

Previous version rendered like this:
image
The new one (at least when I am trying it locally), does this:
image

I believe it became less readable as a phrase. Don't you agree?..

**Pull request merged**
