### PR TITLE
[PRISM] Fix case splat with no predicate

### PR DESCRIPTION
**Pull request by eightbitraptor**
Fixes https://github.com/ruby/prism/issues/2199

### CODE REVIEW

**Review by kddnewton — APPROVED** [review]
This looks right for this example, but I'm surprised that this was in here in the first place. Is there some other case we're not considering where the splatarray is necessary?

**Comment by eightbitraptor** [comment]
> This looks right for this example, but I'm surprised that this was in here in the first place. Is there some other case we're not considering where the splatarray is necessary?

I've only been routinely running `make btest` and `make test/ruby/test_compile_prism.rb` but I haven't seen anything yet that relies on the `splatarray`. That being said, it does look like switching `VM_CHECKMATCH_TYPE_CASE` isn't as simple as it seems.

Marking this as draft again for now while I investigate.

**Comment by eightbitraptor** [comment]
After more investigation, it looks like the value of VM_CHECKMATCH_TYPE varies depending on whether a `predicate` is present. This is represented in the CRuby AST as 2 seperate node types: `NODE_CASE`, and `NODE_CASE2`.

And with this current patch `make -s btest BTESTS="bootstraptest/test_syntax.rb" RUN_OPTS=--parser=prism` is showing only 2 remaining failures, neither of which are `case` related.

**Review by kddnewton — APPROVED** [review]

**Comment by kddnewton** [comment]
Nice investigation!

**Pull request merged**
