### PR TITLE
Make `Yaml/Psych` Ractor-ready

### PR DESCRIPTION
**Pull request by marcandre**
This PR makes it possible to call `YAML` from Ractors.

### CODE REVIEW

**Comment by marcandre** [comment]
PR has 3 commits that are self-contained refactorings. Last commit is the actual Ractor-compatibility.

Only difficulty is the [global config to register custom types / domains](https://github.com/ruby/ruby/blob/master/ext/psych/lib/psych.rb#L599-L620). I have no idea how much this API is used; methods are public but undocumented (and `delete_type` seems buggy or else test file calling is buggy).

Possibilities:
0) Release Ruby 3.0 as currently (YAML only works from main Ractor)
1) Merge this PR. Downside is that config is per Ractor; a custom type registered in the main Ractor will not be available from another Ractor unless also registered there.
2) Store immutable config in constant and update with `const_set` if needed. Issue is that the given blocks must be isolated, which could cause incompatibilities if they rely on outside local variables (for example the current testing approach does not work)
3) Use different API altogether.

@tenderlove which approach should we take?

**Comment by marcandre** [comment]
(Not related: I want to benchmark the class-to-callname cache, might be best to simply disable it on non-main-Ractor.

**Comment by marcandre** [comment]
tenderlove approved this approach.

Benchmark revealed use of `Ractor.local_storage` to be very acceptable. An independent optimization makes cache actually much faster.

**Comment by mrkn** [comment]
+1

**Pull request merged**
