### PR TITLE
pass cflags to transform mjit header

### PR DESCRIPTION
**Pull request by ahorek**
https://bugs.ruby-lang.org/issues/14964

### CODE REVIEW

**Comment by k0kubun** [comment]
Hmm, although ARCH_FLAG is added for universal binary, CFLAGS has never been used from the beginning https://github.com/ruby/ruby/commit/0af44e72611583963220e40215fc36f31fa80185 (not removed at any moment). It sounds fine to try using pass CFLAGS if it makes msys1 build succeed.

For future information, what was in your `$(CFLAGS)`? Can how transform_mjit_header.rb command outputs are changed before and after this patch?

**Comment by k0kubun** [comment]
I've just saw your comment in https://bugs.ruby-lang.org/issues/14964. So, `-msse4.1` matters, right?

**Comment by ahorek** [comment]
yes, FYI the same problem is on msys2. But only if you enable sse4 support via CFLAGS like -msse4.1 or in my case -march=native

if miniruby is compiled with this flag, running transform_mjit_header.rb without these flags causes errors like `error: implicit declaration of function '__builtin_ia32_crc32qi'`

**Comment by ahorek** [comment]
thanks for your prompt response. I retested on ubuntu with custom flags and it seems to be ok.

**Pull request closed without merging**
