### PR TITLE
Mark strings returned by Symbol#to_s as chilled 

### PR DESCRIPTION
**Pull request by casperisfine**
[[Feature #20350]](https://bugs.ruby-lang.org/issues/20350)

`STR_CHILLED` now spans on two user flags. If one bit is set it marks a chilled string literal, if it's the other it marks a `Symbol#to_s` chilled string.

Since it's not possible, and doesn't make much sense to include debug info when `--debug-frozen-string-literal` is set, we can't include allocation source, but we can safely include the symbol name in the warning message, making it much easier to find the source of the issue.

cc @jhawthorn @eregon

@peterzhu2118 do you know if I should bump the ABI version given some flags were moved around?

### CODE REVIEW

**Comment by eregon** [comment]
> @peterzhu2118 do you know if I should bump the ABI version given some flags were moved around?

Yes, changing the values of macros is definitely ABI-incompatible, so it should be bumped.

**Comment by casperisfine** [comment]
@eregon would you happen to remember where it's set.

**Comment by eregon** [comment]
https://github.com/ruby/ruby/blob/master/include/ruby/internal/abi.h

**Review by eregon — APPROVED** [review]
LGTM

**Review by maximecb — APPROVED** [review]

**Pull request merged**
