### PR TITLE
This is an empty commit to see if Travis tests are working

### PR DESCRIPTION
**Pull request by sodabrew**

### CODE REVIEW

**Comment by sodabrew** [comment]
Even with no changes, `ruby_2_2` branch fails tests on Travis with:

```
The command "make test-all TESTS='-q -j2'" exited with 0.
0.08s$ make test-rubyspec
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems ./spec/mspec/bin/mspec run -B ./spec/default.mspec 
/home/travis/build/ruby/ruby/spec/default.mspec:1:in `load': cannot load such file -- /home/travis/build/ruby/ruby/spec/rubyspec/ruby.2.2.mspec (LoadError)
	from /home/travis/build/ruby/ruby/spec/default.mspec:1:in `<top (required)>'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:76:in `load'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:76:in `block (2 levels) in load'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:74:in `each'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:74:in `block in load'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:71:in `each'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:71:in `load'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:89:in `load_default'
	from /home/travis/build/ruby/ruby/spec/mspec/lib/mspec/utils/script.rb:212:in `main'
	from ./spec/mspec/bin/mspec:7:in `<main>'
make: *** [test-rubyspec] Error 1
```

**Comment by eregon** [comment]
@nurse I'll let you fix this, we should just need to change `ruby.2.2.mspec` to `default.mspec` in `spec/default.mspec` in the ruby_2_2 branch.

**Comment by hsbt** [comment]
Already created backport ticket [Backport #10953](https://bugs.ruby-lang.org/issues/10953)

**Comment by sodabrew** [comment]
All tests fail with this Mongolian vowel error, are you sure that this is a reasonable version of rubyspec to run ruby_2_2 against?

```
1)
Regexp with character classes doesn't match Unicode Mongolian vowel seperator characters with [[:blank:]] FAILED
Expected ["᠎"]
 to equal []
/home/travis/build/ruby/ruby/spec/rubyspec/language/regexp/character_classes_spec.rb:152:in `block (3 levels) in <top (required)>'
/home/travis/build/ruby/ruby/spec/rubyspec/language/regexp/character_classes_spec.rb:4:in `<top (required)>'
Finished in 79.910335 seconds
3400 files, 23032 examples, 172617 expectations, 1 failure, 0 errors, 0 tagged
make: *** [test-rubyspec] Error 1
The command "make test-rubyspec" exited with 2.
```

**Pull request closed without merging**
