### PR TITLE
Fix copy coroutine implementation.

### PR DESCRIPTION
**Pull request by ioquatix**
(this PR has changed from the original description).

### CODE REVIEW

**Comment by ioquatix** [comment]
I don't recommend this for final solution, it's just a test case to check if the alloca pointer alignment / elision is the issue or not.

**Comment by ioquatix** [comment]
@jeremyevans  did you get a chance to try this?

**Comment by jeremyevans** [comment]
Not yet, still working on getting access to an OpenBSD/sparc64 box to test with.

**Comment by jeremyevans** [comment]
I've tested with both GCC 4.2.1 and 8.4.0 on OpenBSD/sparc64 and it the error still occurs (same location of error both with and without this patch):

```
Starting program: /usr/ports/pobj/ruby-2.7.2/ruby-2.7.2/ruby27 -e Fiber.new{Fiber.yield}.resume
[New thread 410449]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000ef7321e81c in coroutine_initialize (context=0x0, start=0x0, stack=0x0, size=0, base=0x0) at coroutine/copy/Context.h:74
74              start(context->from, context);
(gdb) bt
#0  0x000000ef7321e81c in coroutine_initialize (context=0x0, start=0x0, stack=0x0, size=0, base=0x0) at coroutine/copy/Context.h:74
#1  0x000000ef7321f478 in fiber_initialize_coroutine (fiber=0xeea164f608, vm_stack_size=0xef7396af28) at cont.c:711
#2  0x000000ef73221534 in fiber_prepare_stack (fiber=0xeea164f400) at cont.c:1775
#3  0x000000ef73221f30 in fiber_store (next_fiber=0xeea164f400, th=0xef3112f200) at cont.c:1977
#4  0x000000ef7322224c in fiber_switch (fiber=0xeea164f400, argc=0, argv=0xef0dace038, is_resume=1, kw_splat=0) at cont.c:2052
#5  0x000000ef73222654 in rb_fiber_resume_kw (fiber_value=1027003953120, argc=0, argv=0xef0dace038, kw_splat=0) at cont.c:2113
#6  0x000000ef7322286c in rb_fiber_m_resume (argc=0, argv=0xef0dace038, fiber=1027003953120) at cont.c:2175
#7  0x000000ef734efcac in call_cfunc_m1 (recv=1027003953120, argc=0, argv=0xef0dace038, func=0xef73222804 <rb_fiber_m_resume>) at vm_insnhelper.c:2336
#8  0x000000ef734f0b34 in vm_call_cfunc_with_frame (ec=0xef16bb3850, reg_cfp=0xef0dbcdf90, calling=0xfffffffffffc5c50, cd=0xef6ff34650, empty_kw_splat=0) at vm_insnhelper.c:2514
#9  0x000000ef734f0d18 in vm_call_cfunc (ec=0xef16bb3850, reg_cfp=0xef0dbcdf90, calling=0xfffffffffffc5c50, cd=0xef6ff34650) at vm_insnhelper.c:2539
#10 0x000000ef734f28a4 in vm_call_method_each_type (ec=0xef16bb3850, cfp=0xef0dbcdf90, calling=0xfffffffffffc5c50, cd=0xef6ff34650) at vm_insnhelper.c:2925
#11 0x000000ef734f2fd4 in vm_call_method (ec=0xef16bb3850, cfp=0xef0dbcdf90, calling=0xfffffffffffc5c50, cd=0xef6ff34650) at vm_insnhelper.c:3028
#12 0x000000ef734f3298 in vm_call_general (ec=0xef16bb3850, reg_cfp=0xef0dbcdf90, calling=0xfffffffffffc5c50, cd=0xef6ff34650) at vm_insnhelper.c:3076
#13 0x000000ef734f6028 in vm_sendish (ec=0xef16bb3850, reg_cfp=0xef0dbcdf90, cd=0xef6ff34650, block_handler=0, method_explorer=0xef734f5e48 <vm_search_method_wrap>) at vm_insnhelper.c:4023
#14 0x000000ef734fe100 in vm_exec_core (ec=0xef16bb3850, initial=0) at insns.def:801
#15 0x000000ef73518b58 in rb_vm_exec (ec=0xef16bb3850, mjit_enable_p=1) at vm.c:1920
#16 0x000000ef73519900 in rb_iseq_eval_main (iseq=0xef1e34bf08) at vm.c:2179
#17 0x000000ef732629f0 in rb_ec_exec_node (ec=0xef16bb3850, n=0xef1e34bf08) at eval.c:278
#18 0x000000ef73262be8 in ruby_run_node (n=0xef1e34bf08) at eval.c:336
#19 0x000000ec8b4007b4 in main (argc=3, argv=0xfffffffffffc70a8) at ./main.c:50

(gdb) disassemble coroutine_initialize
Dump of assembler code for function coroutine_initialize:
   0x000000ef7321e770 <+0>:     save  %sp, -176, %sp
   0x000000ef7321e774 <+4>:     sethi  %hi(0x74c400), %l7
   0x000000ef7321e778 <+8>:     add  %l7, 0x3ac, %l7    ! 0x74c7ac
   0x000000ef7321e77c <+12>:    call  0xef7319c99c <__sparc_get_pc_thunk.l7>
   0x000000ef7321e780 <+16>:    nop 
   0x000000ef7321e784 <+20>:    mov  %l7, %g2
   0x000000ef7321e788 <+24>:    stx  %i0, [ %fp + 0x87f ]
   0x000000ef7321e78c <+28>:    stx  %i1, [ %fp + 0x887 ]
   0x000000ef7321e790 <+32>:    stx  %i2, [ %fp + 0x88f ]
   0x000000ef7321e794 <+36>:    stx  %i3, [ %fp + 0x897 ]
   0x000000ef7321e798 <+40>:    stx  %i4, [ %fp + 0x89f ]
   0x000000ef7321e79c <+44>:    ldx  [ %fp + 0x887 ], %g1
   0x000000ef7321e7a0 <+48>:    brnz  %g1, 0xef7321e7e4 <coroutine_initialize+116>
   0x000000ef7321e7a4 <+52>:    nop 
   0x000000ef7321e7a8 <+56>:    sethi  %hi(0x2400), %g1
   0x000000ef7321e7ac <+60>:    or  %g1, 0x258, %g1     ! 0x2658
   0x000000ef7321e7b0 <+64>:    ldx  [ %g2 + %g1 ], %g1
   0x000000ef7321e7b4 <+68>:    mov  %g1, %o3
   0x000000ef7321e7b8 <+72>:    sethi  %hi(0x2400), %g1
   0x000000ef7321e7bc <+76>:    or  %g1, 0x150, %g1     ! 0x2550
   0x000000ef7321e7c0 <+80>:    ldx  [ %g2 + %g1 ], %g1
   0x000000ef7321e7c4 <+84>:    mov  %g1, %o2
   0x000000ef7321e7c8 <+88>:    mov  0x45, %o1
   0x000000ef7321e7cc <+92>:    sethi  %hi(0x2400), %g1
   0x000000ef7321e7d0 <+96>:    or  %g1, 0x240, %g1     ! 0x2640
   0x000000ef7321e7d4 <+100>:   ldx  [ %g2 + %g1 ], %g1
   0x000000ef7321e7d8 <+104>:   mov  %g1, %o0
   0x000000ef7321e7dc <+108>:   call  0xef73861180 <__assert2@plt>
   0x000000ef7321e7e0 <+112>:   nop 
   0x000000ef7321e7e4 <+116>:   ldx  [ %fp + 0x89f ], %o3
   0x000000ef7321e7e8 <+120>:   ldx  [ %fp + 0x897 ], %o2
   0x000000ef7321e7ec <+124>:   ldx  [ %fp + 0x88f ], %o1
   0x000000ef7321e7f0 <+128>:   ldx  [ %fp + 0x87f ], %o0
   0x000000ef7321e7f4 <+132>:   call  0xef7321e62c <coroutine_initialize_main>
   0x000000ef7321e7f8 <+136>:   nop 
   0x000000ef7321e7fc <+140>:   ldx  [ %fp + 0x87f ], %o0
   0x000000ef7321e800 <+144>:   call  0xef7352a8d4 <coroutine_save_stack>
   0x000000ef7321e804 <+148>:   nop 
   0x000000ef7321e808 <+152>:   mov  %o0, %g1
   0x000000ef7321e80c <+156>:   cmp  %g1, 0
   0x000000ef7321e810 <+160>:   be  %icc, 0xef7321e834 <coroutine_initialize+196>
   0x000000ef7321e814 <+164>:   nop 
   0x000000ef7321e818 <+168>:   ldx  [ %fp + 0x87f ], %g1
=> 0x000000ef7321e81c <+172>:   ldx  [ %g1 + 0x90 ], %g2
   0x000000ef7321e820 <+176>:   ldx  [ %fp + 0x887 ], %g1
   0x000000ef7321e824 <+180>:   ldx  [ %fp + 0x87f ], %o1
   0x000000ef7321e828 <+184>:   mov  %g2, %o0
   0x000000ef7321e82c <+188>:   call  %g1
   0x000000ef7321e830 <+192>:   nop 
   0x000000ef7321e834 <+196>:   nop 
   0x000000ef7321e838 <+200>:   rett  %i7 + 8
   0x000000ef7321e83c <+204>:   nop
```

**Comment by ioquatix** [comment]
Thanks, most helpful.

**Comment by ioquatix** [comment]
@jeremyevans can you give me an update on two points:

- You confirmed it's working.
- It's backported to 2.7

Thanks

**Comment by jeremyevans** [comment]
> @jeremyevans can you give me an update on two points:
> 
> * You confirmed it's working.
> * It's backported to 2.7

Backporting just the `coroutine/copy/Context.c` changes (9de559acc82a28bb0d912ed55cd36cf6f652ea9f), I was able to get OpenBSD/sparc64 through a full make test-all on Ruby 2.7.2 without it crashing.  So yes on both points.

**Comment by ioquatix** [comment]
@jeremyevans I've force pushed the commit to 440983f incorporating one fix implicit casting.

**Comment by ioquatix** [comment]
This PR has passed all tests previously, the current test failure seems to be transient.

**Pull request merged**
