### PR TITLE
Fix 2.6 build

### PR DESCRIPTION
**Pull request by nobu**

### CODE REVIEW

**Comment by mesmerze** [comment]
hey guys!
am I right that this PR is going to fix this error:
```

**Comment by mesmerze** [comment]
hey fellas!
am I right when thinking that this PR is going to fix this issue? 🙂 
```
rbenv install 2.6.7                                                                                                                                                                            17:32:19
Downloading ruby-2.6.7.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.7.tar.bz2
Installing ruby-2.6.7...
ruby-build: using readline from homebrew

BUILD FAILED (macOS 11.2.3 using ruby-build 20210405-2-g693a28e)

Inspect or clean up the working tree at /var/folders/z3/ks1325s16cj909jsmgcc279m0000gn/T/ruby-build.20210406173222.95434.4fwtTn
Results logged to /var/folders/z3/ks1325s16cj909jsmgcc279m0000gn/T/ruby-build.20210406173222.95434.log

Last 10 log lines:
vm.c:2295:9: error: implicit declaration of function 'rb_native_mutex_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        rb_native_mutex_destroy(&vm->waitpid_lock);
        ^
vm.c:2489:34: warning: expression does not compute the number of elements in this array; element type is 'const int', not 'VALUE' (aka 'unsigned long') [-Wsizeof-array-div]
                             sizeof(ec->machine.regs) / sizeof(VALUE));
                                    ~~~~~~~~~~~~~~~~  ^
vm.c:2489:34: note: place parentheses around the 'sizeof(VALUE)' expression to silence this warning
1 warning and 1 error generated.
make: *** [vm.o] Error 1
```

**Comment by hsbt** [comment]
> am I right when thinking that this PR is going to fix this issue? 🙂

No. Stay tuned.

**Comment by hsbt** [comment]
These commits are manually merged to `ruby_2_6`.

**Pull request closed without merging**
