### PR TITLE
lib/net/http/generic_request.rb: remove no-need then

### PR DESCRIPTION
**Pull request by gkta**

### CODE REVIEW

**Comment by marcandre** [comment]
Patch is good, but filename in commit message isn't.

**Comment by gkta** [comment]
Thanks for your comment, and what should I change?  Change the filename to lib/matrix/lup-decomposition.rb and re-create PR?

**Comment by marcandre** [comment]
Not sure I understand your suggestion, but you could amend your commit and force push to your branch.

**Comment by gkta** [comment]
OK, changed commit log.

**Comment by marcandre** [comment]
Your changes are made on `lib/net/http/generic_request.rb` and have nothing to do with the matrix lib...

**Comment by gkta** [comment]
Very sorry！！

**Pull request closed without merging**
