### PR TITLE
Expand heap pages to be exactly 16kb

### PR DESCRIPTION
**Pull request by tenderlove**
This commit expands heap pages to be exactly 16KiB and eliminates the
`REQUIRED_SIZE_BY_MALLOC` constant.

I believe the goal of `REQUIRED_SIZE_BY_MALLOC` was to make the heap
pages consume some multiple of OS page size.  16KiB is convenient because
OS page size is typically 4KiB, so one Ruby page is four OS pages.

Do not guess how malloc works
=============================

We should not try to guess how `malloc` works and instead request (and
use) four OS pages.

Here is my reasoning:

1. Not all mallocs will store metadata in the same region as user requested
memory.  jemalloc specifically states[1]:

> Information about the states of the runs is stored as a page map at the beginning of each chunk.

2. We're using `posix_memalign` to request memory.  This means that the
   first address must be divisible by the alignment.  Our allocation is
   page aligned, so if malloc is storing metadata *before* the page,
   then we've already crossed page boundaries.  I find it very unlikely
   that malloc is storing data at the end of the allocation.

3. Some allocators like glibc will use the memory at the end of the
   page.  I am able to demonstrate that glibc will return pointers
   within the page boundary that contains `heap_page_body`[2].  We
   *expected* the allocation to look like this:

Expected alignment

   But since `heap_page` is allocated immediately after
   `heap_page_body`[3], instead the layout looks like this:

Actual alignment

   This is not optimal because `heap_page` gets allocated immediately
   after `heap_page_body`.  We frequently write to `heap_page`, so the
   bottom OS page of `heap_page_body` is very likely to be copied.

One more object per page
========================

In jemalloc, allocation requests are rounded to the nearest boundary,
which in this case is 16KiB[4], so `REQUIRED_SIZE_BY_MALLOC` space is
just wasted on jemalloc.

On glibc, the space is not wasted, but instead it is very likely to
cause page faults.

Instead of wasting space or causing page faults, lets just use the space
to store one more Ruby object.  Using the space to store one more Ruby
object will prevent page faults, stop wasting space, decrease memory
usage, decrease GC time, etc.

1. https://people.freebsd.org/~jasone/jemalloc/bsdcan2006/jemalloc.pdf
2. https://github.com/ruby/ruby/commit/33390d15e7a6f803823efcb41205167c8b126fbb
3  https://github.com/ruby/ruby/blob/289a28e68f30e879760fd000833b512d506a0805/gc.c#L1757-L1763
4. https://people.freebsd.org/~jasone/jemalloc/bsdcan2006/jemalloc.pdf page 4

### CODE REVIEW

**Comment by tenderlove** [comment]
I thought I got my math right, but maybe not? 😆

**Comment by ioquatix** [comment]
@tenderlove Do you think you'll try to change to using `mmap` directly?

**Comment by tenderlove** [comment]
> @tenderlove Do you think you'll try to change to using `mmap` directly?

At some point, yes. But `mmap` only returns page aligned addresses, and it seems like a pain to get `mmap` to return something that's also aligned to 16KiB.  We'd have to `mmap` something larger and then search for an address.  Using `posix_memalign` seems easier for now.

**Comment by ko1** [comment]
I don't have good reason to decide it. Could you show some measurements on apps?

**Comment by tenderlove** [comment]
@ko1 definitely. I will open a redmine ticket too. I just wanted to see if CI will pass first.

**Comment by tenderlove** [comment]
@ko1 I made a redmine ticket [here](https://bugs.ruby-lang.org/issues/17002)

**Pull request closed without merging**
