### PR TITLE
Fix handling of 6-byte codepoints in left_adjust_char_head in CESU-8 encoding.

### PR DESCRIPTION
**Pull request by djoooooe**
As far as i know, `left_adjust_char_head` should move the given string cursor left by an entire codepoint.
CESU-8 encodes codepoints greater than `0xffff` as a UTF-16 surrogate pair, where the individual surrogate values are encoded in UTF-8, so they look like two individual UTF-8 codepoints. Since `left_adjust_char_head` currently only moves to the previous UTF-8 codepoint head, it will move into the "middle" of surrogate pairs instead of the beginning of the full codepoint.

This pull request aims to fix that.

https://bugs.ruby-lang.org/issues/19532

### CODE REVIEW

**Comment by nobu** [comment]
Could you add a test to test/ruby/enc/test_cesu8.rb?
```ruby
  def test_left_adjust_char_head
    assert_equal("", "\u{10000}".encode("cesu-8").chop)
  end
```

**Comment by djoooooe** [comment]
> Could you add a test to test/ruby/enc/test_cesu8.rb?
> 
> ```ruby
>   def test_left_adjust_char_head
>     assert_equal("", "\u{10000}".encode("cesu-8").chop)
>   end
> ```

done

**Comment by duerst** [comment]
https://www.unicode.org/reports/tr26/ says "CESU-8 documents an obsolete internal-use encoding scheme for Unicode identical to UTF-8 except for its representation of supplementary characters." and "CESU-8 is not intended nor recommended as an encoding used for open information exchange."

Given that, I'm not really sure why we support CESU-8. But if we support it, we better support it correctly than just halfway.

**Comment by eregon** [comment]
FWIW https://bugs.ruby-lang.org/issues/15931 is the ticket about adding CESU-8

**Comment by eregon** [comment]
I filed https://bugs.ruby-lang.org/issues/19532 to track backporting this, so now it just needs a review.
@nobu maybe you could review and merge this?

**Review by nobu — APPROVED** [review]

**Pull request merged**
