### PR TITLE
Set default for Encoding.default_external to UTF-8 on Windows

### PR DESCRIPTION
**Pull request by larskanis**
See discussion on https://bugs.ruby-lang.org/issues/16604 .

### CODE REVIEW

**Comment by larskanis** [comment]
@unak @nobu @nurse Could you please take a look at this request? It's open since February and no one responded.

**Comment by nobu** [comment]
I'm fine myself to switch the default encoding to UTF-8, but wonder if the real world use cases are UTF-8 ready on Windows.
No problems already?

**Comment by larskanis** [comment]
Thanks @nobu for responding!

> No problems already?

None. I switched to UTF-8 as the default_encoding starting with RubyInstaller-2.7.0-1. This is set per `RUBYOPT=-Eutf-8` and since this environment variable affects all installed ruby versions I changed ruby-2.6.6, 2.5.8 and 2.4.10 versions as well. Althought I clearly [communicated this change](https://rubyinstaller.org/2020/01/05/rubyinstaller-2.7.0-1-released.html), I didn't receive a single bug report.

There have been issues with irb/readline in the past, but they are all fixed now.

I would like to drop the `RUBYOPT` crutch starting with RubyInstaller-3.0 by the attached change. In addition to the inconsistencies [already described](https://bugs.ruby-lang.org/issues/16604), it fixes inconsistencies between 7z and exe versions of RubyInstaller (7z doesn't set `RUBYOPT`) and between CI environments (Appveyor uses locale shell encoding while github uses UFT-8).

**Comment by larskanis** [comment]
Can I do anything to get this merged?

**Pull request merged**
