### PR TITLE
FreeBSD fix build warning

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by mame** [comment]
Just to confirm: are you using FreeBSD 13? Our FreeBSD 12.2 CI does not show such a warning.

**Comment by devnexen** [comment]
yes 13.

**Comment by hsbt** [comment]
Can you point the warning at http://rubyci.s3.amazonaws.com/freebsd13/ruby-master/log/20221220T203002Z.log.html.gz ?

I didn't find a warning related your change.

**Comment by devnexen** [comment]
I no longer see this warning either.

**Comment by hsbt** [comment]
Thanks for your confirming ❤️

**Pull request closed without merging**
