### PR TITLE
Avoid improper optimization of case statements mixed integer/rational/complex

### PR DESCRIPTION
**Pull request by jeremyevans**
Fixes [Bug #17857]

### CODE REVIEW

**Comment by shyouhei** [comment]
Oops?  The code seems perfect but wonder if the CI failure is related or not.

**Comment by jeremyevans** [comment]
MJIT CI failure seems unrelated.  I'm rerunning to see if it reoccurs.

**Comment by shyouhei** [comment]
👍

**Comment by mame** [comment]
Thanks!

**Pull request merged**
