### PR TITLE
Omit TestCompilePrism on s390x for now

### PR DESCRIPTION
**Pull request by k0kubun**

### CODE REVIEW

**Comment by nobu** [comment]
Isn’t it better to skip by `-x` option in `.travis.yml`?

**Comment by k0kubun** [comment]
Ruby CI s390x-linux would keep failing with that. I'd be fine with that too, so feel free to push that change though.

**Comment by k0kubun** [comment]
Hmm, but from the gem sync perspective, maybe it's better?

**Comment by k0kubun** [comment]
like this https://github.com/ruby/ruby/pull/9694/commits/417a63fda443b3959f598e42607c896f98a7b8c1? 🤔

**Pull request merged**
