### PR TITLE
Change `ibf_dump_object()` to be able to dedup objects with O(1) using a hash table

### PR DESCRIPTION
**Pull request by NagayamaRyoga**
see: https://bugs.ruby-lang.org/issues/16505

### CODE REVIEW

**Comment by NagayamaRyoga** [comment]
Thanks. I referred an existing implementation that has both `iseq_list` and `iseq_table`.

> I think it might also be possible to drop obj_list and use only the table -- it keeps insertion order after all. What is the reason that we need both?

I didn't know that and it sounds good.
However, `ibf_dump_object()` needs to return an index in `obj_list`, but I couldn't find a public API that returns an index from a key in `st_table`.
Is there something like that?

**Comment by XrXr** [comment]
Since the table maps objects to their index, couldn't we use the index from there?

**Comment by NagayamaRyoga** [comment]
I got it. I'll try soon!

**Comment by NagayamaRyoga** [comment]
I've done.

- master

```shell
$ ./ruby-master -v
ruby 2.8.0dev (2020-02-06T12:20:20Z master e323f50a9c) [x86_64-darwin19]

$ ./ruby-master benchmark.rb
md5 hash: 76ab2b9f009c9ec990bb039da9b5527d
                   user     system      total        real
to_binary x100 26.077924   0.070374  26.148298 ( 26.490767)
```

- PR

```shell
$ ./ruby -v
ruby 2.8.0dev (2020-02-06T13:24:53Z improve-performanc.. e266d162ee) [x86_64-darwin19]
last_commit=compile.c: Fix SEGV

$ ./ruby benchmark.rb
md5 hash: 76ab2b9f009c9ec990bb039da9b5527d
                   user     system      total        real
to_binary x100  1.019290   0.030459   1.049749 (  1.141872)
```

(`benchmark.rb` is the code snippet shown in a ticket above)
The output binary has not changed from `master`
and passed `make test-all RUBY_ISEQ_DUMP_DEBUG='to_binary'`.

**Pull request merged**
