### PR TITLE
Backport: Don't turn on keyword_init for Struct subclass if keyword hash is empty #16138

### PR DESCRIPTION
**Pull request by Prajjwal**
Backports #2423.

### CODE REVIEW

**Comment by hsbt** [comment]
We don't handle to backport on GitHub. Can you file this to https://bugs.ruby-lang.org?

Thanks

**Comment by k0kubun** [comment]
We're not using GitHub for backports. Please file a "backport ticket" referencing the commit https://github.com/ruby/ruby/commit/77596fb7a91cc119b25ac9e19b3c8682709765b4 at https://bugs.ruby-lang.org instead.

See: https://bugs.ruby-lang.org/projects/ruby/wiki/HowToRequestBackport

**Comment by Prajjwal** [comment]
@k0kubun @hsbt I've attached a patch (for only ruby 2.5) on the bug tracker as requested. Can you see if it is acceptable?

https://bugs.ruby-lang.org/issues/16138

**Comment by k0kubun** [comment]
Ah, Jeremy already filed the backport ticket. That looks fine. Stable branch maintainers will take it when they have a chance. Thanks for the heads up.

**Pull request closed without merging**
