### PR TITLE
Introduce setup instructions for better parallelism.

### PR DESCRIPTION
**Pull request by ioquatix**

### CODE REVIEW

**Comment by ioquatix** [comment]
@jeremyevans do you know what environment variable to use for make flags? @nobu said `GNUMAKEFLAGS` but I assume non-GNU make on BSD is something else maybe?

**Comment by ioquatix** [comment]
Okay, I tried using `MAKEFLAGS` and it seems to work.

**Comment by jeremyevans** [comment]
Yep, `MAKEFLAGS` is what the OpenBSD man page describes.

**Comment by nobu** [comment]
`MAKEFLAGS` is relatively common.
That is, "you should know the tool you are using."

**Comment by nobu** [comment]
Replace tabs with 4 spaces.
Tabs are expanded to each 8 columns, 4 spaces are enough for code blocks.
image

**Review by nobu — APPROVED** [review]

**Pull request merged**
