### PR TITLE
Tidy up merge, fixes https://bugs.ruby-lang.org/issues/12886

### PR DESCRIPTION
**Pull request by ioquatix**
I'm happy to make changes or improve this.

I think this change improves merge function. It removes need for merge0 which was not a very useful function.

https://bugs.ruby-lang.org/issues/12886

### CODE REVIEW

**Comment by ioquatix** [comment]
I feel that the ruby gems code needs to be fixed somewhere but I'm not sure where. Perhaps someone can help who is more familiar with the code base.

**Comment by ioquatix** [comment]
Okay so now Rubyspec is failing..

1)
URI#+ raises a URI::BadURIError when adding two relative URIs FAILED
Expected URI::BadURIError
but no exception was raised (#<URI::Generic a/b/d> was returned)
/home/travis/build/ruby/ruby/spec/rubyspec/library/uri/plus_spec.rb:39:in `block (2 levels) in <top (required)>'
/home/travis/build/ruby/ruby/spec/rubyspec/library/uri/plus_spec.rb:5:in `<top (required)>'

I'll fix this if I can get some positive forward movement from a core ruby dev.

**Comment by ioquatix** [comment]
I can't seem to comment on the bug report so I'll just add here:

Matthew, thanks for providing some additional details.

I agree with your points, sticking to the definition of the [RFC](https://tools.ietf.org/html/rfc3986#section-4.2) makes sense. Then, according to the RFC, this implementation is wrong in many ways. For example, `URI("a/b")` should not parse and raise an error. Because it doesn't, it causes confusion.

Either the API should completely support working with both URIs and relative references, or it shouldn't. Otherwise, it's confusing when some things work and others don't.

What might make more sense, is to add URI#relative_reference? and have URI handle this case. I can expand the [PR I made here](https://github.com/ruby/ruby/pull/1469) to add that.

**Comment by ioquatix** [comment]
Thanks for merging some of these changes. Can we discuss removing the `unless self.absolute?` check?

**Comment by ioquatix** [comment]
@nobu @hsbt I've rebased the PR since part of it was merged :) Thanks.

Can we discuss removing the `unless self.absolute?` check?

**Comment by ioquatix** [comment]
Will we ever make progress on this issue, or is it not important?

**Comment by hsbt** [comment]
Maintainer of `URI` is not active in 2017. We will triage this issue next developer meeting.

**Comment by ioquatix** [comment]
Awesome, thanks. Looking forward to an update :)

**Comment by hsbt** [comment]
https://bugs.ruby-lang.org/issues/12886#note-5

**Pull request closed without merging**
