### PR TITLE
Replace RB_TYPE_P macro to FIXNUM_P macro

### PR DESCRIPTION
**Pull request by S-H-GAMELINKS**
Replace `RB_TYPE_P` macro to `FIXNUM_P` macro like these code.

```c
RB_TYPE_P(y, T_FIXNUM)
```

### CODE REVIEW

**Comment by nobu** [comment]
Could you resolve the conflicts?
And `RB_INTEGER_TYPE_P` would be usable for these combinations.

**Comment by S-H-GAMELINKS** [comment]
@nobu 
Thanks your comments. I'll resolve it.

And, added `RB_INTEGER_TYPE_P` macro like this.

```c
RB_INTEGER_TYPE_P(y) && FIXNUM_P(y)
```

**Comment by nobu** [comment]
As `RB_INTEGER_TYPE_P` includes `FIXNUM_P`, it equals mere `FIXNUM_P(y)`.

**Comment by nobu** [comment]
I mean `(RB_TYPE_P(y, T_FIXNUM) || RB_TYPE_P(y, T_BIGNUM))` -> `(RB_INTEGER_TYPE_P(y))`.

**Comment by S-H-GAMELINKS** [comment]
@nobu
Thanks your reply. The conflicts has been resolved and Using `RB_INTEGER_TYPE_P` macro.

**Pull request merged**
