### PR TITLE
Enhanced RDoc for Range#min

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Let's get this one in the can before working on #max and #minmax.

### CODE REVIEW

**Review by jeremyevans — CHANGES_REQUESTED** [review]
This documenation makes it sound like there are four independent cases:

* No argument or block
* Only block
* Only argument
* Both block and argument

It documents each case separately.  However, these cases are all related.  When a block is not passed, it is the same as passing the block `{|a, b| a <=> b}`.

I would restructure the documentation to document the standard behavior without a block, first without an argument, then with an argument.  Then introduce the block argument and show how the behavior is the same with `{|a, b| a <=> b}`, but can be different with a different block.

After that, I would document the corner cases of begin value greater than end value and begin value equal to end value of exclusive range. These return `nil` without an argument or `[]` if an argument is given, and never call a provided block.  I would also document the case of a single element in the range, and how the single element value is always returned (either directly or in an array if an argument is provided), and that the block is not called in this case either.

I would also document the case where an argument is provided that is more than the number of elements in the range, and that all elements of the range will be returned in this case.

**Comment by BurdetteLamar** [comment]
> I would also document the case where an argument is provided that is more than the number of elements in the range, and that all elements of the range will be returned in this case.

Thanks for the prod.  Meant to do that (as elsewhere).

**Comment by BurdetteLamar** [comment]
> This documentation makes it sound like there are four independent cases.

This treatment is similar to that of many other methods, most notably Array#min.

My thinking:  in the end, the user chooses one of the four forms, and is entitled to a full discussion of the implications of their choice.  Let me see about a little more intro about the two choices.

**Comment by BurdetteLamar** [comment]
I've added the large-n examples.

I'm very comfortable with the rest of what I've written, and very uncomfortable with changes you've suggested.  If you think what's here is better than the existing doc (and free of errors), I'll be happy to merge it.  If not, I'll pass, and leave the existing doc.  As always, thanks much for your careful and diligent reviews.

**Review by jeremyevans — CHANGES_REQUESTED** [review]
As a compromise, can you move all discussion of:

* Begin value of the range is larger than the end value
* Begin value of an exclusive range is equal to the end value

To the end of the documentation, right before the discussion of what raises an exception?  These are both unlikely corner cases, and discussing them 4 separate times makes the documentation harder to read.

**Comment by BurdetteLamar** [comment]
> 
> 
> As a compromise, can you move all discussion of:
> 
>     * Begin value of the range is larger than the end value
> 
>     * Begin value of an exclusive range is equal to the end value
> 
> 
> To the end of the documentation, right before the discussion of what raises an exception? These are both unlikely corner cases, and discussing them 4 separate times makes the documentation harder to read.

Yes, and will see whether other trivialities can be thus treated.

**Comment by BurdetteLamar** [comment]
> 
> 
> As a compromise, can you move all discussion of:
> 
>     * Begin value of the range is larger than the end value
> 
>     * Begin value of an exclusive range is equal to the end value
> 
> 
> To the end of the documentation, right before the discussion of what raises an exception? These are both unlikely corner cases, and discussing them 4 separate times makes the documentation harder to read.

Yes, and thanks.  This is much better.

I've grouped all the "Returns nil or an empty array" into two bullets (to emphasize their corner-ness), and have also segregated the "n is zero" passage.

**Review by jeremyevans — APPROVED** [review]
This looks much better, thanks!

**Pull request merged**
