### PR TITLE
WIP: Adjust to pass Travis ppc64le.

### PR DESCRIPTION
**Pull request by junaruga**
Let me just test if the tests pass in Travis ppc64le case, as I see the failing tests in the case below.
https://app.travis-ci.com/github/ruby/ruby/jobs/608696247#L2355

It seems that I cannot run Travis in forked repository by the message below.

https://app.travis-ci.com/github/junaruga/ruby
> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/account/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/account/plan?anchor=oss-consumption).

### CODE REVIEW

**Comment by junaruga** [comment]
I still saw the following message with the following change (`timeout` from `0.0001` to `0.0010`)

https://app.travis-ci.com/github/ruby/ruby/jobs/608742404#L2347

```
Retrying hung up testcases...

[1/2] TestFiberQueue#test_pop_with_timeout
```


```
diff --git a/test/fiber/test_queue.rb b/test/fiber/test_queue.rb
index 10d9540492..01ace17f12 100644
--- a/test/fiber/test_queue.rb
+++ b/test/fiber/test_queue.rb
@@ -12,7 +12,7 @@ def test_pop_with_timeout
       Fiber.set_scheduler(scheduler)
 
       Fiber.schedule do
-        result = queue.pop(timeout: 0.0001)
+        result = queue.pop(timeout: 0.0010)
       end
 
       scheduler.run
@@ -31,7 +31,7 @@ def test_pop_with_timeout_and_value
       Fiber.set_scheduler(scheduler)
 
       Fiber.schedule do
-        result = queue.pop(timeout: 0.0001)
+        result = queue.pop(timeout: 0.0010)
       end
 
       scheduler.run
```

**Comment by junaruga** [comment]
When removing the `test/fiber/test_queue.rb`, I see the Travis ppc64le below succeeded.
https://app.travis-ci.com/github/ruby/ruby/jobs/608749776

But Travis s390x failed.
https://app.travis-ci.com/github/ruby/ruby/jobs/608749777

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

**Comment by ioquatix** [comment]
It's kind of weird that removing a test would cause failures?

**Comment by junaruga** [comment]
> It's kind of weird that removing a test would cause failures?

For the s390x case failure, I am not sure if the issue is related to removing the `test/fiber/test_queue.rb` file. But for the ppc64le case, it passes after removing the `test/fiber/test_queue.rb` file. I believe the file was the cause of failure in ppc64le.
https://app.travis-ci.com/github/ruby/ruby/builds/265536311

**Comment by junaruga** [comment]
> It seems that I cannot run Travis in forked repository by the message below.
> 
> https://app.travis-ci.com/github/junaruga/ruby
> 
> > Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/account/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/account/plan?anchor=oss-consumption).

Today after asking Travis CI's customer support, it seems now I can run Travis build by the push trigger on my forked repository, and the message above was gone. I am not sure if this is only for my forked repository or for other forked repositories too.

**Comment by ioquatix** [comment]
My current hypothesis is `gcc-10` is faulty and the errors depend on code and compiler = faulty codegen.

**Comment by junaruga** [comment]
I would close this PR to test Travis on ruby/ruby. Because I can test Travis on my forked repository now. And the PR 
https://github.com/ruby/ruby/pull/8394 to fix the issue was merged.

**Pull request closed without merging**
