### PR TITLE
Enhancements for IO separator

### PR DESCRIPTION
**Pull request by BurdetteLamar**
Adds symbol synonyms for special values for method argument `sep`:

- `:paragraph` means the same as `''`.
- `:slurp` means the same as `nil`.

Documentation adjusted accordingly.
Tests included.

### CODE REVIEW

**Review by peterzhu2118 — CHANGES_REQUESTED** [review]
This is adding a new feature into Ruby, you should create a feature proposal to bugs.ruby-lang.org to get feedback and approval from Matz before this can be merged.

**Comment by BurdetteLamar** [comment]
> This is adding a new feature into Ruby, you should create a feature proposal to bugs.ruby-lang.org to get feedback and approval from Matz before this can be merged.

Added https://bugs.ruby-lang.org/issues/20261.

**Comment by BurdetteLamar** [comment]
@peterzhu2118, I have added an item for the next dev meeting.  Would you check it for correctness of form and content?  I'd like it to be correct so it can be considered.

**Comment by peterzhu2118** [comment]
Can you put a comment in the ticket as described [in the "Call for agenda items" section](https://bugs.ruby-lang.org/issues/20281#Call-for-agenda-items)?

**Comment by BurdetteLamar** [comment]
In theory, yes I "can."  But I have not figured out how to make it right.
If easier than explaining, please feel free to edit as you like;  or, worst case(?), create a new meeting item and then we I can then delete the bad one.
I like this feature, and would like it to be considered, so I'll appreciate help with this.

    On Monday, February 19, 2024 at 05:07:23 PM CST, Peter Zhu ***@***.***> wrote:  
 
 


Can you put a comment in the ticket as described in the "Call for agenda items" section?

**Comment by peterzhu2118** [comment]
1. Click on "Edit":

    Screenshot 2024-02-19 at 7 28 27 PM

2. Fill out the "Notes" section with your ticket:

    Screenshot 2024-02-19 at 7 29 31 PM

3. Click "Submit".

**Comment by BurdetteLamar** [comment]
Thanks much, Peter!  I think I've got it right now.

I know this has been a pain, but I think it's worth it to school me in how to do this;  I have in mind some additional usability mods, and so I think I will be putting up more PRs, Issues, and dev-meeting items.

    On Monday, February 19, 2024 at 06:32:17 PM CST, Peter Zhu ***@***.***> wrote:  
 
 

   
   -    
Click on "Edit":
 Screenshot.2024-02-19.at.7.28.27.PM.png (view on web)
   -    
Fill out the "Notes" section with your ticket:
 Screenshot.2024-02-19.at.7.29.31.PM.png (view on web)
   -    
Click "Submit".

**Comment by peterzhu2118** [comment]
@BurdetteLamar The format that you submitted still doesn't look quite right. Can you follow the description in the ticket and edit it using the little pencil icon on the top right of your comment?

**Comment by BurdetteLamar** [comment]
Updated.

    On Tuesday, February 20, 2024 at 09:55:46 AM CST, Peter Zhu ***@***.***> wrote:  
 
 


@BurdetteLamar The format that you submitted still doesn't look quite right. Can you follow the description in the ticket and edit it using the little pencil icon on the top right of your comment?

**Pull request closed without merging**
