### PR TITLE
Optimize Pathname#relative? / absolute?

### PR DESCRIPTION
**Pull request by marcandre**

### CODE REVIEW

**Comment by Paxa** [comment]
I made some benchmark:

<details>
  <summary>benchmark code</summary>

```ruby
require 'benchmark/ips'
require 'pathname'

class Pathname
  if File.dirname('A:') == 'A:.' # DOSish drive letter
    ABSOLUTE_PATH = /\A(?:[A-Za-z]:|#{SEPARATOR_PAT})/o
  else
    ABSOLUTE_PATH = /\A#{SEPARATOR_PAT}/o
  end

  def regex_absolute?
    ABSOLUTE_PATH.match?(@path)
  end

  def slash_regx_absolute?
    @path.start_with?(File::SEPARATOR) || ABSOLUTE_PATH.match?(@path)
  end

  if File::ALT_SEPARATOR || File.dirname('A:') == 'A:.' # DOSish drive letter
    ABSOLUTE_PATH = /\A(?:[A-Za-z]:|#{SEPARATOR_PAT})/o
    def slash_absolute?
      ABSOLUTE_PATH.match?(@path)
    end
  else
    def slash_absolute?
      @path.start_with?(File::SEPARATOR)
    end
  end
end

ABS_PATH = Pathname.new("/var/lib/something")
REL_PATH = Pathname.new("xvar/lib/something")

LONG_ABS_PATH = Pathname.new("/var/lib/something" * 300)
LONG_REL_PATH = Pathname.new("xvar/lib/something" * 300)

[:ABS_PATH, :REL_PATH, :LONG_ABS_PATH, :LONG_REL_PATH].each do |path_const|
  puts
  puts "## #{path_const}"
  puts

  path_val = Object.const_get(path_const)

  Benchmark.ips do |x|
    x.warmup = 1

    x.report("absolute?") do
      path_val.absolute?
    end

    x.report("regex_absolute?") do
      path_val.regex_absolute?
    end

    x.report("slash_regx_absolute?") do
      path_val.slash_regx_absolute?
    end

    x.report("slash_absolute?") do
      path_val.slash_absolute?
    end

    x.compare!
  end
end
```
</details>

```

## ABS_PATH

Warming up --------------------------------------
           absolute?    34.574k i/100ms
     regex_absolute?   249.969k i/100ms
slash_regx_absolute?   281.844k i/100ms
     slash_absolute?   286.949k i/100ms
Calculating -------------------------------------
           absolute?    379.710k (± 5.7%) i/s -      1.902M in   5.025698s
     regex_absolute?      6.765M (± 2.0%) i/s -     33.996M in   5.027570s
slash_regx_absolute?      9.397M (± 2.6%) i/s -     47.068M in   5.012913s
     slash_absolute?      9.202M (± 5.3%) i/s -     45.912M in   5.007361s

Comparison:
slash_regx_absolute?:  9396668.1 i/s
     slash_absolute?:  9201897.8 i/s - same-ish: difference falls within error
     regex_absolute?:  6764744.1 i/s - 1.39x  slower
           absolute?:   379710.4 i/s - 24.75x  slower


## REL_PATH

Warming up --------------------------------------
           absolute?    34.590k i/100ms
     regex_absolute?   265.215k i/100ms
slash_regx_absolute?   238.794k i/100ms
     slash_absolute?   263.520k i/100ms
Calculating -------------------------------------
           absolute?    381.938k (± 3.3%) i/s -      1.937M in   5.077918s
     regex_absolute?      8.255M (± 1.6%) i/s -     41.374M in   5.013364s
slash_regx_absolute?      5.742M (± 1.6%) i/s -     28.894M in   5.033634s
     slash_absolute?      9.330M (± 1.9%) i/s -     46.643M in   5.000854s

Comparison:
     slash_absolute?:  9330444.2 i/s
     regex_absolute?:  8254892.8 i/s - 1.13x  slower
slash_regx_absolute?:  5741735.1 i/s - 1.63x  slower
           absolute?:   381938.4 i/s - 24.43x  slower


## LONG_ABS_PATH

Warming up --------------------------------------
           absolute?     7.000  i/100ms
     regex_absolute?   246.296k i/100ms
slash_regx_absolute?   282.560k i/100ms
     slash_absolute?   284.836k i/100ms
Calculating -------------------------------------
           absolute?     74.033  (± 1.4%) i/s -    371.000  in   5.013132s
     regex_absolute?      6.805M (± 1.8%) i/s -     34.235M in   5.032667s
slash_regx_absolute?      9.411M (± 3.6%) i/s -     47.188M in   5.021900s
     slash_absolute?      9.426M (± 5.1%) i/s -     46.998M in   5.001370s

Comparison:
     slash_absolute?:  9426352.7 i/s
slash_regx_absolute?:  9411129.4 i/s - same-ish: difference falls within error
     regex_absolute?:  6804955.9 i/s - 1.39x  slower
           absolute?:       74.0 i/s - 127326.38x  slower


## LONG_REL_PATH

Warming up --------------------------------------
           absolute?     9.000  i/100ms
     regex_absolute?   261.327k i/100ms
slash_regx_absolute?   233.242k i/100ms
     slash_absolute?   285.915k i/100ms
Calculating -------------------------------------
           absolute?     94.830  (± 2.1%) i/s -    477.000  in   5.032763s
     regex_absolute?      8.096M (± 2.8%) i/s -     40.506M in   5.007528s
slash_regx_absolute?      5.729M (± 2.0%) i/s -     28.689M in   5.009684s
     slash_absolute?      9.646M (± 1.6%) i/s -     48.320M in   5.010419s

Comparison:
     slash_absolute?:  9646345.4 i/s
     regex_absolute?:  8096252.7 i/s - 1.19x  slower
slash_regx_absolute?:  5729051.1 i/s - 1.68x  slower
           absolute?:       94.8 i/s - 101722.55x  slower
```

`@path.start_with?(File::SEPARATOR)` is always faster, regex is about 13%-39% slower and default (ruby 2.6) is ~25x slower for small string and much slower with longer strings

**Comment by marcandre** [comment]
Thanks for the benchmark. I guess we might as well have the conditional `def`, then. I've updated the PR.

**Comment by Paxa** [comment]
Should we care about `File::ALT_SEPARATOR`? (I don't know what is it for)

**Comment by marcandre** [comment]
> Should we care about `File::ALT_SEPARATOR`? (I don't know what is it for)

`ALT_SEPARATOR` is `\` on windows. It taken into account by `SEPARATOR_PAT`, but my latest PR assumes that `File.dirname('A:') == 'A:.'` is the same as `ALT_SEPARATOR != nil`. I'm pretty sure that's the case, but maybe it's not worth a few percent of performance to take it for granted. Probably best to come back to my previous version then

**Comment by marcandre** [comment]
@akr any objection?

**Pull request merged**
