### PR TITLE
Cache multiple compiled regexps

### PR DESCRIPTION
**Pull request by dbussink**
This caches compiled versions of different encoded regular expressions.
This helps performance wise in cases where the same regular expression
gets used against different encodings.

In Rails this is a pretty common scenario if templates with user
generated content sometimes only contain ASCII characters, other times
binary and sometimes UTF-8.

This caches the encodings with the lowest three encoding id's, which is
US-ASCII, BINARY and UTF-8. They are also the most commonly used and
provides a compromise between additional size usage and performance.

### CODE REVIEW

**Comment by nurse** [comment]
I merged RREGEXP_PTR change.

The concern is...
* The situation this expects: a regexp matches strings with vary encodings is enough exist?
* This introduces source incompatibility (Maybe this is tiny one)

**Comment by dbussink** [comment]
> The situation this expects: a regexp matches strings with vary encodings is enough exist?

I've seen this quite regularly. The biggest source is strings that are either US-ASCII or UTF-8 that hit the same location. This was extracted for example from the github application and also saw the same cases in other Rails applications. If it hadn't made a real impact, I wouldn't have started the pull request :smile:.

**Comment by k0kubun** [comment]
It seems to have a conflict now. Could you rebase this against master?

**Comment by k0kubun** [comment]
Let me close this as it has not been updated for a while. Please reopen this after resolving conflicts. Thanks.

**Pull request closed without merging**
