### PR TITLE
Use Array#compact before Array#uniq

### PR DESCRIPTION
**Pull request by amerov**

### CODE REVIEW

**Comment by eregon** [comment]
What does it change?

**Comment by amerov** [comment]
```ruby

Benchmark.ips do |x| 
  items = [1, 2, 1, 1, 2, 3, 4, nil, 5, nil, 5] 
  x.report("first uniq") do 
    items.uniq.compact
  end

  x.report("first compact") do 
    items.compact.to_set
  end
end
  ```
```
Calculating -------------------------------------
          first uniq    37.559k i/100ms
       first compact    13.585k i/100ms
-------------------------------------------------
          first uniq    606.085k (± 5.5%) i/s -      3.042M
       first compact    164.800k (± 7.3%) i/s -    828.685k
```

**Comment by eregon** [comment]
That's to_set in the second case, not uniq.

**Comment by amerov** [comment]
sorry, it was not the

**Comment by tenderlove** [comment]
Can you send this to [rubygems/rubygems](https://github.com/rubygems/rubygems)?  After it's merged there, it will be put in to Ruby.

**Comment by amerov** [comment]
:+1: :gem:

**Pull request closed without merging**
