### PR TITLE
Remove pooled_pages

### PR DESCRIPTION
**Pull request by peterzhu2118**
I looked at the code for `pooled_pages` and it seems like it's unnecessary when we have `free_pages`. We conditionally add to `pooled_pages` during sweeping in `gc_sweep_step` and to use it we move it back to `free_pages` during marking in `gc_marks_finish` and `gc_marks_continue`. This commit removes `pooled_pages` and adds pages with empty slots directly to `free_pages` instead.

I've ran a few synthetic benchmarks as well as timed `make test-all` on this branch vs. master and could not find a performance difference beyond the margin of error.

### CODE REVIEW

**Comment by ko1** [comment]
it is used by incremental gc. please re-open the PR if you find incremental gc working without pooled pages.

**Comment by peterzhu2118** [comment]
Hey @ko1, I'm not sure how this is used by incremental GC. Could you explain further (one of the reasons I opened this PR was to hopefully get some explanation for the use of `pooled_pages`)? I didn't see it mentioned in [your post about it](https://blog.heroku.com/incremental-gc). I tried `GC.start(immediate_mark: false)` in a test script and it seems to work fine.

**Comment by ko1** [comment]
If we don't have a pooled pages, there is no free-slots and incremental GC will stop (and run mark_rest).

**Comment by peterzhu2118** [comment]
Thanks a lot for the explanation @ko1!

**Pull request closed without merging**
