### PR TITLE
Remove misleading paragraph in extension docs

### PR DESCRIPTION
**Pull request by dentarg**
All extensions are always built, references:
- https://github.com/RubyCrypto/x25519/pull/29#issuecomment-1240686141
- https://github.com/RubyCrypto/x25519/pull/31

### CODE REVIEW

**Comment by simi** [comment]
:+1: https://github.com/rubygems/rubygems/blob/73b3f6dcdd48ce8d3dad2ee9cff079f200097c00/lib/rubygems/ext/builder.rb#L21-L23

**Comment by nobu** [comment]
It seems uncommon situation.

**Comment by simi** [comment]
@nobu it is actually common @nobu and docs are wrong. What's the reason to keep wrong docs around? :thinking:

**Comment by nobu** [comment]
It is correct.
`create_makefile` creates the makefile to build the target extension library.
If you call the method, the created makefile won't work.
In fact, https://github.com/RubyCrypto/x25519/pull/31 doesn't call `create_makefile`.

**Comment by simi** [comment]
If `create_makefile` is not called, it doesn't create `Makefile`. Per documentation it is expected it will ignore missing Makefile in this case, but it fails instead.

At that link (https://github.com/RubyCrypto/x25519/pull/31) actually stub Makefile is created manually to bypass this.

**Comment by simi** [comment]
Then I misunderstood that @nobu and I'm sorry.

**Pull request closed without merging**
