### PR TITLE
Expose the rb_interned_str_* family of functions

### PR DESCRIPTION
**Pull request by casperisfine**
> I'm now positive "interned_str" 

https://bugs.ruby-lang.org/issues/13381#note-12

Based on this, I think the API should be:

- `VALUE rb_str_interned(VALUE);`, consistent with `rb_str_new_shared / rb_str_new_frozen`, etc.
- `VALUE rb_interned_str(const char *, long);`, consistent with `rb_str_new / rb_usascii_str_new` etc.
- `VALUE rb_interned_str_cstr(const char *);`, consistent with `rb_str_new_cstr / rb_usascii_str_new_cstr` etc.
- `VALUE rb_enc_interned_str(const char *, long, rb_encoding *);`, consistent with `rb_enc_str_new` etc.
- `VALUE rb_enc_interned_str_cstr(const char *, rb_encoding *);`, consistent with  `rb_enc_str_new_cstr` etc. 

For simplicity and keeping this PR small and readable, I declared these new functions and called back to the existing internal `rb_fstring_*` functions, but I can easily rename the old functions in this PR or in a followup.

### CODE REVIEW

**Comment by byroot** [comment]
@ko1 is that acceptable to you?

**Comment by ko1** [comment]
`rb_str_interned` is not acceptable.
I'll ask @nobu about it.

**Comment by casperisfine** [comment]
Understandable. I opted for that to leave `rb_interned_str` for the `const char *, long` signature, as to avoid having to use a suffix such as `_buff`.

I'll try to think of something else while waiting for @nobu's input.

**Comment by casperisfine** [comment]
Maybe:

  - `VALUE rb_interned_str_fetch(VALUE);`
  - `VALUE rb_interned_str_lookup(VALUE);`

**Comment by ko1** [comment]
With @nobu `rb_str_to_interned_str(str)` should be better.
@casperisfine how about it? and could you rewrite the patch?

**Comment by casperisfine** [comment]
@ko1 I updated the patch. There seem to be some CI failures, but as far as I can tell they are unrelated.

> how about it?

It's fine by me. A little bit verbose but at least it avoid any confusion.

**Comment by ko1** [comment]
Thank you, one more request.
Please include ticket number in commit log, and the redmine ticket will be closed automatically. Please refer other logs to see the ticket number notation.

**Comment by casperisfine** [comment]
> Please include ticket number in commit log

Done!

**Comment by ko1** [comment]
Thank you!!

**Comment by ko1** [comment]
FY: getting it from fstring pool can be slow on ractor environment because it requires locking.

**Pull request merged**
