### PR TITLE
Delete ANYARGS

### PR DESCRIPTION
**Pull request by shyouhei**
OK, I understand it's very difficult to implement `rb_define_method` without `ANYARGS`.  But how about `rb_rescue` ?  Because that function has only one usage, I see no reason for its function prototype to use `ANYARGS`.  And here is my changeset to delete such usages.

### CODE REVIEW

**Comment by shyouhei** [comment]
Will merge this.

**Comment by shyouhei** [comment]
done @ 1663d347c993debf7ed83e11e291e7a21e14ed03

**Comment by sodabrew** [comment]
Since https://github.com/ruby/ruby/commit/a569bc09e25a2ba813d0bec1228d9ff65330a3db what should C++ extensions do as a best practice now?

**Comment by shyouhei** [comment]
@sodabrew Currently, if you are using C++ and stick to old style, your compiler complains about it but compiles nonetheless.  I suggest there are two possible best practices:

- If you value static type cheking than backwards compatibility: follow the compiler warnings.  That can save you from e.g. arity mismatch.
- If you value backwards compatibility than that: just ignore what the compiler complains.  Programs worked before should work as-is I believe.  If not please file a bug report.

**Comment by larskanis** [comment]
@shyouhei Just to give you a note: FXRuby [failed to build](https://travis-ci.org/larskanis/fxruby/jobs/589625471) due to latest changes to ANYARGS and C++ type checking/depreciation. I had to do a [bunch of changes](https://github.com/larskanis/fxruby/compare/e9733f2a725109d57f97db12064f35aa97072d09...ff87f10c2d8bf055ed1121ae75984e37801149e0) to make it to compile again and not raising any warnings. So the ANYARGS changes in ruby break backward compatibility in some cases.

However I'm glad to see these changes! I always wondered, why ruby's C-API makes overly much use of ANYARGS. It also revieled some broken function signatures in FXRuby.

**Comment by shyouhei** [comment]
@larskanis Thank you!  The build failure seems related to 17a13663998a98ff75fcc838d1cea95c879fbb88.  @nobu Can you take a look?

**Pull request closed without merging**
