### PR TITLE
Move f_boolcast definination

### PR DESCRIPTION
**Pull request by S-H-GAMELINKS**
Some code has `f_boolcast` definination, but I think it's better to one difinination in `internal.h`.

### CODE REVIEW

**Comment by Maumagnaguagno** [comment]
Why not replace with ``RBOOL``, which is already defined in ``internal.h``?
Related to [Feature #13125](https://bugs.ruby-lang.org/issues/13125).

**Comment by nobu** [comment]
How about replacing with `RBOOL`?

**Comment by S-H-GAMELINKS** [comment]
OK, I'll do it

**Comment by Blackmoses32** [comment]
Thanks for all the help...

**Pull request merged**
