### PR TITLE
Switch the default parser from parse.y to Prism

### PR DESCRIPTION
**Pull request by kddnewton**
This commit switches the default parser to Prism. There are a couple of additional changes related to this that are a part of this as well to make this happen.

* Switch the default parser in parse.h
* Remove the Prism-specific workflow and add a parse.y-specific workflow to CI so that it continues to be tested
* Update a few test exclusions since Prism has the correct behavior but parse.y doesn't per https://bugs.ruby-lang.org/issues/20504.
* Fixes a small bug found in this PR found related to static literals.
* Skips a couple of tests on RBS which are failing because they are using RubyVM::AbstractSyntaxTree.of.

Fixes [Feature #20564](https://bugs.ruby-lang.org/issues/20564)

### CODE REVIEW

**Comment by soutaro** [comment]
`test-bundled-gems` are failing with rbs-gem test fails (and other fails). 

The fails are `RuntimeError: cannot get AST for ISEQ compiled by prism` raised by `RubyVM::AbstractSyntaxTree.of`. I think skipping the failing tests in this repo makes more sense than waiting for the next release of rbs-gem. 

Adding these lines to [tool/rbs_skip_tests](https://github.com/ruby/ruby/blob/master/tool/rbs_skip_tests) will make the rbs test pass.

```
# Switching to prism resulted in an unexpected error, `RuntimeError: cannot get AST for ISEQ compiled by prism`, raised by `RubyVM::AbstractSyntax.of(method)`
test_1(RBS::RuntimePrototypeTest)
test_decls_for_anonymous_class_or_module(RBS::RuntimePrototypeTest)
test_decls_structure(RBS::RuntimePrototypeTest)
test_define_method_alias(RBS::RuntimePrototypeTest)
test_for_initialize_type(RBS::RuntimePrototypeTest)
test_for_overwritten_module_name(RBS::RuntimePrototypeTest)
test_for_yield(RBS::RuntimePrototypeTest)
test_include_owner(RBS::RuntimePrototypeTest)
test_merge_types(RBS::RuntimePrototypeTest)
test_reflection(RBS::RuntimePrototypeTest)
test_todo(RBS::RuntimePrototypeTest)
```

**Comment by kddnewton** [comment]
@mame the typeprof test suite is failing with some failed assertions that only appear to happen on the SHA in `gems/bundled_gems`. If I run this version of Ruby with typeprof HEAD, everything passes. Would it be alright to update the SHA for typeprof on Ruby master?

**Comment by mame** [comment]
@kddnewton The typeprof master is being rebuilt from scratch and is very different from the current bundled version. I hope to have it bundled by the end of this year, but for now, please wait a bit.
In order to merge this PR, can you please add `typeprof` to `TEST_BUNDLED_GEMS_ALLOW_FAILURES` and ignore the failure?

https://github.com/ruby/ruby/blob/83334ebb3c8056534974873b528f44fc0622cd22/.github/workflows/ubuntu.yml#L135

**Comment by kddnewton** [comment]
@mame yes, will do. Thank you!

**Pull request merged**
