### PR TITLE
sort #methods by default

### PR DESCRIPTION
**Pull request by josephecombs**

### CODE REVIEW

**Comment by nobu** [comment]
What's the rationale?

**Comment by josephecombs** [comment]
when you want to see the methods available to an object you nearly always want to see an alphabetically sorted result

**Comment by marcandre** [comment]
When debugging you mean?

**Comment by josephecombs** [comment]
@marcandre yes... maybe there are usages of #methods I am not considering where the computational overhead of #sort is too much a burden to bear?

**Comment by marcandre** [comment]
For debugging, I'd recommend `pry`. It gives you a very nice way to inspect an object:

```
$ pry
[1] pry(main)> cd 42
[2] pry(42):1> ls
Comparable#methods: between?
Numeric#methods: 
  +@    angle  coerce  conjugate  i     imaginary  phase  pretty_print        quo   real?  rectangular  singleton_method_added  to_c
  abs2  arg    conj    eql?       imag  nonzero?   polar  pretty_print_cycle  real  rect   remainder    step                  
Integer#methods: 
  ceil  denominator  floor  gcdlcm    lcm   numerator  pred         round  to_i    to_r      upto
  chr   downto       gcd    integer?  next  ord        rationalize  times  to_int  truncate
Fixnum#methods: 
  %  *   +  -@  <   <=   ==   >   >>  ^        abs         div     even?  inspect    modulo  size  to_f  zero?  ~
  &  **  -  /   <<  <=>  ===  >=  []  __pry__  bit_length  divmod  fdiv   magnitude  odd?    succ  to_s  |    
locals: _  __  _dir_  _ex_  _file_  _in_  _out_  _pry_
```

Alternatively, you could edit your `.irbrc` to prepend a homemade module for `methods` that calls `super.sort`if you prefer.

Since `methods` is a method that can be used for many things, it's best to keep it optimized.

**Comment by josephecombs** [comment]
cool, thanks for helping me understand

**Pull request closed without merging**
