### PR TITLE
Bundled gems warning improvements

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
The improvements are detailed in the separate commit messages.

### CODE REVIEW

**Comment by hsbt** [comment]
Thank you @deivid-rodriguez 

I added https://github.com/ruby/ruby/commit/8f6cf72e661e36410848c1451335fd28a32cecdf

Example case is:

```
$ cat -p Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

gem "bigdecimal"
gem "activesupport"
gem "mutex_m"
```

and run `bundle exec irb`. It shows like this:

```
$ bundle exec irb
/Users/hsbt/.local/share/gem/gems/activesupport-7.0.7.2/lib/active_support/core_ext/big_decimal/conversions.rb:4: warning: bigdecimal/util is found in bigdecimal, which will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec. Also contact author of activesupport-7.0.7.2 to add bigdecimal into its gemspec.
>>
```

We should detect `bigdecimal/util` as bigdecimal feature. But I have no smart idea now.

**Comment by hsbt** [comment]
Ah sorry, I missed full commit message of https://github.com/ruby/ruby/pull/9163/commits/7dd861d4a2c76a9e2137e467d492b20fa93e8185.

We need to cover above case with `bigdecimal` declaration on Gemfile.

**Comment by deivid-rodriguez** [comment]
I feel we should have some tests to cover this feature, because it's very complicated!

**Comment by hsbt** [comment]
Agreed. I only test them with test-cases of Gemfile and ruby script in my local machine. I try to port them to ruby/ruby repo.

**Comment by deivid-rodriguez** [comment]
@hsbt The problem you mention is because ruby master branch vendors bigdecimal 3.1.5 but that does not exist in rubygems.org. So because of this, Bundler defaults to using the default version even if it's specified in the Gemfile. If 3.1.5 is released to rubygems.org or you specify `gem "bigdecimal", "3.1.4"` in your Gemfile, then my patch works. I think this problem is very specific to the current state but should not happen in real life, so https://github.com/ruby/ruby/commit/7dd861d4a2c76a9e2137e467d492b20fa93e8185 could be reverted.

We could also consider that `Bundler` should always prefer rubygems.org gems over default gems for stuff specified directly in the `Gemfile`.

**Comment by deivid-rodriguez** [comment]
Thank you, I will also look into improving Bundler here.

**Comment by albus522** [comment]
Bootsnap passing in fully resolved paths making that the name seems to be the ultimate kicker here

**Comment by hsbt** [comment]
I filed https://bugs.ruby-lang.org/issues/20060

**Pull request merged**
