### PR TITLE
 Patch Ruby 2.7.0 to work in a musl-libc environment on ARMv7

### PR DESCRIPTION
**Pull request by paullj1**
Reference discussion [here](https://github.com/ruby/ruby/commit/acb67472c7da459812aa9008cf8cfbedcdddea67)

### CODE REVIEW

**Comment by paullj1** [comment]
I'm really not sure why the tests are failing.  They appear to be breaking on things that this PR doesn't touch in any way.

**Comment by dentarg** [comment]
> [@github-actions ](/apps/github-actions) ** MinGW / make (check) (pull_request) ** Failing after 33m — make (check)

[This one](https://github.com/ruby/ruby/pull/2994/checks?check_run_id=549722579#step:14:940) fails due to https://github.com/ruby/openssl/issues/355, but the other I don't know about

**Comment by ioquatix** [comment]
It's okay I will merge it.

**Comment by ioquatix** [comment]
@paullj1 can you rebase your branch on master?

**Comment by paullj1** [comment]
Going to do this in another branch/PR off master

**Comment by dentarg** [comment]
The new PR: https://github.com/ruby/ruby/pull/2995

**Pull request closed without merging**
