### PR TITLE
st: Fix indentation

### PR DESCRIPTION
**Pull request by k-takata**
Tabs and spaces were mixed for indentation. Use only spaces based on the
setting of the .editorconfig file.

### CODE REVIEW

**Comment by shyouhei** [comment]
Thank you but we don't do this kind of commits.  See also https://bugs.ruby-lang.org/issues/14246#note-10

**Comment by k-takata** [comment]
Hmm, how about this block then?
https://github.com/ruby/ruby/blob/3a6f51ee35da5d49973aba8f7d8128a65a9d8c4a/st.c#L1611-L1653
This switch block is not well aligned. Especially, the first `case` has obviously wrong indent.
How about fix only this block?

**Comment by k-takata** [comment]
This line also has a style issue:
https://github.com/ruby/ruby/blob/3a6f51ee35da5d49973aba8f7d8128a65a9d8c4a/st.c#L1137
No space needed before `(`.

**Comment by shyouhei** [comment]
Those styles are definitely NG; they should be fixed eventually someday.  However we don't want commits that only concern spacing.  Please fix them when you also have other needs to modify those lines.

**Comment by k-takata** [comment]
But there's a commit just adjusting the coding style...
https://github.com/ruby/ruby/commit/2cc3946d0ed8a21a7bf801b2a1310475f706fc3a

**Comment by shyouhei** [comment]
That commit was done before the ticket I linked.

**Comment by hsbt** [comment]
Finally, we expanded tab to spaces at https://github.com/ruby/ruby/commit/5b21e94bebed90180d8ff63dad03b8b948361089.

**Pull request closed without merging**
